import { sikli, soru, type SoruKarti } from '../tip'

/** 11. sınıf biyoloji konu sonu yoklamaları. Kartlardaki ilişkileri yeni durumlara uygular. */
export const biyoloji11Sorulari: Record<string, Omit<SoruKarti, 'id'>[]> = {
  'byl11-uyaran-tepki': [
    soru('Işığa doğru yüzen öglena ile ışığa eğilen fide aynı tür büyüme hareketini gösterir.', false, 'Öglena yer değiştirerek taksi, fide yönlü büyüyerek tropizma gösterir.'),
    sikli('Küstüm otu dokununca kapanıyor. Bu tepkinin ışığa eğilmeden temel farkı nedir?', ['Yönden bağımsız ve hızlıdır', 'Büyümeyle kalıcıdır'], 0, 'Nasti çoğunlukla turgor değişimiyle hızlı gerçekleşir; tropizma yönlü büyümedir.'),
    soru('Sinir sistemi olmayan bir paramesyum, zararlı kimyasaldan uzaklaşamaz.', false, 'Tek hücreli canlı uyaranı kendi hücresiyle algılar ve hareket ederek yanıt verir.'),
    sikli('Kandaki CO₂ artınca solunum hızlanır. İlk değişim hangi tür uyarandır?', ['Dış ortamdan gelen', 'Vücut içinden gelen'], 1, 'CO₂ kandaki bir değişimdir; solunumun hızlanması bu iç uyarana tepkidir.'),
    soru('Aynı uyarana yanıt veren canlılarda tepkinin hızı ve kullanılan yapı farklı olabilir.', true, 'Bitki büyüme ya da turgorla, hayvan sinir ve kasla yanıt verebilir.'),
    sikli('Yarasanın yankıyla yön bulmasında algılanan dış uyaran hangisidir?', ['Ses dalgası', 'Kan şekerindeki değişim'], 0, 'Yarasa çevreden dönen ses dalgalarını algılar; kan şekeri iç uyarandır.'),
    soru('Besine doğru hareket eden bakterinin tepkisi için duyu organı ve kas gerekir.', false, 'Bakteri tek hücresiyle kimyasal uyarıyı algılayıp hareket eder.'),
    sikli('Bir kök nemli tarafa doğru büyüyor. Bu olay hangisine daha yakındır?', ['Nasti', 'Tropizma'], 1, 'Büyümenin yönü su kaynağının yönüne bağlıdır; bu hidrotropizmadır.'),
    soru('Aynı uyarana verilen tepki, canlının uygun ortamı bulmasına yardım edebilir.', true, 'Besine yönelmek ve zararlı maddeden kaçmak yaşama şansını artırır.'),
    sikli('Bir canlının zararlı ortamdan kaçması için hangi sıra gerekir?', ['Algılama → işleme → tepki', 'Tepki → algılama → işleme'], 0, 'Canlı önce değişimi algılar, sonra bilgiyi işler ve hareket eder.'),
    soru('Büyüme yönünü değiştiren bitki hareketi, uyaranın geldiği yönden bağımsızdır.', false, 'Tropizmada büyümenin yönünü uyaranın yönü belirler; yönsüz olan nastidir.'),
    sikli('Küstüm otu ile mantar hifinin besine yönelmesi nasıl ayrılır?', ['İkisi de yönlü büyümedir', 'Biri turgor, diğeri yönlü büyümedir'], 1, 'Küstüm otunda hızlı turgor değişimi; hifte besin yönüne doğru büyüme vardır.'),
  ],
  'byl11-bitki-hormon': [
    soru('Tepe tomurcuğu kesilen bitkide yan dalların gelişmesi, oksin baskısının artmasından kaynaklanır.', false, 'Tepe tomurcuğundan gelen oksin azalınca yan tomurcuk üzerindeki baskı kalkar.'),
    sikli('Kuraklıkta su kaybını azaltacak hormonun artması beklenir. Hangisi?', ['Absisik asit', 'Gibberellin'], 0, 'ABA stomaları kapatır; gibberellin çimlenme ve uzamayı artırır.'),
    soru('Gövdede uzamayı artıran oksin derişimi kökte de aynı etkiyi gösterir.', false, 'Kök daha duyarlıdır; aynı derişim kökün uzamasını engelleyebilir.'),
    sikli('Doku kültüründe kök yerine sürgün oluşumu isteniyor. Hangi oran artırılır?', ['Oksin/sitokinin', 'Sitokinin/oksin'], 1, 'Sitokininin oksine göre artması sürgün gelişimini destekler.'),
    soru('Gibberellin etkisi ABA etkisine üstün gelirse uyku hâlindeki tohum çimlenebilir.', true, 'Gibberellin çimlenmeyi başlatır; ABA uyku hâlini korur.'),
    sikli('Yeşil koparılan muzun depoda olgunlaşması için hangi hormon kullanılır?', ['Etilen', 'Sitokinin'], 0, 'Etilen gazı meyve olgunlaşmasını hızlandırır; sitokinin yaşlanmayı geciktirir.'),
    soru('Köklenmesi istenen çelikte uygun dozda oksin kullanmak mantıklıdır.', true, 'Oksin kök oluşumunu uyarır; etkisi doza bağlıdır.'),
    sikli('Kesme çiçeklerin yaşlanmasını geciktirmek için hangisi daha uygundur?', ['Etilen', 'Sitokinin'], 1, 'Sitokinin yaprak yaşlanmasını geciktirir; etilen olgunlaşma ve dökülmeyi artırır.'),
    soru('Oksin, yalnızca özelleşmiş bir hormon bezinden salgılanır.', false, 'Bitkide özel hormon bezleri yoktur; sürgün ucu gibi dokular hormon üretir.'),
    sikli('Ucu çıkarılan filiz ışığa eğilmiyorsa deney hangi yapının önemini gösterir?', ['Filiz ucunun', 'Kök ucunun'], 0, 'Işığı algılayıp oksin dağılımını etkileyen sürgün ucudur.'),
    soru('Depodaki olgun bir meyvenin yanındakileri hızla olgunlaştırması gaz hormonla açıklanır.', true, 'Olgun meyveden yayılan etilen çevredeki meyveleri de etkiler.'),
    sikli('Tohumda çimlenme baskılanıp uyku hâli korunuyorsa hangi etki baskındır?', ['Gibberellin', 'Absisik asit'], 1, 'ABA uygun olmayan mevsimde çimlenmeyi önler.'),
  ],
  'byl11-bitki-tepki': [
    soru('Yandan aydınlatılan fidede ışık tarafının daha hızlı uzaması gövdeyi ışığa doğru eğer.', false, 'Oksin gölge tarafta birikir; orası daha çok uzayınca gövde ışığa eğilir.'),
    sikli('Bir kök su borusuna doğru büyüyor. Hangi uyaran belirleyicidir?', ['Nem farkı', 'Dokunma yönü'], 0, 'Kökün nemli bölgeye doğru büyümesi hidrotropizmadır.'),
    soru('Küstüm otunun yaprağı kapanıp yeniden açılıyorsa bu olay kalıcı büyümedir.', false, 'Hızlı ve geri dönen hareket, yaprak tabanındaki turgor değişimiyle olur.'),
    sikli('Yatırılan fidede kök aşağı, gövde yukarı kıvrılır. Yer çekimine tepkileri nasıldır?', ['İkisi de pozitif', 'Kök pozitif, gövde negatif'], 1, 'Kök yer çekimine doğru; gövde ona karşı büyür.'),
    soru('Işığın sağdan ya da soldan gelmesi fototropizmada eğilme yönünü değiştirir.', true, 'Tropizmanın yönü uyaranın geldiği yöne bağlıdır.'),
    sikli('Polen tüpünün yumurtalığın salgısına doğru uzaması hangisidir?', ['Kemotropizma', 'Fotonasti'], 0, 'Büyümenin yönünü kimyasal madde belirler.'),
    soru('Sinek kapan bitkisinin iki dokunuşa tepki vermesi gereksiz kapanmaları azaltır.', true, 'Tek yağmur damlası gibi rastlantısal dokunuşlarda kapanmayı önler.'),
    sikli('Sarmaşık desteğe değdiği yöne doğru sarılıyor. Hangi hareket?', ['Sismonasti', 'Tigmotropizma'], 1, 'Dokunma yönüne bağlı büyüme tigmotropizmadır.'),
    soru('Kök ve gövde aynı oksin birikimine her zaman aynı hızlanmayla yanıt verir.', false, 'Kök oksine daha duyarlıdır; birikim kökte büyümeyi yavaşlatabilir.'),
    sikli('Lale sıcaklık artınca açılıyor; ısı hangi yönden gelirse gelsin sonuç aynı. Bu nedir?', ['Termonasti', 'Termotropizma'], 0, 'Tepki ısının yönüne değil sıcaklık değişimine bağlıdır.'),
    soru('Bitkinin uyarana doğru büyümesi pozitif, uzaklaşması negatif yönelimdir.', true, 'Pozitif ve negatif adları uyarana göre büyüme yönünü anlatır.'),
    sikli('Bir deneyde ışık yönü değişince eğilme yönü de değişiyor. Bu hangi ayrımı destekler?', ['Nastiyi', 'Tropizmayı'], 1, 'Uyaranın yönü hareketi belirlediği için tropizmadır.'),
    soru('Fasulye yapraklarının gece kapanması, uyaran yönünden bağımsız bir nasti örneğidir.', true, 'Niktinastide yaprakların açılıp kapanması gece-gündüz döngüsüne bağlıdır.'),
  ],
  'byl11-uyarti-alma': [
    soru('Bir uyaran eşiği aşınca daha şiddetli olması tek bir uyartının genliğini büyütür.', false, 'Uyartı genliği sabittir; şiddet sıklık ve uyarılan reseptör sayısıyla kodlanır.'),
    sikli('Parmak ucunda iki yakın temas ayırt edilirken sırtta edilemiyor. Temel neden?', ['Reseptör yoğunluğu farkı', 'Sinir iletisinin yönü'], 0, 'Parmak ucunda dokunma reseptörleri daha sıktır.'),
    soru('Sürekli takılan saati bir süre sonra hissetmemek, derideki reseptörlerin tümünün yok olduğunu gösterir.', false, 'Değişmeyen dokunuşa reseptör yanıtı azalır; bu duyusal uyumdur.'),
    sikli('Kandaki CO₂ değişimini izleyen reseptörün türü hangisidir?', ['Fotoreseptör', 'Kemoreseptör'], 1, 'CO₂ kimyasal bir iç uyarandır; kemoreseptörler algılar.'),
    soru('Kapalı göze baskı uygulanınca ışık çakması görülmesi, beynin sinyali geldiği yola göre yorumlamasıyla ilgilidir.', true, 'Basınç fotoreseptörü uyarır; beyin görme yolundan gelen sinyali ışık sayar.'),
    sikli('Çok hafif temas hissedilmiyor, biraz güçlenince hissediliyor. İlk temas nasıldı?', ['Eşik altında', 'Eşik üstünde'], 0, 'Uyartı için gereken en düşük şiddet aşılmadığında temas algılanmaz.'),
    soru('Ağrı reseptörleri çoğu zaman hızla uyum sağlayıp hasar uyarısını susturur.', false, 'Ağrı reseptörleri yavaş uyum sağlar; bu, hasarlı dokuyu korumaya yardım eder.'),
    sikli('Saatin varlığı unutulurken yeni bir iğne batması fark ediliyor. Farkı ne açıklar?', ['Sinyalin sürekli aynı kalması', 'Yeni uyaranın reseptörü etkinleştirmesi'], 1, 'Değişmeyen dokunuşa uyum olur; yeni ağrı uyaranı güçlü yanıt üretir.'),
    soru('Reseptör ışığı ya da basıncı elektriksel sinyale çevirir; sinir sistemi uyaranın kendisini taşımaz.', true, 'Sinir lifinde taşınan şey reseptörde oluşan uyartıdır.'),
    sikli('İç kulakta ses titreşimini algılayan reseptör hangisidir?', ['Mekanoreseptör', 'Termoreseptör'], 0, 'Ses titreşimi mekanik etkidir; iç kulaktaki hücreleri uyarır.'),
    soru('Uyaran şiddetindeki artış, aynı anda uyarılan reseptör sayısını da artırabilir.', true, 'Beyin şiddeti uyartı sıklığı ve etkin reseptör sayısından çıkarır.'),
    sikli('Kola tek toz tanesi konduğunda hissedilmiyorsa en uygun açıklama?', ['Reseptör yoktur', 'Uyaran eşik altındadır'], 1, 'Reseptör bulunabilir; uyaran şiddeti sinyal başlatmaya yetmemiştir.'),
  ],
  'byl11-noron': [
    soru('Miyelin hasarı, uyartının boğumlar arasında daha hızlı ilerlemesini sağlar.', false, 'Miyelin sıçrayıcı iletimi hızlandırır; hasarı genellikle iletimi yavaşlatır.'),
    sikli('Reseptörden omuriliğe bilgi taşıyan lif hangi nörona aittir?', ['Duyu nöronu', 'Motor nöron'], 0, 'Duyu nöronu bilgiyi merkeze; motor nöron emri kasa ya da beze taşır.'),
    soru('Akson, uyartıyı hücre gövdesine doğru alan çok dallı uzantıdır.', false, 'Uyartıyı alan uzantı dendrittir; akson gövdeden uzağa iletir.'),
    sikli('Omurilik yaralanmasının kalıcı olabilmesinin temel nedeni?', ['Aksonların kısa olması', 'Merkezî sinirde onarımın sınırlı olması'], 1, 'Beyin ve omurilik nöronları ile yolları çok sınırlı onarılır.'),
    soru('Omurilik sinirinde hem duyu hem motor akson bulunabilir.', true, 'Karışık sinir, bilgi getiren ve emir götüren aksonları birlikte taşır.'),
    sikli('Nöronda uyarının olağan ilerleme sırası hangisidir?', ['Dendrit → gövde → akson', 'Akson → gövde → dendrit'], 0, 'Dendrit alır, gövde işler, akson uçlarına iletir.'),
    soru('Beyaz maddeyi büyük ölçüde miyelinli aksonlar oluşturur.', true, 'Miyelinin yağlı yapısı akson demetlerine beyaz görünüm verir.'),
    sikli('Bir duyu nöronuyla motor nöron arasında bağlantı kuran hücre?', ['Schwann hücresi', 'Ara nöron'], 1, 'Ara nöron merkezî sinir sisteminde bilgiyi işler ve bağlantıyı kurar.'),
    soru('Glia hücreleri yalnızca nöronlar arası elektriksel uyartı taşır.', false, 'Glia nöronları besler, destekler, miyelin oluşturur ve savunmaya katılır.'),
    sikli('Çevresel sinirde miyelin kılıfı hangi hücre oluşturur?', ['Schwann hücresi', 'Duyu nöronu'], 0, 'Schwann hücreleri çevresel sinirlerde aksonu sararak miyelin yapar.'),
    soru('Uzun bir aksonu olan motor nöron hâlâ tek bir hücredir.', true, 'Omurilikten ayağa uzanan akson bir nöronun parçası olabilir.'),
    sikli('Uyartı akson ucundan sonraki hücreye aktarılacaksa hangi bölüm iş görür?', ['Dendrit', 'Akson ucu'], 1, 'Akson uçları sonraki hücreyle sinaps kurup sinyali aktarır.'),
  ],
  'byl11-sinaps': [
    soru('Eşiğin iki katı şiddetindeki uyarı, tek aksiyon potansiyelinin genliğini iki katına çıkarır.', false, 'Eşik aşılınca aksiyon potansiyeli tam büyüklükte oluşur; genliği uyarana göre artmaz.'),
    sikli('Depolarizasyonda zar içinin pozitifleşmesini hangi hareket başlatır?', ['Na⁺ girişi', 'K⁺ çıkışı'], 0, 'Na⁺ kanalları açılır ve sodyum hücre içine akar.'),
    soru('Sodyum-potasyum pompası ATP harcayarak iyon dağılımının korunmasına yardım eder.', true, 'Pompa 3 Na⁺ dışarı, 2 K⁺ içeri taşıyarak dinlenme düzenini sürdürür.'),
    sikli('Bir sinirde miyelin kaybolursa hangi sonuç beklenir?', ['Uyartı genliği artar', 'İletim yavaşlar'], 1, 'Miyelin boğumlar arasında sıçrayıcı iletimi sağlar; kaybı hızı düşürür.'),
    soru('Repolarizasyon sırasında K⁺ hücre dışına çıkarak zar içinin yeniden negatif olmasına katkı verir.', true, 'Na⁺ girişi durur ve açılan K⁺ kanallarından potasyum dışarı çıkar.'),
    sikli('Sinapsta nörotransmitter salınmasını ilk tetikleyen iyon hangisidir?', ['Ca²⁺', 'Na⁺'], 0, 'Uyartı akson ucuna varınca Ca²⁺ girişi keseciklerden salgıyı başlatır.'),
    soru('Sinaptik aralıkta nöronlar birbirine doğrudan değerek elektrik akımını kesintisiz taşır.', false, 'Arada boşluk vardır; kimyasal aracı reseptöre bağlanarak iletiyi sürdürür.'),
    sikli('Bir ilaç asetilkolinin parçalanmasını engelliyor. Sinapsta ilk beklenen etki?', ['Sinyalin hemen kesilmesi', 'Etkisinin uzaması'], 1, 'Asetilkolin aralıkta kaldıkça karşı hücre reseptörlerini etkilemeyi sürdürür.'),
    soru('Aksonda dirençli dönem, yeni uyartının hemen geriye yayılmasını sınırlar.', true, 'Yeni uyarılan zar kısa süre tekrar uyarılamaz; iletim ileri yönde sürer.'),
    sikli('İletinin sinapsta tek yönlü olmasının temel yapısal nedeni?', ['Keseciklerin yalnız akson ucunda olması', 'Reseptörlerin yalnız akson ucunda olması'], 0, 'Nörotransmitter akson ucundan çıkar, reseptörler karşı hücrede bulunur.'),
    soru('GABA, sinapsta karşı hücreyi uyarmak yerine ketleyebilir.', true, 'GABA ketleyici nörotransmitterdir; sinir sisteminde iletimi baskılar.'),
    sikli('Bir grafikte −70 mV’den +30 mV’ye yükseliş hangi evreye karşılık gelir?', ['Repolarizasyon', 'Depolarizasyon'], 1, 'Na⁺ girişiyle zarın içi pozitife döner.'),
    soru('Miyelinsiz aksonda uyartı, miyelinli aksondaki gibi yalnızca Ranvier boğumlarında oluşur.', false, 'Miyelinsiz aksonda zar boyunca adım adım ilerler; boğumdan boğuma atlama miyelinlide olur.'),
    sikli('Eşik değere ulaşmayan bir uyarıda ne beklenir?', ['Aksiyon potansiyeli oluşmaz', 'Daha küçük aksiyon potansiyeli oluşur'], 0, 'Ya hep ya hiç ilkesine göre eşik altı uyarı tam uyartı başlatmaz.'),
  ],
  'byl11-duyu-organ': [
    soru('Loş ortamda renkleri ayırt etmenin zorlaşması, renk algılayan çomakların az çalışmasındandır.', false, 'Renk algılayan konilerdir; loş ışıkta daha çok çomaklar çalışır.'),
    sikli('Kulakta ses titreşimini sinirsel sinyale çeviren bölüm hangisidir?', ['Salyangoz', 'Yarım daire kanalları'], 0, 'Salyangozdaki duyu hücreleri işitmeyle, yarım daire kanalları dengeyle ilgilidir.'),
    soru('Göz bebeği ışık artınca genişleyerek retinaya daha fazla ışık düşürür.', false, 'Parlak ışıkta göz bebeği daralır ve retinaya giren ışığı azaltır.'),
    sikli('Yakına bakarken görüntünün retinaya düşmesi için hangi yapı biçim değiştirir?', ['Kornea', 'Göz merceği'], 1, 'Mercek uyum yaparak kırma gücünü değiştirir.'),
    soru('Denge kaybı yalnızca işitme reseptörlerinin bozulmasından kaynaklanmak zorunda değildir.', true, 'İç kulaktaki denge yapıları işitme yapılarından ayrıdır.'),
    sikli('Burnu tıkalı biri yemeğin tadını daha az ayırt ediyor. Hangi açıklama uygun?', ['Koku ve tat birlikte yorumlanır', 'Tat alma bütünüyle durur'], 0, 'Lezzet tat ve kokunun birlikte algılanmasıyla oluşur; tat alma tamamen bitmez.'),
    soru('Deri, sıcaklığı ve dokunmayı aynı tür tek reseptörle algılar.', false, 'Isı için termoreseptör, dokunma ve basınç için mekanoreseptör bulunur.'),
    sikli('Başı hızla çevirince hareketi algılayan iç kulak yapısı hangisidir?', ['Kulak zarı', 'Yarım daire kanalları'], 1, 'Yarım daire kanalları başın dönme hareketlerini algılar.'),
    soru('Işık, göze girdiğinde retinaya ulaşmadan önce mercekten geçer.', true, 'Kornea ve göz bebeğinden geçen ışık mercekle odaklanıp retinaya düşer.'),
    sikli('Renk körlüğü hangi reseptörlerin işleviyle daha doğrudan ilgilidir?', ['Koniler', 'Çomaklar'], 0, 'Koniler renkli görmeyi sağlar; çomaklar loş ışıkta etkindir.'),
    soru('Kulaktaki yarım daire kanalları sesin frekansını çözümleyen temel yapıdır.', false, 'Dengeyi algılarlar; sesin sinyale çevrilmesi salyangozda olur.'),
    sikli('Deride doku hasarı oluşturan bir uyaranı hangi reseptör bildirir?', ['Fotoreseptör', 'Ağrı reseptörü'], 1, 'Ağrı reseptörleri doku hasarını algılayıp koruyucu tepkiyi destekler.'),
    soru('Dil ve burundaki reseptörlerin ortak yönü kimyasal maddeleri algılamalarıdır.', true, 'Tat ve koku çözünmüş ya da havada taşınan kimyasal maddelerle başlar.'),
  ],
  'byl11-yorumlama': [
    soru('Göze gelen darbenin ışık çakması gibi algılanması, basıncın görünür ışığa dönüşmesindendir.', false, 'Basınç fotoreseptörleri uyarır; beyin görme yolundan gelen uyartıyı ışık olarak yorumlar.'),
    sikli('Sol elden gelen dokunma bilgisi çoğunlukla hangi yarımkürede yorumlanır?', ['Sağda', 'Solda'], 0, 'Duyu yolları çaprazlandığı için vücudun solu beynin sağına ulaşır.'),
    soru('Koku sinyali, diğer tüm duyular gibi önce talamustan geçmek zorundadır.', false, 'Koku yolu talamusu ilk durak olarak kullanmaz; duygu ve bellekle yakın ilişkilidir.'),
    sikli('Burnu tıkalıyken iki yiyeceği ayırt etmek zorlaşıyor. Hangi ilişkiyi gösterir?', ['Tat tek başına yeterlidir', 'Algıda duyular birleşir'], 1, 'Lezzet tat, koku, doku ve sıcaklığın birlikte yorumlanmasıyla oluşur.'),
    soru('Kesilmiş uzuvda hissedilen ağrı, algının yalnızca yerel reseptöre bağlı olmadığını gösterir.', true, 'Beyindeki uzuv haritası çalışmayı sürdürebilir; hayalet uzuv algısı oluşur.'),
    sikli('Kalp kaynaklı ağrının sol kolda hissedilmesine ne denir?', ['Yansıyan ağrı', 'Duyusal uyum'], 0, 'İç organ ve deri yolları omurilikte ortak bölgeye ulaştığında kaynak karışabilir.'),
    soru('Aynı müziği dinleyen iki kişinin farklı ayrıntı duyması deneyim ve dikkatle ilişkilidir.', true, 'Beyin duyusal bilgiyi birikim ve seçici dikkatle yorumlar.'),
    sikli('Görme uyartıları beynin hangi bölgesinde yorumlanır?', ['Şakak lobu', 'Art kafa lobu'], 1, 'Görme merkezi beyin kabuğunun art kafa lobundadır.'),
    soru('Kör noktadaki boşluğu fark etmemek, retinada oraya yeni reseptör yapılmasıyla olur.', false, 'Beyin çevredeki görsel bilgiyi kullanarak eksik bölgeyi tamamlar.'),
    sikli('Sıcağa dokunan el ağrı bilinçli algılanmadan çekiliyor. Önce hangi süreç işler?', ['Refleks', 'Bilinçli görsel algı'], 0, 'Omurilik refleksi bilinçli ağrı algısından önce kası çalıştırabilir.'),
    soru('Bilinçli algının oluşması, reseptörün sinyal üretmesinden daha ileri bir aşamadır.', true, 'Reseptör uyartıyı üretir; beyin onu anlamlandırınca algı oluşur.'),
    sikli('Kalabalıkta yalnızca arkadaşının sesine odaklanmak hangi olgudur?', ['Yansıyan ağrı', 'Seçici dikkat'], 1, 'Beyin gelen çok sayıdaki ses arasından belirli olanı öne çıkarır.'),
  ],
  'byl11-hayvan-sinir': [
    soru('Süngerin çevresel değişime tepki verebilmesi, dağınık bir sinir ağına sahip olduğunu kanıtlar.', false, 'Süngerde gerçek sinir hücreleri yoktur; hücreleri ayrı ayrı tepki verir.'),
    sikli('Dokunulan hidra bütün vücuduyla büzülüyorsa hangi düzen bunu açıklar?', ['Dağınık sinir ağı', 'Başta yoğunlaşmış beyin'], 0, 'Hidranın merkezsiz sinir ağı uyarıyı çok yöne yayar.'),
    soru('Planaryada sinir düğümlerinin başta toplanması sefalizasyonun erken bir örneğidir.', true, 'Başta gangliyon ve göz lekelerinin bulunması duyusal yoğunlaşmayı gösterir.'),
    sikli('Aktif avcıda duyuların başta yoğunlaşması hangi eğilimle ilgilidir?', ['Nasti', 'Sefalizasyon'], 1, 'Hareket yönündeki uyaranları hızlı değerlendirmek için baş bölgesi gelişir.'),
    soru('Omurgalıların sinir kordonu karın tarafında gangliyon zinciri oluşturur.', false, 'Bu düzen birçok böcek ve solucanda görülür; omurgalı sinir tüpü sırttadır.'),
    sikli('Karın tarafında her halkada gangliyon bulunan canlı hangisine yakındır?', ['Toprak solucanı', 'Hidra'], 0, 'Toprak solucanında halkalara yayılan sinir düğümü zinciri vardır.'),
    soru('Ahtapotun omurgasız olması, karmaşık davranış öğrenemeyeceği anlamına gelmez.', true, 'Ahtapot gelişmiş beyniyle gözlemle öğrenebilir ve problem çözebilir.'),
    sikli('İki boyuna sinir kordonu enine bağlarla birleşiyorsa hangi yapı vardır?', ['Dağınık ağ', 'Merdiven tipi'], 1, 'Planaryadaki boyuna kordonlar enine bağlarla merdiven görünümü oluşturur.'),
    soru('Sinir sistemi karmaşıklığı her hayvanda tek yönde ve aynı hızda artmıştır.', false, 'Yapı türün yaşayışına uyumludur; bir karşılaştırma yalnızca basit üstünlük sırası değildir.'),
    sikli('Omurgalı beynini koruyan yapı hangisidir?', ['Kafatası', 'Karın gangliyonu'], 0, 'Omurgalılarda beyin kafatası, omurilik omurga içinde korunur.'),
    soru('Kuşlarda gelişmiş beyincik, uçuşta denge ve hareket uyumuna katkı verir.', true, 'Beyincik hareketlerin eş güdümünde görevlidir.'),
    sikli('Denizanasında her yönden uyarı gelebilmesi hangi düzene uygundur?', ['Başta tek merkez', 'Vücuda yayılmış ağ'], 1, 'Dağınık sinir ağı farklı yönlerden gelen uyarıları yayabilir.'),
  ],
  'byl11-insan-sinir': [
    soru('Beyincik hasarında kaslar çalışıyorsa hareketlerin eş güdümü mutlaka korunur.', false, 'Beyincik kasın kendisi değil, hareketlerin denge ve uyumunu düzenler.'),
    sikli('Kalp atımı ve soluk alma gibi yaşamsal otomatik işlevleri hangi yapı düzenler?', ['Beyin sapı', 'Büyük beyin kabuğu'], 0, 'Beyin sapındaki merkezler solunum ve dolaşımın temel ritmini düzenler.'),
    soru('Sempatik sistem etkinleşince sindirim hızı artıp kalp atımı yavaşlar.', false, 'Sempatik yanıt kalbi hızlandırıp sindirimi baskılar; dinlenmede parasempatik baskındır.'),
    sikli('Tehlike geçip dinlenme başlayınca hangi kolun etkisi öne çıkar?', ['Sempatik', 'Parasempatik'], 1, 'Parasempatik sistem kalbi yavaşlatır ve sindirimi destekler.'),
    soru('Omurilik hem beyinle beden arasında ileti taşır hem bazı refleksleri yönetir.', true, 'Sinir yolları buradan geçer; birçok refleksin merkezi de omuriliktedir.'),
    sikli('Bilinçli olarak kol kaldırma hangi çevresel bölümle daha doğrudan ilgilidir?', ['Somatik', 'Otonom'], 0, 'Somatik sinir sistemi iskelet kaslarının istemli hareketini yönetir.'),
    soru('Hipotalamus vücut ısısı ve susama gibi homeostatik süreçlere katılır.', true, 'Ara beynin bu bölümü iç ortam değişimlerini izler ve yanıtları düzenler.'),
    sikli('Göz bebeğinin tehlike anında genişlemesi hangi kolun etkisidir?', ['Parasempatik', 'Sempatik'], 1, 'Sempatik sistem savaş ya da kaç tepkisinde göz bebeğini genişletir.'),
    soru('Beyin ve omurilik çevresel sinir sistemine aittir.', false, 'Bu ikisi merkezî sinir sistemini oluşturur; dışarı uzanan sinirler çevreseldir.'),
    sikli('Dengeyi korumak için kas hareketlerini ince ayarlayan yapı?', ['Beyincik', 'Talamus'], 0, 'Beyincik denge ve kasların eş güdümlü hareketi için önemlidir.'),
    soru('Otonom sinir sistemi yalnızca istemli iskelet kası hareketlerini denetler.', false, 'İç organların istemsiz faaliyetleri otonom, iskelet kasının istemli hareketi somatiktir.'),
    sikli('Vücut ısısının ayarı ve hormonlarla sinir sistemi bağlantısında hangi yapı öne çıkar?', ['Omurilik', 'Hipotalamus'], 1, 'Hipotalamus iç ortamı izler ve hipofizle birlikte hormon yanıtını yönlendirir.'),
    soru('Kafatası ve omurga, merkezî sinir sistemindeki yapıların fiziksel korunmasına yardım eder.', true, 'Kafatası beyni, omurga omuriliği sarar.'),
  ],
  'byl11-refleks': [
    soru('Sıcak yüzeyden el çekme, ancak ağrı beyin kabuğunda bilinçli algılandıktan sonra başlar.', false, 'Omurilik refleksi elin çekilmesini bilinçli ağrı algısından önce başlatabilir.'),
    sikli('Diz kapağı refleksinin hızlı olmasında hangi bağlantı öne çıkar?', ['Duyu nöronundan motor nörona doğrudan geçiş', 'Beyin kabuğunda uzun değerlendirme'], 0, 'Diz refleksinde ara nöron bulunmaz; duyu nöronu motor nöronla bağlanır.'),
    soru('Göz bebeğinin parlak ışıkta küçülmesi omurilik merkezli bir reflekstir.', false, 'Göz bebeği refleksinin merkezi beyin sapındadır.'),
    sikli('Yemeğe eşlenen zil bir süre sonra salyayı başlatıyor. Bu hangi reflekstir?', ['Doğuştan', 'Şartlı'], 1, 'Zil ile yemek tekrar tekrar eşlenerek öğrenilmiş tepki oluşturur.'),
    soru('Refleksin başlaması için beynin kabuğunda bilinçli karar verilmesi gerekmez.', true, 'Çoğu refleksin karar merkezi omurilik ya da beyin sapıdır.'),
    sikli('Çiviye basınca ayağı çekmede ilk yanıtı hangi merkez yönetir?', ['Omurilik', 'Beyin kabuğu'], 0, 'Omurilik refleks yayı ayağı hızla çeker; bilinçli ağrı algısı daha sonra olur.'),
    soru('Bir refleks istemsiz başladığı için beyin onu hiçbir koşulda baskılayamaz.', false, 'Beyinden inen sinir yolları bazı refleksleri kısmen baskılayabilir.'),
    sikli('Doktor diz refleksini neden sınar?', ['Kas gücünü tek başına ölçmek için', 'Sinir yolunun işleyişini görmek için'], 1, 'Refleksin eksik ya da aşırı olması sinir yolunda sorun gösterebilir.'),
    soru('Reseptörden gelen bilgi duyu nöronuyla merkeze, emir motor nöronla kasa taşınır.', true, 'Refleks yayında giriş ve çıkış yollarının görevleri farklıdır.'),
    sikli('Öksürmenin refleks merkezi hangi yapıya daha yakındır?', ['Beyin sapı', 'Omurilik'], 0, 'Öksürme ve hapşırma gibi koruyucu refleksler beyin sapında düzenlenir.'),
    soru('Diz refleksinde motor nöron çıkarılırsa bacak yine sıçrar.', false, 'Kasın kasılması için motor nöronun emri iletmesi gerekir.'),
    sikli('İğne olurken kolu bilinçli olarak sabit tutmak neyi gösterir?', ['Refleksin öğrenilmediğini', 'Beynin refleksi baskılayabildiğini'], 1, 'İstemsiz refleks bazı durumlarda üst merkezlerin etkisiyle sınırlandırılabilir.'),
  ],
  'byl11-kemik': [
    soru('Kemikteki organik maddeler sertliği, mineral tuzları esnekliği sağlar.', false, 'Mineraller sertlik, organik lifler esneklik sağlar; görevler ters çevrilmiştir.'),
    sikli('Uzun kemiğin boyca uzamasında hangi bölge etkindir?', ['Büyüme plağı', 'Sarı ilik'], 0, 'Uçlardaki kıkırdak büyüme plağı kemiğin boyca uzamasını sağlar.'),
    soru('Süngerimsi kemik boşlukları kırmızı kemik iliği içerebilir.', true, 'Kırmızı ilik kan hücrelerinin üretimine katılır.'),
    sikli('Kırık sonrası yeni kemik yapımında hangi hücre öncelikle etkindir?', ['Osteoklast', 'Osteoblast'], 1, 'Osteoblastlar kemik matriksini yapar; osteoklastlar yıkar.'),
    soru('Osteoklastların görevi kemiği sürekli yeni matriksle kalınlaştırmaktır.', false, 'Osteoklastlar kemik dokusunu yıkar; yapım osteoblastların işidir.'),
    sikli('Kemikte kan hücresi üreten bölge hangisidir?', ['Kırmızı ilik', 'Sarı ilik'], 0, 'Kırmızı kemik iliği kan hücresi üretir; sarı ilik yağ depolar.'),
    soru('Kıkırdak, oynar eklemde kemik uçları arasındaki sürtünmeyi azaltır.', true, 'Eklem yüzeyini örterek hareketi kolaylaştırır ve darbeyi yumuşatır.'),
    sikli('Kemiğin sertliğinde hangi bileşen daha belirleyicidir?', ['Kolajen', 'Kalsiyum tuzları'], 1, 'Mineral tuzlar sertliği, organik lifler esnekliği destekler.'),
    soru('Kemik dokusunda kan damarı bulunmaz; bu yüzden kırıklar iyileşemez.', false, 'Kemik canlı ve damarlı dokudur; hücreleri kırık onarımına katılır.'),
    sikli('Darbe alan uzun kemikte hafiflik ve iç hacim sağlayan yapı hangisidir?', ['Süngerimsi kemik', 'Sıkı kemik tabakası'], 0, 'Süngerimsi yapı kemiğin dayanımını korurken ağırlığını azaltır.'),
    soru('Kemik, vücuda destek olmanın yanında mineral depolamaya da katılır.', true, 'Kalsiyum ve fosfor için önemli bir depodur.'),
    sikli('Çocukta büyüme plağı zarar görürse hangi süreç doğrudan etkilenir?', ['Kas tonusu', 'Kemiğin boyca uzaması'], 1, 'Uzun kemiğin uçlarındaki büyüme kıkırdağı boy uzamasını sağlar.'),
  ],
  'byl11-eklem-kas': [
    soru('Oynar eklemde eklem sıvısı sürtünmeyi artırarak kemik uçlarını sabitler.', false, 'Eklem sıvısı ve kıkırdak sürtünmeyi azaltıp hareketi kolaylaştırır.'),
    sikli('Kası kemiğe bağlayan yapı hangisidir?', ['Kiriş', 'Bağ'], 0, 'Kiriş kas kuvvetini kemiğe aktarır; bağ kemikleri birbirine bağlar.'),
    soru('Omuz eklemi, yalnız tek eksende hareket eden menteşe ekleme örnektir.', false, 'Omuz küresel eklemdir; çok yöne hareket edebilir.'),
    sikli('Dirsekteki hareket hangi eklem tipine daha uygundur?', ['Küresel', 'Menteşe'], 1, 'Dirsek başlıca bükülme ve açılmaya izin verir.'),
    soru('Düz kaslar isteğe bağlı olarak iskelet kemiğini hareket ettirir.', false, 'Kemik hareketini istemli iskelet kası sağlar; düz kas iç organlarda çalışır.'),
    sikli('İki kemiği eklem çevresinde bir arada tutan yapı hangisidir?', ['Bağ', 'Kiriş'], 0, 'Bağ kemikle kemiği bağlar ve eklemi destekler.'),
    soru('Kalp kası çizgili yapılı olsa da istemsiz çalışır.', true, 'Yapı ve çalışma bakımından iskelet ve düz kaslardan ayrı özellikler taşır.'),
    sikli('Omuzun çok yöne hareket etmesini hangi eklem yapısı sağlar?', ['Menteşe', 'Küresel'], 1, 'Küresel eklem geniş hareket aralığı sunar.'),
    soru('Kas yalnızca çekme kuvveti oluşturabildiğinden karşıt hareketler için farklı kaslar gerekir.', true, 'Bükme ve açma gibi zıt yönlü hareketlerde karşıt kaslar sırayla kasılır.'),
    sikli('Merdiven çıkarken iskelet kaslarının temel işlevi hangisidir?', ['Kemikleri eklemden hareket ettirmek', 'Eklemin bağlarını kısaltmak'], 0, 'İskelet kası kiriş aracılığıyla kemiği çekerek eklemde hareket üretir.'),
    soru('Oynamaz eklemler omuz kadar geniş hareket aralığı sağlar.', false, 'Oynamaz eklemler hareket etmez ya da çok sınırlı hareket eder.'),
    sikli('Bağı kopan oynar eklemde en doğrudan ne zayıflar?', ['Kasın kemiğe tutunması', 'Kemiklerin birbirine tutunması'], 1, 'Bağ eklemde kemikleri birbirine bağlayıp kararlılık sağlar.'),
  ],
  'byl11-kemik-kas-birlikte': [
    soru('Dirsek bükülürken biseps ve trisepsin ikisi de aynı anda tam kuvvetle kasılır.', false, 'Bükülmede biseps kasılır, karşıt triseps gevşer; birlikte güçlü kasılma harekete dirençtir.'),
    sikli('Kol yeniden açılırken hangi kasın kasılması gerekir?', ['Triseps', 'Biseps'], 0, 'Triseps açıcı kastır; biseps bükme sırasında etkindir.'),
    soru('Bir kas kemiği çekebilir ama onu ittiği için aynı kas karşıt hareketi yapamaz.', true, 'Açma için ayrı bir karşıt kas gerekir.'),
    sikli('Dirsek kaldıracında bisepsin kısa koldan kuvvet vermesi ne sağlar?', ['Daha az hareket hızı', 'Elin geniş ve hızlı yer değiştirmesi'], 1, 'Bu kaldıraç kuvvetten kaybedip hız ve hareket uzaklığı kazandırır.'),
    soru('Yürümede kas, kemik, eklem ve sinir sistemi birlikte iş görür.', true, 'Kas kuvvet üretir, kemik kaldıraç olur, eklem yön verir, sinirler zamanı ayarlar.'),
    sikli('Karşıt kasların sırayla çalışmasını hangi sistem eş güdümler?', ['Sinir sistemi', 'İskelet sistemi'], 0, 'Motor sinyaller uygun kasları doğru sırayla etkinleştirir.'),
    soru('Duruşu korurken bütün iskelet kasları tamamen gevşek kalır.', false, 'Bazı motor birimler hafif etkin kalarak kas tonusunu ve duruşu korur.'),
    sikli('Kiriş koparsa kas kasılsa bile hangi aktarım bozulur?', ['Kuvvetin karşıt kasa iletimi', 'Kuvvetin kemiğe iletimi'], 1, 'Kiriş kası kemiğe bağlar; kopması çekme kuvvetinin aktarımını engeller.'),
    soru('Hareketsizlik kas gücünü azaltabilir ve kemik sağlığını etkileyebilir.', true, 'Kas ile iskelet kullanım ve yüklenmeye birlikte uyum sağlar.'),
    sikli('Bir robot kolun bükme ve açma için iki ayrı çekme kablosu kullanması neyi taklit eder?', ['Karşıt kas çiftini', 'Tek kasın itip çekmesini'], 0, 'Canlıdaki kaslar itmez; zıt hareketler için karşıt kaslar çekme uygular.'),
    soru('Dirsekteki hareketin nedeni kemiğin kendi kendine kısalmasıdır.', false, 'Kısalan kas kirişle kemiği çeker; kemik kaldıraç gibi hareket eder.'),
    sikli('Biseps kasılırken triseps de en yüksek kuvvetle kasılırsa ne olur?', ['Kol serbestçe hızlanır', 'Karşıt kuvvet hareketi zorlaştırır'], 1, 'Karşıt kasın aynı anda güçlü kasılması bükme hareketine direnç oluşturur.'),
  ],
  'byl11-kasilma-kontrol': [
    soru('Bir kasın kuvveti yalnız tek lifin kasılma genliğini büyüterek artırılır.', false, 'Tek lif ya hep ya hiç yanıt verir; daha çok motor birim ve sık uyarı toplam kuvveti artırır.'),
    sikli('İnce parmak hareketinde hangi motor birim uygundur?', ['Az lifli küçük birim', 'Çok lifli büyük birim'], 0, 'Küçük motor birimler daha hassas kuvvet ayarı sağlar.'),
    soru('Motor nöron ile kas lifi arasındaki kavşakta asetilkolin salınır.', true, 'Asetilkolin kas zarını uyararak kalsiyum salınımına giden süreci başlatır.'),
    sikli('Kasılma başladıktan sonra Ca²⁺ depoya geri çekilirse ne olur?', ['Kasılma artar', 'Kas gevşemeye başlar'], 1, 'Kalsiyum azalınca aktin bağlanma yerleri kapanır.'),
    soru('Tek bir kas lifi uyarı şiddeti arttıkça kademeli olarak daha çok kasılır.', false, 'Tek lif eşik aşılınca tam yanıt verir; kuvvet motor birim ve sıklıkla ayarlanır.'),
    sikli('Sık uyarılar arasında kas tam gevşemiyorsa hangi durum görülür?', ['Kasılmaların üst üste binmesi', 'Kas tonusunun sıfırlanması'], 0, 'Yeni uyarı gevşeme tamamlanmadan gelince kasılmalar toplanır.'),
    soru('Dinlenirken kas tonusu duruşun korunmasına yardım eder.', true, 'Az sayıda motor birim dönüşümlü çalışarak hafif gerginlik sağlar.'),
    sikli('Yüz metre sprintinde ilk saniyelerde ATP yenilemeye hangi kaynak yardım eder?', ['Yalnız oksijenli solunum', 'Kreatin fosfat'], 1, 'Kreatin fosfat kısa ve yoğun eforda ATP’yi hızla yeniler.'),
    soru('Maratonda enerji gereksinimi yalnızca birkaç saniyelik kreatin fosfat deposuyla karşılanır.', false, 'Uzun süren etkinlikte oksijenli solunum baskın ATP kaynağıdır.'),
    sikli('Kas lifinde kasılmayı doğrudan başlatan iyon hangisidir?', ['Ca²⁺', 'Na⁺'], 0, 'Depodan çıkan Ca²⁺ aktin üzerindeki bağlanma yerlerini açar.'),
    soru('Kramp, istem dışı ve ağrılı uzun süreli kasılmadır.', true, 'Yorgunluk ve su-tuz kaybı gibi durumlar krampla ilişkili olabilir.'),
    sikli('Uzun mesafe koşusunda hangi lifler daha avantajlıdır?', ['Hızlı yorulan güçlü lifler', 'Mitokondrice zengin yavaş lifler'], 1, 'Yavaş lifler oksijenli çalışmaya uygun olup yorgunluğa daha dayanıklıdır.'),
  ],
  'byl11-kasilma-mekanizma': [
    soru('Kasılmada aktin ve miyozin iplikleri kısalır.', false, 'İplikler kendi boylarını korur; birbirinin üzerinden kayarak sarkomeri kısaltır.'),
    sikli('Kasılmada hangi bölgenin boyu değişmez?', ['A bandı', 'I bandı'], 0, 'A bandı miyozin ipliğinin boyunu gösterir; miyozin kısalmaz.'),
    soru('Kasılmada aktin kayarken iki Z çizgisi birbirinden uzaklaşır.', false, 'Aktin merkeze kayınca sarkomer kısalır ve Z çizgileri yaklaşır.'),
    sikli('ATP bağlanamazsa miyozin başı ne yapamaz?', ['Aktine bağlanamaz', 'Aktinden ayrılamaz'], 1, 'Yeni ATP miyozin başının aktinden ayrılmasını sağlar; yokluğunda bağlı kalır.'),
    soru('I bandı ve H bölgesi kasılma sırasında daralabilir.', true, 'Aktin miyozin üzerine kaydıkça yalnız aktin ve yalnız miyozin bölgeleri küçülür.'),
    sikli('Sarkomer hangi iki yapı arasında tanımlanır?', ['Z çizgileri', 'Miyozin başları'], 0, 'Sarkomer iki Z çizgisi arasındaki kasılma birimidir.'),
    soru('Kas gevşerken Ca²⁺ depoya geri pompalanması ATP harcar.', true, 'Kalsiyumun aktif geri taşınması bağlanma yerlerinin kapanmasını sağlar.'),
    sikli('Ölüm katılığında kasın sert kalmasını ne açıklar?', ['Ca²⁺ hiç bulunmaması', 'ATP yokluğunda köprülerin ayrılamaması'], 1, 'Miyozin başları yeni ATP bağlayamayınca aktinden ayrılamaz.'),
    soru('Güç vuruşunda miyozin başı aktini sarkomerin merkezine doğru çeker.', true, 'Çapraz köprü döngüsü aktin ipliğinin miyozin üzerinde kaymasına yol açar.'),
    sikli('Kasılmada kalın ipliğin kendisi ne yapar?', ['Boyunu korur', 'Kısalır'], 0, 'Miyozinin boyu sabit kalır; A bandının değişmemesinin nedeni budur.'),
    soru('ATP yalnızca kasılmaya gerekir; gevşeme enerji gerektirmez.', false, 'ATP miyozinin ayrılması ve Ca²⁺ geri pompalanması için de gereklidir.'),
    sikli('Kas lifindeki miyofibrillerin tekrarlayan temel birimi hangisidir?', ['Motor birim', 'Sarkomer'], 1, 'Miyofibril art arda dizilmiş sarkomerlerden oluşur.'),
  ],
  'byl11-dogal-bagisiklik': [
    soru('Deri ve mukus, mikrop dokuya girdikten sonra çalışan ikinci savunma hattını oluşturur.', false, 'Deri ve mukus girişten önce etkili ilk hattır; fagositler ikinci hatta görev yapar.'),
    sikli('Çizikte kızarıklık ve şişlik oluşmasını hangi madde başlatır?', ['Histamin', 'Antikor'], 0, 'Histamin damarları genişletip geçirgenliği artırır; savunma hücreleri bölgeye gelir.'),
    soru('Doğal bağışıklık aynı mikrop ikinci kez girdiğinde bellek sayesinde daha seçici olur.', false, 'Bellek ve özgül ikinci yanıt kazanılmış bağışıklığın özellikleridir.'),
    sikli('Virüs bulaşmış hücre komşularını hangi maddeyle uyarabilir?', ['Histamin', 'İnterferon'], 1, 'İnterferon komşu hücrelerde virüsün yayılmasına karşı savunmayı artırır.'),
    soru('Ateşin belirli ölçüde yükselmesi mikropların çoğalmasını yavaşlatabilir.', true, 'Hipotalamus ayar noktasını yükseltir; aşırı ateş ise vücut için zararlıdır.'),
    sikli('Mikrobu sarıp içine alarak sindiren olay hangisidir?', ['Fagositoz', 'Antikor üretimi'], 0, 'Fagosit hücre mikrobu yutar ve lizozomla parçalar.'),
    soru('Doğal öldürücü hücreler yalnızca kandaki serbest virüs parçacıklarını yutar.', false, 'Özellikle virüs bulaşmış ya da kanserleşmiş vücut hücrelerini öldürürler.'),
    sikli('Mide asidinin mikropları öldürmesi hangi hatta girer?', ['İkinci savunma hattı', 'Birinci savunma hattı'], 1, 'Mide asidi besinle giren mikrobu dokuya geçmeden durduran engeldir.'),
    soru('İltihaptaki kızarıklık, bölgeye kan akışının artmasıyla ilişkilidir.', true, 'Genişleyen damarlardan bölgeye daha çok kan ve akyuvar gelir.'),
    sikli('Virüs bulaşmış bir vücut hücresini doğrudan öldürmeye hangisi daha uygundur?', ['Doğal öldürücü hücre', 'Nötrofil'], 0, 'Doğal öldürücü hücre bozulmuş vücut hücresini hedef alır.'),
    soru('Gözyaşı, içeri giren mikroplara karşı yalnız mekanik yıkama yapar.', false, 'Yıkamanın yanında bakterileri parçalayan enzim de içerir.'),
    sikli('Lenf düğümünün enfeksiyonda şişmesi hangi işiyle ilişkilidir?', ['Yaşlı alyuvarları yıkması', 'Lenfi süzüp savunma hücresi toplaması'], 1, 'Lenf düğümleri lenfi süzer ve bağışıklık hücreleri burada etkinleşir.'),
  ],
  'byl11-kazanilmis': [
    soru('Aşı, hazır antikor verip bellek oluşturmadan kısa süreli koruma sağlar.', false, 'Bu serumun pasif etkisidir; aşı antijen sunarak vücudun aktif ve bellekli yanıtını uyarır.'),
    sikli('Yılan sokmasında hızlı etki için hangisi uygundur?', ['Hazır antikor içeren serum', 'Yalnız uzun süreli aşı takvimi'], 0, 'Serum hazır antikorla hemen etki eder; aşı koruması zamanla gelişir.'),
    soru('Antikor, her yabancı antijene aynı güçle bağlanan özgül olmayan bir proteindir.', false, 'Antikor belirli antijene özgüdür; B hücreleri tarafından üretilir.'),
    sikli('Virüs bulaşmış vücut hücresini doğrudan hedefleyen kazanılmış yanıt hangisidir?', ['Plazma hücresi salgısı', 'Öldürücü T hücresi'], 1, 'Öldürücü T hücresi enfekte hücreyi yok eder; antikor daha çok serbest hedeflere bağlanır.'),
    soru('İkinci karşılaşmada antikor yanıtının daha hızlı olması bellek hücreleriyle açıklanır.', true, 'İlk karşılaşmada oluşan bellek hücreleri özgül yanıtı çabuk başlatır.'),
    sikli('Bebek anne sütüyle hazır antikor alıyor. Bu hangi bağışıklıktır?', ['Doğal pasif', 'Yapay aktif'], 0, 'Antikoru bebek üretmez; anneden doğal yolla hazır alır.'),
    soru('T lenfositleri timusta olgunlaşır.', true, 'İki lenfosit tipi ilikte üretilir; T hücresi timusta olgunlaşır.'),
    sikli('Aşı ile serum arasındaki temel fark hangisidir?', ['İkisi de hazır antikor verir', 'Aşı bellek oluşturur, serum oluşturmaz'], 1, 'Aşı aktif bağışıklık, serum pasif bağışıklık sağlar.'),
    soru('Organ naklinde doku uyumu aranmasının nedeni yabancı yüzey antijenlerine karşı yanıt oluşabilmesidir.', true, 'Bağışıklık sistemi nakledilen hücreleri yabancı görüp reddedebilir.'),
    sikli('Antikor salgılayan plazma hücresi hangi hücreden gelişir?', ['B lenfositi', 'T lenfositi'], 0, 'Antijeni tanıyan B hücrelerinin bir bölümü plazma hücresine dönüşür.'),
    soru('Serumun etkisi hemen başladığı için bağışıklık belleği de uzun yıllar sürer.', false, 'Hazır antikor kısa sürede azalır; alıcıda bellek hücresi oluşturmaz.'),
    sikli('Aynı antijenle ikinci kez karşılaşmada hangi yanıt beklenir?', ['Daha yavaş ve zayıf', 'Daha hızlı ve güçlü'], 1, 'Bellek hücreleri özgül cevabı ilk karşılaşmaya göre hızla başlatır.'),
    soru('Uyumsuz kan aktarımında hücre yüzeyi antijenleri bağışıklık tepkisine yol açabilir.', true, 'Yabancı yüzey antijenleri tanınır ve kümeleşme gibi tehlikeli tepkiler doğabilir.'),
  ],
  'byl11-alerji': [
    soru('Polen alerjisinde belirtilerin nedeni, polenin herkes için hastalık yapıcı bir mikrop olmasıdır.', false, 'Polen çoğu kişi için zararsızdır; belirtileri aşırı bağışıklık yanıtı doğurur.'),
    sikli('İlk polen temasında belirti yok, sonrakinde hapşırma var. İlk temasta ne oldu?', ['Duyarlılaşma', 'Mikrobun çoğalması'], 0, 'İlk temasta özgül antikorlar oluşup mast hücrelerine bağlanır.'),
    soru('Mast hücresinin salgıladığı histamin damar genişlemesi ve kaşıntıda rol oynar.', true, 'Alerjen ikinci temasta mast hücresini uyarınca histamin çıkar.'),
    sikli('Alerjik tepki ile otoimmün hastalığın hedefi nasıl ayrılır?', ['Kendi dokusu ile dış alerjen', 'Dış alerjen ile kendi dokusu'], 1, 'Alerjide zararsız dış maddeye; otoimmün durumda vücudun kendi dokusuna yanıt olur.'),
    soru('Alerjene ilk karşılaşmada şiddetli belirti oluşması duyarlılaşmanın zorunlu sonucudur.', false, 'İlk temas hazırlık aşamasıdır; belirtiler genellikle sonraki karşılaşmada başlar.'),
    sikli('Alerjende göz kaşıntısı sürüyor, ateş yok ve maruziyetle artıyor. Hangisi daha uygun?', ['Alerji', 'Virüse bağlı soğuk algınlığı'], 0, 'Alerjide göz kaşıntısı ve alerjenle süren belirtiler tipiktir; ateş genellikle yoktur.'),
    soru('Antihistaminik histaminin etkisini azaltarak belirtileri hafifletebilir.', true, 'İlaç histaminin dokudaki etkisini engeller; alerjenin varlığını ortadan kaldırmaz.'),
    sikli('Hava yolu daralıp kan basıncı hızla düşen yaygın alerjik tepki nedir?', ['Hafif rinit', 'Anafilaksi'], 1, 'Anafilaksi hızla gelişen, yaşamı tehdit eden yaygın tepkidir.'),
    soru('Alerjenden kaçınmak, karşılaşmayı azaltarak tepki oluşma olasılığını düşürür.', true, 'Tetikleyici maddeyle temas azalınca mast hücresi yanıtı da azalır.'),
    sikli('Alerjenle sonraki karşılaşmada belirtiyi başlatan hücre hangisidir?', ['Mast hücresi', 'B lenfositi'], 0, 'Mast hücresindeki antikora alerjen bağlanınca histamin salınır.'),
    soru('Alerjinin son yıllarda artmasının tek ve kesin nedeni tamamen açıklanmıştır.', false, 'Mikropla karşılaşma ve hava kirliliği gibi etkenler araştırılıyor; tek kesin neden yok.'),
    sikli('Alerji testi neden kişinin her maddeye değil belirli maddelere tepkisini ölçer?', ['Tüm maddeler aynı antikora bağlanır', 'Yanıt alerjene özgü olabilir'], 1, 'Bağışıklık yanıtı belli alerjenlere yönelir; deri ve kan testleri bunu araştırır.'),
  ],
  'byl11-homeo-canli': [
    soru('Homeostazi, vücut sıcaklığı ve pH’ın gün boyu tek bir sayıda hiç değişmeden kalmasıdır.', false, 'Dinamik dengede değerler dar aralıkta dalgalanır ve sapmalar düzeltilir.'),
    sikli('Tatlı su paramesyumunda fazla suyu atan yapı hangisidir?', ['Kasılabilen koful', 'Hücre zarı'], 0, 'Osmozla giren su kasılabilen koful aracılığıyla dışarı pompalanır.'),
    soru('Deniz balığı vücudundan su kaybettiği için çok bol ve seyreltik idrar yapar.', false, 'Deniz balığı suyu korumak için az idrar üretir ve fazla tuzu solungaçla atar.'),
    sikli('Tatlı su balığının bol seyreltik idrar yapmasının nedeni?', ['Sürekli tuz kaybetmesi', 'Osmozla fazla su alması'], 1, 'Çevre suyu vücuda girdiği için fazla su atılır.'),
    soru('Kertenkele güneşlenerek vücut ısısını çevreden alır.', true, 'Ektoterm canlı ısı üretiminden çok davranış ve çevre ısısını kullanır.'),
    sikli('Çöl hayvanının yoğun idrar yapması hangi kaybı azaltır?', ['Su kaybını', 'Isı üretimini'], 0, 'Az ve yoğun idrarla atılan su miktarı azaltılır.'),
    soru('Bitkinin kuraklıkta stomalarını kapatması su kaybını azaltırken gaz alışverişini de sınırlar.', true, 'Stoma iki işi birden etkiler; su tasarrufu ile CO₂ alımı arasında denge kurulur.'),
    sikli('Köpeğin sıcak havada hızlı soluması temel olarak neyi artırır?', ['Metabolik ısı üretimini', 'Buharlaşmayla ısı atımını'], 1, 'Dil ve solunum yüzeyinden buharlaşma soğumaya yardım eder.'),
    soru('Bütün canlılar iç dengeyi aynı organ ve hormonlarla kurar.', false, 'Paramesyum koful, bitki stoma, memeli hipotalamus ve böbrek kullanabilir.'),
    sikli('Penguen ayağındaki karşı akımlı damar düzeninin sonucu nedir?', ['Çevreye ısı kaybını azaltır', 'Ayağa ısı aktarımını artırır'], 0, 'Sıcak ve soğuk kan yan yana akarak ısının bir bölümünü geri kazanır.'),
    soru('Endoterm canlılar ısılarının önemli bölümünü metabolizmalarıyla üretir.', true, 'Kuş ve memeliler çevre soğuduğunda metabolik ısı üretimini artırabilir.'),
    sikli('İnsanda susama ve ısı yanıtının kontrolünde hangi yapı öne çıkar?', ['Pankreas', 'Hipotalamus'], 1, 'Hipotalamus sıcaklık ve su dengesine ilişkin sinirsel ve hormonal yanıtları düzenler.'),
  ],
  'byl11-homeo-surec': [
    soru('Su kaybeden kişide ADH artışı idrar miktarını artırıp idrarı seyreltir.', false, 'ADH suyun geri emilimini artırır; idrar azalır ve koyulaşır.'),
    sikli('Yemekten sonra kan şekeri yükseldiğinde hangi hormonun etkisi artar?', ['İnsülin', 'Glukagon'], 0, 'İnsülin hücrelerin glikoz almasını ve karaciğerde depolamayı destekler.'),
    soru('Homeostatik kontrol halkasında efektör değişimi algılar, reseptör kası çalıştırır.', false, 'Reseptör algılar; kontrol merkezinin emriyle efektör yanıt verir.'),
    sikli('Soğukta deri damarlarının daralması hangi sonuca hizmet eder?', ['Deriye ısı taşınmasını artırır', 'Isı kaybını azaltır'], 1, 'Deriye daha az sıcak kan gider ve çevreye ısı aktarımı düşer.'),
    soru('Sıcakta terleme, ter buharlaşınca vücuttan ısı alarak soğutur.', true, 'Buharlaşma enerjiyi deriden çektiği için serinletir.'),
    sikli('Kan pH’ındaki ani değişimi ilk anda hangi sistem sınırlar?', ['Bikarbonat tamponu', 'Günler süren böbrek ayarı'], 0, 'Tamponlar saniyeler içinde H⁺ değişimlerini dengeler; böbrek yanıtı yavaştır.'),
    soru('Kan şekeri düşünce glukagon karaciğerde glikojen yıkımını artırabilir.', true, 'Depodan kana glikoz verilmesi düşen şekeri yükseltir.'),
    sikli('Ayağa hızlı kalkınca kan basıncı düşerse ilk yanıt hangisidir?', ['Kalbin yavaşlaması', 'Kalbin hızlanması'], 1, 'Basınç reseptörleri düşüşü bildirir; kalp hızı ve damar daralması artar.'),
    soru('Ayar noktası çevresindeki her küçük dalgalanma homeostazinin bütünüyle bozulduğunu gösterir.', false, 'Dinamik dengede değerler aralık içinde dalgalanabilir.'),
    sikli('Terle çok tuz kaybında özellikle hangi denge zorlanır?', ['İyon dengesi', 'Kan şekerinin düzeni'], 0, 'Na⁺ ve diğer iyonların derişimi sinir-kas işleyişi için korunmalıdır.'),
    soru('Aldosteron böbrekte sodyum tutulmasına katkı verir.', true, 'Sodyum geri emilimi iyon ve sıvı dengesini etkiler.'),
    sikli('Kan şekerini yükseltmek için hangi hormon daha uygundur?', ['İnsülin', 'Glukagon'], 1, 'Glukagon glikojen yıkımını uyararak kana glikoz geçmesini sağlar.'),
  ],
  'byl11-geri-bildirim': [
    soru('Kan şekeri düşünce insülin salgısının daha da artması negatif geri bildirim örneğidir.', false, 'Şeker düşünce insülin azalır; yüksek şekeri düşüren yanıt kendini sınırlar.'),
    sikli('Doğumda kasılma yeni oksitosin salgısını artırıyorsa döngü hangisidir?', ['Pozitif geri bildirim', 'Negatif geri bildirim'], 0, 'Kasılma ve oksitosin birbirini büyütür; doğum tamamlanınca döngü durur.'),
    soru('Pozitif geri bildirim homeostazinin sürekli kullanılan temel düzeltme mekanizmasıdır.', false, 'Dengeyi koruyan ana yol negatif geri bildirimdir; pozitif döngüler kısa süreli olayları tamamlar.'),
    sikli('Tiroksin artınca hipofiz uyarısı azalıyor. Bu ilişki nedir?', ['Değişimi büyütme', 'Negatif geri bildirim'], 1, 'Ürün kendi üretimini başlatan merkezleri baskılayarak artışı sınırlar.'),
    soru('Pıhtılaşmada çağrılan trombositlerin yenilerini çağırması pozitif döngü kurar.', true, 'Her yeni trombosit daha fazla sinyal vererek olayı yarayı kapatıncaya kadar büyütür.'),
    sikli('Oda ısınınca kombinin kapanması hangi ilkeye benzer?', ['Negatif geri bildirim', 'Pozitif geri bildirim'], 0, 'Isınma, onu oluşturan ısıtmayı durdurur.'),
    soru('Pozitif döngünün güvenli biçimde sonlanması çoğu zaman olayın tamamlanmasına bağlıdır.', true, 'Doğumda bebeğin çıkması, pıhtılaşmada yaranın kapanması döngüyü bitirir.'),
    sikli('Bebek emmeyi bırakınca süt salgısı döngüsünün zayıflaması neyi gösterir?', ['Tiroksin ayarını', 'Uyarının sürmesine bağımlılığı'], 1, 'Emme pozitif döngüyü besler; kesilince hormon uyarısı azalır.'),
    soru('Negatif geri bildirim sapmayı büyüterek ayar noktasından uzaklaştırır.', false, 'Negatif geri bildirim sapmaya ters yönde etki edip değeri ayar noktasına yaklaştırır.'),
    sikli('Şokta düşen basınç kalbe giden kanı azaltıp basıncı daha da düşürüyorsa ne var?', ['Kontrolsüz pozitif döngü', 'Başarılı negatif düzeltme'], 0, 'İlk değişim kendi şiddetini artırır; tehlikeli pozitif geri bildirim oluşur.'),
    soru('Ateşin yükselmesi metabolizmayı, metabolizmanın ısı üretimini artırırsa değişim kendini güçlendirir.', true, 'Isı artışı yeniden ısı üretimini artırdığı için pozitif döngüye dönüşebilir.'),
    sikli('Bir yanıt başlangıçtaki değişimi azaltıyorsa adı nedir?', ['Pozitif geri bildirim', 'Negatif geri bildirim'], 1, 'Yanıt sapmayı tersine çevirip dengeye döndürüyorsa negatiftir.'),
  ],
  'byl11-sinir-homeo': [
    soru('Hipotalamus, hormonlardan bağımsız çalıştığı için susama ve ADH yanıtını birlikte yönetemez.', false, 'Hipotalamus sinirsel bilgiyi hipofiz üzerinden hormonal yanıtla birleştirir.'),
    sikli('Ani tehlikede kalp hızlanıp sindirim yavaşlıyorsa hangi kol etkindir?', ['Sempatik', 'Parasempatik'], 0, 'Sempatik yanıt kaynakları kaçış ve mücadeleye yöneltir.'),
    soru('Parasempatik sistem dinlenme sırasında sindirim salgılarını artırabilir.', true, 'Dinlen ve sindir yanıtı enerji kazanma ve toparlanmayı destekler.'),
    sikli('Kan yoğunlaşınca susama ve ADH artışını hangi merkez başlatır?', ['Beyincik', 'Hipotalamus'], 1, 'Hipotalamus ozmotik değişimi algılar ve davranış ile hormon yanıtını düzenler.'),
    soru('Sempatik sistemin her organı hızlandırması beklenir.', false, 'Kalbi hızlandırırken sindirimi yavaşlatır; etki organın görevine bağlıdır.'),
    sikli('Kandaki CO₂ artışına hızlı solunum yanıtı hangi merkezle ilgilidir?', ['Soğancık', 'Büyük beyin kabuğu'], 0, 'Beyin sapındaki soğancık solunum ritmini CO₂ değişimine göre ayarlar.'),
    soru('Sinirsel düzenleme genellikle hormonal düzene göre daha hızlı başlar ve kısa sürer.', true, 'Uyartılar belirli hücrelere hızla gider; hormonlar kanla daha yaygın ve uzun etki eder.'),
    sikli('Isı yükselince ter bezlerine emir gitmesi hangi işlevin sonucudur?', ['Yalnız omurilik refleksinin', 'Hipotalamus ve otonom yanıtın'], 1, 'Hipotalamus sıcaklığı karşılaştırır; otonom yollar ter bezlerini çalıştırır.'),
    soru('Uzun süreli sempatik etkinlik, kalp ve sindirim düzenini zorlayabilir.', true, 'Sürekli stres yüksek basınç ve sindirim sorunlarıyla ilişkili olabilir.'),
    sikli('Yemek sonrası toparlanmada hangi yanıt daha uygundur?', ['Kalbin yavaşlaması, sindirimin artması', 'Sindirimin azalması, kalbin hızlanması'], 0, 'Parasempatik kol dinlenme ve sindirim sırasında baskınlaşır.'),
    soru('Vücut ısısı artınca reseptör, hipotalamus ve efektörler bir kontrol halkası oluşturur.', true, 'Değişim algılanır, merkez karşılaştırır, damar ve ter bezleri yanıt verir.'),
    sikli('Sinirsel yanıtın hormona göre farkı hangisidir?', ['Kanla yaygın dağılması', 'Belirli hedefe hızla ulaşması'], 1, 'Sinirsel uyartı belirli yollardan çok hızlı iletilir.'),
  ],
  'byl11-endokrin': [
    soru('Bir hormon kanla her hücreye ulaştığı için bütün hücrelerde aynı etkiyi oluşturur.', false, 'Yalnızca uygun reseptörlü hedef hücreler hormona yanıt verir.'),
    sikli('Kan kalsiyumu düşerse hangi hormonun etkisi artmalıdır?', ['Parathormon', 'Kalsitonin'], 0, 'Parathormon kan kalsiyumunu yükseltir; kalsitonin düşürür.'),
    soru('İnsülin ile glukagon aynı değişkeni zıt yönlerde düzenler.', true, 'İnsülin kan şekerini düşürür, glukagon yükseltir.'),
    sikli('İyot eksikliğinde hangi hormonun yapımı zorlaşır?', ['Aldosteron', 'Tiroksin'], 1, 'Tiroksin yapısında iyot bulunur; eksikliği tiroit işleyişini etkiler.'),
    soru('Arka hipofiz ADH ve oksitosini depolayıp kana salabilir.', true, 'Hormonlar hipotalamusta üretilir; arka hipofizden salınır.'),
    sikli('Ani tehlikede kalbi hızlandıran böbrek üstü hormonu hangisidir?', ['Adrenalin', 'Kortizol'], 0, 'Adrenalin öz bölgesinden salgılanır; kortizol uzun süreli stres yanıtındadır.'),
    soru('Tiroksin artışı hipofiz ve hipotalamustaki uyarıyı azaltabilir.', true, 'Hormonun fazlası negatif geri bildirimle üretim zincirini frenler.'),
    sikli('Böbrekte Na⁺ tutulması ve kan hacmi artışı hangi hormonla ilişkilidir?', ['ADH', 'Aldosteron'], 1, 'Aldosteron Na⁺ geri emilimini artırır; su da sodyumu izleyebilir.'),
    soru('ADH eksikliği suyun geri emilimini artırıp idrarı koyulaştırır.', false, 'ADH azalırsa su geri emilimi düşer; bol ve seyreltik idrar oluşur.'),
    sikli('Kan şekeri yüksekken hangi pankreas hormonu daha uygundur?', ['İnsülin', 'Glukagon'], 0, 'İnsülin glikozun hücrelere alınmasını ve depolanmasını artırır.'),
    soru('Endokrin bezler hormonlarını bir kanalla sindirim boşluğuna verir.', false, 'Endokrin bezler kanalsızdır; hormonları doğrudan kana verir.'),
    sikli('Metabolizmanın yavaşlaması, üşüme ve yorgunluk hangi azlıkla uyumludur?', ['Adrenalin', 'Tiroksin'], 1, 'Tiroksin metabolizma hızını düzenler; azalınca bu belirtiler görülebilir.'),
    soru('Hormon etkisi, sinirsel yanıta göre genellikle daha yavaş başlar ama daha uzun sürebilir.', true, 'Hormon kanla taşınır ve hedef hücrede süreğen düzenleme sağlar.'),
  ],
  'byl11-dolasim-homeo': [
    soru('Kılcal duvarın ince olması, kan ile doku arasındaki gaz alışverişini engeller.', false, 'İnce duvar difüzyon mesafesini azaltarak O₂ ve CO₂ alışverişini kolaylaştırır.'),
    sikli('Sıcakta deri damarlarının genişlemesi hangi sonucu artırır?', ['Isı kaybını', 'Kasın ATP üretimini'], 0, 'Deriye daha çok sıcak kan gelir ve çevreye ısı aktarılır.'),
    soru('Atardamarların temel görevi kanı her zaman oksijenli olarak taşımaktır.', false, 'Atardamar kanı kalpten uzaklaştırır; akciğer atardamarı oksijence fakir kan taşır.'),
    sikli('Kan basıncı düşerse ilk telafi tepkisi hangisidir?', ['Kalbin yavaşlaması', 'Kalbin hızlanması'], 1, 'Basınç reseptörleri düşüşü bildirir; kalp ve damar yanıtı basıncı yükseltir.'),
    soru('Egzersizde çalışan kasa daha çok kan yönelmesi oksijen ve besin taşınmasını artırır.', true, 'Dolaşım çalışan dokunun artan gereksinimine uyum sağlar.'),
    sikli('Dokudan kalbe dönen sıvının taşınmasında hangi sistem görev alır?', ['Lenf sistemi', 'Solunum sistemi'], 0, 'Lenf damarları doku sıvısının dolaşıma geri dönmesine yardım eder.'),
    soru('Kalp, küçük dolaşımda kanı akciğere göndererek gaz alışverişine aracılık eder.', true, 'Kan akciğerde CO₂ verir, O₂ alır ve kalbe döner.'),
    sikli('Kandaki CO₂ hangi taşıyıcıyla hücrelerden akciğere ulaşır?', ['Sinirler', 'Dolaşım sistemi'], 1, 'Kan dokudan aldığı CO₂’yi akciğerlere taşır.'),
    soru('Deri damarlarının daralması soğukta ısı kaybını sınırlayabilir.', true, 'Deriye daha az kan yönelmesi dışarı ısı aktarımını azaltır.'),
    sikli('Besin ve gaz alışverişi hangi damarda en doğrudan gerçekleşir?', ['Kılcal damar', 'Büyük toplardamar'], 0, 'Kılcalın ince duvarı ve geniş yüzeyi doku alışverişine uygundur.'),
    soru('Alyuvarlar kanın oksijen taşımasına katkı verir.', true, 'Hemoglobin oksijeni bağlayıp dokulara taşır.'),
    sikli('Uzun süreli susuzluk kan hacmini azaltırsa hangi değer de düşebilir?', ['Alyuvar sayısı', 'Kan basıncı'], 1, 'Daha düşük kan hacmi damar içi basıncı azaltabilir.'),
  ],
  'byl11-solunum-homeo': [
    soru('Kandaki CO₂ arttığında solunum merkezi soluğu yavaşlatarak CO₂’yi biriktirir.', false, 'CO₂ artışı solunum merkezini uyarır; hızlanan soluk CO₂ atımını artırır.'),
    sikli('Alveolden kana geçmesi beklenen gaz hangisidir?', ['O₂', 'CO₂'], 0, 'Oksijen alveol havasından kana; karbondioksit kandan alveole geçer.'),
    soru('Hızlı soluma CO₂ atımını artırarak kanın asitliğini azaltabilir.', true, 'CO₂ azalınca karbonik asit dengesi değişir ve pH yükselir.'),
    sikli('Soluk tutulduğunda nefes alma isteğini özellikle ne artırır?', ['Kandaki O₂ artışı', 'Kandaki CO₂ artışı'], 1, 'CO₂ birikimi solunum merkezini güçlü biçimde uyarır.'),
    soru('Alveol duvarının kalınlaşması gaz alışverişini kolaylaştırır.', false, 'Gazların difüzyon mesafesi artar ve alışveriş zorlaşır.'),
    sikli('Egzersizde kaslar daha çok CO₂ üretirse solunum nasıl yanıt verir?', ['Hızlanır', 'Yavaşlar'], 0, 'Artan CO₂ ve asitlik solunum merkezini uyarır.'),
    soru('Karbon monoksit hemoglobine bağlanıp oksijen taşınmasını engelleyebilir.', true, 'CO hemoglobinle güçlü bağ kurar; dokulara O₂ taşınması azalır.'),
    sikli('Yüksek rakımda düşük O₂ basıncına uzun uyumda hangi değişim beklenir?', ['Alyuvarların azalması', 'Alyuvar üretiminin artması'], 1, 'Düşük oksijen koşulları uzun vadede alyuvar üretimini uyarır.'),
    soru('Soluk verme sırasında diyaframın gevşemesi göğüs hacmini azaltabilir.', true, 'Diyafram kubbeleşir ve akciğerlerden hava dışarı çıkar.'),
    sikli('Kandaki asitliği dakikalar içinde etkileyen homeostatik yol hangisidir?', ['CO₂ atımını değiştiren solunum', 'Yavaş işleyen böbrek pH ayarı'], 0, 'Solunum CO₂ miktarını hızla değiştirerek pH’ı etkiler.'),
    soru('Akciğerler yalnız oksijen almakla ilgilidir; pH dengesine katkı vermez.', false, 'CO₂ atımını ayarlayarak kanın asit-baz dengesine katkı verir.'),
    sikli('Alveolde gaz geçişinin temel yönünü ne belirler?', ['Aktif taşıma pompaları', 'Kısmi basınç farkı'], 1, 'Gazlar yüksek kısmi basınçtan düşüğe doğru difüze olur.'),
  ],
  'byl11-bosaltim-homeo': [
    soru('Glikoz sağlıklı nefronda süzülür ve idrarla düzenli olarak atılır.', false, 'Süzülen glikoz normalde tümüyle geri emilir; idrarda görülmesi olağan değildir.'),
    sikli('Su kaybından sonra idrar azalıyor ve koyulaşıyor. Hangi hormon artmıştır?', ['ADH', 'İnsülin'], 0, 'ADH toplama kanalında suyun geri emilimini artırır.'),
    soru('Kan hücreleri ve büyük proteinler normal süzülmede Bowman kapsülüne bolca geçer.', false, 'Sağlıklı süzme bariyeri bu büyük öğeleri kanda tutar.'),
    sikli('Nefronda H⁺ kandan kanalcığa verilirse hangi süreç gerçekleşir?', ['Geri emilim', 'Salgılama'], 1, 'Salgılamada madde kandan süzüntüye aktarılır; pH ayarına yardım eder.'),
    soru('Aldosteron Na⁺ geri emilimini artırarak su ve kan hacmini de etkileyebilir.', true, 'Su sodyumu izlediğinde kan hacmi ve basıncı artabilir.'),
    sikli('Süzülen sıvının büyük bölümünün yeniden kana dönmesi hangi basamaktır?', ['Geri emilim', 'Süzülme'], 0, 'Süzülmeden sonra yararlı su ve maddeler kanalcıklardan kana alınır.'),
    soru('Sağlıklı böbrekte idrar miktarı süzülen sıvı miktarına yaklaşık eşittir.', false, 'Süzülen sıvının çok büyük bölümü geri emilir; az bir bölümü idrar olur.'),
    sikli('İdrarda protein görülmesi hangi yapıda hasar düşündürür?', ['Nefronun geri emilim bölgesinde', 'Glomerul süzme bariyerinde'], 1, 'Büyük proteinler normalde süzüntüye geçmez; görülmeleri bariyer sorununu düşündürür.'),
    soru('Böbrek kan asitleştiğinde H⁺ atıp bikarbonatı geri alarak pH’ı düzenler.', true, 'Bu ayar solunuma göre yavaş ama uzun süre etkili olabilir.'),
    sikli('Böbrekte oluşan idrar mesaneye hangi yoldan gider?', ['Üreter', 'Üretra'], 0, 'Üreter böbrekten idrar kesesine taşır; üretra keseden dışarı çıkarır.'),
    soru('Alkol ADH’yi baskılarsa suyun geri emilimi azalabilir.', true, 'Daha çok su idrarla atılır; sık idrara çıkma görülür.'),
    sikli('Kan basıncı düşüp aldosteron artarsa böbrekte ne beklenir?', ['Daha az Na⁺ geri emilimi', 'Daha çok Na⁺ geri emilimi'], 1, 'Aldosteron tuz tutulmasını artırıp kan hacmini destekler.'),
  ],
  'byl11-es-gudum': [
    soru('Egzersizde solunum hızlanması çalışan kasa daha çok O₂ taşımaya tek başına yeterlidir.', false, 'Solunum O₂ alır; dolaşım da onu çalışan kasa taşımalıdır.'),
    sikli('Koşuda terleme su kaybını artırınca hangi yanıt tamamlayıcıdır?', ['ADH artışı ve böbrekte su tutulması', 'ADH azalması ve bol idrar'], 0, 'Kaybedilen suyu korumak için böbrek geri emilimi artırır.'),
    soru('Kan şekeri düşerken yalnız pankreas çalışır; karaciğerin bu dengeyle ilgisi yoktur.', false, 'Pankreas glukagon salar, karaciğer glikojeni yıkar ve kana glikoz verir.'),
    sikli('Yemekten sonra insülin artışı hangi işle birlikte beklenir?', ['Karaciğerde glikojen yıkımı', 'Karaciğerde glikojen depolanması'], 1, 'İnsülin yükselen kan şekerinin glikojen olarak depolanmasını destekler.'),
    soru('Hipotalamus sinirsel ve hormonal yanıtları bağlayarak sistemlerin eş güdümüne katkı verir.', true, 'Hipofiz üzerinden hormon salınımını yönlendirir; iç değişimleri sinirsel olarak da izler.'),
    sikli('Soğukta ısıyı koruyan iki eş zamanlı yanıt hangisidir?', ['Deri damarlarının daralması ve titreme', 'Deri damarlarının genişlemesi ve terleme'], 0, 'Damar daralması ısı kaybını azaltır, titreme ısı üretir.'),
    soru('Böbrek yetmezliği kan pH’ı ve basıncı gibi başka değişkenleri de bozabilir.', true, 'Su-tuz ve H⁺ ayarı bozulunca etkiler dolaşım ve asit-baz dengesine yayılır.'),
    sikli('Ani tehlikede sindirimin yavaşlayıp kanın kaslara yönelmesinde ne birlikte çalışır?', ['Parasempatik sistem ve insülin', 'Sempatik sistem ve adrenalin'], 1, 'İki yol savaş ya da kaç yanıtında kalp ve kaslara kaynak yönlendirir.'),
    soru('Homeostaziyi yalnız en güçlü tek organ sağlar; diğer sistemler birbirinden bağımsızdır.', false, 'Sinir, hormon, dolaşım, solunum ve böbrek yolları birbirini tamamlar.'),
    sikli('Koşuda CO₂ artışı ile vücut ısısı yükselişi hangi iki yanıtı tetikler?', ['Hızlı soluma ve terleme', 'Soluk yavaşlaması ve titreme'], 0, 'CO₂ artışı soluğu, ısı artışı terlemeyi hızlandırır.'),
    soru('Soğukta titreme kasla, damar daralması dolaşımla, metabolizma artışı hormonla ilişkilidir.', true, 'Aynı ısı dengesi için birkaç sistem farklı görev üstlenir.'),
    sikli('Böbrek yetersizliğinde kansızlık görülmesi hangi bağlantıyı gösterir?', ['Böbreğin alyuvarları doğrudan üretmesini', 'Alyuvar yapımını uyaran hormonun azalmasını'], 1, 'Böbrek bu hormonun üretimine katılır; yetmezlik kan hücresi yapımını etkileyebilir.'),
  ],
  'byl11-homeo-bozulma': [
    soru('Tip 1 diyabette sorun insülin üreten hücrelerin kaybıyla ilişkilidir.', true, 'Bağışıklık saldırısı pankreasın insülin üretimini azaltır ya da durdurur.'),
    sikli('İnsülin var ama hücre yanıtı yetersizse hangi durum daha uygundur?', ['Tip 2 diyabet', 'Tip 1 diyabet'], 0, 'Tip 2’de insülin direnci öne çıkar; tip 1’de üretim eksikliği belirgindir.'),
    soru('Şekersiz diyabette çok seyreltik idrarın nedeni doğrudan kan şekerinin yüksekliğidir.', false, 'ADH eksikliği ya da böbreğin ADH’ye yanıtsızlığı su kaybına yol açar; idrarda şeker yoktur.'),
    sikli('Çok seyreltik idrar, normal kan şekeri ve aşırı susama hangi soruna yakındır?', ['İnsülin direnci', 'ADH yolunda bozukluk'], 1, 'Şekersiz diyabette suyun geri emilimi aksar; kan şekeri normal kalabilir.'),
    soru('Diyabette kan şekeri uzun süre yüksek kalırsa böbrek ve damarlar zarar görebilir.', true, 'Sürekli yüksek glikoz birden çok organ sistemini etkiler.'),
    sikli('81 kg ve 1,80 m boy için BKİ yaklaşık kaçtır?', ['25', '45'], 0, '81 ÷ (1,80 × 1,80) = 81 ÷ 3,24 = 25.'),
    soru('Düşük tansiyonda ani ayağa kalkış baş dönmesine yol açabilir.', true, 'Basınç ayarı gecikirse beyne giden kan geçici olarak azalabilir.'),
    sikli('Tuz tüketimi ile basınç ilişkisi denenirken ölçülen bağımlı değişken nedir?', ['Günlük tuz miktarı', 'Kan basıncı'], 1, 'Tuz miktarı değiştirilen etken; basınç ölçülen sonuçtur.'),
    soru('BKİ tek başına bütün sağlık durumunu ve yağ dağılımını kesin olarak gösterir.', false, 'BKİ kütle-boy oranıdır; tek başına vücut bileşimini ya da tüm riski belirlemez.'),
    sikli('Sürekli yüksek basınç neden başka organlar için de risk taşır?', ['Damar, kalp ve böbreği zorlayabilir', 'Yalnız geçici baş dönmesi yapar'], 0, 'Uzun süreli yüksek basınç damar duvarı ve organlara yük bindirir.'),
    soru('Obezite, tip 2 diyabet ve yüksek tansiyon riskini artırabilir.', true, 'Aşırı yağ birikimi metabolik ve dolaşım yüküyle ilişkilidir.'),
    sikli('İdrarda glikoz ve yüksek kan şekeri varsa hangi bozukluk daha olasıdır?', ['Şekersiz diyabet', 'Şeker hastalığı'], 1, 'Diabetes mellitusta glikoz yüksek olup idrara geçebilir; insipidusta şeker normal olabilir.'),
  ],
}
