import { program, tema } from '../tip'
import { onBirinciSinifKonusu, type OnBirinciSinifKonusu } from './11-yardimci'
import { cografyaDerinligi } from './11-cografya-derinlik'

/** 11. sınıf Coğrafya; yedi ünite ve konu sırası MEB Maarif içerik çerçevesine dayanır. */
const taslaklar: OnBirinciSinifKonusu[][] = [
  [{
    id: 'cog11-mekansal-sorun', ad: 'Mekânsal Sorunlar Karşısında Coğrafya',
    kartlar: [
      ['Mekânsal sorun', 'Bir sorun yerle ilişkiliyse dağılışı ve çevresi incelenir.\nSel riski, trafik ve su kıtlığı buna örnektir.'],
      ['Dağılış sorusu', 'Coğrafya önce “Nerede yoğunlaşıyor?” diye sorar.\nHarita ve veri, örüntüyü görünür kılar.'],
      ['Neden ve sonuç', 'Eğim, iklim, nüfus ve arazi kullanımı birlikte ele alınır.\nTek bir neden çoğu sorunu açıklamaz.'],
      ['Ölçek seçimi', 'Mahalle ölçeğindeki sorun ile ülke ölçeğindeki sorun farklı veri ister.\nYanlış ölçek önemli ayrıntıyı gizler.'],
      ['Diğer bilimlerle ilişki', 'Coğrafya mühendislik, ekonomi ve sağlık verisinden yararlanır.\nKatkısı mekânsal bağlantıyı kurmaktır.'],
      ['Çözüm tasarlama', 'Riskli yeri belirle, nedenleri karşılaştır, etkileri tart.\nÖneriyi harita ve kanıtla destekle.'],
    ],
    not: 'Bir sorunu coğrafi yapan, sadece konumu değil konumlar arasındaki ilişki ve dağılıştır.',
    iddialar: [
      ['Coğrafya bir sorunun dağılışını haritayla inceleyebilir.', true, 'Mekânsal örüntü haritada görünür.'],
      ['Sel riski yalnızca yağış miktarına bağlıdır.', false, 'Eğim, zemin ve yapılaşma da etkilidir.'],
      ['Araştırma ölçeği seçilen veriyi etkiler.', true, 'Mahalle ve ülke farklı ayrıntı gerektirir.'],
      ['Mekânsal sorunlarda başka bilimlerin verileri kullanılamaz.', false, 'Coğrafya farklı alanlardan veri alır.'],
    ],
  }],
  [{
    id: 'cog11-cbs', ad: 'Web Tabanlı CBS Uygulamaları',
    kartlar: [
      ['CBS nedir?', 'Coğrafi bilgi sistemi, konuma bağlı verileri katmanlar hâlinde işler.\nHarita yalnızca resim değil, sorgulanabilir veridir.'],
      ['Katman mantığı', 'Nüfus, yol, akarsu ve yükseklik ayrı katman olabilir.\nÜst üste getirildiğinde ilişkiler aranır.'],
      ['Veri kaynağı', 'Veriyi resmî ve güncel kaynaktan al.\nTarih, ölçü birimi ve kapsanan alanı denetle.'],
      ['Tematik harita', 'Tek bir değişkenin dağılışını gösterir.\nRenk aralıkları ve lejant doğru okunmalıdır.'],
      ['Sorgulama', 'Örneğin okulların taşkın alanlarına yakınlığı incelenebilir.\nMesafe tek başına güvenlik kararı verdirmez.'],
      ['Harita üretimi', 'Başlık, ölçek, yön, lejant ve kaynak ekle.\nVeri eksikse haritada da belirt.'],
    ],
    not: 'İki katmanın çakışması nedensellik kanıtı değildir; harita bir soru üretir, tek başına hüküm vermez.',
    iddialar: [
      ['CBS konuma bağlı verileri katmanlar hâlinde gösterebilir.', true, 'Yol ve nüfus ayrı katman olabilir.'],
      ['Tematik haritada lejantın bulunması gereksizdir.', false, 'Renklerin neyi temsil ettiği lejantla anlaşılır.'],
      ['CBS verisinin tarihi ve kaynağı denetlenmelidir.', true, 'Eski veri yanlış çıkarıma yol açabilir.'],
      ['İki katmanın çakışması neden-sonuç ilişkisini kesin kanıtlar.', false, 'Ek karşılaştırma ve kanıt gerekir.'],
    ],
  }],
  [
    {
      id: 'cog11-su-kaynaklari', ad: 'Su Kaynakları',
      kartlar: [
        ['Su döngüsü', 'Buharlaşma, yoğunlaşma, yağış ve akış suyu dolaştırır.\nYenilenme hızı her kaynağa aynı değildir.'],
        ['Yüzey suları', 'Akarsu, göl ve sulak alan yüzey suyudur.\nAkış ve depolama koşulları farklıdır.'],
        ['Yer altı suyu', 'Sızan su geçirgen katmanlarda birikir.\nAşırı çekim su seviyesini düşürebilir.'],
        ['Tuzlu ve tatlı', 'Okyanus suyu tuzludur; içme ve sulama için doğrudan kullanılamaz.\nTatlı su toplamın küçük kısmıdır.'],
        ['Buz ve kar', 'Buzullar ve kar örtüsü tatlı suyu depolar.\nErime rejimi akarsuların akışını etkiler.'],
        ['Sınıflandırma', 'Suyu konumuna, tuzluluğuna ve yenilenme biçimine göre ayır.\nTek bir ölçüt bütün farkları göstermez.'],
      ],
      not: 'Yer altı suyu da su döngüsüne bağlıdır; depoda bulunması sınırsız olduğu anlamına gelmez.',
      iddialar: [
        ['Akarsu ve göller yüzey suyu kaynağıdır.', true, 'İkisi de yüzeyde bulunur.'],
        ['Yer altı suyu çekildikçe her zaman hemen yenilenir.', false, 'Yenilenme hızı çekimden yavaş olabilir.'],
        ['Buzullar tatlı su depolayabilir.', true, 'Kar ve buz önemli depolardır.'],
        ['Okyanus suyu doğrudan içme suyu olarak kullanılabilir.', false, 'Tuzludur; arıtma gerekir.'],
      ],
    },
    {
      id: 'cog11-turkiye-su', ad: 'Türkiye’deki Su Kaynaklarının Etkileri',
      kartlar: [
        ['Dağılış farklıdır', 'Yağış ve akış Türkiye’nin her yerinde aynı değildir.\nKurak ve nemli bölgelerin su yönetimi ayrışır.'],
        ['Tarım ve sulama', 'Sulama üretimi artırabilir.\nYanlış yöntem su kaybı ve toprakta tuzlanma doğurabilir.'],
        ['Enerji üretimi', 'Akarsu ve barajlardan hidroelektrik elde edilir.\nÜretim ile ekosistem etkisi birlikte tartılmalıdır.'],
        ['Kentlerin ihtiyacı', 'İçme suyu nüfus artışı ve kuraklıkla baskı altına girer.\nKayıp-kaçak azaltımı da çözümün parçasıdır.'],
        ['Sınır aşan sular', 'Bir akarsu birden fazla ülkeyi etkileyebilir.\nKullanım kararları iş birliği gerektirir.'],
        ['Kültür ve çevre', 'Göl, nehir ve sulak alan yaşam biçimini ve biyoçeşitliliği etkiler.\nSu yalnız ekonomik bir girdi değildir.'],
      ],
      not: 'Barajın enerji yararını değerlendirirken akış, yerleşim ve canlı yaşamına etkisini de sor.',
      iddialar: [
        ['Su kaynaklarının dağılışı Türkiye’de her bölgede aynıdır.', false, 'Yağış ve akış koşulları değişir.'],
        ['Yanlış sulama toprakta tuzlanmaya yol açabilir.', true, 'Buharlaşma ve drenaj sorunu tuzu biriktirir.'],
        ['Hidroelektrik üretiminin çevresel etkisi yoktur.', false, 'Akış ve habitat değişebilir.'],
        ['Sınır aşan sular ülkeler arasında iş birliği gerektirebilir.', true, 'Akarsu birden çok ülkeyi etkiler.'],
      ],
    },
  ],
  [
    {
      id: 'cog11-yerlesme', ad: 'Yerleşmelerin Mekânsal Organizasyonu',
      kartlar: [
        ['Yerleşme düzeni', 'Konut, iş, hizmet ve ulaşım mekânda belirli örüntüler oluşturur.\nBu düzen çevre koşullarıyla ilişkilidir.'],
        ['Doğal etkenler', 'Yer şekli, su ve iklim yer seçimini etkiler.\nDüz ova ile dağlık alan aynı yoğunlukta yerleşmez.'],
        ['Beşerî etkenler', 'İş, ulaşım ve kamu hizmeti insanları çeker.\nYatırımlar yeni merkezler doğurabilir.'],
        ['Kır ve kent', 'Kırda tarım alanı ve konut ilişkisi öne çıkar.\nKentte işlevler daha yoğun ve çeşitlidir.'],
        ['Merkez ve çevre', 'Kent merkezinde erişim yüksek, arazi pahalı olabilir.\nKonut ve sanayi işlevleri farklı bölgelere yayılır.'],
        ['Planlama', 'Taşkın yatağı ve fay gibi riskler yerleşim kararında önemlidir.\nMekânsal düzen yalnız bugünkü ihtiyaca göre kurulmaz.'],
      ],
      not: 'Yerleşme yeri seçimini yalnız iklimle açıklama; iş ve ulaşım da çoğu zaman belirleyicidir.',
      iddialar: [
        ['Ulaşım ağı yerleşmelerin büyümesini etkileyebilir.', true, 'Erişilebilirlik iş ve hizmetleri toplar.'],
        ['Yerleşmeler yalnızca iklime göre kurulur.', false, 'Ekonomi, su ve ulaşım da etkilidir.'],
        ['Kentte farklı işlevler farklı alanlarda yoğunlaşabilir.', true, 'Konut, ticaret ve sanayi bölgeleri ayrışabilir.'],
        ['Taşkın yatakları yerleşim planlamasında önemsizdir.', false, 'Afet riski yer seçimini belirler.'],
      ],
    },
    {
      id: 'cog11-etki-alani', ad: 'Yerleşmelerin Etki Alanları',
      kartlar: [
        ['Etki alanı', 'Bir yerleşme çevresine mal, hizmet ve iş sağlar.\nBu ilişkinin uzandığı alan etki alanıdır.'],
        ['Hizmet çeşitliliği', 'Uzman hastane ve üniversite daha uzak yerlerden insan çekebilir.\nGünlük bakkalın alanı dardır.'],
        ['Ulaşımın rolü', 'Hızlı ulaşım erişimi genişletebilir.\nMesafe yalnız kilometreyle ölçülmez; süre de önemlidir.'],
        ['Nüfus ve ekonomi', 'Büyük nüfus ve güçlü işlevler etki alanını büyütebilir.\nHer büyük kent aynı hizmetleri sunmaz.'],
        ['Kademelenme', 'Köy, ilçe ve büyük kent farklı hizmet düzeyleri sunar.\nİnsanlar bazı ihtiyaçlar için üst merkeze gider.'],
        ['Haritada izleme', 'Hasta, öğrenci veya alışveriş akışını haritalandır.\nEtki alanı idari sınırla aynı olmak zorunda değildir.'],
      ],
      not: 'Bir ilçenin idari sınırı ile hizmet verdiği gerçek alanı karıştırma.',
      iddialar: [
        ['Uzman hastane çevre yerleşmelerden hasta çekebilir.', true, 'Özel hizmetin etki alanı geniştir.'],
        ['Etki alanı her zaman il sınırında biter.', false, 'Hizmet akışı sınırı aşabilir.'],
        ['Ulaşım süresi etki alanını değiştirebilir.', true, 'Erişim kolaylaşınca daha uzak yerler bağlanır.'],
        ['Bakkal ile üniversitenin etki alanı daima aynıdır.', false, 'Hizmetin niteliği alanı etkiler.'],
      ],
    },
  ],
  [
    {
      id: 'cog11-gida', ad: 'Tarımsal Faaliyetler ve Gıda Güvencesi',
      kartlar: [
        ['Gıda güvencesi', 'İnsanların yeterli ve güvenli gıdaya sürekli erişebilmesidir.\nÜretim miktarı tek başına yeterli değildir.'],
        ['Dört boyut', 'Bulunabilirlik, erişim, kullanım ve süreklilik birlikte düşünülür.\nGıda var ama pahalıysa erişim sorunu vardır.'],
        ['İklim riski', 'Kuraklık, don ve aşırı yağış hasadı etkiler.\nTek ürüne bağlı üretim riski büyütür.'],
        ['Toprak ve su', 'Verimli toprak ile güvenilir su tarımın temelidir.\nAşırı kullanım gelecek üretimi azaltır.'],
        ['Dağıtım zinciri', 'Depolama, taşıma ve soğuk zincir kaybı azaltır.\nÜretim ile tüketim arasındaki kopukluk israfa yol açar.'],
        ['Çözüm birlikte', 'Çeşitlendirme, yerel üretim ve erişilebilir fiyat önemlidir.\nSosyal ve çevresel koşullar birlikte değerlendirilir.'],
      ],
      not: 'Gıda güvencesi “ülkede gıda var” cümlesinden daha geniştir: herkesin erişimi gerekir.',
      iddialar: [
        ['Gıdaya erişim, gıda güvencesinin parçasıdır.', true, 'Üretim olsa da erişim engeli olabilir.'],
        ['Bir ülkede bol üretim varsa herkes otomatik olarak yeterli beslenir.', false, 'Fiyat ve dağıtım erişimi etkiler.'],
        ['Kuraklık hasat miktarını etkileyebilir.', true, 'Su eksikliği verimi düşürebilir.'],
        ['Soğuk zincir gıda kayıplarını artırmak için kurulur.', false, 'Bozulmayı azaltmaya yarar.'],
      ],
    },
    {
      id: 'cog11-surdurulebilir-tarim', ad: 'Tarım Uygulamalarında Sürdürülebilirlik',
      kartlar: [
        ['Temel ölçüt', 'Bugünkü üretim toprağın ve suyun gelecekteki verimini tüketmemeli.\nEkonomik geçim de korunmalı.'],
        ['Sulama yöntemi', 'Damla sulama suyu kök bölgesine verir.\nYine de toplam kullanım ve yerel koşullar izlenmelidir.'],
        ['Toprak koruma', 'Eğimli arazide teras ve bitki örtüsü erozyonu azaltır.\nÇıplak toprak kayba açıktır.'],
        ['Ürün çeşitliliği', 'Ekim nöbeti toprağın tek yönlü kullanımını azaltabilir.\nHastalık ve fiyat riskini dağıtır.'],
        ['Girdi kullanımı', 'Gübre ve ilaç ihtiyaca göre verilmelidir.\nAşırı kullanım suyu ve toprağı kirletebilir.'],
        ['Karar verme', 'Verim, su tüketimi, toprak sağlığı ve çiftçi geliri birlikte ölçülür.\nTek bir sayı sürdürülebilirliği kanıtlamaz.'],
      ],
      not: 'Yüksek verim tek başına sürdürülebilirlik değildir; kaynak kaybını da ölç.',
      iddialar: [
        ['Ekim nöbeti tek ürüne bağlılığı azaltabilir.', true, 'Riskleri ve toprağın yükünü dağıtır.'],
        ['Gübreyi ne kadar çok kullanırsak çevresel etki o kadar azalır.', false, 'Aşırı kullanım kirliliğe yol açabilir.'],
        ['Erozyon toprağın verimli katmanını götürebilir.', true, 'Toprak koruma bu yüzden önemlidir.'],
        ['Yüksek ürün miktarı sürdürülebilirliği tek başına kanıtlar.', false, 'Su ve toprak üzerindeki etkiler de incelenir.'],
      ],
    },
    {
      id: 'cog11-maden', ad: 'Stratejik ve Kritik Madenler',
      kartlar: [
        ['İki terim', 'Stratejik maden ekonomi ve güvenlik için önem taşır.\nKritiklikte arz kesintisi riski de öne çıkar.'],
        ['Neden önemli?', 'Batarya, elektronik ve savunma üretimi çeşitli minerallere bağlıdır.\nTedarik zinciri ülkeleri birbirine bağlar.'],
        ['Dağılış', 'Yataklar dünyaya eşit dağılmamıştır.\nÇıkarma ile işleme çoğu zaman farklı ülkelerde yapılır.'],
        ['Türkiye örneği', 'Bor mineralleri Türkiye için önemli bir kaynaktır.\nHam madeni katma değerli ürüne dönüştürmek ayrı aşamadır.'],
        ['Çevresel maliyet', 'Madencilik su, toprak ve habitat üzerinde baskı yaratabilir.\nRehabilitasyon planı çıkarma kadar önemlidir.'],
        ['Tedarik güvenliği', 'Geri dönüşüm, çeşitlendirme ve teknoloji arz riskini azaltabilir.\nTek kaynağa bağımlılık kırılgandır.'],
      ],
      not: '“Maden var” demek “işlenmiş üründe güçlü” demek değildir; değer zincirine bak.',
      iddialar: [
        ['Maden yatağı ile işleme tesisi farklı ülkelerde olabilir.', true, 'Tedarik zinciri birden çok ülkeye yayılır.'],
        ['Kritik madenlerin arzında kesinti riski önemsizdir.', false, 'Kritiklikte arz güvenliği önemlidir.'],
        ['Geri dönüşüm bazı madenlerde tedarik baskısını azaltabilir.', true, 'Birincil kaynağa bağımlılığı düşürebilir.'],
        ['Madenciliğin çevresel etkisi bulunmaz.', false, 'Su, toprak ve habitat etkilenebilir.'],
      ],
    },
    {
      id: 'cog11-enerji', ad: 'Enerji Kaynakları',
      kartlar: [
        ['Kaynakları ayır', 'Kömür, petrol ve doğal gaz fosil kaynaklardır.\nGüneş, rüzgâr ve akarsu yenilenebilir kaynaklardır.'],
        ['Kullanım değişiyor', 'Teknoloji ve fiyatlar enerji karışımını etkiler.\nBir kaynağın payı zamanla artıp azalabilir.'],
        ['Fosil yakıt etkisi', 'Yakıldığında sera gazı ve hava kirleticileri açığa çıkar.\nÇıkarma ve taşıma da çevreyi etkiler.'],
        ['Yenilenebilir sınırı', 'Güneş ve rüzgârın üretimi hava koşuluna bağlıdır.\nDepolama ve şebeke yönetimi gerekir.'],
        ['Enerji güvenliği', 'Kaynak çeşitliliği ve verimlilik dışa bağımlılığı azaltabilir.\nYalnız yeni santral kurmak çözüm değildir.'],
        ['Karşılaştırma', 'Kaynakları maliyet, süreklilik, emisyon ve yer seçimiyle karşılaştır.\nHer koşulda tek bir “en iyi” kaynak yoktur.'],
      ],
      not: 'Yenilenebilir kaynak da etkisiz değildir; çevreye ve şebekeye etkisini birlikte incele.',
      iddialar: [
        ['Petrol fosil enerji kaynağıdır.', true, 'Yenilenemez fosil yakıttır.'],
        ['Güneş enerjisi gece de aynı düzeyde elektrik üretir.', false, 'Üretim güneş ışığına bağlıdır.'],
        ['Enerji verimliliği kaynak ihtiyacını azaltabilir.', true, 'Aynı işi daha az enerjiyle yapmak mümkündür.'],
        ['Bütün enerji kaynaklarının çevresel etkisi aynıdır.', false, 'Etkiler kaynağa ve yere göre değişir.'],
      ],
    },
    {
      id: 'cog11-sanayi-mekan', ad: 'Sanayileşmenin Mekânsal Etkileri',
      kartlar: [
        ['Yer seçimi', 'Sanayi ham madde, enerji, işgücü ve pazara erişimi tartar.\nUlaşım maliyeti de kararı değiştirir.'],
        ['Kümelenme', 'Yakın tesisler tedarikçi ve uzman işgücünü paylaşabilir.\nBu, bölgenin çekim gücünü artırır.'],
        ['Kentleşme', 'İş olanakları göç çeker.\nKonut, ulaşım ve altyapı ihtiyacı büyür.'],
        ['Çevresel etki', 'Atık ve emisyon su ile havayı etkileyebilir.\nArıtma ve denetim bu yüzden gereklidir.'],
        ['Bölgesel fark', 'Yatırımın yoğunlaştığı yer büyürken diğerleri geride kalabilir.\nBölgesel politika denge arar.'],
        ['Dönüşüm', 'Eski sanayi alanları işlev değiştirebilir.\nYeni teknoloji bazı yerlerde üretimi yeniden toplar.'],
      ],
      not: 'Sanayinin etkisini yalnız fabrika arsasında arama; göç, trafik ve konut çevreye yayılır.',
      iddialar: [
        ['Ulaşım maliyeti sanayi tesisinin yerini etkileyebilir.', true, 'Ham madde ve pazar bağlantısı önemlidir.'],
        ['Sanayi kente göçü hiçbir zaman etkilemez.', false, 'İş olanakları göç çekebilir.'],
        ['Arıtma, sanayi atığının etkisini azaltabilir.', true, 'Su ve hava üzerindeki baskı azaltılabilir.'],
        ['Sanayinin etkisi yalnız tesis binasında kalır.', false, 'Konut, ulaşım ve çevreye yayılır.'],
      ],
    },
  ],
  [
    {
      id: 'cog11-gezegen-siniri', ad: 'Gezegen Sınırı',
      kartlar: [
        ['Kavram', 'Gezegen sınırları, insan faaliyetlerinin bozabileceği çevresel süreçleri anlatır.\nGüvenli işleyiş alanı hedeflenir.'],
        ['İklim sistemi', 'Sera gazı birikimi enerji dengesini değiştirir.\nIsınma başka çevre süreçlerini de etkiler.'],
        ['Canlı çeşitliliği', 'Habitat kaybı türleri ve ekosistem işlevlerini zayıflatır.\nYalnız tür sayısı değil ilişkiler de önemlidir.'],
        ['Su ve toprak', 'Tatlı su çekimi ile arazi değişimi sınırlar üzerinde baskı kurar.\nYerel etkiler küresel sonuç doğurabilir.'],
        ['Döngüler', 'Azot ve fosforun aşırı kullanımı su ekosistemlerini etkiler.\nTarım uygulaması bu döngülere bağlıdır.'],
        ['Çözüm yaklaşımı', 'Tüketim, üretim ve koruma birlikte ele alınır.\nTek bir sorunu düzeltmek bütün sistemi düzeltmeyebilir.'],
      ],
      not: 'Gezegen sınırı “tek bir sayıyı geçince her şey biter” demek değil; artan sistem riskini anlatır.',
      iddialar: [
        ['Habitat kaybı canlı çeşitliliğini etkileyebilir.', true, 'Yaşam alanı türlerin sürmesi için gereklidir.'],
        ['Tatlı su çekimi çevresel süreçlerden bağımsızdır.', false, 'Su döngüsü ve ekosistemler etkilenir.'],
        ['Azotun aşırı kullanımı su ekosistemlerini bozabilir.', true, 'Besin yükü artışı kirlilik yaratabilir.'],
        ['Gezegen sınırları yalnız iklim değişikliğinden oluşur.', false, 'Su, arazi ve canlı çeşitliliği de vardır.'],
      ],
    },
    {
      id: 'cog11-iklim', ad: 'Küresel İklim Değişikliği',
      kartlar: [
        ['Temel neden', 'İnsan kaynaklı sera gazları ısı tutulmasını artırır.\nFosil yakıt kullanımı başlıca kaynaktır.'],
        ['Azaltım', 'Emisyonu düşürmek iklim değişikliğinin hızını sınırlar.\nVerimlilik ve temiz enerji buna örnektir.'],
        ['Uyum', 'Kaçınılmaz etkilere hazırlanmak uyumdur.\nSel erken uyarısı ve kuraklığa dayanıklı tarım örnektir.'],
        ['Etkiler', 'Sıcak hava dalgaları, yağış düzeni ve su erişimi değişebilir.\nEtki bölgeden bölgeye farklıdır.'],
        ['Adalet boyutu', 'Etkiden en çok zarar görenler en çok emisyon yayanlar olmayabilir.\nUyum kapasitesi eşit dağılmaz.'],
        ['İki yol birlikte', 'Azaltım gelecekteki riski, uyum bugünkü kırılganlığı hedefler.\nBiri diğerinin yerine geçmez.'],
      ],
      not: '“Azaltım” emisyonu, “uyum” etkiden doğan zararı hedefler; ikisini karıştırma.',
      iddialar: [
        ['Erken sel uyarısı iklim değişikliğine uyum örneğidir.', true, 'Mevcut riske hazırlık sağlar.'],
        ['Emisyon azaltımı uyumla aynı anlama gelir.', false, 'Azaltım nedeni, uyum etkiyi hedefler.'],
        ['İklim etkileri her bölgede aynı düzeyde yaşanır.', false, 'Coğrafi ve toplumsal koşullar değişir.'],
        ['Enerji verimliliği emisyon azaltımına katkı verebilir.', true, 'Aynı hizmet daha az enerjiyle sağlanır.'],
      ],
    },
    {
      id: 'cog11-su-surdurulebilir', ad: 'Türkiye’de Suyun Sürdürülebilir Kullanımı',
      kartlar: [
        ['Su bütçesi', 'Çekilen su, kaynağın yenilenme ve ekosistem ihtiyacıyla karşılaştırılır.\nYıllık ortalama tek başına yeterli değildir.'],
        ['Tarımda kullanım', 'Sulama büyük su talebi doğurur.\nÜrün seçimi ve doğru zamanlama tasarruf sağlar.'],
        ['Şehir şebekesi', 'Boru kayıpları ve kaçaklar giderilirse yeni kaynak arama baskısı azalır.\nÖlçüm ve bakım gerekir.'],
        ['Yer altı suyu', 'Aşırı çekim seviye düşüşüne ve bazı alanlarda çökme riskine yol açar.\nİzin ve izleme önemlidir.'],
        ['Kirlilik', 'Atık su arıtımı kullanılabilir suyu korur.\nKirlenen kaynağı temizlemek çoğu zaman pahalıdır.'],
        ['Havza yaklaşımı', 'Yukarı ve aşağı kesimdeki kararlar birbirini etkiler.\nYönetim havza bütününde yapılmalıdır.'],
      ],
      not: 'Tasarruf sadece musluğu kısmak değil; tarım, şebeke ve havza yönetimini birlikte düzeltmektir.',
      iddialar: [
        ['Şebeke kayıplarını azaltmak su tasarrufu sağlar.', true, 'Kaybolan su kullanılabilir hâle gelir.'],
        ['Yer altı suyu sınırsız hızla yenilenir.', false, 'Çekim yenilenmeyi aşabilir.'],
        ['Atık su arıtımı kaynakların korunmasına katkı verir.', true, 'Kirlilik baskısı azalır.'],
        ['Havzanın yukarısındaki kullanım aşağı kesimi etkilemez.', false, 'Aynı akış sistemi bağlıdır.'],
      ],
    },
  ],
  [
    {
      id: 'cog11-kulturel-hinterland', ad: 'Türkiye’nin Kültürel Hinterlandı',
      kartlar: [
        ['Hinterland', 'Bir merkezin ilişkilerinin uzandığı çevredir.\nKültürel bağ siyasi sınırdan daha geniş olabilir.'],
        ['Tarihî bağ', 'Ortak tarih, dil ve göç geçmişi etkileşimi güçlendirebilir.\nHer bağın derecesi aynı değildir.'],
        ['Türk dünyası', 'Orta Asya ve Kafkasya’daki bazı toplumlarla dil ve kültür bağları vardır.\nBu coğrafya tek tip değildir.'],
        ['Balkanlar', 'Osmanlı mirası, göç ve aile bağları kültürel etkileşim yaratır.\nGüncel ilişkiler de değişir.'],
        ['Etkinin yolları', 'Eğitim, turizm, medya ve ticaret kültürel teması artırır.\nTek yönlü etki varsayılmaz.'],
        ['Kanıtla yorum', 'Dil, kültür kurumu ve göç verilerini karşılaştır.\nBir ülkeyi yalnız tarihî yakınlıkla tanımlama.'],
      ],
      not: 'Kültürel hinterland, siyasi egemenlik alanı değildir; ilişki ve etkileşim ağıdır.',
      iddialar: [
        ['Kültürel bağlar devlet sınırlarının ötesine uzanabilir.', true, 'Dil ve göç bağları sınır aşar.'],
        ['Kültürel hinterland siyasi egemenlikle aynı şeydir.', false, 'Etkileşim ağı, yönetim sınırı değildir.'],
        ['Balkanlarla göç ve aile bağları etkileşimi etkileyebilir.', true, 'Tarihî ve güncel bağlantılar vardır.'],
        ['Türk dünyasındaki bütün toplumlar tamamen aynıdır.', false, 'Farklı tarih ve kültür özellikleri bulunur.'],
      ],
    },
    {
      id: 'cog11-tarim-ulke', ad: 'Tarımsal Üretim: Örnek Ülke',
      kartlar: [
        ['Ülkeyi tanı', 'İklim, toprak, su ve nüfus tarımsal üretimi etkiler.\nÜrünü bu koşullarla birlikte incele.'],
        ['Verim ve miktar', 'Toplam üretim ile hektar başına verim farklı ölçüdür.\nBüyük alan her zaman yüksek verim demek değildir.'],
        ['Gıda ihtiyacı', 'Üretimi nüfus ve tüketimle karşılaştır.\nİhracat yapan ülke de bazı ürünleri ithal edebilir.'],
        ['Gelir etkisi', 'Tarım iş, ihracat ve sanayiye girdi sağlar.\nKatma değer işleme ve lojistikle artabilir.'],
        ['Dışa bağlılık', 'Tohum, gübre ve enerji ithalatı üretim maliyetini etkiler.\nÜrün bağımsızlığı girdi bağımsızlığı değildir.'],
        ['Karşılaştırma', 'Aynı yılın güvenilir verilerini kullan.\nİklim, verim, tüketim ve gelir arasında neden-sonuç ara.'],
      ],
      not: 'Çok üretmek ile halkın gıdaya erişmesi ayrı sorulardır; veri ikisini de göstermeli.',
      iddialar: [
        ['Toplam üretim ile birim alan verimi farklıdır.', true, 'Alan büyüklüğü toplam miktarı etkiler.'],
        ['İhracat yapan ülke hiçbir tarım ürünü ithal etmez.', false, 'Farklı ürünlerde ithalat olabilir.'],
        ['İşlenmiş ürün tarımın katma değerini artırabilir.', true, 'Ham ürüne işlem ve hizmet eklenir.'],
        ['Tarımsal üretim iklimden bağımsızdır.', false, 'Sıcaklık ve yağış ürün yetişmesini etkiler.'],
      ],
    },
    {
      id: 'cog11-sanayi-ulke', ad: 'Sanayileşme Süreci: Örnek Ülkeler',
      kartlar: [
        ['Karşılaştırma zemini', 'Ülkelerin sanayileşme zamanını, sektörünü ve konumunu belirle.\nTek sayı süreç farkını açıklamaz.'],
        ['İlk koşullar', 'Kömür, demir ve liman bazı erken sanayi bölgelerini destekledi.\nTeknolojiyle bu bağlılık değişebilir.'],
        ['Emek ve eğitim', 'Nitelikli işgücü yeni sanayiler için önemlidir.\nEğitim yatırımı üretimin türünü etkiler.'],
        ['Ulaşım ve pazar', 'Liman, demiryolu ve pazar erişimi maliyeti düşürür.\nKüresel ağlar üretimi farklı ülkelere dağıtır.'],
        ['Politika', 'Yatırım, ticaret ve teknoloji politikaları sanayi yapısını şekillendirir.\nDoğal kaynak tek başına kader değildir.'],
        ['Sonuçları ölç', 'İstihdam, ihracat ve çevresel etkiyi birlikte incele.\nYüksek üretim her zaman eşit refah yaratmaz.'],
      ],
      not: 'Ülkeleri “sanayileşmiş/sanayileşmemiş” diye bırakma; hangi yolla geliştiklerine bak.',
      iddialar: [
        ['Liman erişimi sanayi maliyetini etkileyebilir.', true, 'Taşıma kolaylaşabilir.'],
        ['Doğal kaynak yoksa sanayi hiçbir koşulda gelişemez.', false, 'Teknoloji, eğitim ve ticaret de belirleyicidir.'],
        ['Nitelikli işgücü sanayinin türünü etkiler.', true, 'Teknoloji yoğun üretim uzmanlık ister.'],
        ['Sanayileşmeyi yalnız fabrika sayısıyla açıklamak yeterlidir.', false, 'Sektör ve etkiler de incelenmelidir.'],
      ],
    },
    {
      id: 'cog11-madencilik-ulke', ad: 'Madencilik Faaliyetleri: Örnek Ülke',
      kartlar: [
        ['Kaynağı bul', 'Hangi maden, nerede ve ne miktarda çıkarılıyor?\nRezerv ile yıllık üretimi ayrı oku.'],
        ['Değer zinciri', 'Çıkarma, zenginleştirme, işleme ve ihracat farklı aşamalardır.\nGelir aşamaya göre değişir.'],
        ['Grafik seçimi', 'Yıllara göre üretim çizgi; maden payları sütun grafikle gösterilebilir.\nBirim ve kaynak yaz.'],
        ['Ekonomik etki', 'İstihdam ve ihracat geliri yaratabilir.\nFiyat değişimi geliri oynatır.'],
        ['Çevresel etki', 'Atık, su kullanımı ve arazi bozulması izlenmelidir.\nKapanış sonrası rehabilitasyon planı gerekir.'],
        ['Yorum sınırı', 'Rezervin büyük olması o yıl üretimin yüksek olduğunu kanıtlamaz.\nİki göstergeyi ayrı değerlendir.'],
      ],
      not: 'Rezerv yer altındaki potansiyel, üretim çıkarılan miktardır; tabloda birimlerini de ayır.',
      iddialar: [
        ['Rezerv ve yıllık üretim aynı ölçü değildir.', true, 'Biri potansiyel, diğeri çıkarılan miktardır.'],
        ['Grafikte ölçü birimi yazılmasa da karşılaştırma kesindir.', false, 'Birim bilinmezse sayı yorumlanamaz.'],
        ['Maden fiyatı ihracat gelirini etkileyebilir.', true, 'Miktar aynı kalsa fiyat değişebilir.'],
        ['Madencilikten sonra araziyi iyileştirmeye gerek yoktur.', false, 'Rehabilitasyon çevresel zararları azaltır.'],
      ],
    },
    {
      id: 'cog11-enerji-ulke', ad: 'Enerji Kaynakları: Örnek Ülkeler',
      kartlar: [
        ['Enerji karması', 'Bir ülkenin elektrik üretiminde hangi kaynakların payı olduğuna bak.\nÜretim ile toplam enerji tüketimini karıştırma.'],
        ['Doğal olanak', 'Güneşlenme, rüzgâr ve akarsu potansiyeli ülkeden ülkeye değişir.\nTeknoloji ve yatırım kullanımı belirler.'],
        ['İthalat bağımlılığı', 'Kaynağı bulunmayan ülke ithalata yönelebilir.\nFiyat ve tedarik kesintisi riski doğar.'],
        ['Emisyon farkı', 'Fosil ağırlıklı üretim daha çok sera gazı yaratabilir.\nKaynakları yaşam döngüsüyle karşılaştırmak gerekir.'],
        ['Zaman değişimi', 'Bir yılın payı kalıcı eğilim değildir.\nBirden çok yıla ve kurulu güç ile gerçek üretim farkına bak.'],
        ['Politika önerisi', 'Çeşitlendirme, depolama ve verimlilik birlikte düşünülebilir.\nÜlkenin koşuluna uygun çözüm seç.'],
      ],
      not: 'Kurulu güç santralin kapasitesi, üretim gerçekten ürettiği elektriktir; eşit değiller.',
      iddialar: [
        ['Enerji karması ülkeden ülkeye değişebilir.', true, 'Doğal olanak ve politika farklıdır.'],
        ['Kurulu güç her zaman gerçek üretimle aynıdır.', false, 'Çalışma süresi ve koşullar farklıdır.'],
        ['Tek kaynağa bağımlılık tedarik riskini artırabilir.', true, 'Kesinti için yedek azalır.'],
        ['Bir yıllık veri kalıcı eğilimi kanıtlar.', false, 'Yıllar arası değişime bakılmalıdır.'],
      ],
    },
  ],
]

export const cografya11 = program('cografya', 11, 'Mekândan kaynaklara ve dünyaya', [
  tema('cog11-t1', 'Coğrafyanın Doğası', taslaklar[0].map((t) => onBirinciSinifKonusu(t, cografyaDerinligi[t.id]))),
  tema('cog11-t2', 'Mekânsal Bilgi Teknolojileri', taslaklar[1].map((t) => onBirinciSinifKonusu(t, cografyaDerinligi[t.id]))),
  tema('cog11-t3', 'Doğal Sistemler Ve Süreçler', taslaklar[2].map((t) => onBirinciSinifKonusu(t, cografyaDerinligi[t.id]))),
  tema('cog11-t4', 'Beşerî Sistemler Ve Süreçler', taslaklar[3].map((t) => onBirinciSinifKonusu(t, cografyaDerinligi[t.id]))),
  tema('cog11-t5', 'Ekonomik Faaliyetler Ve Etkileri', taslaklar[4].map((t) => onBirinciSinifKonusu(t, cografyaDerinligi[t.id]))),
  tema('cog11-t6', 'Afetler Ve Sürdürülebilir Çevre', taslaklar[5].map((t) => onBirinciSinifKonusu(t, cografyaDerinligi[t.id]))),
  tema('cog11-t7', 'Bölgeler, Ülkeler Ve Küresel Bağlantılar', taslaklar[6].map((t) => onBirinciSinifKonusu(t, cografyaDerinligi[t.id]))),
])
