import { sikli, soru } from '../tip'

type Iddia = [ifade: string, dogru: boolean, aciklama: string]
type Secim = [soru: string, dogru: string, yanlis: string, aciklama: string]
type Soru = ReturnType<typeof soru> | ReturnType<typeof sikli>

/** Doğru şıkkın yeri, konu ve soru sırasına göre dönüşümlü belirlenir. */
function derle(id: string, iddialar: Iddia[], secimler: Secim[]): Soru[] {
  const sonuc: Soru[] = []
  const enCok = Math.max(iddialar.length, secimler.length)
  for (let i = 0; i < enCok; i++) {
    if (i < iddialar.length) sonuc.push(soru(...iddialar[i]))
    if (i < secimler.length) {
      const [metin, dogru, yanlis, aciklama] = secimler[i]
      const konum = ((id.length + i) % 2) as 0 | 1
      sonuc.push(sikli(metin, konum === 0 ? [dogru, yanlis] : [yanlis, dogru], konum, aciklama))
    }
  }
  return sonuc
}

export const fizik11Sorulari: Record<string, Soru[]> = {
  'fzk11-serbest': derle('fzk11-serbest', [
    ['Hava direnci yoksa farklı kütleli cisimler aynı yükseklikten aynı anda yere ulaşır.', true, 'Serbest düşme ivmesi g, kütleden bağımsızdır.'],
    ['Serbest düşen cismin ağırlığı artarken ivmesi de artar.', false, 'Ağırlık m ile artsa da F/m oranı g olarak kalır.'],
    ['g = 10 m/s² iken 2 saniye serbest düşen cismin hızı 20 m/s olur.', true, 'İlk hız sıfırdır; v = g·t = 10·2 = 20 m/s.'],
    ['Serbest düşmede eşit sürelerde alınan yollar eşittir.', false, 'Hız arttığı için ardışık saniyelerde 5, 15, 25 m alınır.'],
    ['Düşme yüksekliği dört kat olursa düşme süresi iki kat olur.', true, 't = √(2h/g); süre yüksekliğin kareköküyle değişir.'],
    ['Yukarı atılan cismin tepesinde hem hızı hem ivmesi sıfırdır.', false, 'Tepede hız sıfırdır; ivme yine aşağı yönlü g değerindedir.'],
    ['Aşağı atılan cismin ivmesi, serbest bırakılanınkinden daha büyüktür.', false, 'İlk hızlar farklı olsa da hava direnci yoksa ikisinin ivmesi g olur.'],
  ], [
    ['g = 10 iken 3 saniye düşen cismin toplam yolu kaç metredir?', '45 m', '30 m', 'h = ½gt² = 5·9 = 45 m.'],
    ['g = 10 iken ilk 2 saniyede 20 m düşen cisim 3. saniyede kaç metre iner?', '25 m', '45 m', 'Üç saniyedeki toplam 45 m; son saniyedeki yol 45−20 = 25 m.'],
    ['g = 10 iken 80 m’den bırakılan cismin çarpma hızı kaçtır?', '40 m/s', '80 m/s', 't = 4 s, v = gt = 40 m/s.'],
    ['20 m/s hızla yukarı atılan cisim tepeye kaç saniyede çıkar? (g = 10)', '2 s', '4 s', 'Tepede v = 0; t = v₀/g = 2 s.'],
    ['Hız-zaman grafiğinde doğrunun eğimi hangi niceliği verir?', 'Yer çekimi ivmesini', 'Düşülen toplam yolu', 'v = gt olduğundan eğim g; yol grafiğin altındaki alandır.'],
    ['Aynı yerde iki cisimden birinin kütlesi iki katına çıkarsa düşme süresi nasıl değişir?', 'Değişmez', 'İki katına çıkar', 'Serbest düşmede süre yalnız h ve g değerlerine bağlıdır.'],
    ['Hava direncinin etkisini ayırmak için hangi deney uygundur?', 'Vakumda tüy ve para bırakmak', 'Açık havada tüy ve para bırakmak', 'Vakumda hava direnci ortadan kalkar; iki cisim birlikte düşer.'],
  ]),
  'fzk11-iki-boyut': derle('fzk11-iki-boyut', [
    ['Yatay atışta yatay ve düşey hareketin ortak değişkeni zamandır.', true, 'İki bileşen bağımsız çözülür; ikisinde de aynı t kullanılır.'],
    ['Yatay atış hızını artırmak, aynı yükseklikten düşme süresini kısaltır.', false, 'Düşme süresini yalnız düşey hareket, yani yükseklik ve g belirler.'],
    ['Hava direnci yoksa yatay atışta yatay hız sabit kalır.', true, 'Yatay yönde ivme yoktur; x = v₀t.'],
    ['Eğik atışta tepe noktasında cismin sürati sıfır olur.', false, 'Yalnız düşey hız sıfırlanır; yatay bileşen sürer.'],
    ['Aynı hızla ve 30° ile 60° açılarla atışların menzilleri eşittir.', true, 'Menzil sin 2α ile değişir; sin 60° = sin 120°.'],
    ['Eğik atışta yatay hız bileşeni uçuş boyunca büyür.', false, 'Yatay yönde ivme yoksa yatay hız sabit kalır.'],
    ['Aynı seviyeye dönen eğik atışta çıkış süresi toplam uçuş süresine eşittir.', false, 'Çıkış süresi v₀ᵧ/g, uçuş süresi bunun iki katıdır.'],
  ], [
    ['45 m yükseklikten 10 m/s ile yatay atılan cisim kaç metre uzağa düşer? (g = 10)', '30 m', '45 m', 'Düşme süresi 3 s; menzil 10·3 = 30 m.'],
    ['Yatay atışta 2 s sonra düşey hız kaçtır? (g = 10)', '20 m/s', '10 m/s', 'Başlangıç düşey hızı sıfır; vᵧ = gt = 20 m/s.'],
    ['v₀ₓ = 40, v₀ᵧ = 30 m/s olan atışın tepeye çıkış süresi kaçtır? (g = 10)', '3 s', '4 s', 'Çıkış süresini düşey bileşen belirler: 30/10 = 3 s.'],
    ['v₀ₓ = 40 ve v₀ᵧ = 30 m/s olan atışta menzil kaç metredir? (g = 10; aynı seviyeye iniş)', '240 m', '120 m', 'Toplam süre 2·30/10 = 6 s; x = 40·6 = 240 m.'],
    ['Sabit hızla giden trende yukarı atılan top yerdeki gözlemciye nasıl görünür?', 'Parabolik yol izler', 'Düşey doğru izler', 'Top trenin yatay hızını korurken düşeyde ivmelenir.'],
    ['Aynı hızla hangi açı daha uzun menzil verir? (Aynı seviyeye iniş)', '45°', '60°', 'Menzil sin 2α ile orantılı; sin 90° en büyük değerdir.'],
    ['Yatay atışta çarpma sürati nasıl bulunur?', 'Hız bileşenlerinin bileşkesiyle', 'Yatay ve düşey hızları doğrudan toplayarak', 'Birbirine dik hızlar Pisagor bağıntısıyla birleştirilir.'],
  ]),
  'fzk11-newton': derle('fzk11-newton', [
    ['Net kuvvet sıfır olan cisim sabit hızla hareket edebilir.', true, 'Birinci yasa, duran ya da sabit hızlı hareket eden cismi kapsar.'],
    ['Kütlesi iki kat olan cisme aynı net kuvvet uygulanırsa ivmesi de iki kat olur.', false, 'F = ma; aynı kuvvette kütle iki katına çıkınca ivme yarıya iner.'],
    ['Etki-tepki kuvvetleri farklı cisimlere etki eder.', true, 'Bu yüzden eşit ve zıt olsalar da birbirlerini dengelemezler.'],
    ['Masadaki kitabın ağırlığı ile masa kuvveti etki-tepki çiftidir.', false, 'İki kuvvet de kitaba etkir; etki-tepki çiftleri farklı cisimlerdedir.'],
    ['Aya giden kişinin kütlesi değişmez, ağırlığı azalır.', true, 'Kütle madde miktarıdır; ağırlık mg olduğu için g ile değişir.'],
    ['Otobüs frenleyince yolcunun öne savrulması eylemsizlikle açıklanır.', true, 'Yolcunun gövdesi hareket durumunu koruma eğilimindedir.'],
    ['Sabit hızla yükselen asansörde tartı mg değerinden büyük gösterir.', false, 'Sabit hızda ivme sıfırdır; normal kuvvet mg olur.'],
    ['Serbest cisim diyagramında cismin başkasına uyguladığı kuvvet de çizilir.', false, 'Diyagram yalnız seçilen cisme etki eden kuvvetleri gösterir.'],
  ], [
    ['4 kg cisme 12 N net kuvvet etki ederse ivme kaç m/s² olur?', '3', '48', 'a = F/m = 12/4 = 3 m/s².'],
    ['Sağa 10 N ve sola 6 N kuvvet alan cismin net kuvveti nedir?', 'Sağa 4 N', 'Sağa 16 N', 'Zıt yönlü kuvvetler çıkarılır; yön büyük kuvvetinkidir.'],
    ['2 kg ve 3 kg bağlı kütleler 20 N ile çekilirse sistem ivmesi kaçtır?', '4 m/s²', '10 m/s²', 'Sürtünme yoksa toplam kütle 5 kg; a = 20/5 = 4.'],
    ['Bağlı 2 ve 3 kg cisimler 20 N ile çekilirse 2 kg cisimdeki ip gerilmesi kaç N? (Sürtünmesiz)', '8 N', '20 N', 'Sistem ivmesi 20/5 = 4 m/s²; ip gerilmesi 2·4 = 8 N.'],
    ['Yukarı ivmelenen asansörde tartı hangi değeri gösterir?', 'mg değerinden büyük', 'mg değerinden küçük', 'N = m(g+a); normal kuvvet büyür.'],
    ['Masadaki kitabın ağırlığının tepkisi hangi kuvvettir?', 'Kitabın Dünya’yı çekmesi', 'Masanın kitabı itmesi', 'Dünya kitabı çeker; karşı kuvvet kitabın Dünya’yı çekmesidir.'],
    ['Kütleleri 3 ve 2 kg olan makaralı sistemin ivmesi kaçtır? (g = 10)', '2 m/s²', '5 m/s²', 'a = (3−2)·10/(3+2) = 2 m/s².'],
  ]),
  'fzk11-surtunme': derle('fzk11-surtunme', [
    ['Duran cisimde statik sürtünme her zaman en büyük değerindedir.', false, 'Statik sürtünme uygulanan kuvvete uyum sağlar; μₛN yalnız üst sınırdır.'],
    ['Cisim kayarken kinetik sürtünme yaklaşık μₖN değerindedir.', true, 'Kinetik sürtünme normal kuvvetle orantılıdır.'],
    ['Yüzeye eğik biçimde yukarı çekmek normal kuvveti azaltabilir.', true, 'Kuvvetin yukarı bileşeni yüzeyin taşıdığı yükü azaltır.'],
    ['Yatay düzlemde tuğlanın temas alanını büyütmek sürtünme kuvvetini mutlaka artırır.', false, 'Modelde sürtünme normal kuvvet ve yüzey cinsine bağlıdır.'],
    ['Kayma başladıktan sonra sürtünme kuvveti genellikle azalır.', true, 'Çoğu yüzeyde μₛ, μₖ değerinden büyüktür.'],
    ['Eğik düzlemde normal kuvvet mg değerine eşittir.', false, 'Normal kuvvet mg cosθ olur; ağırlığın dik bileşenidir.'],
    ['ABS, tekerleği kilitleyerek kinetik sürtünmeyi artırır.', false, 'ABS kilitlenmeyi önler; yuvarlanma sırasında daha büyük statik sürtünmeden yararlanılır.'],
  ], [
    ['N = 100 N, μₛ = 0,4 iken 30 N çekilen duran cisimde sürtünme kaç N?', '30 N', '40 N', '30 N sınır olan 40 N’u aşmaz; statik sürtünme çekişe eşitlenir.'],
    ['N = 100 N, μₖ = 0,3 iken kayan cisme etki eden sürtünme kaç N?', '30 N', '50 N', 'Kayma sırasında fₖ = μₖN = 0,3·100 = 30 N.'],
    ['Sürtünmesiz eğimde aşağı çeken ağırlık bileşeni hangisidir?', 'mg sinθ', 'mg cosθ', 'Eğime paralel bileşen mg sinθ, dik bileşen mg cosθ olur.'],
    ['37° eğimde μₖ = 0,5 ise ivme kaçtır? (g = 10; sin37 = 0,6; cos37 = 0,8)', '2 m/s²', '6 m/s²', 'a = 10(0,6−0,5·0,8) = 2 m/s².'],
    ['Hangi değişiklik kayan cisimde sürtünmeyi azaltır?', 'Yüzeyleri yağlamak', 'Yüzeyleri pürüzlendirmek', 'Yağlama yüzeyler arası etkileşimi azaltır.'],
    ['Yatay yüzeye aşağı eğik itme, normal kuvveti nasıl değiştirir?', 'Artırır', 'Azaltır', 'Kuvvetin aşağı bileşeni yüzeye uygulanan baskıyı artırır.'],
    ['Harekete geçmek üzere duran cisimde sürtünmenin üst sınırı nedir?', 'μₛN', 'μₖN', 'Statik sürtünmenin en büyük değeri μₛN olur.'],
  ]),
  'fzk11-limit-hiz': derle('fzk11-limit-hiz', [
    ['Düşen cisim hızlandıkça akışkan direnci artabilir.', true, 'Yaklaşık F = kAv² bağıntısında direnç süratle büyür.'],
    ['Limit hızda cisme hiç kuvvet etki etmez.', false, 'Ağırlık ile direnç eşit ve zıttır; net kuvvet sıfırdır.'],
    ['Limit hıza yaklaşırken ivme azalır ama hız bir süre daha artar.', true, 'İvme sıfıra yaklaşır; pozitif kaldığı sürece hız artmayı sürdürür.'],
    ['Aynı biçimdeki daha ağır cisim daha düşük limit hıza sahiptir.', false, 'v(limit) = √(mg/kA); kütle artarsa limit hız büyür.'],
    ['Paraşüt açılır açılmaz paraşütçü aşağı giderken ivmesi yukarı yönlü olabilir.', true, 'Direnç ağırlığı aşar; hız aşağı, net kuvvet ve ivme yukarıdır.'],
    ['Limit hıza yaklaşan cismin hız-zaman grafiği gittikçe dikleşir.', false, 'Direnç arttıkça ivme azalır; grafik yataya yaklaşır.'],
    ['Kesit alanını büyütmek, aynı kütlede limit hızı büyütür.', false, 'Büyük alan direnci artırır; eşitlik daha düşük hızda kurulur.'],
  ], [
    ['Hız iki katına çıkarsa yaklaşık kAv² direnci kaç kat olur?', '4 kat', '2 kat', 'Direnç hızın karesiyle orantılıdır: 2² = 4.'],
    ['Limit hızda ağırlık ile direnç arasındaki ilişki nedir?', 'Büyüklükleri eşit', 'Direnç daha büyük', 'Sabit hız için net kuvvet sıfır olmalı; direnç mg’ye eşittir.'],
    ['Aynı koşullarda kesit alanı dört katına çıkarsa limit hız nasıl değişir?', 'Yarıya iner', 'Dörtte birine iner', 'v(limit) ∝ 1/√A; alan dört kat olursa hız yarıya iner.'],
    ['Paraşüt açılınca ilk anda net kuvvet hangi yöndedir?', 'Yukarı', 'Aşağı', 'Artan direnç ağırlığı geçer; cisim aşağı giderken yavaşlar.'],
    ['Bir kayakçı çömelince hava direnci neden azalır?', 'Kesit alanı küçülür', 'Kütlesi küçülür', 'Akışa dik görünen alan azalır; kütle değişmez.'],
    ['Limit hıza yaklaşan hız-zaman eğrisinin eğimi neyi gösterir?', 'Azalan ivmeyi', 'Artan ağırlığı', 'Grafiğin eğimi ivmedir; direnç arttıkça net ivme azalır.'],
  ]),
  'fzk11-cembersel': derle('fzk11-cembersel', [
    ['Düzgün çembersel harekette sürat sabit olsa da hız değişir.', true, 'Hızın yönü sürekli değiştiği için merkezcil ivme vardır.'],
    ['Periyot yarıya inerse frekans da yarıya iner.', false, 'f = 1/T; periyot yarıya inerse frekans iki kat olur.'],
    ['Aynı milde dönen iki noktadan dıştaki daha büyük açısal hıza sahiptir.', false, 'İkisi aynı sürede aynı açıyı tarar; yalnız çizgisel hız dışta büyüktür.'],
    ['Kayışla bağlı kasnaklarda küçük kasnağın açısal hızı daha küçüktür.', false, 'Kenar hızları eşittir; ω = v/r, küçük yarıçap daha büyük ω verir.'],
    ['İp kopunca cisim bulunduğu noktadaki teğet yönünde ilerler.', true, 'Merkezcil kuvvet kalkar; cisim anlık hız yönünü korur.'],
    ['Merkezcil kuvvet bağımsız, yeni bir kuvvet türüdür.', false, 'Merkeze yönelen net kuvvetin adıdır; ip, sürtünme veya çekim sağlayabilir.'],
    ['Aynı yarıçapta hız iki kat olursa merkezcil ivme dört kat olur.', true, 'a = v²/r bağıntısında hız karesiyle etki eder.'],
  ], [
    ['Periyodu 4 s olan hareketin frekansı kaç Hz olur?', '0,25', '4', 'f = 1/T = 1/4 Hz.'],
    ['Yarıçap 2 m, periyot 4 s ise çizgisel sürat nedir?', 'π m/s', '2π m/s', 'v = 2πr/T = 2π·2/4 = π m/s.'],
    ['v = 10 m/s, r = 5 m ise merkezcil ivme kaçtır?', '20 m/s²', '2 m/s²', 'a = v²/r = 100/5 = 20 m/s².'],
    ['Yarıçap sabitken viraj hızı iki kat olursa gereken merkezcil kuvvet ne olur?', '4 katına çıkar', '2 katına çıkar', 'F = mv²/r; hızın karesiyle büyür.'],
    ['Eş merkezli dönme dolapta dıştaki kabinin hangi hızı daha büyüktür?', 'Çizgisel hızı', 'Açısal hızı', 'ω aynıdır; v = ωr dış noktada daha büyüktür.'],
    ['Düz yolda viraj alan araçta merkezcil kuvveti genellikle ne sağlar?', 'Lastik-yol sürtünmesi', 'Aracın ağırlığı', 'Yatay merkez yönünde kuvveti sürtünme verir.'],
    ['Düşey çemberde ipin gerilmesi genellikle nerede en büyüktür?', 'En altta', 'En üstte', 'Dipte gerilme hem mg’yi dengeler hem merkezcil kuvveti sağlar.'],
  ]),
  'fzk11-elektrik-alan': derle('fzk11-elektrik-alan', [
    ['İki yükün uzaklığı iki katına çıkarsa elektriksel kuvvet dörtte birine iner.', true, 'Coulomb kuvveti uzaklığın karesiyle ters orantılıdır.'],
    ['Yükleri farklı iki cismin birbirine uyguladığı kuvvetlerin büyüklüğü farklıdır.', false, 'Etki-tepki gereği kuvvetler eşit büyüklükte ve zıt yönlüdür.'],
    ['Pozitif yükün alan çizgileri yükten dışarı yönelir.', true, 'Alan yönü pozitif deneme yüküne etki eden kuvvetin yönüdür.'],
    ['Bir noktadaki elektrik alan, ölçmek için koyulan yükün büyüklüğüyle artar.', false, 'Alanı kaynak yük belirler; deneme yükü alanı değiştirmez.'],
    ['Negatif yük, elektrik alanın yönüne zıt kuvvet görür.', true, 'F = qE bağıntısında q negatifse kuvvet alan yönüne terstir.'],
    ['Paralel levhalar arasındaki düzgün alanın her noktasında yön aynıdır.', true, 'Düzgün alanın hem büyüklüğü hem yönü sabittir.'],
    ['Faraday kafesinin içindeki elektrik alan, dış alanla aynı büyüklüktedir.', false, 'Yükler dış yüzeye dağılır; korunmuş iç bölgede alan sıfırdır.'],
    ['Alan çizgileri güçlü alanlarda daha seyrek çizilir.', false, 'Çizgilerin sık olduğu yerde alan daha güçlüdür.'],
  ], [
    ['Uzaklık 3 katına çıkarsa Coulomb kuvveti ne olur?', 'Dokuzda birine iner', 'Üçte birine iner', 'F ∝ 1/d²; 3² = 9.'],
    ['Aynı yükler arasındaki kuvvet 0,6 N ise bir yük iki kat olunca kaç N olur?', '1,2 N', '0,3 N', 'Kuvvet yüklerin çarpımıyla doğru orantılıdır.'],
    ['E = 200 N/C alanında +0,01 C yük kaç N kuvvet görür?', '2 N', '200 N', 'F = qE = 0,01·200 = 2 N.'],
    ['12 V levhalar arası 2 cm ise alanın büyüklüğü kaç N/C olur?', '600', '24', 'E = V/d = 12/0,02 = 600 N/C.'],
    ['Alan çizgileri negatif noktasal yüke göre hangi yöndedir?', 'Yüke doğru', 'Yükten dışarı', 'Pozitif deneme yükü negatif kaynağa çekilir.'],
    ['Birden çok yükün bileşke kuvveti nasıl bulunur?', 'Vektörel toplamla', 'Büyüklükleri doğrudan toplayarak', 'Kuvvetlerin yönleri önemlidir; vektörler birleştirilir.'],
    ['Paralel levhada yatay giren elektron neden sapar?', 'Alan ona düşey kuvvet uygular', 'Yatay hızı kendiliğinden azalır', 'Elektrik alanın kuvveti, elektronun hareket yönünü değiştirir.'],
  ]),
  'fzk11-manyetik': derle('fzk11-manyetik', [
    ['Bir mıknatıs ikiye bölünürse yalnız N kutuplu parça elde edilir.', false, 'Her parça yeniden N ve S kutuplu küçük mıknatıs olur.'],
    ['Akım geçen telin yanındaki pusulanın sapması akımın alan oluşturduğunu gösterir.', true, 'Oersted deneyi elektrik akımının manyetik etkisini gösterir.'],
    ['Düz telin akımı artarsa belli uzaklıktaki manyetik alanı artar.', true, 'Düz tel çevresinde B, I ile doğru orantılıdır.'],
    ['Makaranın sarım sayısı artırılırsa içindeki manyetik alan zayıflar.', false, 'B, sarım sayısıyla doğru orantılıdır.'],
    ['Alana paralel akım taşıyan tele manyetik kuvvet etki etmez.', true, 'F = BIℓ sinθ; paralellikte sin0 = 0.'],
    ['Aynı yönlü akım taşıyan paralel teller birbirini iter.', false, 'Aynı yönlü akımlar telleri birbirine çeker.'],
    ['Manyetik kuvvet hareketli yükün hızına dik olduğundan süratini değiştirmez.', true, 'Kuvvet yön değiştirir; hıza dik kuvvet iş yapmaz.'],
    ['Elektrik motoru hareket enerjisini elektrik enerjisine dönüştürür.', false, 'Elektrik motoru akımlı makarayı döndürerek elektrik enerjisini harekete çevirir.'],
  ], [
    ['B = 0,5 T, I = 4 A, ℓ = 0,2 m; tel alana dikse kuvvet kaç N?', '0,4 N', '4 N', 'F = BIℓ = 0,5·4·0,2 = 0,4 N.'],
    ['Manyetik alana paralel akım taşıyan telde manyetik kuvvet kaç N olur?', '0 N', '0,4 N', 'Paralel durumda θ = 0 ve sinθ = 0.'],
    ['Akım makarasının alanı hangi değişiklikle güçlenir?', 'Demir çekirdek yerleştirmekle', 'Sarım sayısını azaltmakla', 'Demir çekirdek alanı büyütür; daha az sarım zayıflatır.'],
    ['Akımı iki kat yapılan düz telin aynı noktadaki alanı ne olur?', 'İki katına çıkar', 'Dört katına çıkar', 'Düz tel için B ∝ I/d.'],
    ['Zıt yönlü akım taşıyan paralel teller ne yapar?', 'Birbirini iter', 'Birbirini çeker', 'Zıt akımlı paralel teller arasında itme vardır.'],
    ['Manyetik alana dik giren yükün yolu hangi biçimde olabilir?', 'Çembersel', 'Düzgün doğrusal', 'Manyetik kuvvet hıza dik ve merkezcil olabilir.'],
    ['Pusula iğnesinin N ucu alanın hangi yönünü gösterir?', 'Manyetik alan yönünü', 'Alan yönünün tersini', 'Alan yönü pozitif kuzey kutbuna etki eden kuvvet yönüdür.'],
  ]),
  'fzk11-induksiyon': derle('fzk11-induksiyon', [
    ['Bobindeki manyetik akı sabitken indüksiyon akımı oluşmaz.', true, 'Akımı doğuran akının kendisi değil, zamanla değişimidir.'],
    ['Mıknatıs bobinden uzaklaşırken oluşan akım, yaklaşırken oluşanın ters yönündedir.', true, 'Akı değişiminin yönü tersine döner; Lenz yönü de tersine döner.'],
    ['Sarım sayısı iki katına çıkarsa aynı akı değişimindeki gerilim yarıya iner.', false, 'ε = N·|ΔΦ|/Δt; gerilim iki katına çıkar.'],
    ['Lenz yasasına göre indüksiyon akımı kendisini doğuran değişime karşı koyar.', true, 'Bu yön seçimi enerjinin korunumuyla tutarlıdır.'],
    ['Alternatörde bobin dönerken akı sabit kaldığı için gerilim doğmaz.', false, 'Dönüş açıyı ve akıyı periyodik değiştirir; alternatif gerilim doğar.'],
    ['Prizdeki 220 V değeri alternatif gerilimin en büyük anlık değeridir.', false, '220 V etkin değerdir; tepe değeri yaklaşık 311 V olur.'],
    ['Sabit doğru akımla çalışan bobin, sürekli değişen manyetik akı oluşturur.', false, 'Sabit akım sabit alan doğurur; sürekli indüksiyon için değişim gerekir.'],
  ], [
    ['100 sarımda akı 0,02 Wb kadar 0,1 s’de değişirse gerilim kaç V?', '20 V', '2 V', '|ε| = N|ΔΦ|/Δt = 100·0,02/0,1 = 20 V.'],
    ['Bobindeki aynı akı değişimi yarı sürede gerçekleşirse gerilim ne olur?', 'İki katına çıkar', 'Yarıya iner', 'Gerilim değişim süresiyle ters orantılıdır.'],
    ['B = 0,5 T, ℓ = 0,4 m, v = 10 m/s çubukta gerilim kaç V?', '2 V', '5 V', 'ε = Bℓv = 0,5·0,4·10 = 2 V.'],
    ['N kutbu bobine yaklaşırken bobinin yakın ucu ne olur?', 'N kutbu', 'S kutbu', 'Bobin yaklaşmayı engelleyecek biçimde mıknatısı iter.'],
    ['220 V etkin gerilimin yaklaşık tepe değeri kaç V’tur?', '311 V', '156 V', 'V(maks) = V(etkin)·√2 ≈ 311 V.'],
    ['Transformatör çekirdeğindeki girdap akımı hangi soruna yol açar?', 'Isı kaybına', 'Sarım oranının değişmesine', 'Girdap akımları çekirdeği ısıtarak enerji kaybettirir.'],
    ['Dönen bobinli alternatörde akım yönü neden değişir?', 'Akı değişiminin yönü değişir', 'Bobinin direnci sıfırlanır', 'Dönme sırasında akı periyodik değişir; indüksiyon yönü tersine döner.'],
  ]),
  'fzk11-transformator': derle('fzk11-transformator', [
    ['Transformatör sabit doğru akımda sürekli gerilim dönüşümü yapabilir.', false, 'İkincil sargıda gerilim için değişen manyetik akı gerekir.'],
    ['İkincil sarım sayısı birincilden büyükse ideal transformatör gerilimi yükseltir.', true, 'V₂/V₁ = N₂/N₁ oranı geçerlidir.'],
    ['İdeal transformatörde gerilim yükselince akım da aynı oranda yükselir.', false, 'Güç korunur; gerilim artarken akım düşer.'],
    ['Yüksek gerilimde iletim, aynı güç için hattaki akımı düşürür.', true, 'P = VI; gerilim artarsa gereken akım azalır.'],
    ['Hattaki akım yarıya düşerse I²R ısı kaybı dörtte bire iner.', true, 'Isı kaybı akımın karesiyle değişir.'],
    ['Katmanlı çekirdek girdap akımlarının yol açtığı ısı kaybını artırır.', false, 'İnce katmanlar girdap akımı halkalarını keserek kaybı azaltır.'],
  ], [
    ['N₁ = 200, N₂ = 10, V₁ = 220 V ise V₂ kaç volttur?', '11 V', '4400 V', 'V₂ = V₁N₂/N₁ = 220·10/200 = 11 V.'],
    ['İdeal transformatörde V₁ = 220 V, V₂ = 11 V, I₂ = 2 A ise I₁ kaç A?', '0,1 A', '40 A', 'V₁I₁ = V₂I₂; 220I₁ = 11·2, dolayısıyla 0,1 A.'],
    ['N₂/N₁ = 4 ise gerilim ve akım nasıl değişir?', 'Gerilim 4 kat, akım dörtte bir', 'Gerilim ve akım 4 kat', 'İdeal güç korunur; gerilimdeki artış akımdaki azalışla dengelenir.'],
    ['İletimde gerilim 10 katına çıkarılırsa aynı güçte ısı kaybı ne olur?', 'Yüzde birine iner', 'Onda birine iner', 'Akım onda bire, I²R kaybı yüzde bire iner.'],
    ['Sargı direnci kaynaklı kaybı hangi değişiklik azaltır?', 'Daha kalın bakır tel', 'Daha ince bakır tel', 'Kalın telin direnci daha küçüktür; I²R kaybı azalır.'],
    ['Şarj adaptöründe transformatör genellikle ne yapar?', 'Gerilimi düşürür', 'Gerilimi yükseltir', 'Şebeke gerilimi cihazın düşük çalışma gerilimine indirilir.'],
  ]),
  'fzk11-aydinlanma': derle('fzk11-aydinlanma', [
    ['Işık şiddeti, kaynaktan uzaklaşınca azalır.', false, 'Işık şiddeti kaynağın bir yöndeki özelliğidir; azalan yüzey aydınlanmasıdır.'],
    ['Aynı ışık daha geniş yüzeye yayılırsa birim alanın aydınlanması azalır.', true, 'E = Φ/A; alan büyürse akı birim alana daha az düşer.'],
    ['Kaynak-yüzey uzaklığı iki kat olursa dik aydınlanma dörtte bire iner.', true, 'E = I/d² bağıntısında uzaklığın karesi etkilidir.'],
    ['Işık yüzeye eğik gelirse dik gelişe göre aydınlanma artar.', false, 'Aynı akı daha geniş alana yayılır; cosα çarpanı küçülür.'],
    ['Lümen, yüzeydeki aydınlanmanın birimidir.', false, 'Lümen ışık akısının, lüks yüzey aydınlanmasının birimidir.'],
    ['Aynı lümeni daha az watt ile veren lamba daha verimlidir.', true, 'Verim watt başına lümen olarak karşılaştırılır.'],
  ], [
    ['90 cd kaynak 3 m uzakta yüzeyi dik aydınlatırsa E kaç lüks olur?', '10 lx', '30 lx', 'E = I/d² = 90/9 = 10 lx.'],
    ['Dik ışın 10 lx veriyorsa ışın normalle 60° yaptığında aydınlanma kaç lx olur?', '5 lx', '20 lx', 'cos60° = 0,5 olduğundan aydınlanma yarıya iner.'],
    ['40 cd kaynak 2 m’de 10 lx verirse 10 cd kaynak aynı E için kaç metreye konmalı?', '1 m', '4 m', 'E = I/d²; 10/1² = 40/2² = 10 lx.'],
    ['Lamba etiketinde 800 lm yazıyorsa hangi nicelik verilmiştir?', 'Işık akısı', 'Işık şiddeti', 'Lümen ışık akısının birimidir; şiddetin birimi kandeladır.'],
    ['Işık şiddetlerini karşılaştırmak için yağ lekeli kâğıt hangi araçta kullanılır?', 'Fotometrede', 'Transformatörde', 'Fotometrede iki yönden gelen aydınlanma eşitlenir.'],
    ['Her yöne eşit ışık saçan 10 cd kaynağın akısı kaç lümendir?', '40π lm', '10π lm', 'Φ = 4πI = 40π lm.'],
  ]),
  'fzk11-duzlem-ayna': derle('fzk11-duzlem-ayna', [
    ['Düzlem aynada gelme ve yansıma açıları normale göre ölçülür.', true, 'Açıların referansı yüzeye dik çizilen normaldir.'],
    ['Pürüzlü yüzeyde dağınık yansıma, yansıma yasalarını bozduğu için oluşur.', false, 'Her noktada yasa geçerlidir; farklı normaller ışınları farklı yönlere yollar.'],
    ['Düzlem aynanın görüntüsü aynanın arkasında ve sanaldır.', true, 'Yansıyan ışınların yalnız uzantıları arkada kesişir.'],
    ['Cisim aynaya yaklaşınca düzlem aynadaki görüntüsü büyür.', false, 'Düzlem aynada görüntü boyu cismin boyuna eşittir.'],
    ['Ayna 10° dönerse sabit gelen ışının yansıma doğrultusu 20° döner.', true, 'Normalin dönüşü geliş ve yansıma açısını birlikte değiştirir.'],
    ['Boy aynasının gerekli en küçük uzunluğu aynaya uzaklıkla değişir.', false, 'Tam boy görmek için boyun yarısı kadar ayna yeter; uzaklıktan bağımsızdır.'],
    ['Aynaya yaklaşan kişinin görüntüsü de aynaya yaklaşır.', true, 'Görüntünün aynaya uzaklığı cismin aynaya uzaklığına eşittir.'],
  ], [
    ['1,8 m boylu kişinin tamamını görmek için ayna en az kaç metre olmalı?', '0,9 m', '1,8 m', 'En küçük boy aynası kişinin boyunun yarısıdır.'],
    ['Kişi aynaya 1 m yaklaşırsa kişi-görüntü arası uzaklık ne kadar azalır?', '2 m', '1 m', 'Her iki tarafta uzaklık 1 m azalır; aradaki fark toplam 2 m.'],
    ['Aralarında 90° olan iki aynada kaç görüntü oluşur?', '3', '4', 'n = 360°/90° − 1 = 3.'],
    ['Bir aynaya normalle 30° açı yapan ışın kaç dereceyle yansır?', '30°', '60°', 'Gelme ve yansıma açıları normale göre eşittir.'],
    ['Aynaya yaklaşınca görüş alanı nasıl değişir?', 'Genişler', 'Daralır', 'Göz, aynanın kenarlarından daha geniş bir bölgeyi görebilir.'],
    ['Köşe yansıtıcıda iki kez yansıyan ışın nasıl çıkar?', 'Geliş doğrultusuna paralel, ters yönde', 'Geliş doğrultusuna dik yönde', 'Birbirine dik iki yansıma ışını ters yöne çevirir.'],
    ['Düzlem ayna görüntüsü perdeye düşürülebilir mi?', 'Hayır', 'Evet', 'Sanal görüntü ışın uzantılarıyla oluşur; ışınlar arkada gerçekte buluşmaz.'],
  ]),
  'fzk11-kuresel-ayna': derle('fzk11-kuresel-ayna', [
    ['Çukur ayna asal eksene paralel ışınları odakta toplar.', true, 'Paralel gelen ışınlar odaktan geçerek yansır.'],
    ['Tümsek aynanın odağı aynanın önündedir ve gerçektir.', false, 'Tümsekte yansıyan ışınların uzantıları arkadaki sanal odaktan gelir.'],
    ['Tümsek aynada görüntü cismin konumundan bağımsız olarak düz ve küçüktür.', true, 'Görüntü hep aynanın arkasında F ile T arasında oluşur.'],
    ['Çukur aynada cisim odak içinde ise görüntü ters ve gerçektir.', false, 'Odak içinde görüntü sanal, düz ve büyük olur.'],
    ['Gerçek görüntü, yansıyan ışınların kendilerinin kesişmesiyle oluşur.', true, 'Bu nedenle gerçek görüntü perdeye düşürülebilir.'],
    ['Küresel aynada odak uzaklığı eğrilik yarıçapının iki katıdır.', false, 'Odak uzaklığı yarıçapın yarısıdır: f = r/2.'],
    ['Tümsek aynanın geniş görüş alanı araç yan aynasında işe yarar.', true, 'Görüntü küçük olsa da daha geniş çevre görülür.'],
  ], [
    ['Eğrilik yarıçapı 40 cm olan küresel aynanın odak uzaklığı nedir?', '20 cm', '80 cm', 'f = r/2 = 20 cm.'],
    ['f = 10 cm çukur aynada cisim 30 cm’deyse görüntü uzaklığı kaçtır?', '15 cm', '30 cm', '1/dg = 1/10 − 1/30 = 1/15.'],
    ['f = 10 cm çukur aynada 30 cm’deki cismin görüntüsü boyca nasıldır?', 'Yarı boyda ve ters', 'İki kat büyük ve düz', 'Görüntü uzaklığı 15 cm; büyütme −15/30 = −1/2.'],
    ['Çukur aynada cisim odağa konursa yansıyan ışınlar nasıl çıkar?', 'Birbirine paralel', 'Odakta birleşerek', 'Odaktan gelen ışınlar asal eksene paralel yansır.'],
    ['Makyaj aynasında büyük ve düz görüntü için yüz nereye konmalı?', 'Odak ile ayna arasına', 'Merkezin dışına', 'Çukur aynada odak içindeki cismin görüntüsü sanal ve büyüktür.'],
    ['Hangi ayna daha geniş görüş alanı verir?', 'Tümsek ayna', 'Çukur ayna', 'Tümsek ayna ışığı dağıtır ve çevrenin daha geniş bölümünü gösterir.'],
    ['Perdeye düşen görüntünün niteliği nedir?', 'Gerçek', 'Sanal', 'Perdeye ancak ışınların kendisinin kesiştiği gerçek görüntü düşer.'],
  ]),
  'fzk11-kirilma': derle('fzk11-kirilma', [
    ['Işık ortama dik girerse doğrultusu değişmez ama hızı değişebilir.', true, 'Gelme açısı sıfır olduğunda sapma olmaz; ortam hızı yine değiştirir.'],
    ['Kırıcılık indisi büyük ortamda ışığın hızı da büyüktür.', false, 'n = c/v; indis büyüdükçe ışığın o ortamdaki hızı küçülür.'],
    ['Havadan suya eğik giren ışık normale yaklaşır.', true, 'Daha büyük indise geçişte kırılma açısı küçülür.'],
    ['Işık ortam değiştirince frekansı da değişir.', false, 'Frekans kaynağa bağlıdır; değişen hız ve dalga boyudur.'],
    ['Tam yansıma, büyük indisten küçük indise geçişte oluşabilir.', true, 'İlk şart n₁ > n₂; ayrıca gelme açısı sınırı aşmalıdır.'],
    ['Gelme açısı sınır açısından küçükse ışık tamamen yansır.', false, 'Tam yansıma sınır açısı aşıldığında gerçekleşir.'],
    ['Paralel yüzlü levhadan çıkan ışın, giren ışına paralel olabilir.', true, 'İki kırılma sonunda doğrultu aynı kalır, ışın yalnız yana kayar.'],
  ], [
    ['Havadan suya gelme açısı 53°, sin53 = 0,8 ve n(su) = 4/3 ise kırılma açısı nedir?', '37°', '53°', 'Snell ile sinθ₂ = 0,8·3/4 = 0,6; θ₂ = 37°.'],
    ['n = 1,5 olan camda ışığın hızı c’nin kaç katıdır?', '2/3’ü', '1,5 katı', 'v = c/n = c/1,5 = 2c/3.'],
    ['Su-hava geçişinde gelme açısı artırılırsa ışın nasıl sapar?', 'Normalden uzaklaşır', 'Normale yaklaşır', 'Düşük indise geçerken kırılma açısı gelme açısından büyüktür.'],
    ['Camdan havaya geçişte tam yansıma için hangisi gereklidir?', 'Açı sınır açısından büyük olmalı', 'Açı sıfır olmalı', 'Büyük indisten küçük indise geçişte sınır açısı aşılır.'],
    ['Kırmızı ışık sudan havaya çıkınca hangi özelliği sabit kalır?', 'Frekansı', 'Hızı', 'Ortam değişse de frekans kaynaktan belirlenir.'],
    ['Serapta görülen yol üstü parlaklık hangi etkiden doğar?', 'Hava katmanlarında kırılma', 'Asfaltın aynalaşması', 'Sıcaklıkla indisi değişen hava ışınların yolunu büker.'],
    ['Paralel cam levhadan çıkan ışın gelen ışına göre nasıl olur?', 'Paralel ve yana kaymış', 'Aynı çizgide ve hızlanmış', 'Giriş ve çıkış yüzleri paraleldir; iki kırılmanın açısal etkisi dengelenir.'],
  ]),
  'fzk11-gorunur-derinlik': derle('fzk11-gorunur-derinlik', [
    ['Havadan bakılan su içindeki cisim olduğundan sığda görünür.', true, 'Sudan havaya çıkan ışık normalden uzaklaşır; uzantısı yukarıdan gelir.'],
    ['Görünür derinlik hesabı dike yakın bakış için verilmiştir.', true, 'Eğik bakışta ışık daha çok kırılır ve basit oran yeterli olmaz.'],
    ['Sudaki balık havadaki kuşu olduğundan yakın görür.', false, 'Sudan havaya bakınca kuş olduğundan daha uzakta görünür.'],
    ['Suyun kırıcılık indisi artarsa aynı gerçek derinlik daha küçük görünür.', true, 'Havadan bakışta h(görünür) = h(gerçek)/n.'],
    ['Su içindeki kalemin yalnız suya batmış kısmı yer değiştirmiş görünür.', true, 'Sudaki kısımdan gelen ışın kırılır; havadaki kısım yerinde kalır.'],
    ['Görünür derinlik gerçek derinliğe her bakış açısında eşittir.', false, 'Ortam sınırındaki kırılma görünür konumu değiştirir.'],
  ], [
    ['2 m derin sudaki taban, n = 4/3 iken havadan kaç metrede görünür?', '1,5 m', '2,67 m', 'h(görünür) = 2/(4/3) = 1,5 m.'],
    ['12 cm derindeki para 9 cm’de görünüyorsa sıvının indisi kaçtır?', '4/3', '3/4', 'n = h(gerçek)/h(görünür) = 12/9 = 4/3.'],
    ['Suyun içinden havadaki kuşa bakan balık kuşu nerede görür?', 'Daha uzakta', 'Daha yakında', 'Gözlemci indisi daha büyük olduğundan görünür yükseklik artar.'],
    ['Mızrakla sudaki balığı hedefleyen kişi nereye nişan almalı?', 'Görünen balığın altına', 'Görünen balığın üstüne', 'Balığın gerçek konumu görünen konumundan daha derindedir.'],
    ['Havadan bakışta 4 cm su ve 6 cm cam katmanı nasıl ele alınır?', 'Her katmanın görünür katkısı toplanır', 'Derinlikler toplanıp tek indis kullanılır', 'Farklı indisli katmanların her biri ayrı hesaplanır.'],
  ]),
  'fzk11-fiber': derle('fzk11-fiber', [
    ['Fiberde çekirdeğin kırıcılık indisi örtününkinden büyüktür.', true, 'Çekirdek-örtü sınırında tam yansıma için bu sıralama gereklidir.'],
    ['Fiberde iletim, ışığın çekirdekten sürekli dışarı kırılmasıyla olur.', false, 'Işık çekirdek içinde tekrar tekrar tam yansır.'],
    ['Kablo çok keskin bükülürse ışık dışarı kaçıp sinyal zayıflayabilir.', true, 'Sınırdaki gelme açısı tam yansıma koşulunun altına düşebilir.'],
    ['Fibere her açıdan giren ışık aynı verimle iletilir.', false, 'Yalnız kabul açısı içindeki giriş ışınları lifte hapsolur.'],
    ['Tek modlu fiber uzun mesafede daha uygundur.', true, 'İnce çekirdekte ışık tek yol izler; yayılma farkı azalır.'],
    ['Fiber elektromanyetik girişimden bakır kablo kadar etkilenir.', false, 'Veri elektrik akımı yerine ışıkla taşındığı için parazite dayanıklıdır.'],
  ], [
    ['Çekirdek-örtü sınırında ışığı içeride tutan olay hangisidir?', 'Tam yansıma', 'Dağınık yansıma', 'Büyük indisten küçük indise sınır açı aşılınca tam yansıma olur.'],
    ['Fiberin çok keskin bükülmesi sinyali neden azaltır?', 'Bazı ışınlar örtüye kaçar', 'Işığın frekansı sıfırlanır', 'Gelme açısı sınır açısının altına düşebilir.'],
    ['Uzun mesafeli bağlantı için hangi lif daha uygundur?', 'Tek modlu fiber', 'Çok modlu fiber', 'Tek yol gecikme farklarını azaltır.'],
    ['Lazerin hızlı yanıp sönmesi fiberde hangi bilgiyi taşır?', 'İkili veri darbelerini', 'Sargıdaki akım yönünü', 'Işık var/yok darbeleri 1 ve 0 olarak okunabilir.'],
    ['Endoskopta görüntüyü dışarı getiren ortam hangisidir?', 'Fiber lif demeti', 'Bakır sargı', 'Lif demeti görüntüyü tam yansımayla taşır.'],
    ['Fiberin bakıra göre parazit üstünlüğü neye dayanır?', 'Işıkla iletime', 'Daha kalın çekirdeğe', 'Elektromanyetik girişim elektrik iletimini etkiler; optik iletimi etkilemez.'],
  ]),
  'fzk11-prizma': derle('fzk11-prizma', [
    ['Prizmadan geçen ışın girişte ve çıkışta iki kez kırılır.', true, 'İki farklı ortam sınırından geçer.'],
    ['Prizmadan çıkan ışın genellikle tepeye doğru sapar.', false, 'İki kırılmanın toplam etkisi tabana doğrudur.'],
    ['Beyaz ışık prizmada ayrılır çünkü kırıcılık indisi renge göre değişir.', true, 'Mor ve kırmızı ışığın sapma miktarları farklıdır.'],
    ['Prizmada kırmızı ışık mor ışıktan daha çok kırılır.', false, 'Mor en çok, kırmızı en az sapar.'],
    ['En küçük sapmada ışığın prizma içindeki yolu simetriktir.', true, 'Giriş ve çıkış açıları eşit; iç yol tabana paraleldir.'],
    ['Newton tek renk ışığı ikinci prizmada yeniden bütün renklere ayırdı.', false, 'Tek renk yeniden ayrılmaz; renkler beyaz ışığın içindedir.'],
    ['Tam yansımalı prizma, uygun açıda ışığı kayıpsız denecek kadar geri çevirir.', true, '45° geliş, cam-hava sınır açısını aştığında tam yansıma olur.'],
  ], [
    ['n = 1,5 ve tepe açısı 10° olan ince prizmada yaklaşık sapma kaç derecedir?', '5°', '15°', 'δ ≈ (n−1)A = 0,5·10° = 5°.'],
    ['Beyaz ışıkta hangi renk prizma tabanına daha çok sapar?', 'Mor', 'Kırmızı', 'Mor ışık camda daha büyük indisle daha çok kırılır.'],
    ['Gökkuşağı için Güneş gözlemciye göre nerede olmalı?', 'Arkasında', 'Önünde', 'Yağmur damlasından dönen ışığı görmek için Güneş arkada kalır.'],
    ['Tam yansımalı cam prizmada 45° geliş niçin yansır? (sınır 42°)', '45° sınır açısından büyüktür', '45° sınır açısından küçüktür', 'Büyük indisten küçüğe geçişte sınır aşıldığı için tam yansıma oluşur.'],
    ['Prizmada en küçük sapma hangi ışık yolunda görülür?', 'İç yol tabana paralelken', 'İç yol tepeye doğruyken', 'Simetrik yolda giriş ve çıkış açıları eşitlenir.'],
    ['Bir elementin ışık çizgilerini incelemek için hangi araç kullanılır?', 'Spektroskop', 'Fotometre', 'Spektroskop prizmada ayrılan renk çizgilerini inceler.'],
    ['Tek renk ışık ikinci prizmadan geçirilince ne olur?', 'Yönü değişebilir, rengi ayrılmaz', 'Beyaz ışığa dönüşür', 'Tek renk bileşenlerine ayrılamaz; yine kırılarak sapabilir.'],
  ]),
  'fzk11-mercek': derle('fzk11-mercek', [
    ['Havadaki ince kenarlı cam mercek paralel ışığı odakta toplar.', true, 'Yakınsak mercek paralel ışınları karşı taraftaki odaktan geçirir.'],
    ['Kalın kenarlı merceğin görüntüsü cisim nerede olursa olsun gerçek ve terstir.', false, 'Iraksak mercekte görüntü sanal, düz ve küçüktür.'],
    ['Optik merkezden geçen ışın yönünü değiştirmeden ilerler.', true, 'İnce mercek çiziminde optik merkez ışını sapmaz.'],
    ['İnce kenarlı mercekte cisim odak içinde ise görüntü perdeye düşer.', false, 'Bu konumda görüntü sanal ve düz; perdeye düşmez.'],
    ['Miyop gözlüğünde kalın kenarlı mercek kullanılır.', true, 'Iraksak mercek görüntüyü retinanın üzerine taşımaya yardım eder.'],
    ['Merceğin yakınsama gücü odak uzaklığıyla doğru orantılıdır.', false, 'P = 1/f; odak uzaklığı küçüldükçe güç büyür.'],
    ['İnce kenarlı merceğin gerçek görüntüsü merceğin öte yanında oluşur.', true, 'Işınlar kırılıp mercekten geçtikten sonra karşı tarafta kesişir.'],
  ], [
    ['f = 20 cm ince kenarlı mercekte cisim 60 cm’deyse görüntü uzaklığı kaçtır?', '30 cm', '40 cm', '1/dg = 1/20−1/60 = 1/30.'],
    ['f = 20 cm ince kenarlı mercekte 60 cm’deki cismin görüntüsü nasıldır?', 'Yarısı ve ters', 'İki katı ve düz', 'Görüntü 30 cm’de; m = −30/60 = −1/2.'],
    ['Odak uzaklığı +0,5 m olan merceğin gücü kaç diyoptridir?', '+2 D', '+0,5 D', 'P = 1/f = 1/0,5 = +2 D.'],
    ['Cisim ince kenarlı merceğin odak içindeyse görüntü nasıldır?', 'Sanal, düz ve büyük', 'Gerçek, ters ve küçük', 'Bu bölgede kırılan ışınların uzantıları cisim tarafında kesişir.'],
    ['Uzağı bulanık gören miyop kişi hangi merceği kullanır?', 'Kalın kenarlı', 'İnce kenarlı', 'Iraksak mercek görüntünün retinada oluşmasına yardım eder.'],
    ['Fotoğraf makinesinde uzak cismin görüntüsü genellikle nasıldır?', 'Küçük ve gerçek', 'Büyük ve sanal', 'Cisim 2F dışında olduğunda görüntü F ile 2F arasında gerçek ve küçüktür.'],
    ['f = −0,25 m merceğin gücü kaç diyoptridir?', '−4 D', '+4 D', 'P = 1/f = 1/(−0,25) = −4 D.'],
  ]),
}
