import { sikli, soru, type SoruKarti } from '../tip'

/** İlk iki İngilizce temasının bağlama dayalı konu sonu soruları. */
export const ingilizce11Sorulari1: Record<string, Omit<SoruKarti, 'id'>[]> = {
  'ing11-okul-turleri': [
    soru('"A private school may charge a fee" cümlesi, bütün özel okulların aynı ücreti aldığı anlamına gelir.', false, 'May olasılık bildirir; tutar ya da bütün okullar hakkında kesin yargı vermez.'),
    sikli('Bir okulun uygulamalı meslek eğitimi verdiğini hangi cümle anlatır?', ['It offers vocational training.', 'It charges a higher fee.'], 0, 'Vocational training mesleki uygulamalı eğitimi belirtir; ücret eğitim türünü göstermez.'),
    soru('"Both schools offer art, whereas only B has a workshop" ortaklık ve farkı birlikte gösterir.', true, 'Both ortak özelliği, whereas ise karşıtlığı belirtir.'),
    sikli('"Optional subjects are chosen by students" cümlesinde hangi bilgi öne çıkar?', ['Öğretmenin seçimi', 'Seçmeli derslerin seçilmesi'], 1, 'Edilgen cümlenin öznesi optional subjects olur; eylemin sonucu öne çıkar.'),
    soru('"New computers are being installed now" bugün süren işi edilgen yapıyla anlatır.', true, 'Are being installed, şimdiki zamanda sürmekte olan edilgendir.'),
    sikli('Bir okulu değerlendirmek için hangi karşılaştırma daha sağlamdır?', ['Aynı ölçütlerle kaynak ve katılıma bakmak', 'Yalnız okul ücretine bakmak'], 0, 'Kaynak ve katılım gibi ortak ölçütler ücretin tek başına veremediği bilgiyi sağlar.'),
    soru('Resource ile facility her bağlamda tam eş anlamlıdır.', false, 'Resource genel kaynak; facility okulun laboratuvarı gibi fiziksel olanağı olabilir.'),
    sikli('"Students use the lab twice a week" cümlesinde sıklık hangisidir?', ['The lab', 'Twice a week'], 1, 'Twice a week, etkinliğin haftada kaç kez yapıldığını belirtir.'),
    soru('Student-centred sınıfta öğrenciler proje seçimine katılabilir.', true, 'Öğrenci merkezli yaklaşım öğrencinin karar ve etkinliğe katılımını öne çıkarır.'),
    sikli('Okulun ders planını anlatmak için hangi sözcük daha uygundur?', ['Curriculum', 'Fee'], 0, 'Curriculum müfredattır; fee ise ödenen ücrettir.'),
    soru('"Higher fees do not always mean better outcomes" ücreti başarı için kesin kanıt sayar.', false, 'Do not always, ücret ile sonuç arasında zorunlu bağ kurulamayacağını söyler.'),
    sikli('"The meeting is held in the library on Fridays" cümlesinde yer hangisidir?', ['On Fridays', 'In the library'], 1, 'In the library yer; on Fridays zaman bilgisidir.'),
  ],
  'ing11-egitim-sistemleri': [
    soru('İki sistemin başarısını yalnız ortalama puanla kıyaslamak, katılım farkını gözden kaçırabilir.', true, 'Ortalama puan yükselirken katılım düşebilir; iki gösterge birlikte okunmalıdır.'),
    sikli('"Projects are assessed at the end of each term" cümlesinde odak nedir?', ['Değerlendirilen projeler', 'Değerlendiren öğretmen'], 0, 'Edilgen yapıda projects özne olur; yapan kişi belirtilmez.'),
    soru('Compulsory, öğrencinin isterse seçebileceği ders anlamındadır.', false, 'Compulsory zorunlu; isteğe bağlı ders için optional kullanılır.'),
    sikli('"The curriculum is being revised this term" neyi anlatır?', ['Her yıl değişmeyen kuralı', 'Bu dönem devam eden yenilemeyi'], 1, 'Is being revised sürmekte olan edilgen işi gösterir.'),
    soru('"Applications are submitted online each spring" düzenli tekrarlanan bir süreci anlatır.', true, 'Each spring sıklık/zaman öbeğidir; are submitted geniş zaman edilgenidir.'),
    sikli('Bir okul politikasının etkisini hangi veriyle değerlendirmek daha uygundur?', ['Katılım ve öğrenme sonuçlarıyla', 'Yalnız politika başlığıyla'], 0, 'Politikanın adı değil, uygulama sonrası katılım ve sonuçlar etkisini gösterir.'),
    soru('Curriculum tek bir dersin sayfa içeriği, content ise bütün okulun müfredatıdır.', false, 'Curriculum genel ders planı; content işlenen ayrıntılı içeriktir.'),
    sikli('"Students do not have equal access to digital resources" cümlesinden ne çıkar?', ['Tüm öğrenciler aynı cihazı kullanır', 'Erişim koşulları farklıdır'], 1, 'Equal access yokluğu, öğrencilerin kaynaklara aynı biçimde erişemediğini anlatır.'),
    soru('Outcome ve participation her zaman aynı değişimi gösterir.', false, 'Öğrenme sonucu ile katılım ayrı göstergelerdir; farklı yönlerde hareket edebilir.'),
    sikli('"Science is compulsory; drama is optional" cümlesi neyi karşılaştırır?', ['Derslerin zorunluluk durumunu', 'Öğretmenlerin deneyimini'], 0, 'Compulsory zorunlu, optional seçmeli oluşu belirtir.'),
    soru('"The policy allows students to revise their work" öğrencilerin taslaklarını düzeltebildiğini söyler.', true, 'Revise, yapılmış bir işi gözden geçirip iyileştirmektir.'),
    sikli('İki ülkenin sistemini adil kıyaslamak için ne gerekir?', ['Birinin yalnız ücretine bakmak', 'Aynı ölçütleri ikisine uygulamak'], 1, 'Müfredat, erişim ve ölçme gibi ortak ölçütler karşılaştırmayı anlamlı kılar.'),
  ],
  'ing11-milli-gunler': [
    soru('"Republic Day is celebrated on 29 October" cümlesi günün ne zaman kutlandığını belirtir.', true, 'On 29 October tarih öbeğidir; is celebrated geniş zaman edilgenidir.'),
    sikli('23 Nisan’ın resmî İngilizce adı hangisidir?', ['National Sovereignty and Children’s Day', 'Commemoration of Atatürk Day'], 0, 'National Sovereignty and Children’s Day 23 Nisan’ı adlandırır.'),
    soru('"The programme is being prepared today" yıllardır değişmeyen bir geleneği anlatır.', false, 'Is being prepared bugün devam eden hazırlığı anlatır.'),
    sikli('"Young people join sports events on 19 May" cümlesindeki join ne demek?', ['Etkinliği ertelemek', 'Etkinliğe katılmak'], 1, 'Join, bir gruba veya etkinliğe katılmayı anlatır.'),
    soru('"Our school holds a ceremony every year" düzenli tekrarı geniş zamanla anlatır.', true, 'Every year sıklık bildirir; holds alışılmış eylemi gösterir.'),
    sikli('30 August için uygun İngilizce ad hangisidir?', ['Victory Day', 'Republic Day'], 0, 'Victory Day 30 Ağustos’tur; Republic Day 29 Ekim’dir.'),
    soru('"Flags are displayed in the school hall" cümlesi bayrakları sergileyen kişiyi öne çıkarır.', false, 'Edilgen yapıda flags özne olur; yapan kişi cümlede belirtilmez.'),
    sikli('"The concert is being prepared now" hangi anlama yakındır?', ['Her yıl aynı anda olur', 'Hazırlık şu anda sürüyor'], 1, 'Being prepared now, devam eden edilgen eylemi gösterir.'),
    soru('Eid al-Fitr, İngilizcede Kurban Bayramı’nın adıdır.', false, 'Eid al-Fitr Ramazan Bayramı; Kurban Bayramı Eid al-Adha’dır.'),
    sikli('"In the school hall on Friday" öbekleri neyi verir?', ['Yer ve gün', 'Sıklık ve süre'], 0, 'In the school hall yer, on Friday gün bilgisidir.'),
    soru('"Keep me in the loop" konuşmacının gelişmelerden haberdar edilmesini istemesidir.', true, 'Bu ifade, bir konudaki yeni bilgilerden haberdar kalma isteğini belirtir.'),
    sikli('15 July için programdaki İngilizce gün adı hangisidir?', ['Victory Day', 'Democracy and National Unity Day'], 1, 'Democracy and National Unity Day 15 Temmuz’un adıdır.'),
  ],
  'ing11-ogrenme-bicimleri': [
    soru('"I prefer diagrams for this topic" öğrencinin bütün konularda değişmez bir öğrenme tipi olduğunu kanıtlar.', false, 'Prefer, bu konu için bir tercihtir; kişiyi kalıcı tek tipe indirmez.'),
    sikli('Model kurup deneyen sınıf için hangi etkinlik daha uygundur?', ['Practical workshop', 'Silent copying drill'], 0, 'Atölye uygulamaya uygundur; kopyalama model kurmayı sağlamaz.'),
    soru('"The workshop starts at nine tomorrow" sabit ders çizelgesini geniş zamanla verebilir.', true, 'Programlanmış gelecekteki başlangıçlar simple present ile söylenebilir.'),
    sikli('"We are meeting our study group tomorrow" neyi gösterir?', ['Genel alışkanlığı', 'Kararlaştırılmış buluşmayı'], 1, 'Present progressive, önceden ayarlanmış gelecek buluşmasını anlatır.'),
    soru('Kısa tekrar alıştırması yararlı olabilir; bir etkinliğin değeri amacına bağlıdır.', true, 'Drill biçim öğrenmeye, tartışma fikir geliştirmeye yardım edebilir.'),
    sikli('Bir arkadaş "I need a partner" dediği anda gönüllü olmak için hangisi uygun?', ['I will join you.', 'I am going to join you.'], 0, 'Konuşma anında verilen karar için will daha uygundur; going to önceden kurulmuş planı çağrıştırır.'),
    soru('"Group work can promote interaction" grup çalışmasının her koşulda etkileşimi artırdığını kesin söyler.', false, 'Can olasılık bildirir; etkileşim bağlama ve uygulamaya bağlıdır.'),
    sikli('Nazikçe son adımı açıklamasını isterken hangisi uygun?', ['You explained it.', 'Could you explain the last step?'], 1, 'Could you, nazik rica kalıbıdır.'),
    soru('"I am going to join the debate" o anda verilen beklenmedik karar için en belirgin yapıdır.', false, 'Be going to önceden kurulan planı; anlık karar genellikle will ile anlatılır.'),
    sikli('Yazmadan önce fikirleri birlikte tartışan grup nasıl çalışır?', ['Collaboratively', 'Independently without interaction'], 0, 'Collaboratively, ortak fikir geliştirip birlikte üretmeyi anlatır.'),
    soru('"Noise may restrict concentration" gürültünün odaklanmayı sınırlayabileceğini belirtir.', true, 'Restrict kısıtlamak; may ise olasılık bildirir.'),
    sikli('"Could you help me with the chart?" ifadesinin işlevi nedir?', ['Kesin ders çizelgesi', 'Nazik yardım isteği'], 1, 'Could you birinden kibarca yardım istemek için kullanılır.'),
  ],
  'ing11-geleneksel-dijital': [
    soru('"The video can be replayed" dijital kaydın yeniden izlenebileceğini söyler.', true, 'Replay yeniden oynatmak demektir; basılı notun çevrim dışı çalışmasından farklı bir olanaktır.'),
    sikli('İnternet yokken hangi kaynak doğrudan kullanılabilir?', ['Printed handout', 'Online-only video'], 0, 'Basılı dağıtım çevrim dışıdır; yalnız çevrim içi video bağlantı ister.'),
    soru('"Some students cannot access the platform at home" herkeste aynı dijital erişim olduğunu gösterir.', false, 'Cannot access, bazı öğrencilerin evde platforma ulaşamadığını açıkça söyler.'),
    sikli('"The smart board will be updated next week" cümlesinde odak nedir?', ['Güncelleyen teknisyen', 'Güncellenecek tahta'], 1, 'Will be updated gelecek zaman edilgenidir; nesneyi öne çıkarır.'),
    soru('"We are installing antivirus software tomorrow" önceden ayarlanmış gelecek işi anlatabilir.', true, 'Present progressive burada belirlenmiş gelecek düzenlemesi için kullanılır.'),
    sikli('"Hand in the task" ifadesinin karşılığı hangisidir?', ['Görevi teslim et', 'Görevi gözden geçir'], 0, 'Hand in teslim etmek; go over gözden geçirmek demektir.'),
    soru('Teknoloji bir ders için yararlıysa bütün öğrencilerin cihaza eşit erişimi olduğu varsayılabilir.', false, 'Ders planı yapılırken bağlantı ve cihaz erişimi ayrıca sorgulanmalıdır.'),
    sikli('Proje için dijital kaynak kullanımı önceden planlandı. Hangi cümle bunu vurgular?', ['We may use digital resources.', 'We are going to use digital resources.'], 1, 'Be going to hazır planı bildirir; may ise yalnız olasılık anlatır.'),
    soru('"The textbook gives a clear sequence, whereas the app offers instant feedback" iki aracın farklı yararını karşılaştırır.', true, 'Whereas karşıtlığı kurar; cümle her araca ayrı güçlü yön verir.'),
    sikli('Nazikçe form doldurulmasını isterken hangi cümle uygun?', ['Could you fill out this form, please?', 'You fill out this form now.'], 0, 'Could you ve please kibar rica kurar.'),
    soru('"Keep up with the class" sınıfın hızına yetişemeyip geride kalmak anlamındadır.', false, 'Keep up with yetişmek ve takip etmektir; geride kalmak fall behind olur.'),
    sikli('"The online session starts at ten tomorrow" neden geniş zamandır?', ['Anlık karar olduğu için', 'Sabit çizelgeyi anlattığı için'], 1, 'Programlı başlangıç saatleri simple present ile verilebilir.'),
  ],
}
