import { soru, sikli } from '../tip'
import type { SoruKarti } from '../tip'

/** Bağlamı okuma ve dili doğru kullanma yoklamaları; her konuda altı iddia, altı seçim. */
export const ingilizce11Sorulari4: Record<string, Omit<SoruKarti, 'id'>[]> = {
  'ing11-kuresellesme': [
    soru('“Cultural exchange” iki toplumun birbirinden fikir ve gelenek öğrenmesini anlatabilir.', true, 'Exchange karşılıklı paylaşım demektir; tek yönlü bir aktarım zorunlu değildir.'),
    soru('“Standard of living” yalnızca bir ülkedeki ortalama maaşı belirtir.', false, 'Yaşam düzeyi, gelir yanında sağlık, barınma ve eğitim gibi olanakları da kapsar.'),
    soru('“Companies will be trading at noon tomorrow” gelecekteki belirli anda süren işi anlatır.', true, 'Will be + -ing, gelecekte belirtilen anda devam eden eyleme odaklanır.'),
    soru('“New policies will be being discussed” cümlesinde politikalar tartışmayı yürütür.', false, 'Edilgen yapıda politikalar tartışılan ögedir; yapan kişi öne çıkarılmaz.'),
    soru('“Face up to a health crisis” krizi görmezden gelmek yerine onunla yüzleşmektir.', true, 'Face up to, zor bir sorunu kabul ederek ele alma anlamına gelir.'),
    soru('“Therefore” bir cümlede nedenin ardından karşıt görüşe geçmek için kullanılır.', false, 'Therefore sonuç bildirir; karşıtlık kurmak için however veya although gibi bağlaçlar gerekir.'),
    sikli('Ucuz ithalatın yerel üreticiye etkisini de anan en dengeli yorum hangisi?', ['Trade helps everyone equally.', 'Trade helps buyers but may pressure firms.'], 1, 'İkinci cümle yararı ve olası bedeli birlikte değerlendirir; kesin ve gerekçesiz genelleme yapmaz.'),
    sikli('Bir ülke farklı ülkelerden öğrenci ağırlıyor. Hangi ifade uygun?', ['A cross-cultural programme', 'A job-loss programme'], 0, 'Farklı kültürlerin temas ettiği program için cross-cultural kullanılır.'),
    sikli('“Firms ___ goods across borders at this time next year.” Boşluk nasıl tamamlanır?', ['will have traded', 'will be trading'], 1, 'At this time next year, gelecekte belirli bir anda sürmekte olacak eylemi işaret eder.'),
    sikli('Ülkeler kriz sırasında ilaç gönderiyor. Hangi fiil amacı doğrudan anlatır?', ['supply', 'contrast'], 0, 'Supply ihtiyaç duyulan malzemeyi sağlamak, contrast ise karşılaştırmaktır.'),
    sikli('“Come up with” hangi öbekle anlamca uyumludur?', ['a new solution', 'a problem to ignore'], 0, 'Come up with bir çözüm veya fikir geliştirmeyi anlatır; sorunu yok saymak değildir.'),
    sikli('“Because demand rose, prices increased.” Aynı ilişkiyi hangi cümle korur?', ['Demand rose; however, prices increased.', 'Demand rose; therefore, prices increased.'], 1, 'Therefore artan talebin ardından gelen fiyat artışını sonuç olarak bağlar.'),
    sikli('Bir metinde “job loss” geçiyorsa hangi başlık daha uygun olur?', ['Trade and its possible costs', 'School celebrations'], 0, 'Job loss iş kaybıdır; ticaretin veya küreselleşmenin olası maliyetleriyle ilgilidir.'),
  ],
  'ing11-cevre-sorunlari': [
    soru('“Cut down on single-use plastics” tek kullanımlık plastik tüketimini azaltmayı önerir.', true, 'Cut down on miktarı azaltmaktır; cümle tüketim davranışına yönelir.'),
    soru('“Clean up the river” nehirdeki kirliliği temizlemeyi değil, yenisini üretmeyi anlatır.', false, 'Clean up mevcut kirliliği gidermeye yönelik bir eylemdir.'),
    soru('“Sea level rise” ile “melting ice caps” bir neden-sonuç zincirinde birlikte ele alınabilir.', true, 'Buz örtülerinin erimesi deniz seviyesinin yükselmesine katkıda bulunabilir.'),
    soru('“Ozone layer” ve “greenhouse effect” çevre metninde aynı olgunun iki adıdır.', false, 'Biri atmosfer katmanı, diğeri ısı tutma sürecidir; anlamları farklıdır.'),
    soru('“More waste will be being recycled” cümlesinde atık, eylemden etkilenen ögedir.', true, 'Edilgen gelecekte sürme yapısı, atığın geri dönüştürülmekte olacağını anlatır.'),
    soru('“Zero-waste” yalnızca çöp kutularını daha sık boşaltmak anlamına gelir.', false, 'Sıfır atık öncelikle atığın oluşmasını azaltma, yeniden kullanma ve onarmayı içerir.'),
    sikli('Bir fabrika salımı azaltacaksa hangi öneri soruna doğrudan yönelir?', ['Cut down on carbon emissions', 'Increase carbon emissions'], 0, 'Cut down on, karbon salımını azaltmak demektir.'),
    sikli('“The river is contaminated” ifadesine en yakın anlam hangisi?', ['The river is polluted.', 'The river is protected.'], 0, 'Contaminated kirlenmiş demektir; protected korunmuş anlamındadır.'),
    sikli('Bir metin “glaciers are shrinking” diyorsa hangi çıkarım güvenlidir?', ['Bütün buzullar artık yoktur.', 'Metin buzulların küçüldüğünü bildirir.'], 1, 'Shrinking küçülme anlamı taşır; tamamının yok olduğu sonucunu vermez.'),
    sikli('“Cities ___ emissions at this time next year.” Süreç anlamı için doğru seçenek hangisi?', ['will reduce', 'will be reducing'], 1, 'Will be reducing, gelecekte belirtilen anda sürmekte olacak azaltma eylemini belirtir.'),
    sikli('Hangi cümle önerisine somut dayanak ekler?', ['Recycling is always perfect.', 'Recycling cuts waste sent to landfill.'], 1, 'İkinci cümle öneriyi gözlenebilir bir sonuçla temellendirir; “always” gibi mutlak bir hüküm kurmaz.'),
    sikli('Kirliliği oluşmadan önlemeye en yakın eylem hangisi?', ['Use reusable containers.', 'Collect litter after it spreads.'], 0, 'Yeniden kullanılabilir kap seçimi atığı baştan azaltır; toplama, oluştuktan sonra müdahaledir.'),
    sikli('Buzul küçülmesini doğrudan belirten ifade hangisi?', ['Glaciers are shrinking.', 'Glaciers are growing.'], 0, 'Shrinking küçülmeyi, growing büyümeyi anlatır.'),
  ],
  'ing11-gelecek-yasam': [
    soru('AR, gerçek çevrenin üstüne sayısal bilgi ekleyebilir.', true, 'Augmented reality, görülen gerçek dünyayı sayısal bir katmanla zenginleştirir.'),
    soru('VR ve AR, kullanıcının gerçek çevreyi aynı biçimde görmesini sağlar.', false, 'VR sayısal ortama taşır; AR gerçek görüntünün üzerine sayısal öge ekler.'),
    soru('“If I had a smart home, I would save energy” bugün için gerçek dışı bir varsayım kurar.', true, 'If + geçmiş biçim ve would, bugüne ilişkin varsayımsal ikinci koşuldur.'),
    soru('“I wish I had more time” cümlesindeki “had” mutlaka geçmişte bitmiş bir zamanı gösterir.', false, 'Wish + geçmiş biçim, şu an karşılanmayan dileği de anlatır.'),
    soru('“Telecommuting saves travel time” işe gidiş geliş süresinin azalabileceğini söyler.', true, 'Uzaktan çalışma, ofise yolculuk gereksinimini azaltabilir; cümledeki odak budur.'),
    soru('“Could” ve “will certainly” bir gelecek tahmininde aynı kesinlik düzeyini taşır.', false, 'Could olasılık bildirir; will certainly güçlü kesinlik ileri sürer.'),
    sikli('Öğrenci gerçek odaya kamera tutup ekranda sanal mobilya görüyor. Teknoloji hangisi?', ['Augmented reality', 'Virtual reality'], 0, 'Gerçek görüntü üzerine sayısal mobilya eklemek AR örneğidir.'),
    sikli('“If I ___ more time, I would read more.” Hangi sözcük koşulu tamamlar?', ['have', 'had'], 1, 'İkinci koşulda if bölümünde geçmiş biçim had kullanılır.'),
    sikli('“I wish my home ___ quieter.” Hangisi dileği uygun biçimde verir?', ['were', 'will be'], 0, 'Şimdiki gerçek dışı wish yapısında were kullanılabilir.'),
    sikli('“Wearable device” için yerinde bir örnek hangisi?', ['A wall projector', 'A watch that tracks steps'], 1, 'Vücutta taşınan ve adım izleyen saat giyilebilir teknolojidir.'),
    sikli('Bir tasarımın olası yararını kesinleştirmeden nasıl söylersin?', ['It could save energy.', 'It will always solve everything.'], 0, 'Could olasılığı ve sınırı açık bırakır; ikinci cümle dayanaksız mutlak iddiadır.'),
    sikli('“Equipped with sensors” ifadesi neyi anlatır?', ['Sensörlerden yoksun', 'Sensörlerle donatılmış'], 1, 'Equipped with, bir araç veya yapının belirtilen donanıma sahip olmasıdır.'),
    sikli('Bugünkü odası gürültülü olan kişi hangi dileği söyler?', ['I wish my room were quieter.', 'I wish my room is noisy.'], 0, 'Wish + geçmiş biçim, bugünkü durumdan farklı bir dileği anlatır.'),
  ],
  'ing11-gelecek-teknolojileri': [
    soru('“Solar panels generate electricity” cümlesinde generate üretmek anlamındadır.', true, 'Generate enerjinin üretilmesini anlatır; depolama başka bir iştir.'),
    soru('“A sensor tracks air quality” sensörün hava kalitesini izlediğini söyler.', true, 'Track zaman içindeki durumu izlemektir; cümle kesin olarak çözüm üretildiğini söylemez.'),
    soru('“If I designed a robot, it would…” kesinleşmiş üretim takvimini açıklar.', false, 'İkinci koşul bir tasarımı varsayımsal olarak ele alır; gerçekleşmiş plan değildir.'),
    soru('“Cutting-edge” sözü herhangi bir eski ama pahalı cihazı tanımlamak için yeterlidir.', false, 'Cutting-edge çok yeni ve ileri teknolojiye işaret eder; fiyat tek başına ölçüt değildir.'),
    soru('“I wish batteries lasted longer” bugünkü pil ömründen memnuniyetsizliği sezdirir.', true, 'Wish + geçmiş biçim, mevcut gerçeklikten farklı bir istek kurar.'),
    soru('“Detect an obstacle” ve “avoid an obstacle” aynı eylemi anlatır.', false, 'Detect fark etmek; avoid engelden kaçınmaktır. Arada karar verme gerekir.'),
    sikli('Güneş paneli elektriği üretiyor, batarya onu saklıyor. Doğru fiil ikilisi hangisi?', ['generate / store', 'store / generate'], 0, 'Panel generate eder, batarya store eder; üretim ve depolama ayrıdır.'),
    sikli('Küçük ölçekte malzeme geliştiren alan hangisi?', ['Robotics', 'Nanotechnology'], 1, 'Nanotechnology çok küçük ölçekli malzeme ve aygıtlarla ilgilenir.'),
    sikli('Bir drone tıbbi malzeme taşıyor. Hangi değerlendirme dengelidir?', ['It is useful, but safety must be considered.', 'It can never cause a problem.'], 0, 'İlk cümle yararı belirtirken güvenlik sınırını da dikkate alır.'),
    sikli('“I wish batteries ___ longer.” Doğru kullanım hangisi?', ['will last', 'lasted'], 1, 'Wish ile bugünkü karşılanmayan dilek geçmiş biçim lasted ile anlatılır.'),
    sikli('“A headset creates an immersive digital world.” Hangi aygıtla daha çok ilgilidir?', ['A VR headset', 'A solar panel'], 0, 'Sanal ortama dalma VR başlığının işlevidir; güneş paneli elektrik üretir.'),
    sikli('Teknolojinin mahremiyet etkisini ihtiyatla söyleyen ifade hangisi?', ['It never affects privacy.', 'It may raise privacy questions.'], 1, 'May olasılık bildirir ve henüz kanıtlanmamış kesin bir sonuç dayatmaz.'),
    sikli('Bir aygıtın yeni ve ileri olduğunu anlatan sıfat hangisi?', ['outdated', 'cutting-edge'], 1, 'Cutting-edge güncel ve ileri düzey teknolojiyi niteler; outdated eski kalmış demektir.'),
  ],
}
