import { sikli, soru, type SoruKarti } from '../tip'

type Iddia = [ifade: string, dogru: boolean, aciklama: string]
type Secim = [soru: string, siklar: [string, string], dogru: 0 | 1, aciklama: string]

function sorular(iddialar: Iddia[], secimler: Secim[]): Omit<SoruKarti, 'id'>[] {
  const sonuc: Omit<SoruKarti, 'id'>[] = []
  for (let i = 0; i < Math.max(iddialar.length, secimler.length); i++) {
    if (i < iddialar.length) sonuc.push(soru(...iddialar[i]))
    if (i < secimler.length) sonuc.push(sikli(...secimler[i]))
  }
  return sonuc
}

export const kimya11Sorulari: Record<string, Omit<SoruKarti, 'id'>[]> = {
  'kim11-enerji-degisim': sorular([
    ['Yalıtılmış kaptaki su ısınırken tepkime sisteminin verdiği ısının işareti negatiftir.', true, 'Su ortamdır; su ısı alıyorsa tepkime ısı verir ve ΔH negatiftir.'],
    ['Tepkime ters yazıldığında ΔH’nin işareti değişir, mutlak değeri aynı kalır.', true, 'Ters yönde aynı miktarda ısı alınır veya verilir.'],
    ['Ürünler tepkenlerden yüksek enerjideyse ileri tepkime ekzotermiktir.', false, 'Yüksekteki ürünlere ulaşmak için sistem enerji alır; ΔH pozitiftir.'],
    ['100 g suyun sıcaklığı 10 °C artarsa aldığı ısı yaklaşık 4,18 kJ’dür.', true, 'q = 100 × 4,18 × 10 = 4180 J = 4,18 kJ.'],
    ['Bir tepkimenin denklemi ikiyle çarpılırsa mol başına ΔH değişmeden kalır.', false, 'Termokimyasal denklemde tepkime miktarı iki katına çıkınca yazılan toplam ΔH de iki katına çıkar.'],
    ['Buharlaşma ve yoğuşma aynı yönde ısı alışverişi yapar.', false, 'Buharlaşma ısı alır; ters olay olan yoğuşma ısı verir.'],
  ], [
    ['ΔH = −80 kJ olan tepkime ters çevrilip ikiyle çarpılırsa yeni ΔH nedir?', ['+160 kJ', '−160 kJ'], 0, 'Ters çevirme işareti, ikiyle çarpma büyüklüğü değiştirir.'],
    ['200 g su 5 °C ısınırsa tepkimenin verdiği ısı yaklaşık kaç kJ olur?', ['2,09', '4,18'], 1, 'q = 200 × 4,18 × 5 = 4180 J = 4,18 kJ.'],
    ['Sıcak paket hazırlanırken hangi olay seçilir?', ['NH₄NO₃’ün çözünmesi', 'CaCl₂’nin çözünmesi'], 1, 'CaCl₂ çözünmesi ısı verir; NH₄NO₃ çözünmesi ısı alır.'],
    ['Tepken 120, ürün 70 kJ düzeyindeyse ΔH kaç kJ olur?', ['−50', '+50'], 0, 'ΔH = H(ürün) − H(tepken) = 70 − 120 = −50 kJ.'],
    ['Suyun ısındığı kalorimetrede sistem hangi yönde ısı aktarır?', ['Sistemden suya', 'Sudan sisteme'], 0, 'Isınan su ısı alır; tepkime sistemi aynı ısıyı verir.'],
    ['H₂O(g) yerine H₂O(s) oluşursa ΔH neden farklı olur?', ['Hâl değişiminin enerjisi eklenir', 'Atom sayısı değişir'], 0, 'Su yoğuşurken ayrıca ısı verir; atom sayısı iki hâlde de aynıdır.'],
    ['Hangi durumda ürünlerin enerjisi daha düşüktür?', ['Endotermik ayrışma', 'Ekzotermik yanma'], 1, 'Ekzotermik tepkimede enerji ortama verilir ve ürünler daha düşük düzeyde kalır.'],
  ]),
  'kim11-enerji-kaynagi': sorular([
    ['Yakıtları kJ/mol ile sıralamak, kJ/g ile aynı sıralamayı vermek zorundadır.', false, 'Mol kütleleri farklıdır; hidrojen kJ/g bakımından, metan kJ/mol bakımından öndedir.'],
    ['30 g yağın enerji değeri yaklaşık 270 kcal’dir.', true, 'Yağın gramı yaklaşık 9 kcal verir; 30 × 9 = 270 kcal.'],
    ['Biyogazın metanı atıklardan üretilebilir.', true, 'Organik atıkların oksijensiz ayrışması metan içeren biyogaz oluşturur.'],
    ['Bir yakıtın enerji değeri yüksekse depolama güvenliği ayrıca değerlendirilemez.', false, 'Enerji değeri yalnız bir ölçüttür; taşınma, güvenlik ve emisyon da önemlidir.'],
    ['Alkanlarda karbon sayısı arttıkça verilen mol başına yanma enerjisi de artabilir.', true, 'Metan, etan ve propan verileri mol başına enerjinin arttığını gösterir.'],
    ['Pil kimyasal enerjiyi yalnızca yakma tepkimesiyle elektriğe dönüştürür.', false, 'Pil yanma olmadan elektrokimyasal tepkimelerle elektrik sağlar.'],
  ], [
    ['Eşit kütlede en çok enerji hangi yakıttan elde edilir?', ['Metan: 55 kJ/g', 'Hidrojen: 142 kJ/g'], 1, 'Karşılaştırma eşit gram üzerinden yapıldığından 142 kJ/g daha büyüktür.'],
    ['Eşit mol yakıttan hangisi daha çok enerji verir?', ['Metan: 890 kJ/mol', 'Hidrojen: 286 kJ/mol'], 0, 'Bu kez ölçüt mol başına enerjidir; metan daha yüksektir.'],
    ['20 g karbonhidrat yaklaşık kaç kcal verir?', ['80 kcal', '180 kcal'], 0, 'Karbonhidrat 4 kcal/g; 20 × 4 = 80 kcal.'],
    ['100 kcal yaklaşık kaç kJ’dür?', ['239 kJ', '418 kJ'], 1, '1 kcal = 4,18 kJ; 100 kcal = 418 kJ.'],
    ['Kükürt içeren kömür yakıldığında hangi çevresel sonuç beklenir?', ['Asit yağmuru riski', 'CO₂ çıkışının durması'], 0, 'Oluşan SO₂ asit yağmuruna katkıda bulunur; CO₂ çıkışı da sürer.'],
    ['Birim kütledeki enerji yüksek olsa da hidrojen için hangi sorun araştırılır?', ['Depolama ve taşıma', 'Mol başına kütlenin sabitliği'], 0, 'Hidrojenin güvenli ve yoğun biçimde depolanması kullanım kararında önemlidir.'],
  ]),
  'kim11-bag-entalpi': sorular([
    ['Bağ koparmak enerji gerektirdiğinden bağ enerjisi pozitif tanımlanır.', true, 'Gaz hâlindeki bir mol bağı koparmak için sisteme enerji verilir.'],
    ['Oluşan bağların toplam enerjisi kırılanlardan büyükse ΔH pozitiftir.', false, 'ΔH = kırılan − oluşan; büyük oluşan toplamı sonucu negatif yapar.'],
    ['CH₄ molekülündeki dört C–H bağı hesaba dört kez katılır.', true, 'Bağ sayısı molekülün yapısından ve denklem katsayısından bulunur.'],
    ['C=C bağının enerjisi C–C ile aynı alınabilir.', false, 'Çift bağın kopma enerjisi tek bağdan farklıdır.'],
    ['Ortalama bağ enerjileriyle bulunan ΔH yaklaşık bir değerdir.', true, 'Değerler birçok gaz molekülünden türetilen ortalamalardır.'],
  ], [
    ['Kırılan bağlar 500, oluşanlar 650 kJ ise ΔH kaç kJ olur?', ['−150', '+150'], 0, 'ΔH = 500 − 650 = −150 kJ.'],
    ['H₂ + Cl₂ → 2HCl için kaç H–Cl bağı oluşur?', ['Bir', 'İki'], 1, 'Ürün tarafındaki 2HCl toplam iki H–Cl bağı içerir.'],
    ['H–H 436, Cl–Cl 243, H–Cl 432 kJ/mol ise ΔH yaklaşık kaçtır?', ['−185 kJ', '+185 kJ'], 0, 'Kırılanlar 679, oluşanlar 864 kJ; fark −185 kJ.'],
    ['N₂’nin tepkimeye girmekte zorlanması hangi bağla ilişkilidir?', ['N–N tek bağı', 'N≡N üçlü bağı'], 1, 'N≡N üçlü bağı çok yüksek kopma enerjisine sahiptir.'],
    ['Bağ enerjisi yöntemi hangi ortam için doğrudan uygundur?', ['Gaz hâlindeki maddeler', 'Sulu çözeltiler'], 0, 'Tablo değerleri gaz moleküllerinin bağlarını koparmaya aittir.'],
    ['Metan yanarken 2648 kJ bağ kırılıp 3450 kJ bağ kurulursa net olay?', ['802 kJ ısı verir', '802 kJ ısı alır'], 0, 'ΔH = 2648 − 3450 = −802 kJ; negatif sonuç ısı verildiğini gösterir.'],
  ]),
  'kim11-olusum-entalpisi': sorular([
    ['O₂(g) standart hâldeki element olduğundan ΔH°f değeri sıfırdır.', true, 'En kararlı standart hâlindeki elementlerin oluşum entalpisi sıfır kabul edilir.'],
    ['O₃(g) elementlerden oluştuğu için standart oluşum entalpisi sıfırdır.', false, 'Oksijenin standart ve en kararlı hâli O₂(g)’dir; ozonunki sıfır değildir.'],
    ['Bir oluşum denkleminde ürün tarafında tam 1 mol bileşik bulunur.', true, 'Standart oluşum entalpisi 1 mol bileşiğin elementlerinden oluşmasına tanımlıdır.'],
    ['CO + ½O₂ → CO₂, CO₂’nin standart oluşum tepkimesidir.', false, 'CO element değildir; tepkime elementlerden başlamalıdır.'],
    ['Tepkime entalpisi, ürün ve tepken oluşum entalpileri farkıyla bulunabilir.', true, 'Katsayılı ürün toplamından katsayılı tepken toplamı çıkarılır.'],
    ['Bağ enerjisi ve oluşum entalpisi hesaplarının ölçüm temeli özdeştir.', false, 'Bağ enerjileri ortalama gaz bağı değerleri; oluşum entalpileri maddeye özgü ölçümlerdir.'],
  ], [
    ['H₂(g) + ½O₂(g) → H₂O(s) tepkimesi hangi niceliği verir?', ['H₂O’nun ΔH°f değeri', 'H₂O’nun bağ enerjisi'], 0, 'Standart elementlerden bir mol sıvı su oluşmaktadır.'],
    ['2H₂ + O₂ → 2H₂O için ΔH = −572 kJ ise H₂O’nun ΔH°f değeri?', ['−572 kJ/mol', '−286 kJ/mol'], 1, 'İki mol suyun toplamı −572 kJ ise mol başına −286 kJ’dür.'],
    ['Ürün toplamı −900, tepken toplamı −100 kJ ise ΔH kaç kJ?', ['−800', '+800'], 0, 'ΔH = −900 − (−100) = −800 kJ.'],
    ['Grafit ve elmas için hangisinin standart oluşum entalpisi sıfırdır?', ['Elmasın', 'Grafitin'], 1, 'Karbonun standart koşullardaki en kararlı hâli grafittir.'],
    ['CH₄ + 2O₂ → CO₂ + 2H₂O için hangi terim ikiyle çarpılır?', ['H₂O’nun ΔH°f değeri', 'CH₄’ün ΔH°f değeri'], 0, 'Oluşum entalpileri denklem katsayılarıyla çarpılır; suyun katsayısı 2’dir.'],
    ['Tepkime farklı ara basamaklarla yürütülürse toplam ΔH için ne söylenir?', ['Basamak sayısıyla artar', 'Başlangıç ve sona bağlı kalır'], 1, 'Entalpi hâl fonksiyonudur; izlenen yol toplam ΔH’yi değiştirmez.'],
    ['H₂O(s) yerine H₂O(g) oluşursa hesapta ne değişir?', ['Suyun ΔH°f değeri', 'O₂’nin sıfır değeri'], 0, 'Fiziksel hâl değiştiği için suyun standart oluşum entalpisi farklıdır.'],
  ]),
  'kim11-hiz-sartlar': sorular([
    ['Yeterli enerjili her çarpışma, yönelim ne olursa olsun ürün oluşturur.', false, 'Etkin çarpışma için enerji yanında uygun yönelim de gerekir.'],
    ['İleri aktivasyon enerjisi 50, geri 80 kJ ise ileri tepkime ekzotermiktir.', true, 'ΔH = Ea(ileri) − Ea(geri) = −30 kJ.'],
    ['Ekzotermik odun yanmasının başlaması için de ilk enerji girdisi gerekir.', true, 'Kibrit veya sürtünme aktivasyon engelinin aşılmasını sağlar.'],
    ['Aktifleşmiş kompleks ürünlerden daha düşük enerjidedir.', false, 'Geçiş hâli enerji diyagramının en yüksek noktasındadır.'],
    ['Aynı sıcaklıktaki tüm tanecikler eşit kinetik enerji taşır.', false, 'Taneciklerin enerjisi dağılım gösterir; yalnız bir kesimi Ea’yı aşar.'],
    ['Tepkimenin ısı vermesi, gözlenebilir hızda gerçekleşeceğini kanıtlamaz.', true, 'Elmasın grafite dönüşümü gibi olaylar yüksek Ea yüzünden çok yavaş olabilir.'],
  ], [
    ['Ea ileri 75, geri 45 kJ ise ΔH kaç kJ’dür?', ['+30', '−30'], 0, 'ΔH = 75 − 45 = +30 kJ; ileri yön endotermiktir.'],
    ['CO ile NO₂ çarpışmasında hangi uçların teması uygundur?', ['CO’nun C’si, NO₂’nin O’su', 'CO’nun C’si, NO₂’nin N’si'], 0, 'CO’nun karbonu NO₂’deki oksijenle yeni bağ kurar.'],
    ['Bir tepkime çok yavaşsa enerji diyagramında hangi özellik beklenir?', ['Düşük ürün enerjisi', 'Yüksek ileri Ea'], 1, 'Büyük aktivasyon engelini az tanecik aşar; hız düşer.'],
    ['Sıcaklık artınca hangi kesim özellikle büyür?', ['Enerjisi Ea’yı aşanlar', 'Aktifleşmiş kompleksin kütlesi'], 0, 'Enerji dağılımında eşik üzerindeki taneciklerin payı artar.'],
    ['Geçiş hâlinin enerjisi 100, tepkenlerin 40 kJ ise Ea(ileri)?', ['140 kJ', '60 kJ'], 1, 'Ea ileri = geçiş hâli − tepkenler = 100 − 40 = 60 kJ.'],
    ['Ürünler 20, tepkenler 40 kJ ise hangi yönde Ea daha büyüktür?', ['İleri', 'Geri'], 1, 'Ürünler daha aşağıda olduğu için tepeye çıkış geri yönde daha uzundur.'],
  ]),
  'kim11-ortalama-hiz': sorular([
    ['Tepken derişimi azalırken hesaplanan tepkime hızının pozitif olması için eksi işareti kullanılır.', true, 'Tepkenin Δ derişimi negatiftir; −Δ[tepken]/Δt pozitif hız verir.'],
    ['N₂ + 3H₂ → 2NH₃ tepkimesinde H₂, N₂’den üç kat hızlı harcanır.', true, 'Derişim değişimlerinin oranı denklem katsayılarının oranına eşittir.'],
    ['Bir ürünün derişim-zaman grafiğinin eğimi oluşma hızını gösterir.', true, 'Birim zamandaki derişim artışı grafiğin eğimidir.'],
    ['Ortalama hız, eğrinin seçilen tek noktasındaki teğet eğimidir.', false, 'Tek noktadaki teğet anlık hızı; aralıktaki değişim bölü süre ortalama hızı verir.'],
    ['Açık kaptan CO₂ kaçan tepkime kütle kaybıyla izlenebilir.', true, 'Gaz ortamdan ayrıldığı için terazide ölçülen toplam kütle azalır.'],
    ['Derişim eğrisi yataylaştığında her zaman tüm tepkenler tükenmiştir.', false, 'Dengeye ulaşan tersinir tepkimede de derişimler sabit kalabilir.'],
  ], [
    ['[A] 0,50 M’den 10 s’de 0,30 M’ye düşerse ortalama kaybolma hızı?', ['0,02 M/s', '0,20 M/s'], 0, '0,20 M değişim 10 saniyeye bölünür: 0,02 M/s.'],
    ['N₂ + 3H₂ → 2NH₃; N₂ 0,01 M/s azalırsa NH₃ kaç M/s artar?', ['0,01', '0,02'], 1, 'NH₃’ün katsayısı N₂’nin iki katıdır.'],
    ['2N₂O₅ → 4NO₂ + O₂; N₂O₅ 0,02 M/s harcanırsa O₂ oluşumu?', ['0,01 M/s', '0,04 M/s'], 0, 'O₂ katsayısı 1, N₂O₅ katsayısı 2; oluşma hızı yarısıdır.'],
    ['Mg + HCl tepkimesinin hızını doğrudan izlemek için hangi ölçüm uygundur?', ['H₂ gaz hacmi', 'Başlangıç HCl hacmi'], 0, 'Oluşan hidrojenin hacmi zamanla artar; başlangıç hacmi değişimi göstermez.'],
    ['Renkli bir tepkenin rengi açılıyorsa hangi ölçüm hızla ilişkilidir?', ['Renk şiddetinin zamana göre değişimi', 'Kabın toplam hacminin sabitliği'], 0, 'Derişim azaldıkça renk şiddeti değişir; değişim hızı izlenebilir.'],
    ['2N₂O₅ → 4NO₂ + O₂; NO₂ 0,04 M/s oluşursa tepkime hızı?', ['0,04 M/s', '0,01 M/s'], 1, 'Tepkime hızı, NO₂ oluşma hızının katsayı 4’e bölünmüş hâlidir.'],
  ]),
  'kim11-hiz-faktor': sorular([
    ['Katı bir tepkeni toz hâline getirmek temas yüzeyini artırır.', true, 'Aynı kütlenin daha büyük yüzeyi çarpışmaya açılır.'],
    ['Katalizör ileri ve geri yönlerin ikisini de hızlandırır.', true, 'Her iki yön için daha düşük aktivasyon enerjili yol sağlar.'],
    ['Katalizör tepkimenin ΔH değerini değiştirir.', false, 'Başlangıç ve ürün enerjileri aynı kalır; yalnız geçilen yol değişir.'],
    ['Sıcaklığı artırmak aktivasyon enerjisini azaltır.', false, 'Ea aynı kalır; onu aşabilecek taneciklerin oranı büyür.'],
    ['Gaz kabının hacmini küçültmek gaz derişimini ve çarpışma sıklığını artırır.', true, 'Aynı tanecik sayısı daha küçük hacme sıkışır.'],
    ['Katı bir tepkenin derişimini artırma düşüncesi, çözeltilerdeki kadar anlamlıdır.', false, 'Saf katının derişimi sabittir; hız etkisi daha çok temas yüzeyiyle olur.'],
    ['İnhibitör ve katalizör tepkime hızını aynı yönde değiştirir.', false, 'İnhibitör yavaşlatır; katalizör hızlandırır.'],
  ], [
    ['Toz kireçtaşı aynı kütledeki parçasından neden hızlı tepkime verir?', ['Temas yüzeyi daha büyük', 'Aktivasyon enerjisi daha küçük'], 0, 'Tozlaştırma yüzeyi artırır; aynı tepkimenin Ea’sını değiştirmez.'],
    ['Buzdolabında bozulmanın yavaşlamasını hangi etki açıklar?', ['Azalan tanecik enerjisi', 'Artan temas yüzeyi'], 0, 'Düşük sıcaklık etkin çarpışma olasılığını azaltır.'],
    ['Katalizör eklenince enerji diyagramında hangisi değişir?', ['Ürün enerji düzeyi', 'Tepe yüksekliği'], 1, 'Katalizör Ea’yı düşüren alternatif yol sağlar; ΔH sabittir.'],
    ['Gaz tepkimesinde kabın hacmi küçülürse ilk etki nedir?', ['Derişimin artması', 'Bağ enerjisinin azalması'], 0, 'Birim hacimde daha çok gaz taneciği bulunur.'],
    ['Aynı tepkimeyi daha hızlı başlatan sıcaklık etkisi hangisidir?', ['Ea değerinin düşmesi', 'Ea’yı aşan kesrin artması'], 1, 'Sıcaklık Ea’yı değil taneciklerin enerji dağılımını değiştirir.'],
    ['H₂O₂ ayrışmasına MnO₂ eklenirse hangi nicelik aynı kalır?', ['Toplam ürün miktarı', 'Başlangıç hızı'], 0, 'Katalizör hızı artırır; aynı başlangıç miktarından elde edilen toplam ürünü değiştirmez.'],
    ['Un tozu havada kütle hâlindeki undan neden daha çabuk yanar?', ['Havadaki O₂ azalır', 'Geniş temas yüzeyi oluşur'], 1, 'Dağılmış ince tanecikler oksijenle daha çok yüzeyden temas eder.'],
  ]),
  'kim11-hiz-denklemi': sorular([
    ['Çok basamaklı tepkimelerde hız denkleminin üsleri yalnız denklem katsayılarından okunur.', false, 'Üsler deneyle belirlenir; katsayı eşitliği ancak tek basamaklı adımda beklenir.'],
    ['r = k[A]²[B] denkleminde toplam tepkime derecesi üçtür.', true, 'Üslerin toplamı 2 + 1 = 3’tür.'],
    ['A derişimi iki katına çıkıp hız dört katına çıkıyorsa A’ya göre derece ikidir.', true, '2² = 4 olduğundan A’nın üssü 2’dir.'],
    ['Derişimi değiştirmek hız sabiti k’yı da zorunlu olarak değiştirir.', false, 'Sıcaklık ve katalizör sabitken k aynı kalır; hız derişim üzerinden değişir.'],
    ['Saf katıların derişimi sabit olduğu için hız denkleminde ayrıca yazılmaz.', true, 'Katının miktarı değil temas yüzeyi hızı etkileyebilir.'],
    ['r = k[A][B] için iki gazın derişimi iki katına çıkarsa hız dört katına çıkar.', true, '2 × 2 = 4; iki tepken birinci derecedendir.'],
  ], [
    ['r = k[A]²[B]; A üç kat, B yarı olursa hız kaç katına çıkar?', ['4,5', '1,5'], 0, '3² × ½ = 4,5.'],
    ['A iki katına çıktığında hız değişmiyorsa A’nın derecesi?', ['Bir', 'Sıfır'], 1, '2⁰ = 1 olduğundan A değişimi hızı etkilemez.'],
    ['r = k[A]²[B]; gaz hacmi yarıya inerse ilk hız kaç katına çıkar?', ['8', '4'], 0, 'Her gaz derişimi iki katına çıkar: 2² × 2 = 8.'],
    ['Üçüncü dereceden tepkimede k’nın birimi hangisidir?', ['s⁻¹', 'L²/mol²·s'], 1, 'k birimi hız M/s’nin M³’e bölünmesiyle M⁻²/s olur.'],
    ['C(k) + O₂(g) → CO₂(g) tek adımlıysa hız denkleminde hangisi görünür?', ['[O₂]', '[C]'], 0, 'Saf katı C’nin derişimi sabit kabul edilir.'],
    ['İki deneyde yalnız B iki kat ve hız iki kat olursa B’nin üssü?', ['1', '2'], 0, 'Hızın B ile doğru orantılı değişmesi birinci derecedir.'],
    ['Hız sabiti değişip derişimler aynı kalırsa hangi etki olasıdır?', ['Gaz hacminin azalması', 'Sıcaklığın artması'], 1, 'k sıcaklığa bağlıdır; hacim değişimi derişimi değiştirir.'],
  ]),
  'kim11-tersinir': sorular([
    ['Dengedeki tersinir tepkimede ileri ve geri tepkimeler durur.', false, 'Dinamik dengede iki yön sürer; eşit olan hızlarıdır.'],
    ['Dengede tepken ve ürün derişimlerinin birbirine eşit olması gerekmez.', true, 'Derişimler zamanla sabit kalır; eşit hız eşit derişim anlamına gelmez.'],
    ['Gaz ürün açık kaptan kaçarsa geri tepkimenin kurulması güçleşir.', true, 'Geri yönde gereken ürün ortamda tutulamadığında denge kurulamaz.'],
    ['Tepkenlerle veya ürünlerle başlayarak aynı sıcaklıkta dengeye ulaşılabilir.', true, 'Tersinir tepkime iki yönde yürüdüğünden dengeye iki taraftan yaklaşılır.'],
    ['Dengeye ulaşınca gözlenen rengin sabit kalması, tepkimenin durduğunu kanıtlar.', false, 'Sabit renk, ileri ve geri hızların eşitlenmesine de bağlı olabilir.'],
    ['Tersinir tepkimede ürünün çekilmesi ileri yönde daha çok ürün oluşmasını sağlayabilir.', true, 'Ürün azalınca sistem onu yeniden oluşturacak yöne kayar.'],
  ], [
    ['Başta yalnız tepken varken hangi hız sıfırdan başlar?', ['Geri tepkime hızı', 'İleri tepkime hızı'], 0, 'Ürün yoksa geri tepkimenin tepkeni de yoktur.'],
    ['Dengeye yaklaşırken ileri ve geri hızlar için ne beklenir?', ['İkisi de sıfırlanır', 'Birbirine yaklaşır'], 1, 'Tepken azalırken ileri hız düşer, ürün artarken geri hız yükselir.'],
    ['Kapalı NO₂ tüpünde rengin ısıtıp soğutunca iki yönde değişmesi neyi gösterir?', ['Tersinirliği', 'Tepkimenin tek yönlü olduğunu'], 0, 'Sistem koşula göre NO₂ ve N₂O₄ yönlerinde ilerleyebilir.'],
    ['CaCO₃ ayrışmasında CO₂’nin kaçmaması için hangi kap gerekir?', ['Açık kap', 'Kapalı kap'], 1, 'Kapalı kapta CO₂ birikip geri tepkimeyi sürdürebilir.'],
    ['Dengede 1 M tepken, 3 M ürün varsa hangi nicelikler eşittir?', ['İleri ve geri hızlar', 'Tepken ve ürün derişimleri'], 0, 'Derişimler farklı olsa da iki yöndeki hızlar eşittir.'],
    ['H₂ + I₂ ⇌ 2HI için yalnız HI ile başlanırsa ilk hangi yön ilerler?', ['İleri', 'Geri'], 1, 'Başlangıçta H₂ ve I₂ yoktur; HI ayrışarak onları oluşturur.'],
  ]),
  'kim11-fiziksel-denge': sorular([
    ['Kapalı kaptaki sıvı-buhar dengesinde buharlaşma ve yoğuşma devam eder.', true, 'İki hız eşit olduğu için toplam buhar miktarı sabit kalır.'],
    ['Buhar basıncı, sıvı varken yalnız sıvının miktarını artırarak yükseltilebilir.', false, 'Sabit sıcaklıkta denge buhar basıncı sıvı miktarından bağımsızdır.'],
    ['Doygun çözeltide katı varsa çözünme ve çökelme aynı anda olabilir.', true, 'İki hız eşitlendiğinde çözeltinin derişimi sabit kalır.'],
    ['H₂O(s) ⇌ H₂O(g) kimyasal dengedir çünkü moleküllerin kimliği değişir.', false, 'İki hâlde de madde H₂O’dur; olay fiziksel dengedir.'],
    ['Gazlı içecek kapağı açılınca CO₂ kaybı çözünme dengesini bozar.', true, 'Gaz dışarı çıkınca çözünmüş CO₂ de gaz hâline geçer.'],
  ], [
    ['Kapalı kapta sıvı suyun buhar basıncını artıran etki?', ['Sıcaklığı artırmak', 'Aynı sıcaklıkta daha çok sıvı eklemek'], 0, 'Sıcaklık yükselince denge buhar basıncı artar.'],
    ['0 °C’de buz-su dengesinde eşit olan nedir?', ['Buz ve su kütlesi', 'Erime ve donma hızları'], 1, 'Hızlar eşittir; iki fazın kütleleri eşit olmak zorunda değildir.'],
    ['N₂O₄ ⇌ 2NO₂ hangi denge türüdür?', ['Kimyasal', 'Fiziksel'], 0, 'Bağlar değişir ve farklı maddeler oluşur.'],
    ['Doygun çözeltiye aynı sıcaklıkta biraz daha katı eklenirse çözünmüş derişim?', ['Artar', 'Aynı kalır'], 1, 'Dipte katı varken doygun çözeltinin derişimi aynı sıcaklıkta sabittir.'],
    ['Akciğerde O₂ arttığında Hb + O₂ ⇌ HbO₂ hangi yönde ilerler?', ['HbO₂ oluşumu', 'HbO₂ ayrışması'], 0, 'Artan O₂, hemoglobinin oksijen bağlamasını destekler.'],
    ['Sıvı-buhar dengesi için kabın hacmi büyütülürse uzun vadede basınç?', ['Başlangıçtaki denge değerine döner', 'Kalıcı olarak azalır'], 0, 'Sıvı bulunduğu sürece daha çok buharlaşma olur ve aynı sıcaklıkta denge basıncı geri gelir.'],
  ]),
  'kim11-denge-sabiti': sorular([
    ['N₂ + 3H₂ ⇌ 2NH₃ için [NH₃] ifadesi Kc payında kare alınır.', true, 'Ürün katsayısı 2, denge ifadesinde üs olur.'],
    ['CaCO₃(k) ⇌ CaO(k) + CO₂(g) için Kc = [CO₂] olur.', true, 'Saf katılar denge bağıntısına girmez.'],
    ['Kc’nin büyük olması tepkimenin mutlaka hızlı olduğunu gösterir.', false, 'Kc denge bileşimini gösterir; hızı belirlemez.'],
    ['Dengedeki bir gazın derişimi değişince aynı sıcaklıktaki Kc değeri de değişir.', false, 'Sistem yeni dengeye kayar; Kc yalnız sıcaklıkla değişir.'],
    ['Denklem ters çevrilince yeni denge sabiti eski K’nın tersidir.', true, 'Ürün ve tepken yer değiştirince denge kesri ters döner.'],
    ['Mol verileriyle Kc hesabında kap hacmi göz ardı edilebilir.', false, 'Kc mol değil molar derişim kullanır; mol sayısı hacme bölünmelidir.'],
  ], [
    ['H₂ + I₂ ⇌ 2HI; derişimler 0,1, 0,1 ve 0,8 M ise Kc?', ['64', '8'], 0, '0,8² / (0,1 × 0,1) = 64.'],
    ['K = 9 olan denklem ikiyle çarpılırsa yeni K?', ['18', '81'], 1, 'Denklem iki katına çıkınca K² = 81 olur.'],
    ['K = 4 olan tepkime ters yazılırsa yeni K?', ['0,25', '4'], 0, 'Ters yönde K = 1/4 = 0,25.'],
    ['2 L kapta 0,4 mol NH₃ varsa denge derişimi?', ['0,4 M', '0,2 M'], 1, 'Molarite mol/hacim = 0,4/2 = 0,2 M.'],
    ['H₂ + I₂ ⇌ 2HI için Kp/Kc hangi durumda 1’dir?', ['Δn gaz = 0 olduğunda', 'Ürünler sıvı olduğunda'], 0, 'Gaz mol sayısı iki tarafta eşittir; (RT)⁰ = 1.'],
    ['3Fe(k) + 4H₂O(g) ⇌ Fe₃O₄(k) + 4H₂(g) ifadesinde pay?', ['[Fe₃O₄] × [H₂]⁴', '[H₂]⁴'], 1, 'Katı Fe₃O₄ yazılmaz; gaz H₂ dördüncü kuvvettedir.'],
    ['Kc = 0,001 ise dengede genellikle hangi taraf baskındır?', ['Tepkenler', 'Ürünler'], 0, 'Kc çok küçükse ürün/tepken oranı küçüktür.'],
  ]),
  'kim11-tepkime-orani': sorular([
    ['Q, Kc ile aynı bağıntıyla yazılır ama herhangi bir anın derişimlerini kullanır.', true, 'K yalnız dengede, Q ise o andaki değerlerden hesaplanır.'],
    ['Q < K ise sistem geri yönde ilerleyerek Q’yu büyütür.', false, 'Q küçükse ürün oluşturacak ileri yön Q’yu büyütür.'],
    ['Dengedeki sisteme ürün eklenirse ilk anda Q artabilir.', true, 'Ürünler Q’nun payındadır; artış Q’yu K’nın üstüne çıkarabilir.'],
    ['Q = K olduğunda ileri ve geri tepkimelerin hızları eşittir.', true, 'Q’nun K’ya eşitliği denge koşuludur.'],
    ['Katı miktarındaki değişim Q’ya doğrudan katılır.', false, 'Saf katıların derişimi Q ve K bağıntılarında bulunmaz.'],
  ], [
    ['A ⇌ 2B için K = 4, [A]=1 M, [B]=1 M; ilk yön?', ['İleri', 'Geri'], 0, 'Q = 1²/1 = 1; Q < 4 olduğundan ürün oluşur.'],
    ['Q = 100, K = 64 ise sistem hangi yöne kayar?', ['İleri', 'Geri'], 1, 'Q > K olduğundan ürünler tüketilerek Q küçülür.'],
    ['Dengedeki sistemden ürün çekilirse Q ile K ilişkisi ilk anda?', ['Q < K', 'Q > K'], 0, 'Ürün Q’nun payındadır; çekilince Q azalır.'],
    ['A ⇌ B; [A]=0,5 ve [B]=1,0 M ise Q?', ['0,5', '2'], 1, 'Q = [B]/[A] = 1,0/0,5 = 2.'],
    ['K = 2, Q = 2 olan kap için hangi yorum doğru?', ['Dengededir', 'İleri tepkime durmuştur'], 0, 'Q = K dengeyi gösterir; tepkime iki yönde devam eder.'],
    ['Başlangıçta yalnız tepken varsa Q kaçtır?', ['0', '1'], 0, 'Paydaki ürün derişimi sıfır olduğundan Q = 0 olur.'],
  ]),
  'kim11-denge-faktor': sorular([
    ['N₂ + 3H₂ ⇌ 2NH₃ dengesinde hacmi küçültmek NH₃ yönünü destekler.', true, 'Basınç artınca gaz molü az olan iki mollü ürün tarafı desteklenir.'],
    ['H₂ + I₂ ⇌ 2HI için hacmi küçültmek dengeyi HI yönüne kaydırır.', false, 'Her iki tarafta da iki mol gaz vardır; basınç değişimi kayma yaratmaz.'],
    ['Saf CaCO₃ katısını eklemek CaCO₃ ⇌ CaO + CO₂ dengesinin K’sını artırır.', false, 'Saf katı bağıntıda yoktur; K yalnız sıcaklığa bağlıdır.'],
    ['Ekzotermik dengede sıcaklık artışı K değerini azaltabilir.', true, 'Isıtma endotermik geri yönü destekleyip ileri yöndeki K’yı küçültür.'],
    ['Katalizör dengeye varış süresini kısaltabilir ama denge konumunu değiştirmez.', true, 'İleri ve geri yönler aynı oranda hızlanır.'],
    ['Sabit hacimde soy gaz eklemek reaktif gazların kısmi basınçlarını değiştirmez.', true, 'Hacim ve reaktif gaz mol sayıları aynı kaldığı için kısmi basınçları sabittir.'],
    ['Ürün çekilirse denge, çekilen ürünü yeniden oluşturan yöne kayar.', true, 'Ürün azalışı Q’yu düşürür; ileri tepkime yeni dengeye götürür.'],
  ], [
    ['NH₃ sentezinde üretimi artırmak için hangi basınç seçilir?', ['Yüksek basınç', 'Düşük basınç'], 0, 'Ürün tarafında daha az gaz molü vardır; yüksek basınç onu destekler.'],
    ['2NO₂ ⇌ N₂O₄, ΔH < 0; ısıtınca hangi tür artar?', ['N₂O₄', 'NO₂'], 1, 'Isıtma endotermik geri yöne kaydırır; kahverengi NO₂ artar.'],
    ['Ekzotermik ileri tepkimede sıcaklık düşürülürse K nasıl değişir?', ['Artar', 'Azalır'], 0, 'Soğutma ısı veren ürün yönünü destekler.'],
    ['Sabit basınçta soy gaz eklemek gaz molü çok olan tarafı nasıl etkiler?', ['Destekler', 'Bastırır'], 0, 'Hacim artar; sistem gaz molü çok olan tarafa kayar.'],
    ['Haber sürecinde NH₃’ü sürekli çekmenin etkisi?', ['Geri yönü destekler', 'İleri yönü destekler'], 1, 'Ürün eksilince sistem onu yeniden üretir.'],
    ['Hacim, derişim, sıcaklıktan hangisi K’yı değiştirebilir?', ['Sıcaklık', 'Derişim'], 0, 'Denge sabitinin değeri yalnız sıcaklığa bağlıdır.'],
    ['Dengede demir katalizör eklenirse NH₃ miktarı nasıl değişir?', ['Artar', 'Denge miktarı aynı kalır'], 1, 'Katalizör denge konumunu değil dengeye ulaşma süresini değiştirir.'],
  ]),
  'kim11-otoiyonizasyon': sorular([
    ['25 °C’de nötr çözeltide [H⁺] ve [OH⁻] eşittir.', true, 'Nötrlük iki iyonun derişimlerinin eşitliğidir.'],
    ['Asit eklenince OH⁻ derişimi sıfıra iner.', false, 'Kw sabit kalır; [H⁺] artınca [OH⁻] azalır ama sıfır olmaz.'],
    ['25 °C’de pH 3 ve pH 5 çözeltilerinin H⁺ derişimleri arasında 100 kat fark vardır.', true, 'Logaritmik ölçekte iki pH basamağı 10² = 100 kat demektir.'],
    ['60 °C’de saf suyun pH’ı 7’nin altında diye asidik olduğu söylenebilir.', false, 'Yüksek sıcaklıkta Kw değişir; saf suda yine [H⁺] = [OH⁻] ve su nötrdür.'],
    ['Suyun otoiyonizasyonu endotermik olduğundan ısıtılınca Kw büyüyebilir.', true, 'Sıcaklık artışı iyonlaşma yönünü destekler.'],
    ['Saf su iyi iletkendir çünkü su moleküllerinin çoğu iyonlaşır.', false, 'Saf suda iyonlaşan molekül oranı çok küçüktür; iletkenlik zayıftır.'],
  ], [
    ['25 °C’de [H⁺] = 10⁻⁴ M ise [OH⁻] kaç M?', ['10⁻¹⁰', '10⁻⁴'], 0, 'Kw = [H⁺][OH⁻] = 10⁻¹⁴; 10⁻¹⁴/10⁻⁴ = 10⁻¹⁰.'],
    ['25 °C’de pH = 9 ise pOH kaçtır?', ['9', '5'], 1, 'pH + pOH = 14; pOH = 5.'],
    ['[H⁺] = 10⁻³ M için pH kaçtır?', ['3', '11'], 0, 'pH = −log(10⁻³) = 3.'],
    ['pH 4’ten 3’e inerse [H⁺] nasıl değişir?', ['10 kat azalır', '10 kat artar'], 1, 'Bir pH basamağı azalış, H⁺ derişiminde 10 kat artıştır.'],
    ['Kw = 10⁻¹⁴ ve [H⁺] = 10⁻² M ise çözeltinin niteliği?', ['Asidik', 'Bazik'], 0, '[OH⁻] = 10⁻¹² M; H⁺ daha fazladır.'],
    ['Saf su ısıtılınca nötrlük hangi koşulla korunur?', ['pH’ın 7 kalmasıyla', '[H⁺] = [OH⁻] olmasıyla'], 1, 'Nötrlük eşit iyon derişimidir; sıcaklık değişince nötr pH değişebilir.'],
  ]),
  'kim11-asit-baz-teori': sorular([
    ['NH₃, H₂O’dan proton aldığında Brønsted-Lowry bazı gibi davranır.', true, 'Proton alıcısı bazdır; NH₃, NH₄⁺ iyonuna dönüşür.'],
    ['NH₃ formülünde OH⁻ bulunmaması onun sulu çözeltisini bazik yapmasını engeller.', false, 'NH₃ sudan proton alıp OH⁻ oluşturur.'],
    ['HF ile F⁻ bir konjuge asit-baz çiftidir.', true, 'İki tür arasında yalnız bir proton farkı vardır.'],
    ['H₂O her tepkimede yalnız baz olarak davranır.', false, 'H₂O karşısındaki türe göre proton alabilir veya verebilir.'],
    ['Gaz hâlindeki HCl + NH₃ tepkimesi Arrhenius tanımının kapsamı dışındadır.', true, 'Arrhenius tanımı sulu çözeltide H⁺ veya OH⁻ oluşumuna dayanır.'],
    ['Bir Brønsted asidi proton verdikten sonra konjuge bazına dönüşür.', true, 'Asitten H⁺ ayrılınca geriye onun konjuge bazı kalır.'],
  ], [
    ['NH₃ + H₂O ⇌ NH₄⁺ + OH⁻ tepkimesinde asit hangisidir?', ['NH₃', 'H₂O'], 1, 'H₂O proton verip OH⁻ hâline geçer.'],
    ['HF + H₂O ⇌ F⁻ + H₃O⁺ tepkimesinde HF’nin konjuge bazı?', ['F⁻', 'H₃O⁺'], 0, 'HF bir proton kaybedince F⁻ olur.'],
    ['HCO₃⁻ proton verirse hangi türe dönüşür?', ['H₂CO₃', 'CO₃²⁻'], 1, 'HCO₃⁻ bir H⁺ kaybedince CO₃²⁻ oluşur.'],
    ['HCO₃⁻ proton alırsa hangi tür oluşur?', ['H₂CO₃', 'CO₃²⁻'], 0, 'H⁺ eklenince H₂CO₃ oluşur; bu yüzden HCO₃⁻ amfoterdir.'],
    ['Suda çözünüp iki OH⁻ veren birim hangisidir?', ['NaOH', 'Ca(OH)₂'], 1, 'Ca(OH)₂ formülünde iki hidroksit grubu vardır.'],
    ['H₃O⁺ ile H₂O arasındaki ilişki?', ['Konjuge asit-baz çifti', 'İki protonluk fark'], 0, 'H₃O⁺, H₂O’dan yalnız bir proton fazladır.'],
    ['HCl + NH₃ gaz tepkimesini hangi tanım açıklar?', ['Yalnız Arrhenius', 'Brønsted-Lowry'], 1, 'Proton aktarımı vardır, ancak sulu çözelti şartı yoktur.'],
  ]),
  'kim11-asit-kuvvet': sorular([
    ['Kuvvetli asit tanımı yüksek başlangıç derişimi anlamına gelir.', false, 'Kuvvet iyonlaşmanın tamamlanma derecesidir; derişim ayrı bir niceliktir.'],
    ['Aynı derişimde HCl, CH₃COOH’dan daha çok iyon oluşturur.', true, 'HCl tamamen, asetik asit kısmen iyonlaşır.'],
    ['Ka büyüdükçe asidin iyonlaşma eğilimi artar.', true, 'Ka ürün iyonların tepken aside oranını ölçer.'],
    ['Kuvvetli asidin konjuge bazı da kuvvetli bazdır.', false, 'Ka × Kb = Kw; asit güçlendikçe konjuge baz zayıflar.'],
    ['Zayıf asit seyreltildikçe iyonlaşma yüzdesi artabilir.', true, 'Seyreltme dengeyi daha çok iyon oluşacak yöne kaydırır.'],
    ['H₃PO₄’ün proton verme basamakları eşit kuvvettedir.', false, 'Birinci basamağın Ka değeri ikinciden, ikinci de üçüncüden büyüktür.'],
  ], [
    ['0,1 M asitte [H⁺] = 0,001 M ise iyonlaşma yüzdesi?', ['%1', '%10'], 0, '0,001/0,1 × 100 = %1.'],
    ['Ka = 10⁻³ ve Ka = 10⁻⁵ asitlerinden hangisi kuvvetli?', ['Ka = 10⁻⁵', 'Ka = 10⁻³'], 1, 'Büyük Ka daha çok iyonlaşma demektir.'],
    ['Ka = 10⁻⁴ olan asidin konjuge bazının Kb değeri?', ['10⁻¹⁰', '10⁻⁴'], 0, 'Ka × Kb = 10⁻¹⁴; Kb = 10⁻¹⁰.'],
    ['Eşit derişimli HCl ve HF çözeltilerinde hangisi daha iletkendir?', ['HF', 'HCl'], 1, 'HCl kuvvetli asittir, daha çok serbest iyon taşır.'],
    ['HCl ile HI arasında proton verme eğilimi daha yüksek olan?', ['HI', 'HCl'], 0, 'H–I bağı daha zayıftır; hidrojen halojenürlerde kuvvet aşağı doğru artar.'],
    ['HClO₄ ile HClO asitlerinden hangisi daha kuvvetlidir?', ['HClO', 'HClO₄'], 1, 'Oksijen sayısı arttıkça konjuge baz daha iyi kararlılaşır.'],
    ['NH₃ için Kb artarsa bazın proton alma eğilimi nasıl değişir?', ['Artar', 'Azalır'], 0, 'Kb büyümesi bazın iyonlaşma ürünlerinin daha fazla oluştuğunu gösterir.'],
  ]),
  'kim11-ph': sorular([
    ['0,01 M HCl tamamen iyonlaştığından 25 °C’de pH değeri 2’dir.', true, '[H⁺] = 10⁻² M; pH = 2.'],
    ['0,005 M Ca(OH)₂ çözeltisinde [OH⁻] = 0,005 M olur.', false, 'Her Ca(OH)₂ iki OH⁻ verir; derişim 0,010 M’dir.'],
    ['Zayıf asit hesabında x/C %5’in altındaysa C − x ≈ C yaklaşımı uygundur.', true, 'Küçük iyonlaşma miktarı başlangıç derişimini önemli ölçüde değiştirmez.'],
    ['Aynı derişimde her asit aynı pH’ı verir.', false, 'Kuvvetli ve zayıf asitlerin iyonlaşma oranları farklıdır.'],
    ['Kuvvetli asit 10 kat seyreltilince pH yaklaşık bir birim artar.', true, '[H⁺] 10 kat azalır; negatif logaritma bir birim büyür.'],
    ['Zayıf bazın [OH⁻] değeri bulununca pH doğrudan −log[OH⁻] ile hesaplanır.', false, '−log[OH⁻] pOH verir; 25 °C’de pH = 14 − pOH.'],
  ], [
    ['0,005 M Ca(OH)₂ için 25 °C’de pH kaçtır?', ['12', '11'], 0, '[OH⁻] = 2 × 0,005 = 0,01 M; pOH 2, pH 12.'],
    ['Ka = 10⁻⁵ ve C = 0,1 M için yaklaşık [H⁺]?', ['10⁻³ M', '10⁻⁵ M'], 0, '√(Ka × C) = √10⁻⁶ = 10⁻³ M.'],
    ['0,01 M HCl 10 kat seyreltilirse pH kaç olur?', ['1', '3'], 1, 'Derişim 10⁻³ M’ye iner; pH 3 olur.'],
    ['[H⁺] = 2 × 10⁻³ M için pH yaklaşık kaçtır? log2 ≈ 0,3', ['3,3', '2,7'], 1, 'pH = 3 − log2 ≈ 2,7.'],
    ['0,1 M HA için pH 3 ise yaklaşık Ka kaçtır?', ['10⁻⁵', '10⁻³'], 0, 'x = 10⁻³ M; Ka ≈ x²/C = 10⁻⁶/0,1 = 10⁻⁵.'],
    ['0,1 M NH₃ için pOH 2,87 ise pH yaklaşık?', ['2,87', '11,13'], 1, '25 °C’de pH = 14 − 2,87 = 11,13.'],
  ]),
  'kim11-notrallesme': sorular([
    ['HCl ve NaOH eşdeğer miktarlarda tepkimeye girerse NaCl ve su oluşur.', true, 'H⁺ ile OH⁻ suyu; kalan iyonlar NaCl tuzunu oluşturur.'],
    ['H₂SO₄’ün bir molünü tam nötrlemek için bir mol KOH yeterlidir.', false, 'H₂SO₄ iki proton verir; iki mol KOH gerekir.'],
    ['Tam nötrleşmiş her asit-baz karışımının pH’ı 7’dir.', false, 'Zayıf bileşenden gelen tuz iyonu suyla tepkimeye girip pH’ı değiştirebilir.'],
    ['Kuvvetli asit ve kuvvetli bazın nötrleşmesi ısı verir.', true, 'H⁺ + OH⁻ → H₂O tepkimesi yaklaşık 56 kJ/mol ısı açığa çıkarır.'],
    ['NH₄Cl çözeltisi nötrleşmeyle oluşsa da asidik olabilir.', true, 'NH₄⁺ suyla tepkimeye girip H⁺ derişimini artırır.'],
    ['Derişik asit seyreltilirken su yavaşça aside eklenir.', false, 'Sıçramayı önlemek için asit suya yavaşça eklenir.'],
  ], [
    ['50 mL 0,2 M HCl’yi kaç mL 0,1 M NaOH nötrler?', ['100 mL', '50 mL'], 0, 'HCl 0,010 mol; aynı OH⁻ için 0,010/0,1 = 0,100 L gerekir.'],
    ['0,02 mol HCl ile 0,01 mol NaOH tepkimesinden ne artar?', ['0,01 mol NaOH', '0,01 mol HCl'], 1, 'Bir mol HCl bir mol NaOH ile nötrleşir; HCl 0,01 mol fazladır.'],
    ['NH₄Cl tuzu hangi çiftin tepkimesinden oluşabilir?', ['HCl + NH₃', 'CH₃COOH + NaOH'], 0, 'HCl’den Cl⁻, NH₃’ten NH₄⁺ gelir.'],
    ['CH₃COONa sulu çözeltisi genellikle nasıl davranır?', ['Asidik', 'Bazik'], 1, 'Zayıf asidin konjuge bazı CH₃COO⁻ suyla tepkimeye girer.'],
    ['0,02 mol kuvvetli asit nötrleşirse yaklaşık kaç kJ ısı çıkar?', ['1,12', '56'], 0, 'Bir mol H₂O için yaklaşık 56 kJ; 0,02 mol için 1,12 kJ.'],
    ['Mide asidini gidermek için hangi baz uygun olur?', ['Derişik NaOH', 'Mg(OH)₂ içeren antiasit'], 1, 'Mg(OH)₂ uygun dozda asidi nötrler; NaOH dokuyu yakar.'],
  ]),
  'kim11-titrasyon': sorular([
    ['Bürette derişimi bilinen standart çözelti bulunur.', true, 'Büret ölçülmüş hacimde standart çözelti eklemeye yarar.'],
    ['Dönüm noktası ile eşdeğerlik noktası kavramsal olarak aynı ölçüttür.', false, 'Dönüm noktası renk değişimi; eşdeğerlik noktası H⁺ ve OH⁻ mol eşitliğidir.'],
    ['H₂SO₄ titrasyonunda asidin bir molü iki mol OH⁻ tüketebilir.', true, 'H₂SO₄ iki protonlu asittir.'],
    ['Dönüm noktasını aşmak, hesaplanan harcanan baz hacmini büyütür.', true, 'Fazladan damlalar bürette daha büyük hacim okunmasına yol açar.'],
    ['Kuvvetli asit-kuvvetli baz eşdeğerliğinde 25 °C’de pH yaklaşık 7’dir.', true, 'Eşdeğerlikte artan H⁺ veya OH⁻ yoktur; tuz da nötrdür.'],
    ['Büretin ucundaki hava kabarcığı sonuç üzerinde etkisizdir.', false, 'İlk verilen çözelti kabarcığı doldurabilir; okunan hacim gerçek eklenenden farklı olur.'],
  ], [
    ['25 mL HCl için 20 mL 0,1 M NaOH harcandı; HCl derişimi?', ['0,08 M', '0,125 M'], 0, 'M × 25 = 0,1 × 20; M = 0,08 M.'],
    ['10 mL H₂SO₄, 20 mL 0,1 M NaOH ile nötrleşirse asit derişimi?', ['0,2 M', '0,1 M'], 1, '2 × M × 10 = 0,1 × 20; M = 0,1 M.'],
    ['Erlenmayere hangi sıvı konur?', ['Derişimi aranan örnek', 'Yalnız standart çözelti'], 0, 'Örneğin üzerine büretten standart çözelti damlatılır.'],
    ['İyi bir indikatör için hangi özellik aranır?', ['Renk dönüşü eşdeğerliğe yakın', 'Renk dönüşü başlangıçta'], 0, 'Dönüm ile eşdeğerlik noktaları yakın olursa ölçüm hatası azalır.'],
    ['Büret hacmi nasıl okunmalıdır?', ['Menisküsün üstünden, yukarıdan', 'Menisküsün altından, göz hizasında'], 1, 'Paralaks hatasını azaltmak için göz hizasında menisküsün altı okunur.'],
    ['Titrasyonda güvenilir sonucu hangisi destekler?', ['Bir denemeyi yeterli saymak', 'Tekrarların ortalamasını almak'], 1, 'Birden çok tekrar rastlantısal ölçüm farklarının etkisini azaltır.'],
  ]),
  'kim11-urun-secimi': sorular([
    ['Kireçli mermer yüzeyde asitli temizleyici kullanmak yüzeyi aşındırabilir.', true, 'Mermer CaCO₃ içerir; asit karbonatı çözebilir.'],
    ['Yağlı kir için bazik ürün seçiminin nedeni yağın bazla sabunlaşabilmesidir.', true, 'Baz yağın suda uzaklaştırılabilecek maddelere dönüşmesini sağlar.'],
    ['Çamaşır suyuyla HCl karıştırmak temizlik gücünü güvenle artırır.', false, 'Karışım zehirli klor gazı oluşturabilir.'],
    ['Cildin yaklaşık pH 5,5 olan yüzeyi hafif asidiktir.', true, 'Asidik tabaka mikrop çoğalmasına karşı koruyucu ortam sağlar.'],
    ['Mide asidi için kullanılan antiasidin kuvvetli NaOH olması uygundur.', false, 'NaOH aşındırıcıdır; uygun antiasitler zayıf bazlar ve karbonatlardır.'],
    ['Ürün seçerken etkinlik kadar yüzey güvenliği ve çevresel etkisi de değerlendirilmelidir.', true, 'Kir çözülse bile yüzey hasarı veya çevresel zarar uygun seçim değildir.'],
  ], [
    ['Çaydanlıktaki CaCO₃ kireci için hangi ürün uygundur?', ['Sitrik asitli çözelti', 'Kuvvetli bazlı fırın temizleyici'], 0, 'Asit CaCO₃ ile tepkimeye girerek birikintiyi çözer.'],
    ['Yağlı fırın yüzeyinde hangi ürün daha uygundur?', ['Sirke', 'Bazik yağ çözücü'], 1, 'Yağlı kir bazla sabunlaşarak uzaklaşır.'],
    ['Asitli toprak için hangi düzenleme uygundur?', ['CaCO₃ eklemek', 'Daha çok kükürt eklemek'], 0, 'Kireç toprağın fazla asitliğini nötrlemeye yardım eder.'],
    ['Alüminyum yüzeyde hangi ürün özellikle risklidir?', ['Hafif nötr temizleyici', 'Kuvvetli bazlı açıcı'], 1, 'Alüminyum kuvvetli bazla aşınır.'],
    ['Çamaşır suyu hangi ürünle karıştırılmamalıdır?', ['Tuz ruhu', 'Su'], 0, 'HCl ile karışması zehirli Cl₂ gazı çıkarabilir.'],
    ['Cilt pH’ına yakın ürünün olası üstünlüğü?', ['Asit tabakayı daha az bozması', 'Yağları daha güçlü sabunlaştırması'], 0, 'Cilde yakın pH koruyucu asit tabakayı daha az bozabilir.'],
  ]),
  'kim11-molar-cozunurluk': sorular([
    ['PbI₂ için molar çözünürlük s ise [I⁻] = 2s olur.', true, 'Her formül birimi iki iyodür iyonu verir.'],
    ['Doygun çözeltinin dibine daha çok katı eklemek aynı sıcaklıkta iyon derişimini artırır.', false, 'Dipte katı zaten varken denge derişimi ek katıyla değişmez.'],
    ['Az çözünen AgCl’nin suda hiç iyon oluşturmadığı söylenebilir.', false, 'Az çözünse de çözünen bölüm Ag⁺ ve Cl⁻ iyonlarına ayrılır.'],
    ['Doygun çözeltide çözünme ve çökelme hızları eşittir.', true, 'Dinamik denge nedeniyle net çözünmüş miktar sabit kalır.'],
    ['BaSO₄’ün zehirli Ba²⁺ iyonunu az vermesi düşük çözünürlüğüyle ilgilidir.', true, 'Çok az çözünen BaSO₄’ten çözeltiye az Ba²⁺ geçer.'],
  ], [
    ['PbI₂ için s = 1,5 × 10⁻³ M ise [I⁻]?', ['3 × 10⁻³ M', '1,5 × 10⁻³ M'], 0, 'PbI₂ biriminden iki I⁻ çıkar; [I⁻] = 2s.'],
    ['Ca₃(PO₄)₂ için [Ca²⁺] hangi ifadeye eşittir?', ['s', '3s'], 1, 'Formül birimi üç kalsiyum iyonu verir.'],
    ['233 g/mol BaSO₄ çözünürlüğü 2,33 × 10⁻³ g/L ise s?', ['10⁻⁵ M', '10⁻³ M'], 0, '2,33 × 10⁻³ / 233 = 10⁻⁵ mol/L.'],
    ['1 L doygun çözeltide 0,002 mol AB tuzu çözünmüşse s?', ['0,004 M', '0,002 M'], 1, 'Molar çözünürlük çözünmüş tuzun litre başına mol sayısıdır.'],
    ['Doygun AgCl çözeltisinde eşit olan iyon derişimleri?', ['Ag⁺ ve Cl⁻', 'Ag⁺ ve OH⁻'], 0, 'Bir AgCl bir Ag⁺ ve bir Cl⁻ oluşturur.'],
    ['Doygun çözeltide dibe katı eklenince hangi büyüklük sabit kalır?', ['Çözünmüş iyon derişimi', 'Toplam katı kütlesi'], 0, 'Katı kütlesi artar; denge iyon derişimi aynı sıcaklıkta sabit kalır.'],
  ]),
  'kim11-kcc': sorular([
    ['AgCl için Kçç ifadesine katı AgCl’nin derişimi yazılmaz.', true, 'Saf katı sabit etkinlikli olduğu için denge bağıntısından çıkarılır.'],
    ['PbI₂ için Kçç = [Pb²⁺][I⁻]² bağıntısı kullanılır.', true, 'İyodürün katsayısı 2, bağıntıda üs olur.'],
    ['Farklı iyon oranlı iki tuzun çözünürlüğü yalnız Kçç büyüklüğüyle kesin sıralanır.', false, 'Kçç’nin s ile ilişkisi stokiyometriye bağlıdır; önce s hesaplanmalıdır.'],
    ['Qçç > Kçç ise çökelme eğilimi vardır.', true, 'İyon çarpımı doygunluk sınırını aşmıştır.'],
    ['Ortak iyon eklenmesi aynı sıcaklıktaki Kçç değerini büyütür.', false, 'Ortak iyon çözünürlüğü değiştirir; Kçç yalnız sıcaklığa bağlıdır.'],
    ['Eşit hacimli iki çözelti karıştırıldığında iyonların başlangıç derişimi yarılanabilir.', true, 'Toplam hacim iki katına çıkarken her çözeltinin iyon molü aynı kalır.'],
  ], [
    ['AB tuzunda s = 2 × 10⁻⁵ M ise Kçç?', ['4 × 10⁻¹⁰', '2 × 10⁻⁵'], 0, 'AB için Kçç = s² = 4 × 10⁻¹⁰.'],
    ['AB₂ tuzunda s = 10⁻³ M ise Kçç?', ['10⁻⁶', '4 × 10⁻⁹'], 1, 'Kçç = s(2s)² = 4s³ = 4 × 10⁻⁹.'],
    ['Qçç < Kçç olduğunda çözelti için hangi durum geçerli?', ['Doymamış, çökelme yok', 'Aşırı doymuş, çökelme var'], 0, 'İyon çarpımı çözünürlük sınırının altındadır.'],
    ['10⁻³ M iki çözelti eşit hacimde karışırsa her iyonun ilk derişimi?', ['10⁻³ M', '5 × 10⁻⁴ M'], 1, 'Hacim iki katına çıktığı için her başlangıç derişimi yarılanır.'],
    ['Ag₂CrO₄ için Kçç ifadesi hangisidir?', ['[Ag⁺]²[CrO₄²⁻]', '[Ag⁺][CrO₄²⁻]²'], 0, 'Bir formül birimi iki Ag⁺ ve bir CrO₄²⁻ verir.'],
    ['Kçç = 4 × 10⁻⁹ olan AB₂ tuzunun s değeri?', ['4 × 10⁻³ M', '10⁻³ M'], 1, '4s³ = 4 × 10⁻⁹; s = 10⁻³ M.'],
  ]),
  'kim11-cozunurluk-faktor': sorular([
    ['AgCl dengesine Cl⁻ eklemek AgCl’nin molar çözünürlüğünü azaltır.', true, 'Ortak iyon eklenmesi dengeyi katı yönüne kaydırır.'],
    ['Ortak iyon aynı sıcaklıkta Kçç değerini değiştirir.', false, 'İyon derişimleri yeniden ayarlanır; Kçç sabit kalır.'],
    ['Endotermik çözünen tuzun çözünürlüğü ısıtılınca genellikle artar.', true, 'Isı çözünme yönünün tepkeni gibi davranır.'],
    ['Asit, CaCO₃’ün çözünmesini kolaylaştırabilir.', true, 'H⁺ karbonat iyonunu tüketerek çözünme dengesini ürün yönüne çeker.'],
    ['Aynı sıcaklıkta çözeltiye daha çok katı eklemek Kçç’yi büyütür.', false, 'Denge sabiti ve doygun derişimler ek katıdan etkilenmez.'],
    ['BaSO₄ ortamına SO₄²⁻ eklemek çözünmüş Ba²⁺ miktarını azaltabilir.', true, 'Ortak sülfat iyonu BaSO₄ çözünme dengesini sola iter.'],
  ], [
    ['Kçç(AgCl) = 1,8 × 10⁻¹⁰; 0,1 M Cl⁻ ortamında s yaklaşık?', ['1,8 × 10⁻⁹ M', '1,8 × 10⁻⁵ M'], 0, 's × 0,1 ≈ 1,8 × 10⁻¹⁰; s = 1,8 × 10⁻⁹ M.'],
    ['Ca(OH)₂ ekzotermik çözünüyorsa ısıtıldığında çözünürlük?', ['Artar', 'Azalır'], 1, 'Isı ürün tarafındadır; ısıtma katı yönünü destekler.'],
    ['Ortak iyon eklenince hangi çift doğru?', ['s azalır, Kçç aynı', 's ve Kçç azalır'], 0, 'Ortak iyon çözünürlüğü etkiler, denge sabitini değil.'],
    ['BaSO₄ çözeltisine hangi tuz ortak iyon sağlar?', ['NaCl', 'Na₂SO₄'], 1, 'Na₂SO₄ sülfat iyonu verir.'],
    ['Asit yağmurunun mermeri aşındırması hangi dengeyle ilişkilidir?', ['CaCO₃’ün daha çok çözünmesi', 'CaCO₃’ün tamamen çökelmesi'], 0, 'H⁺ karbonatı tüketince CaCO₃ çözünmesi artar.'],
    ['Ca²⁺ içeren sert suya CO₃²⁻ eklenirse beklenen sonuç?', ['CaCO₃ çökelmesi', 'Ca²⁺ derişiminin artması'], 0, 'İyon çarpımı çözünürlük sınırını aşarsa CaCO₃ çöker.'],
  ]),
  'kim11-yesil-hidrojen': sorular([
    ['Karanlık fermantasyonda ışık gerekmez ama oksijensiz ortam gerekir.', true, 'Bazı bakteriler şekeri oksijensiz ve ışıksız koşulda parçalar.'],
    ['Asetik asit yolunda 1 mol glikozdan en çok 4 mol H₂ oluşabilir.', true, 'Karttaki dengelenmiş denklemde H₂ katsayısı 4’tür.'],
    ['Gri hidrojen üretiminde fosil kaynaktan çıkan CO₂ mutlaka yakalanır.', false, 'CO₂ yakalanıp depolanırsa üretim mavi; salınırsa gri olarak anılır.'],
    ['Reaktörde H₂ birikmesi üretimi yavaşlatabilir.', true, 'Ürünün ortamdan çekilmesi fermantasyon verimini destekler.'],
    ['Metan üreten bakteriler hidrojen verimini artırır.', false, 'Metancılar oluşan H₂’yi tüketir ve ölçülen hidrojen verimini düşürür.'],
    ['Atık kullanılması süreci döngüsel ekonomiyle ilişkilendirir.', true, 'Gıda artıkları yakıta dönüşürken atık miktarı da azalır.'],
  ], [
    ['2 mol glikoz asetik asit yolundan geçerse en çok kaç mol H₂?', ['8', '4'], 0, 'Bir mol glikoz en çok dört mol H₂ verir; iki mol sekiz mol verir.'],
    ['pH etkisini denemek için hangi değişken sabit tutulmalı?', ['Toplanan H₂ hacmi', 'Atık türü ve miktarı'], 1, 'pH bağımsız değişkendir; atığın değişmesi sonucu karıştırır.'],
    ['Hidrojen üretimini hangi koşul daha çok destekler?', ['pH 5,5 ve 36 °C', 'pH 9 ve 10 °C'], 0, 'Kartta verilen uygun aralık pH 5–6 ve 35–37 °C’dir.'],
    ['Metan üreten bakterileri baskılamak için hangi uygulama kullanılabilir?', ['H₂’yi reaktörde biriktirmek', 'Başlangıç karışımını kısa kaynatmak'], 1, 'Kısa ısıtma metancıları azaltırken sporlu H₂ üreticileri dayanabilir.'],
    ['Gri ile mavi hidrojen arasındaki temel fark?', ['CO₂’nin yakalanması', 'Fosil kaynak kullanımı'], 0, 'İki yöntem de fosil kaynak kullanır; mavide CO₂ yakalanıp depolanır.'],
    ['Yakıt hücresinde H₂ enerjisi hangi yolla kullanılır?', ['Yalnız alevle yakılarak', 'Doğrudan elektrik üreterek'], 1, 'Yakıt hücresi H₂ ve O₂ tepkimesini elektrik üretimine bağlar.'],
    ['Fermantasyon gazı yakıt hücresine girmeden önce neden ayrıştırılır?', ['H₂’yi CO₂’den ayırmak', 'Glikozun mol sayısını artırmak'], 0, 'Karanlık fermantasyon H₂ ile birlikte CO₂ de üretir.'],
  ]),
  'kim11-nano': sorular([
    ['Parçacık küçüldükçe yüzey/hacim oranı artabilir.', true, 'Aynı kütlede daha çok dış yüzey tepkimeye açık hâle gelir.'],
    ['Nano ölçekte altının rengi büyük altın parçalarıyla her zaman aynıdır.', false, 'Boyuta bağlı optik özellikler nanoparçacık rengini değiştirebilir.'],
    ['Gümüş nanoparçacıklar atık suda yararlı bakterileri de etkileyebilir.', true, 'Mikrop öldürücü özellik hedef dışındaki arıtma bakterilerini de etkileyebilir.'],
    ['Üründe nano sözcüğü bulunması güvenliğini tek başına kanıtlar.', false, 'Parçacık boyutu, maruziyet yolu ve güvenlik verisi ayrıca incelenmelidir.'],
    ['Aynı nano içerik sprey biçiminde solunma riskini artırabilir.', true, 'Sprey parçacıkları havaya dağıtır ve solunum yoluna taşıyabilir.'],
    ['Nanoteknoloji yalnızca tıbbi ürünlerde kullanılır.', false, 'Güneş kremi, su filtresi, kumaş ve enerji ürünlerinde de kullanılır.'],
  ], [
    ['1 nm kaç metredir?', ['10⁻⁹ m', '10⁻⁶ m'], 0, 'Nano öneki metrenin milyarda birini gösterir.'],
    ['Eşit miktar maddeyi küçük parçalara bölmek hangi özelliği artırır?', ['Toplam kütleyi', 'Toplam yüzeyi'], 1, 'Yeni açılan yüzeyler toplam dış yüzey alanını büyütür.'],
    ['Güneş kremindeki nano ZnO’nun yararı?', ['Daha az beyaz iz', 'UV ışınını artırması'], 0, 'Nano boyutlu ZnO görünür beyaz izi azaltırken UV koruması sağlar.'],
    ['Solunma riski açısından hangisi daha ihtiyatlı seçimdir?', ['Sprey', 'Krem'], 1, 'Kremde havaya saçılan parçacık daha azdır.'],
    ['Nano gümüşlü kumaşın atık suyunda hangi risk araştırılır?', ['Arıtma bakterilerine etki', 'Suda daha hızlı çözünmesi'], 0, 'Gümüş nanoparçacıklar yararlı mikroorganizmaları da baskılayabilir.'],
    ['Hedefli ilaç taşıyıcısının amaçlanan üstünlüğü?', ['İlacı her yere eşit dağıtmak', 'İlacı hasta hücreye yöneltmek'], 1, 'Hedefleme sağlıklı dokudaki gereksiz maruziyeti azaltmayı amaçlar.'],
  ]),
  'kim11-mikroplastik': sorular([
    ['Sentetik kumaşın yıkanırken bıraktığı lifler ikincil mikroplastik kaynağıdır.', true, 'Lifler daha büyük plastik malzemenin aşınmasıyla ortaya çıkar.'],
    ['Plastik parçalandıkça mutlaka kimyasal olarak yok olur.', false, 'Büyük parça çok sayıda küçük parçaya dönüşebilir ve ortamda kalabilir.'],
    ['Mikroplastikler kirleticileri yüzeylerine tutup taşıyabilir.', true, 'Tarım ilaçları ve ağır metaller parçacık yüzeyine bağlanabilir.'],
    ['Nanoplastiklerin uzun süreli insan sağlığı etkileri kesin olarak tamamen açıklanmıştır.', false, 'Vücutta bulunmaları gösterilse de uzun vadeli etkileri araştırılmaktadır.'],
    ['Endüstriyel kompost gerektiren PLA’nın denizde hızla yok olacağı varsayılamaz.', true, 'Gerekli sıcaklık ve koşullar denizde bulunmayabilir.'],
    ['Parçacıkları saymak tek başına hangi plastikten yapıldıklarını gösterir.', false, 'Polimer türünü belirlemek için spektroskopi gibi kimyasal analiz gerekir.'],
  ], [
    ['Plastik üretim peleti hangi kaynağa örnektir?', ['Birincil mikroplastik', 'İkincil mikroplastik'], 0, 'Pelet baştan küçük plastik tanecik olarak üretilir.'],
    ['Lastik aşınması sonucu çıkan parçacık hangi kaynaktır?', ['Birincil', 'İkincil'], 1, 'Büyük lastiğin kullanımda aşınmasıyla küçük parçalar oluşur.'],
    ['Bir parçacığın polimer türünü belirlemek için hangi yöntem gerekir?', ['Spektroskopi', 'Yalnız mikroskopta boyut ölçümü'], 0, 'Boyut ölçümü türü göstermez; spektrum polimerin kimyasal yapısını ayırt eder.'],
    ['Mikroplastik tüketen deniz canlısında hangi etki görülebilir?', ['Besin alımının azalması', 'Besin değerinin artması'], 0, 'Parçacık sahte tokluk hissi ve sindirim yolu sorunları yaratabilir.'],
    ['Evsel mikroplastik yükünü azaltmak için hangi adım etkili?', ['Tek kullanımlık plastiği azaltmak', 'Plastiği daha küçük kırmak'], 0, 'Kaynağında kullanım azaltımı yeni parçacık oluşumunu sınırlar.'],
    ['PLA için biyobozunur etiketi hangi koşulu garanti etmez?', ['Endüstriyel kompostta bozunmayı', 'Denizde hızla bozunmayı'], 1, 'Birçok PLA türü endüstriyel kompost koşullarına ihtiyaç duyar.'],
    ['İçme suyunda parçacık analizinin ilk adımı hangisi olabilir?', ['Örneği süzerek parçacıkları toplamak', 'Yalnız suyun pH’ını ölçmek'], 0, 'Filtreleme parçacıkları toplar; pH parçacık sayısını vermez.'],
  ]),
}
