import { sikli, soru, type SoruKarti } from '../tip'

type Iddia = [ifade: string, dogru: boolean, gerekce: string]
type Secim = [metin: string, dogru: string, yanlis: string, gerekce: string]

let secimSirasi = 0

function sorular(iddialar: Iddia[], secimler: Secim[]): Omit<SoruKarti, 'id'>[] {
  const dogruYanlis = iddialar.map(([ifade, dogru, gerekce]) => soru(ifade, dogru, gerekce))
  const ikiSikli = secimler.map(([metin, dogru, yanlis, gerekce]) => {
    const yanit = (secimSirasi++ % 2) as 0 | 1
    return sikli(metin, yanit === 0 ? [dogru, yanlis] : [yanlis, dogru], yanit, gerekce)
  })
  return ikiSikli.flatMap((secim, dizin) => [dogruYanlis[dizin], secim])
    .concat(dogruYanlis.slice(ikiSikli.length))
}

/** Her yoklama karttaki kavramı farklı bir veri, şekil ya da işlem üzerinde kullandırır. */
export const matematik11Sorulari: Record<string, Omit<SoruKarti, 'id'>[]> = {
  'mat11-iki-nicel': sorular([
    ['İki nicel değişkenli araştırmada her katılımcı için eşleşen iki sayı kaydedilir.', true, 'Serpme diyagramındaki her nokta aynı bireyin iki ölçümüdür.'],
    ['Serpme diyagramında noktaların sağa doğru yükselmesi negatif ilişkiyi gösterir.', false, 'Sağa doğru yükselen bulut pozitif ilişkiyi gösterir.'],
    ['r = −0,8 ilişkisi, r = 0,4 ilişkisinden doğrusal açıdan daha güçlüdür.', true, 'Güç için işarete değil |r| değerine bakılır.'],
    ['r sıfıra yakınsa değişkenler arasında hiçbir tür ilişki olamaz.', false, 'r doğrusal ilişkiyi ölçer; eğrisel ilişki bulunabilir.'],
    ['Noktalar doğru çevresinde ne kadar sıkıysa doğrusal ilişki o kadar güçlüdür.', true, 'Bulutun dağılması gücü belirler; eğimin dikliği değil.'],
    ['Bütün x değerlerine 5 eklenmesi korelasyon katsayısını artırır.', false, 'Sabit eklemek sapmaları değiştirmez; r aynı kalır.'],
    ['Korelasyon tek başına bir değişkenin diğerine neden olduğunu kanıtlamaz.', true, 'Üçüncü değişken ya da ters yönlü etki olabilir.'],
    ['Tek bir uç gözlem, küçük örneklemde r değerini belirgin biçimde değiştirebilir.', true, 'Uç noktanın sapması hesapta büyük ağırlık taşır.'],
  ], [
    ['Çalışma süresi artarken net de artıyorsa ilişkinin yönü?', 'Pozitif', 'Negatif', 'İki değişken birlikte artıyor.'],
    ['r = −0,9 ve r = 0,6 için hangisi daha güçlü?', 'r = −0,9', 'r = 0,6', 'Doğrusal ilişkinin gücü mutlak değerle karşılaştırılır.'],
    ['Boy metreye çevrilirse boy-kilo korelasyonu ne olur?', 'Değişmez', '100 katına çıkar', 'Ölçü birimi değişimi r değerini değiştirmez.'],
    ['Veriler bir U eğrisi oluşturuyorsa r ≈ 0 neyi dışlamaz?', 'Eğrisel ilişkiyi', 'Her türlü ilişkiyi', 'Korelasyon katsayısı doğrusal bağı ölçer.'],
    ['Bir nokta buluttan çok uzaktaysa ilk ne incelenir?', 'Ölçüm ve bağlamı', 'Doğrudan silinmesi', 'Uç değer hata da olabilir, gerçek gözlem de.'],
    ['İki değişkenin ilişkisinde nedensellik için ne gerekir?', 'Ek kanıt ve tasarım', 'Yalnız yüksek r', 'Yüksek korelasyon neden-sonuç kanıtı değildir.'],
    ['Serpme diyagramında tek nokta neyi temsil eder?', 'Bir bireyin iki ölçümünü', 'İki bireyin ortalamasını', 'Eşleşen (x, y) çifti tek gözlemdir.'],
    ['r = 1 için noktalar hangi biçimde dizilir?', 'Artan bir doğru üzerinde', 'Geniş dağılmış bulutta', 'Tam pozitif doğrusal ilişki vardır.'],
  ]),
  'mat11-hazir-veri': sorular([
    ['Bir araştırmanın örneklemi yalnız gönüllülerden oluşursa seçim yanlılığı olabilir.', true, 'Gönüllüler hedef kitlenin tamamını temsil etmeyebilir.'],
    ['Örneklem büyüdüğünde her türlü örneklem yanlılığı kendiliğinden kaybolur.', false, 'Büyük ama yanlı bir örneklem yine yanıltır.'],
    ['Sıfırdan başlamayan dikey eksen küçük farkı görsel olarak büyütebilir.', true, 'Eksen kesimi sütun yüksekliklerinin algısını değiştirir.'],
    ['Birlikte değişen iki değer arasında mutlaka doğrudan neden ilişkisi vardır.', false, 'Ortak neden veya ters nedensellik araştırılmalıdır.'],
    ['Yüzde artışın anlamı başlangıçtaki miktara bağlıdır.', true, 'Yüzde, dayandığı taban sayı bilinmeden yorumlanamaz.'],
    ['Alt gruplardaki eğilim ile toplam verideki eğilim her zaman aynı yöndedir.', false, 'Grup büyüklükleri değişince toplam eğilim tersine dönebilir.'],
    ['Grafiğin yılı ve veri kaynağı görülmeden güncel bir sonuç çıkarılamaz.', true, 'Eski veya seçilmiş veri bugün için temsil edici olmayabilir.'],
  ], [
    ['1000 kişilik yalnız bir okul anketinin temel sorunu?', 'Temsil gücü', 'Sayı yetersizliği', 'Büyük örneklem hedef kitleyi temsil etmeyebilir.'],
    ['İki yıldaki %20 artışı kıyaslamak için ne gerekli?', 'Başlangıç miktarları', 'Yalnız renk ölçeği', 'Aynı yüzde farklı tabanlarda farklı mutlak artıştır.'],
    ['Y ekseni 95’ten başlıyorsa sütun farkı nasıl görünür?', 'Abartılmış görünebilir', 'Mutlaka küçülür', 'Kesilmiş eksen göreli yüksekliği büyütür.'],
    ['İki değişken birlikte artıyorsa ilk temkinli yorum?', 'İlişki olabilir', 'Biri ötekine kesin neden', 'Birlikte hareket nedensellik kanıtı değildir.'],
    ['Bir araştırmanın sonucunu başka ülkeye taşımadan önce?', 'Örneklem ve bağlam incelenir', 'Yalnız grafik türü değiştirilir', 'Farklı toplulukta sonuç değişebilir.'],
    ['Toplam oran alt grup oranlarıyla çelişiyorsa ne incelenir?', 'Grup ağırlıkları', 'Yalnız yuvarlama', 'Grupların büyüklüğü toplam oranı etkiler.'],
    ['Grafikte hangi bilgi eksikse sayı yanlış okunabilir?', 'Ölçü birimi ve ölçek', 'Başlığın yazı tipi', 'Eksenin ne ölçtüğü açık olmalıdır.'],
  ]),
  'mat11-dortgen': sorular([
    ['Her dörtgenin iç açıları toplamı 360°dir.', true, 'Dörtgen iki üçgene ayrılır; 2 × 180° = 360°.'],
    ['Yamuğun bir çift karşı kenarı paraleldir.', true, 'Yamuk tanımında paralel bir kenar çifti bulunur.'],
    ['Paralelkenarın köşegenleri birbirini dik kesmek zorundadır.', false, 'Köşegenler birbirini ortalar; diklik özel durumdur.'],
    ['Dikdörtgenin köşegen uzunlukları birbirine eşittir.', true, 'Dik açılar köşegen eşitliğini sağlar.'],
    ['Her eşkenar dörtgen aynı zamanda karedir.', false, 'Eşkenar dörtgende açılar 90° olmak zorunda değildir.'],
    ['Kare hem dikdörtgen hem eşkenar dörtgendir.', true, 'Dört eşit kenar ve dört dik açı birlikte vardır.'],
    ['Deltoidin tüm karşılıklı kenarları paraleldir.', false, 'Deltoidde komşu kenar çiftleri eşittir; karşı kenarlar genel olarak paralel değildir.'],
    ['Paralelkenarın alanı taban ile o tabana ait yüksekliğin çarpımıdır.', true, 'Eğik yan kenar yükseklik yerine kullanılamaz.'],
  ], [
    ['Bir dörtgenin üç açısı 80°, 90°, 100° ise dördüncü açı?', '90°', '100°', '360° − 270° = 90°.'],
    ['Paralelkenarın alanında taban 8, yükseklik 5 ise alan?', '40', '64', 'Alan taban × yükseklik ile bulunur.'],
    ['Köşegenleri eşit ve birbirini ortalayan dörtgen kesin hangi sınıfa girer?', 'Dikdörtgen', 'Eşkenar dörtgen', 'Bu koşullar dikdörtgeni verir; dört kenarın eşitliği bilinmez.'],
    ['Karşı kenarları paralel olmayan, komşu kenar çiftleri eşit biçim?', 'Deltoid', 'Yamuk', 'Bu koşullar deltoidi tarif eder; yamukta paralel kenar çifti vardır.'],
    ['Paralelkenarda köşegenlerin kesişim noktası ne yapar?', 'İkisini ortalar', 'İkisini dik keser', 'Ortalama her paralelkenarda, diklik özel türde görülür.'],
    ['Tabanları 6 ve 10, yüksekliği 4 olan yamuğun alanı?', '32', '64', 'Alan (6 + 10) × 4 / 2 = 32.'],
    ['Kareyi eşkenar dörtgenden ayıran ek koşul?', 'Bir açının dik olması', 'Köşegenin bulunması', 'Eşit kenarların yanında dik açı kareyi belirler.'],
  ]),
  'mat11-ozel-dortgen': sorular([
    ['Her kare paralelkenardır.', true, 'Karede iki çift karşı kenar paraleldir.'],
    ['Her dikdörtgen karedir.', false, 'Dikdörtgende bütün kenarlar eşit olmak zorunda değildir.'],
    ['Bir paralelkenarın tek açısı dikse bütün açıları diktir.', true, 'Komşu açılar bütünler, karşı açılar eşittir.'],
    ['Bir paralelkenarın köşegenleri eşitse dikdörtgendir.', true, 'Eşit köşegen, paralelkenarda dikdörtgen koşuludur.'],
    ['Köşegenleri dik kesişen her dörtgen karedir.', false, 'Deltoid veya eşkenar dörtgen de bu özelliği taşıyabilir.'],
    ['Bir paralelkenarda komşu kenarlar eşitse eşkenar dörtgendir.', true, 'Karşı kenarlar da eşit olduğundan dört kenar eşitlenir.'],
    ['Bir şeklin kare olduğunu kanıtlamak için yalnız dört kenarın eşitliği yeterlidir.', false, 'Dik açı da gösterilmelidir.'],
  ], [
    ['Paralelkenara hangi ek koşul dikdörtgen kazandırır?', 'Bir dik açı', 'Bir köşegen', 'Bir dik açı tüm açılara taşınır.'],
    ['Dikdörtgenin kare olması için hangi ek koşul?', 'Komşu kenarlar eşit', 'Köşegenler eşit', 'Dikdörtgende köşegen eşitliği zaten vardır.'],
    ['Eşkenar dörtgenin kare olması için ne gerekir?', 'Bir dik açı', 'Köşegenlerin dikliği', 'Eşkenar dörtgende köşegenler zaten diktir.'],
    ['Sadece köşegenleri birbirini ortalayan dörtgen?', 'Paralelkenar', 'Mutlaka dikdörtgen', 'Ortalama koşulu paralelkenarı verir; dik açı garanti değildir.'],
    ['Dik ve birbirini ortalayan köşegenler hangi aileyi verir?', 'Eşkenar dörtgen', 'Her zaman dikdörtgen', 'Diklik ile ortalama eşkenar dörtgen özelliğidir.'],
    ['Köşegenleri birbirini ortalayıp eşit olan dörtgen için kesin sonuç?', 'Dikdörtgendir', 'Kare olmak zorundadır', 'Bu koşullar dikdörtgeni verir; kenar eşitliği bilinmez.'],
    ['Karşı kenarların paralelliği kime aktarılır?', 'Kareye de', 'Yalnız yamuğa', 'Paralelkenarın alt türü bu özelliği taşır.'],
  ]),
  'mat11-cokgen-sinif': sorular([
    ['Çokgen kapalı ve doğru parçalarından oluşan bir şekildir.', true, 'Eğri kenar veya açık zincir çokgen değildir.'],
    ['Her üçgen dışbükeydir.', true, 'Üçgende içeri doğru giren köşe oluşmaz.'],
    ['İçbükey çokgende en az bir iç açı 180°den büyüktür.', true, 'İçe giren köşenin iç açısı doğru açıyı aşar.'],
    ['Tüm kenarları eşit bir çokgen zorunlu olarak düzgün çokgendir.', false, 'Düzgünlük için açılar da eşit olmalıdır.'],
    ['Dışbükey çokgende iki iç noktanın birleştirilmesi şeklin dışına taşabilir.', false, 'Dışbükeylikte her iki iç nokta arasındaki parça içeride kalır.'],
    ['Düzgün çokgende hem kenarlar hem iç açılar eşittir.', true, 'Tek başına kenar eşitliği yeterli değildir.'],
    ['Kenar sayısı bir şekli içbükey veya dışbükey olarak tek başına belirler.', false, 'Aynı kenar sayısıyla iki tür şekil çizilebilir.'],
  ], [
    ['Açık bırakılmış doğru parçası zinciri nedir?', 'Çokgen değildir', 'İçbükey çokgendir', 'Çokgenin sınırı kapanmalıdır.'],
    ['Bir köşesi içeri giren beşgen nasıl sınıflanır?', 'İçbükey', 'Dışbükey', 'En az bir iç açı 180°yi aşar.'],
    ['Kenar uzantılarından biri şeklin içinden geçerse?', 'İçbükey', 'Düzgün', 'Dışbükey çokgende kenar uzantısı iç bölgeyi kesmez.'],
    ['Eşit kenarlı ama farklı açılı beşgen için hangisi?', 'Düzgün değildir', 'Düzgündür', 'Düzgünlük iki eşitliği birlikte ister.'],
    ['Altı kenarlı ve bir iç açısı 200° olan şekil?', 'İçbükey altıgen', 'Dışbükey altıgen', '180°yi aşan iç açı içbükeyliği gösterir.'],
    ['Dışbükeylik için hangi ölçüt güçlüdür?', 'İç noktaları birleştirince içeride kalma', 'Yalnız kenarların eşitliği', 'Bu, dışbükey bölgenin tanımıdır.'],
  ]),
  'mat11-disbukey': sorular([
    ['n kenarlı dışbükey çokgen n − 2 üçgene ayrılabilir.', true, 'Bir köşeden çizilen köşegenler üçgenlere ayırır.'],
    ['Dış açılar toplamı kenar sayısı arttıkça büyür.', false, 'Her dışbükey çokgende dış açılar toplamı 360°dir.'],
    ['Düzgün altıgenin bir iç açısı 120°dir.', true, '(6 − 2) × 180° / 6 = 120°.'],
    ['Sekizgenin köşegen sayısı sekizdir.', false, 'n(n − 3)/2 ile 8 × 5 / 2 = 20.'],
    ['Düzgün çokgende bir dış açı 360°/n değerindedir.', true, 'Eşit dış açılar toplamı 360°yi paylaşır.'],
    ['Çokgenin bir köşesinden bütün köşelerine köşegen çizilebilir.', false, 'Kendisine ve iki komşu köşeye köşegen çizilemez.'],
    ['Düzgün altıgen altı eşkenar üçgene ayrılabilir.', true, 'Merkez açısı 60°dir ve yarıçapı kenara eşittir.'],
    ['Düzgün çokgenin alanı çevre × apotem / 2 ile bulunabilir.', true, 'Merkezden kurulan üçgenlerin alanları toplanır.'],
  ], [
    ['Yedigenin iç açıları toplamı?', '900°', '720°', '(7 − 2) × 180° = 900°.'],
    ['Bir düzgün çokgenin dış açısı 45° ise kenar sayısı?', '8', '6', 'n = 360° / 45° = 8.'],
    ['Altıgenin köşegen sayısı?', '9', '6', '6 × (6 − 3) / 2 = 9.'],
    ['On kenarlı çokgen bir köşeden kaç üçgene ayrılır?', '8', '10', 'Üçgen sayısı n − 2 olur.'],
    ['Düzgün beşgenin bir iç açısı?', '108°', '72°', '72° dış açıdır; iç açı 180° − 72°dir.'],
    ['Düzgün altıgenin merkez açısı?', '60°', '120°', 'Tam açı altı eş parçaya bölünür.'],
    ['Çevresi 24, apotemi 3 olan düzgün çokgenin alanı?', '36', '72', 'Alan 24 × 3 / 2 = 36.'],
  ]),
  'mat11-cokgen-problem': sorular([
    ['Çokgenin iç açıları toplamı bir açıya değil kenar sayısına bağlıdır.', true, '(n − 2) × 180° kullanılır.'],
    ['Düzgün çokgende bir dış açı, 360°nin kenar sayısına bölümüdür.', true, 'Tüm dış açılar eşit ve toplamları 360°dir.'],
    ['Yamuğun orta tabanı iki tabanın farkının yarısıdır.', false, 'Orta taban taban uzunlukları toplamının yarısıdır.'],
    ['Dikdörtgenin köşegeni Pisagor ile bulunabilir.', true, 'Köşegen, iki kenarla dik üçgen kurar.'],
    ['Paralelkenarda alan hesabında eğik kenar doğrudan yükseklik yerine geçer.', false, 'Tabana dik uzaklık kullanılmalıdır.'],
    ['Düzgün altıgenin çevresi kenarının altı katıdır.', true, 'Altı kenar aynı uzunluktadır.'],
    ['Köşegen sayısı hesabında her köşegen iki kez sayıldığı için ikiye bölünür.', true, 'İki uçtan aynı köşegen sayılır.'],
  ], [
    ['İç açı toplamı 1260° olan çokgen kaç kenarlı?', '9', '7', '(n − 2) × 180° = 1260° → n = 9.'],
    ['Bir köşeden 5 köşegen çizilebilen çokgen kaç kenarlı?', '8', '7', 'Bir köşeden n − 3 köşegen çıkar.'],
    ['Tabanları 8 ve 14 olan yamuğun orta tabanı?', '11', '6', '(8 + 14) / 2 = 11.'],
    ['Kenarları 6 ve 8 olan dikdörtgenin köşegeni?', '10', '14', '6² + 8² = 10².'],
    ['Köşegen sayısı 14 olan çokgenin kenar sayısı?', '7', '8', '7 × 4 / 2 = 14.'],
    ['Dış açısı 30° olan düzgün çokgenin kenar sayısı?', '12', '10', '360° / 30° = 12.'],
  ]),
  'mat11-trig-fonk': sorular([
    ['180° açının radyan ölçüsü πdir.', true, 'Derece-radyan dönüşümünde 180° = π radyan.'],
    ['Birim çemberde sinüs yatay koordinata karşılık gelir.', false, 'Yatay koordinat kosinüs, düşey koordinat sinüstür.'],
    ['sin²x + cos²x = 1 bütün gerçek x değerleri için geçerlidir.', true, 'Birim çemberin x² + y² = 1 bağıntısıdır.'],
    ['Tanjantın periyodu 2πdir ve π daha kısa bir periyot değildir.', false, 'Tanjantın temel periyodu πdir.'],
    ['İkinci bölgede sinüs pozitif, kosinüs negatiftir.', true, 'Birim çemberde y > 0, x < 0.'],
    ['sin(x + 2π) değeri sin x değerinden farklıdır.', false, 'Sinüs 2π periyotla yinelenir.'],
    ['y = 2 sin x grafiğinin genliği 2dir.', true, 'Dikey katsayının mutlak değeri genliği verir.'],
    ['y = sin(x − π/2) grafiği sola π/2 ötelenir.', false, 'İçteki eksi işareti sağa ötelemeyi gösterir.'],
    ['Kosinüsün değer kümesi [−1, 1] aralığıdır.', true, 'Birim çemberin yatay koordinatı bu aralıkta kalır.'],
  ], [
    ['150° açısının radyan ölçüsü?', '5π/6', '2π/3', '150 × π/180 = 5π/6.'],
    ['Birim çemberde 0° noktasının koordinatları?', '(1, 0)', '(0, 1)', 'Yatay koordinat 1, düşey koordinat 0dır.'],
    ['sin 30° değeri?', '1/2', '√3/2', '30° özel açısında sinüs 1/2dir.'],
    ['cos 120° değeri?', '−1/2', '1/2', '120° ikinci bölgede; referans açı 60°dir.'],
    ['sinüsün temel periyodu?', '2π', 'π', 'π ötelenince sinüsün işareti değişebilir.'],
    ['tan x hangi açıda tanımsızdır?', 'π/2', 'π', 'cos(π/2) = 0 olduğundan bölüm tanımsızdır.'],
    ['y = sin x + 3 grafiğinin değer kümesi?', '[2, 4]', '[−1, 1]', 'Dikey öteleme değerleri 3 artırır.'],
    ['y = −cos x grafiği nasıl elde edilir?', 'x eksenine göre yansıtarak', 'Sağa birim öteleyerek', 'Öndeki eksi tüm y değerlerinin işaretini çevirir.'],
  ]),
  'mat11-trig-denklem': sorular([
    ['sin x = 2 denkleminin gerçek çözümü yoktur.', true, 'Sinüs yalnız [−1, 1] aralığında değer alır.'],
    ['sin x = sin α eşitliğinde tek çözüm ailesi x = α + 2kπdir.', false, 'x = π − α + 2kπ ailesi de vardır.'],
    ['cos x = 0 denkleminin çözümleri π/2 + kπ biçimindedir.', true, 'Kosinüs tek sayılı π/2 katlarında sıfırdır.'],
    ['tan x = tan α için periyot π olduğundan x = α + kπdir.', true, 'Tanjant π aralıkla aynı değeri alır.'],
    ['sin 2x = 0 çözülürken x yerine doğrudan kπ yazılır.', false, 'Önce 2x = kπ, sonra x = kπ/2 bulunur.'],
    ['Trigonometrik denklemde tanımsız nokta çözüm olarak kabul edilebilir.', false, 'Bölme veya tanjant kullanımı tanım kümesini daraltır.'],
    ['sin x = 1 denklemi bir periyotta bir kez sağlanır.', true, 'Sinüs maksimumunu x = π/2 noktasında alır.'],
    ['Denklemi sin x ile bölerken sin x = 0 olasılığı ayrıca incelenmelidir.', true, 'Sıfıra bölme bazı çözümleri kaybettirir.'],
  ], [
    ['0 ≤ x < 2π için sin x = 0 çözüm sayısı?', '2', '1', 'x = 0 ve x = π; 2π aralık dışında.'],
    ['0 ≤ x < 2π için cos x = −1/2 çözümleri?', '2π/3 ve 4π/3', 'π/3 ve 5π/3', 'Kosinüs ikinci ve üçüncü bölgede negatiftir.'],
    ['tan x = 1 denkleminin genel çözümü?', 'π/4 + kπ', 'π/4 + 2kπ', 'Tanjantın temel periyodu πdir.'],
    ['sin 2x = 0 için en küçük pozitif x?', 'π/2', 'π', '2x = π ilk pozitif kökü verir.'],
    ['sin x = 1/2 için [0, 2π) aralığında kaç çözüm?', '2', '1', 'π/6 ve 5π/6 çözümdür.'],
    ['cos x = 2 denklemi için ne söylenir?', 'Çözüm yoktur', 'Bir periyotta iki çözüm vardır', 'Kosinüs 2 değerini alamaz.'],
    ['Bir denklemi cos x ile böldükten sonra ne denetlenir?', 'cos x = 0 durumları', 'Yalnız x = 0', 'Sıfır bölen olan noktalar ayrı ele alınır.'],
    ['0 ≤ x < 2π için sin x = −1 hangi açı?', '3π/2', 'π/2', 'Sinüs alt uç değeri dördüncü bölge sınırındadır.'],
  ]),
  'mat11-ustel': sorular([
    ['Üstel fonksiyonda taban pozitif ve 1den farklı olmalıdır.', true, 'Bu koşul gerçek sayılarda üstel fonksiyonun tanımlanmasını sağlar.'],
    ['a > 1 için aˣ, x arttıkça azalır.', false, 'a > 1 tabanında fonksiyon artandır.'],
    ['0 < a < 1 için aˣ pozitiftir ve azalandır.', true, 'Grafik x eksenine yaklaşır ama onu kesmez.'],
    ['2ˣ fonksiyonunun y ekseni kesimi 2dir.', false, 'x = 0 için 2⁰ = 1 olur.'],
    ['y = 3ˣ + 2 grafiğinin yatay asimptotu y = 2dir.', true, 'Dikey öteleme asimptotu da taşır.'],
    ['Üstel büyümede eşit zamanlarda eşit miktar eklenir.', false, 'Eşit zamanlarda aynı oranla çarpılır.'],
    ['a > 1 olduğunda aˣ = aʸ eşitliği x = y gerektirir.', true, 'Üstel fonksiyon bire birdir.'],
    ['Üstel azalma sonucunda değer sonlu bir zamanda kendiliğinden sıfır olur.', false, 'Pozitif tabanlı fonksiyon sıfıra yaklaşır ama ulaşmaz.'],
  ], [
    ['2ˣ = 3 eşitliğinde x hangi aralıktadır?', '1 ile 2 arasında', '2 ile 3 arasında', '2¹ < 3 < 2² olduğundan üs 1 ile 2 arasındadır.'],
    ['y = 2^(x − 1) grafiği 2ˣ grafiğine göre nerede?', '1 birim sağda', '1 birim solda', 'x yerine x − 1 yazmak sağa öteler.'],
    ['Başlangıç 100, her dönemde ikiye katlanırsa 3 dönem sonra?', '800', '300', '100 × 2³ = 800.'],
    ['y = (1/2)ˣ için x büyüyünce y ne yapar?', 'Azalır', 'Artar', '0 < taban < 1 olduğundan fonksiyon azalandır.'],
    ['3ˣ = 81 için x?', '4', '3', '81 = 3⁴.'],
    ['y = 5ˣ − 3 için yatay asimptot?', 'y = −3', 'y = 0', 'Dikey öteleme asimptotu −3e taşır.'],
    ['2ˣ ve 3ˣ için x = 2 noktasında hangisi büyük?', '3ˣ', '2ˣ', '3² = 9, 2² = 4.'],
  ]),
  'mat11-ustel-ters': sorular([
    ['aˣ fonksiyonunun tersi logₐ x fonksiyonudur.', true, 'aˣ = y eşitliği x = logₐ y biçimine dönüşür.'],
    ['Üstel fonksiyonun görüntü kümesi bütün gerçek sayılardır.', false, 'Üstel değerler daima pozitiftir.'],
    ['Üstel ve logaritmik fonksiyonların grafikleri y = x doğrusuna göre simetriktir.', true, 'Ters fonksiyonda x ve y koordinatları yer değiştirir.'],
    ['log₂ 8 = 3 ifadesi 2³ = 8 anlamına gelir.', true, 'Logaritma üssü bulur.'],
    ['logₐ 0 değeri her pozitif a için sıfırdır.', false, 'Logaritmanın içi pozitif olmalıdır; 0 tanımsızdır.'],
    ['Ters fonksiyonda tanım ve görüntü kümeleri yer değiştirir.', true, 'Üstelin görüntüsü logaritmanın tanım kümesidir.'],
    ['f(x) = 2ˣ + 3 fonksiyonunun tersi log₂ x + 3tür.', false, 'Önce 3 çıkarılır: f⁻¹(x) = log₂(x − 3).'],
  ], [
    ['4ˣ = 64 eşitliğinin logaritmik karşılığı?', 'log₄ 64 = x', 'log₆₄ 4 = x', 'Taban 4, sonuç 64, aranan üs xtir.'],
    ['log₃ 1 değeri?', '0', '1', '3⁰ = 1.'],
    ['y = 2ˣ grafiğindeki (3, 8) noktası tersinde nereye gider?', '(8, 3)', '(3, 8)', 'Ters fonksiyonda koordinatlar yer değiştirir.'],
    ['f(x) = 2ˣ + 3 tersinin tanım kümesi?', 'x > 3', 'x > 0', 'f değerleri 3ten büyüktür.'],
    ['log₅ 25 kaçtır?', '2', '5', '5² = 25.'],
    ['Üstelin tersi hangi aralıktaki x için tanımlıdır?', 'x > 0', 'x ≥ 0', 'Üstel çıktı sıfır olamaz.'],
  ]),
  'mat11-log': sorular([
    ['logₐ x yalnız x > 0 için tanımlıdır.', true, 'Üstel fonksiyonun çıktısı pozitiftir.'],
    ['log₂(8 · 4) = log₂ 8 + log₂ 4 eşitliği doğrudur.', true, 'Çarpım kuralı logaritmaları toplar.'],
    ['log₃(9 + 3) = log₃ 9 + log₃ 3 eşitliği genel kuraldır.', false, 'Logaritma toplam üzerine dağıtılmaz.'],
    ['0 < a < 1 için logₐ x artan fonksiyondur.', false, 'Bu tabanda logaritma azalandır.'],
    ['logₐ a = 1 olur.', true, 'a¹ = a.'],
    ['log₂(x − 4) için x = 4 değeri tanım kümesine girer.', false, 'İçerisi sıfırdır; x > 4 gerekir.'],
    ['logₐ(xⁿ) = n logₐ x, x > 0 için uygulanır.', true, 'Üs kuralı geçerli tanım alanında kullanılır.'],
  ], [
    ['log₂ 32 kaçtır?', '5', '4', '2⁵ = 32.'],
    ['log₃ 27 + log₃ 9 kaçtır?', '5', '6', '3 + 2 = 5.'],
    ['log₂ 8 − log₂ 2 hangi tek logaritmaya eşit?', 'log₂ 4', 'log₂ 6', 'Bölüm kuralı: log₂(8/2).'],
    ['log₅(x − 1) için tanım koşulu?', 'x > 1', 'x ≥ 1', 'Logaritmanın içi sıfırdan büyük olmalıdır.'],
    ['log₂ 7 ve log₂ 8 hangisi büyük?', 'log₂ 8', 'log₂ 7', 'Taban 1den büyük olduğu için fonksiyon artar.'],
    ['log₁/₂ 2 değeri?', '−1', '1', '(1/2)⁻¹ = 2.'],
    ['log₂ 5 ifadesinin yaklaşık aralığı?', '2 ile 3 arasında', '1 ile 2 arasında', '2² = 4 < 5 < 8 = 2³.'],
  ]),
  'mat11-ustel-log-denklem': sorular([
    ['2ˣ = 16 eşitliğinde x = 4 olur.', true, '16 = 2⁴.'],
    ['log₂(x − 1) = 3 denkleminin çözümü x = 9 olur.', true, 'x − 1 = 8 ve x = 9; tanım koşulu da sağlanır.'],
    ['Logaritmik denklemin aday kökü, iç ifadeyi sıfır yapsa da kabul edilir.', false, 'Her logaritma içi pozitif olmalıdır.'],
    ['0 < a < 1 tabanında aˣ > aʸ ise x < ydir.', true, 'Azalan fonksiyonda eşitsizlik yönü döner.'],
    ['log₃ x > log₃ 9 eşitsizliği x < 9 sonucunu verir.', false, 'Taban 1den büyüktür; x > 9 gerekir.'],
    ['Yarılanma süresi sabitse kalan miktar üstel olarak azalır.', true, 'Eşit sürelerde miktar aynı oranla çarpılır.'],
    ['Bileşik faizde yalnız ilk anaparanın faizi yeniden eklenir.', false, 'Her dönem birikmiş toplam üzerinden faiz işler.'],
  ], [
    ['3^(x+1) = 81 için x?', '3', '4', 'x + 1 = 4 olduğundan x = 3.'],
    ['log₅ x = 2 için x?', '25', '10', '5² = 25.'],
    ['log₂(x − 2) = 1 için x?', '4', '3', 'x − 2 = 2 ve x > 2.'],
    ['(1/2)ˣ > (1/2)³ için x aralığı?', 'x < 3', 'x > 3', 'Azalan tabanda eşitsizlik yönü tersine döner.'],
    ['100 lira yılda %10 bileşik faizle iki yıl sonra?', '121 lira', '120 lira', '100 × 1,1² = 121.'],
    ['Miktar 80den her saat yarılanırsa 3 saat sonra?', '10', '20', '80 × (1/2)³ = 10.'],
    ['log x = −2 için x?', '0,01', '−100', '10⁻² = 0,01 ve logaritma içi pozitiftir.'],
  ]),
  'mat11-bileske': sorular([
    ['(f ∘ g)(x) ifadesinde önce g, sonra f uygulanır.', true, 'Bileşke işlem sırası içten dışadır.'],
    ['Fonksiyon bileşkesinde sıra her zaman değiştirilebilir.', false, 'Genel olarak f ∘ g ile g ∘ f farklıdır.'],
    ['Bileşkenin tanım kümesi için g(x) değerinin f tanım kümesinde olması gerekir.', true, 'İç fonksiyonun çıktısı dış fonksiyona girdi olur.'],
    ['Birim fonksiyonla bileşke fonksiyonu değiştirmez.', true, 'f ∘ I = I ∘ f = f.'],
    ['f ile tersinin bileşkesi uygun tanımda birim fonksiyondur.', true, 'Ters işlemler birbirini geri alır.'],
    ['f(g(x)) hesabında g, f çıktısına uygulanır.', false, 'g önce x üzerinde, sonra f g çıktısı üzerinde uygulanır.'],
    ['f(x) = x² ve g(x) = x + 1 için f ∘ g = g ∘ f olur.', false, '(x + 1)² ile x² + 1 farklıdır.'],
  ], [
    ['f(x)=2x, g(x)=x+3 ise (f∘g)(1)?', '8', '5', 'Önce g(1)=4, sonra f(4)=8.'],
    ['f(x)=2x, g(x)=x+3 ise (g∘f)(1)?', '5', '8', 'Önce f(1)=2, sonra g(2)=5.'],
    ['f(x)=√x, g(x)=x−2 ise f∘g tanım koşulu?', 'x ≥ 2', 'x ≥ 0', 'Karekökün içi x − 2 negatif olamaz.'],
    ['f(x)=x² ve g(x)=x+1 için (f∘g)(x)?', '(x+1)²', 'x²+1', 'Önce 1 eklenir, sonra karesi alınır.'],
    ['(f∘I)(x) sonucu?', 'f(x)', 'I(f(x)) + x', 'Birim fonksiyon uygulandığı değeri değiştirmez.'],
    ['Bileşkede iç fonksiyonun çıktısı ne olur?', 'Dış fonksiyonun girdisi', 'Dış fonksiyonun katsayısı', 'Fonksiyonlar ardışık çalışır.'],
    ['f(x)=3x−2 için f⁻¹(f(4))?', '4', '10', 'Ters fonksiyon f uygulamasını geri alır.'],
  ]),
  'mat11-dort-islem': sorular([
    ['(f + g)(x) iki fonksiyonun aynı xteki çıktılarını toplar.', true, 'Fonksiyon işlemleri noktasal yapılır.'],
    ['(f/g)(x) tanımında g(x) = 0 olan xler kullanılabilir.', false, 'Payda sıfır olamaz.'],
    ['Toplamın tanım kümesi iki fonksiyonun tanım kümelerinin kesişimidir.', true, 'İki çıktı da aynı x için var olmalıdır.'],
    ['Çarpım fonksiyonu f(g(x)) bileşkesiyle daima aynıdır.', false, 'Çarpım f(x)g(x), bileşke f(g(x))dir.'],
    ['Kesirli fonksiyonda cebirsel sadeleştirme silinen tanımsız noktayı geri getirmez.', true, 'Asıl paydanın sıfır olduğu x dışarıda kalır.'],
    ['Tek iki fonksiyonun toplamı çifttir.', false, 'f(−x)+g(−x)=−f(x)−g(x); toplam tektir.'],
    ['İki tek fonksiyonun çarpımı çifttir.', true, 'İki eksi işaret çarpımda artıya döner.'],
  ], [
    ['f(x)=x+1, g(x)=2x için (f+g)(2)?', '7', '6', 'f(2)=3 ve g(2)=4; toplam 7.'],
    ['f(x)=x+1, g(x)=2x için (fg)(2)?', '12', '8', 'Noktasal çarpım 3 × 4 = 12.'],
    ['f(x)=x²−1, g(x)=x−1 için f/g nerede tanımsız?', 'x = 1', 'x = −1', 'Payda x − 1 sıfır olmamalıdır.'],
    ['f(x)=x²−1, g(x)=x−1 için x=1 sadeleşince?', 'Yine tanımsız', 'Değeri 2 olur', 'Asıl bölüm x=1 için tanımsızdır.'],
    ['İki fonksiyonun toplamı nerede tanımlı?', 'Ortak tanım kümesinde', 'Tanım kümelerinin birleşiminde', 'İki fonksiyonun da değeri bulunmalıdır.'],
    ['İki tek fonksiyonun çarpımı nasıl olur?', 'Çift', 'Tek', 'f(−x)g(−x)=f(x)g(x).'],
    ['f(x)=x ve g(x)=x+1 için fg ile f∘g farkı?', 'x(x+1) ve x+1', 'İkisi de x(x+1)', 'Çarpım ve bileşke farklı işlemlerdir.'],
  ]),
}
