import { cografya12Konusu } from './12-cografya-yardimci'

/** 12. sınıf Coğrafya, 4. ünite: Çevre ve Toplum (2018 programı 12.4.1-12.4.4). */
export const cografya12Cevre = [
  cografya12Konusu({
    id: 'cog12-cevre-sinir',
    ad: 'Doğal Çevrenin Sınırlılığı',
    kartlar: [
      ['Kaynaklar sınırlıdır', 'Dünya’nın su, toprak, maden ve enerji kaynakları sınırlıdır.\nİnsan nüfusu ve tüketimi arttıkça baskı büyür.'],
      ['Yenilenebilir ve yenilenemez', '- **Yenilenebilir:** güneş, rüzgâr, su, orman (kullanım hızı yenilenmeyi aşmazsa)\n- **Yenilenemez:** kömür, petrol, doğal gaz, madenler'],
      ['Taşıma kapasitesi', 'Bir ekosistemin kalıcı biçimde besleyebileceği canlı ya da insan sayısıdır.\nAşılınca doğa kendini yenileyemez.'],
      ['Ekolojik ayak izi', 'İnsanın tüketimi için gereken ve atığını eritmek için gereken alan miktarıdır.\nBüyük ayak izi gezegenin yenilenme kapasitesini aşabilir.'],
      ['Toprak ve su', 'Verimli toprağın oluşması yüzyıllar alır; erozyon çok kısa sürede yok eder.\nTatlı suyun küçük bir bölümü kullanılabilir durumdadır.'],
      ['Atmosfer ve atık', 'Sera gazları, kirleticiler ve atıklar doğanın temizleme gücünü aşabilir.\nHava, su ve toprak kirliliği sınır tanımaz.'],
      ['Biyoçeşitlilik kaybı', 'Yaşam alanı yok olunca türler yok olur.\nBir türün kaybı besin zincirini bozabilir.'],
      ['Çözüm yönü', 'Azalt, yeniden kullan, geri dönüştür; yenilenebilir enerjiye geç.\nDöngüsel ekonomi atığı yeni üretimin hammaddesine çevirir.'],
    ],
    not: 'Sınırlılığı “kaynak bitiyor” değil “kullanım hızı yenilenme hızını aşıyor” diye oku; soruların anahtarı bu.',
    notKarti: 3,
    iddialar: [
      ['Kömür ve petrol yenilenemez kaynaklardır.', true, 'Oluşumları milyonlarca yıl sürer; kullanım hızına yetişemez.'],
      ['Güneş ve rüzgâr enerjisi yenilenemez kaynaktır.', false, 'Güneş ve rüzgâr yenilenebilir kaynaklardır.'],
      ['Taşıma kapasitesi aşıldığında ekosistem kendini yenilemekte zorlanır.', true, 'Kullanım doğanın yenilenmesini aşar.'],
      ['Ekolojik ayak izi, insanın doğa üzerindeki baskısını ölçer.', true, 'Tüketim ve atık için gereken alanı gösterir.'],
      ['Verimli toprak çok kısa sürede, birkaç haftada oluşur.', false, 'Toprak oluşumu yüzyıllar alır.'],
      ['Döngüsel ekonomi atığı yeni üretimde hammadde olarak kullanmayı hedefler.', true, 'Kaynak kullanımını azaltır.'],
    ],
    secimler: [
      ['Yenilenebilir kaynak hangisi?', 'Rüzgâr', 'Kömür', 'Rüzgâr tükenmez.'],
      ['Yenilenemez kaynak hangisi?', 'Petrol', 'Güneş', 'Petrol çok uzun sürede oluşur.'],
      ['Ekolojik ayak izi neyi ölçer?', 'Doğa üzerindeki baskıyı', 'Yağış miktarını', 'Tüketim ve atık için gereken alanı.'],
      ['Atığı hammadde yapan yaklaşım?', 'Döngüsel ekonomi', 'Tek yönlü üretim', 'Atık yeniden girdi olur.'],
    ],
    kontroller: [['Taşıma kapasitesi aşılırsa ne olur?', 'Ekosistem bozulur', 'Verim artar', 'Doğa kendini yenileyemez hale gelir.', 3]],
  }),
  cografya12Konusu({
    id: 'cog12-cevre-politika',
    ad: 'Ülkelerin Çevre Politikaları',
    kartlar: [
      ['Aynı sorun, farklı olanak', 'Çevre sorunları sınır tanımaz; ülkelerin imkânları ve öncelikleri farklıdır.\nGelişmişlik düzeyi politikaları belirler.'],
      ['Gelişmiş ülkeler', 'Katı çevre standartları, arıtma teknolojisi ve yenilenebilir enerji yatırımı uygularlar.\nAB, Emisyon Ticaret Sistemi’ni 2005’te başlattı.'],
      ['Gelişmekte olan ülkeler', 'Önce kalkınma ve istihdam öncelikli olabilir.\nTeknoloji ve finansman yetersizliği çevre yatırımlarını zorlaştırır.'],
      ['Ortak ama farklı sorumluluk', 'Rio Zirvesi’nde (1992) kabul edilen ilkeye göre herkes sorumludur.\nTarihsel salımı çok olan gelişmiş ülkelerin payı daha büyüktür.'],
      ['Salımda karşılaştırma', 'Çin toplam karbon salımında ilk sıradadır.\nKişi başına salımda ise ABD gibi gelişmiş ülkeler yüksektir.'],
      ['Teknoloji ve finans aktarımı', 'Gelişmiş ülkeler gelişmekte olanlara temiz teknoloji ve iklim finansmanı sağlama sözü verir.\nYeterlilik tartışılır.'],
      ['Sınırda karbon düzenlemesi', 'AB, karbon yoğun ithal ürünlere sınırda fiyat koyan düzenleme (SKDM) getirdi.\nBu, ticaret ortaklarının politikasını da etkiler.'],
      ['Türkiye', 'Türkiye Paris Anlaşması’nı 2021’de onayladı ve 2053 net sıfır emisyon hedefi açıkladı.\nYenilenebilir enerji yatırımları artıyor.'],
    ],
    not: 'Tabloyu iki cümlede topla: gelişmişler kaynak ve teknolojiyle önde, gelişmekte olanlar kalkınma baskısıyla gerideler.',
    notKarti: 4,
    iddialar: [
      ['Gelişmiş ülkelerde çevre standartları genellikle daha katıdır.', true, 'Teknoloji ve finansman olanağı daha geniştir.'],
      ['Rio Zirvesi’ndeki ilkeye göre bütün ülkelerin sorumluluğu birebir aynıdır.', false, 'İlke ortak ama farklılaştırılmış sorumluluktur.'],
      ['Çin toplam karbon salımında dünyada ilk sıradadır.', true, 'Büyük sanayi ve nüfusu nedeniyle toplam salımı en yüksektir.'],
      ['AB Emisyon Ticaret Sistemi 2005’te başlamıştır.', true, 'Karbon salımına fiyat koyan bir sistemdir.'],
      ['Gelişmekte olan ülkeler çevre yatırımı için her zaman yeterli finansmana sahiptir.', false, 'Finans ve teknoloji eksikliği önemli engeldir.'],
      ['Türkiye 2053 net sıfır emisyon hedefi açıklamıştır.', true, 'Hedef Paris Anlaşması onayıyla birlikte açıklandı.'],
    ],
    secimler: [
      ['Rio Zirvesi hangi yılda toplandı?', '1992', '1972', '1992’de İklim Çerçeve Sözleşmesi kabul edildi.'],
      ['AB’nin karbon salımına fiyat koyan sistemi?', 'Emisyon Ticaret Sistemi', 'Gümrük Birliği', 'Emisyon Ticaret Sistemi 2005’te başladı.'],
      ['Toplam karbon salımında ilk sırada olan ülke?', 'Çin', 'Norveç', 'Toplam salımda Çin ilk sıradadır.'],
      ['Türkiye’nin net sıfır hedef yılı?', '2053', '2030', '2053 olarak açıklandı.'],
    ],
    kontroller: [['Ortak ama farklı sorumluluk ilkesi nerede kabul edildi?', 'Rio Zirvesi', 'Kyoto', 'Rio’da (1992) vurgulandı.', 4]],
  }),
  cografya12Konusu({
    id: 'cog12-orgut-anlasma',
    ad: 'Çevre Örgütleri ve Uluslararası Anlaşmalar',
    kartlar: [
      ['Neden uluslararası iş birliği?', 'Kirlilik ve iklim sorunları sınır tanımaz.\nTek ülkenin önlemi yetmez; ortak kurallar gerekir.'],
      ['Stockholm ve UNEP', 'BM İnsan Çevresi Konferansı 1972’de Stockholm’de toplandı.\nBM Çevre Programı (UNEP) aynı yıl kuruldu.'],
      ['Sulak alan ve tür koruma', 'Ramsar Sözleşmesi (1971) sulak alanları, CITES (1973) tehlike altındaki türlerin ticaretini düzenler.\nTürkiye de Ramsar’a taraftır.'],
      ['Ozon tabakası', 'Montreal Protokolü (1987), ozonu delen maddelerin üretimini azalttı.\nDünyanın en başarılı çevre anlaşmalarından biri sayılır.'],
      ['Rio Zirvesi (1992)', 'İklim Değişikliği Çerçeve Sözleşmesi, Biyolojik Çeşitlilik Sözleşmesi ve Gündem 21 kabul edildi.\nSürdürülebilir kalkınma ilkesi öne çıktı.'],
      ['Kyoto Protokolü', '1997’de imzalandı; 2005’te yürürlüğe girdi.\nGelişmiş ülkelere bağlayıcı sera gazı azaltım hedefleri koydu.'],
      ['Paris Anlaşması', '2015’te kabul edilen anlaşma, sıcaklık artışını 2 °C’nin altında tutmayı, 1,5 °C’yi hedeflemeyi amaçlar.\nÜlkeler kendi azaltım katkılarını belirler.', { tur: 'tablo', basliklar: ['Anlaşma', 'Yıl', 'Konu'], satirlar: [['Ramsar', '1971', 'Sulak alan'], ['Montreal', '1987', 'Ozon'], ['Rio', '1992', 'İklim ve biyoçeşitlilik'], ['Kyoto', '1997', 'Sera gazı'], ['Paris', '2015', 'İklim']] }],
      ['Sivil toplum', 'Greenpeace (1971) ve WWF (1961) gibi örgütler kamuoyu oluşturur ve hükümetlere baskı yapar.\nBilimsel veriye dayalı raporlarla politika etkiler.'],
    ],
    not: 'Anlaşmaları konularıyla eşle: Ramsar = sulak alan, Montreal = ozon, Kyoto = sera gazı, Paris = sıcaklık sınırı.',
    notKarti: 4,
    iddialar: [
      ['Montreal Protokolü ozon tabakasına zarar veren maddeleri azaltmayı hedefler.', true, 'Bu maddelerin üretimi büyük ölçüde sonlandırıldı.'],
      ['Ramsar Sözleşmesi tehlike altındaki türlerin ticaretini düzenler.', false, 'Ramsar sulak alanları korur; tür ticareti CITES’tir.'],
      ['Kyoto Protokolü 2005’te yürürlüğe girmiştir.', true, '1997’de imzalanmış, 2005’te yürürlüğe girmiştir.'],
      ['Paris Anlaşması sıcaklık artışını 2 °C’nin altında tutmayı hedefler.', true, '1,5 °C için çaba gösterilmesi de öngörülür.'],
      ['UNEP, 1972 Stockholm Konferansı’ndan sonra kurulmuştur.', true, 'BM Çevre Programı 1972’de kuruldu.'],
      ['Rio Zirvesi 1972’de toplanmış ve İklim Çerçeve Sözleşmesi’ni kabul etmiştir.', false, 'Rio Zirvesi 1992’dedir; 1972 Stockholm’dür.'],
    ],
    secimler: [
      ['Sulak alanları koruyan sözleşme?', 'Ramsar', 'Montreal', 'Ramsar 1971’dedir.'],
      ['Ozon tabakasına yönelik protokol?', 'Montreal', 'Kyoto', 'Kyoto sera gazlarını düzenler.'],
      ['Sera gazlarına bağlayıcı hedef koyan protokol?', 'Kyoto', 'Ramsar', 'Kyoto gelişmiş ülkelere hedef koydu.'],
      ['2015’te kabul edilen iklim anlaşması?', 'Paris', 'Stockholm', 'Paris Anlaşması 2015’tedir.'],
    ],
    kontroller: [['Tehlike altındaki türlerin ticaretini hangi sözleşme düzenler?', 'CITES', 'Ramsar', 'CITES 1973’te kabul edildi.', 3]],
  }),
  cografya12Konusu({
    id: 'cog12-miras-tehdit',
    ad: 'Ortak Doğal ve Kültürel Mirasa Tehditler',
    kartlar: [
      ['Ortak miras', 'Bir ülkenin değil tüm insanlığın mirası sayılan doğal ve kültürel değerlerdir.\nUNESCO Dünya Mirası Sözleşmesi (1972) bunları koruma altına alır.'],
      ['Dünya Mirası Listesi', 'Listeye kültürel, doğal ve karma alanlar alınır.\nPamukkale-Hierapolis hem doğal hem kültürel ölçütle (karma) listededir.'],
      ['Savaş ve çatışma', 'Silahlı çatışmalar tarihî kentleri ve eserleri yok edebilir.\nPalmira ve Halep’teki tahribat bunun örnekleridir.'],
      ['İklim değişikliği', 'Deniz seviyesi yükselmesi, mercan beyazlaması ve buzul erimesi doğal alanları tehdit eder.\nKıyıdaki tarihî kentler de risk altındadır.'],
      ['Kitle turizmi ve kentleşme', 'Aşırı ziyaretçi, yapılaşma ve altyapı tarihî dokuyu yıpratır.\nVenedik hem batma hem turist baskısı altındadır.'],
      ['Kaçakçılık ve yağma', 'Kaçak kazılar ve eser kaçakçılığı mirası yerinden eder.\nBağlamı kaybolan eser bilimsel değerini yitirir.'],
      ['Kuruyan göller', 'Aral Gölü’nün küçülmesi çevreyi ve yerel kültürü yok etti.\nBalıkçı kasabaları gölden uzakta kaldı.'],
      ['Koruma yolları', 'Envanter, kontrollü turizm, hukuki koruma ve uluslararası iş birliği gerekir.\nTehlike altındaki alanlar özel listeye alınır.'],
    ],
    not: 'Tehditleri ikiye ayır: insan eliyle (savaş, turizm, yağma) ve doğa kaynaklı (iklim, deprem); çözümler ayrışır.',
    notKarti: 3,
    iddialar: [
      ['UNESCO Dünya Mirası Sözleşmesi 1972’de kabul edilmiştir.', true, 'Sözleşme ortak mirasın korunmasını amaçlar.'],
      ['Pamukkale-Hierapolis yalnızca doğal ölçütle listeye alınmıştır.', false, 'Hem doğal hem kültürel ölçütle (karma) listededir.'],
      ['Silahlı çatışmalar kültürel mirasa kalıcı zarar verebilir.', true, 'Palmira ve Halep örnektir.'],
      ['Kitle turizmi tarihî dokuyu hiçbir şekilde olumsuz etkilemez.', false, 'Aşırı ziyaretçi dokuyu yıpratır.'],
      ['Kaçak kazılar eserlerin bilimsel değerini azaltır.', true, 'Eser bağlamından koparılır.'],
      ['Deniz seviyesi yükselmesi kıyı kentlerinin tarihî dokusunu tehdit edebilir.', true, 'Venedik gibi alçak kıyı alanları risk altındadır.'],
    ],
    secimler: [
      ['Dünya Mirası Sözleşmesi hangi yılda?', '1972', '1992', 'UNESCO sözleşmesi 1972’dedir.'],
      ['Hem doğal hem kültürel ölçütlü alan?', 'Pamukkale-Hierapolis', 'Aral Gölü', 'Karma miras olarak listededir.'],
      ['Tarihî kentlere savaş zararına örnek?', 'Halep', 'Bursa', 'Halep çatışmalarda tahrip oldu.'],
      ['Eser kaçakçılığı hangi tehdittir?', 'Yağma', 'Erozyon', 'Kaçak kazı ve kaçakçılıktır.'],
    ],
    kontroller: [['Mirası koruyan UNESCO sözleşmesi kaç yılında?', '1972', '1987', '1972’de kabul edildi.', 1]],
  }),
]
