import { cografya12Konusu } from './12-cografya-yardimci'

/** 12. sınıf Coğrafya, 2. ünite (ikinci yarı): hizmet, ulaşım, ticaret ve turizm (2018 programı 12.2.6-12.2.17). */
export const cografya12BeseriB = [
  cografya12Konusu({
    id: 'cog12-hizmet',
    ad: 'Hizmet Sektörü ve Kalkınma',
    kartlar: [
      ['Hizmet sektörü', 'Mal üretmeyen, hizmet sunan faaliyetlerdir.\nTicaret, ulaşım, turizm, eğitim, sağlık, finans ve iletişim bu gruptadır.'],
      ['Gelişmişlikle ilişki', 'Ülke geliştikçe hizmetin ekonomideki payı artar.\nGelişmiş ülkelerde GSYH ve istihdamın büyük bölümü hizmetten gelir.'],
      ['Türkiye’de hizmetin yeri', 'Hizmet sektörü Türkiye’de hem katma değerde hem istihdamda en büyük sektördür.\nTarımın payı yıllar içinde azaldı.'],
      ['Ticaret ve finans', 'Alım satımı örgütleyen ticaret ve parayı yönlendiren finans üretimi destekler.\nBu işler büyük kentlerde toplanır.'],
      ['Eğitim ve sağlık', 'Üniversite ve hastaneler çevre illerden hizmet talebi çeker.\nErişim farkı bölgeler arasında eşitsizlik yaratır.'],
      ['Bilişim ve yeni hizmetler', 'Yazılım, e-ticaret ve lojistik hızla büyüyen hizmetlerdir.\nÜretimden bağımsız çalışma yeni istihdam alanı açar.'],
      ['Mekânsal dağılış', 'Hizmetler nüfusun ve alım gücünün yoğun olduğu kentlerde toplanır.\nİstanbul finans ve ticarette ülkenin ana merkezidir.'],
      ['Kalkınmadaki rolü', 'İstihdam, döviz (turizm, ulaştırma) ve üretimi destekleyen altyapı sağlar.\nMevsimlik dalgalanma ve dış etkiye duyarlılık riskleri vardır.'],
    ],
    not: 'Hizmet sektörünü “mal olmayan her şey” diye hatırla; ticaret, turizm, sağlık ve bankacılık aynı sepette.',
    notKarti: 1,
    iddialar: [
      ['Eğitim ve sağlık hizmet sektörünün içinde yer alır.', true, 'İkisi de mal üretmeyen hizmet faaliyetidir.'],
      ['Gelişmiş ülkelerde hizmetin GSYH içindeki payı genellikle düşüktür.', false, 'Gelişmiş ekonomilerde hizmetin payı yüksektir.'],
      ['Türkiye’de hizmet sektörü katma değer bakımından en büyük sektördür.', true, 'Tarım ve sanayiden daha büyük paya sahiptir.'],
      ['Finans hizmetleri nüfusun seyrek olduğu kırsal alanlarda yoğunlaşır.', false, 'Finans büyük kentlerde yoğunlaşır.'],
      ['Turizm, hizmet sektörünün döviz getiren kollarından biridir.', true, 'Yabancı ziyaretçi harcaması döviz girdisi sağlar.'],
      ['Hizmet sektörü, dış etkenlerden ve mevsimsellikten hiç etkilenmez.', false, 'Turizm gibi kollar mevsime ve dış gelişmelere duyarlıdır.'],
    ],
    secimler: [
      ['Aşağıdakilerden hangisi hizmet faaliyetidir?', 'Bankacılık', 'Madencilik', 'Banka mal üretmez, finans hizmeti sunar.'],
      ['Türkiye’de en çok katma değer üreten sektör?', 'Hizmet', 'Tarım', 'Hizmetler en büyük paya sahiptir.'],
      ['Finans merkezi olarak öne çıkan Türk kenti?', 'İstanbul', 'Bayburt', 'İstanbul ticaret ve finansın merkezidir.'],
      ['Üniversite ve hastane hizmetleri nereden talep çeker?', 'Çevre illerden', 'Yalnız aynı mahalleden', 'Hizmet alanı çevre illeri kapsar.'],
    ],
    kontroller: [['Hizmet sektörü payı ülke geliştikçe nasıl değişir?', 'Artar', 'Azalır', 'Gelişmiş ekonomiler hizmet ağırlıklıdır.', 2]],
  }),
  cografya12Konusu({
    id: 'cog12-ulasim-faktor',
    ad: 'Ulaşım Sistemi, Ağlar ve Yerleşme',
    kartlar: [
      ['Ulaşım sistemi', 'Yol, taşıt, terminal ve işletmeden oluşur.\nKara, demir, deniz, hava ve boru hattı ulaşımı olarak ayrılır.'],
      ['Yer şekilleri', 'Dağlar engel, ova ve vadiler kolaylıktır.\nTünel ve viyadük maliyeti artırır; Gülek Boğazı gibi geçitler yolu belirler.'],
      ['İklim', 'Kar, buzlanma ve sis ulaşımı aksatır.\nDoğu Anadolu’da kışın yollar kapanabilir; sisli havada uçuş ve Boğaz geçişi durur.'],
      ['Nüfus ve ekonomi', 'Nüfusun ve sanayinin yoğun olduğu yerlerde ağ sıklaşır.\nSeyrek nüfuslu bölgede yatırım yetersiz kalır.'],
      ['Teknoloji ve yatırım', 'Tünel, köprü ve hızlı tren teknoloji ve büyük sermaye ister.\nYatırım maliyetini yük ve yolcu talebi karşılar.'],
      ['Siyasi etkenler', 'Sınır kapıları ve uluslararası anlaşmalar ağın yönünü belirler.\nBoğazlardan geçiş Montrö Sözleşmesi (1936) ile düzenlenir.'],
      ['Ağ ve yerleşme', 'Yolların kesiştiği yerde kent gelişir.\nEskişehir ve Afyonkarahisar demiryolu ve karayolu kavşağı olarak büyüdü.'],
      ['Ağ ve ekonomik faaliyet', 'Ulaşım ürünü pazara taşır; liman çevresinde sanayi kurulur.\nİskenderun, Mersin ve Kocaeli limanları bunun örnekleridir.'],
    ],
    not: 'Her ulaşım hattını “neden burada?” diye sor; cevap çoğu zaman yer şekli, nüfus ya da ekonomik talepte saklı.',
    notKarti: 2,
    iddialar: [
      ['Dağlık alanlarda tünel ve viyadük ulaşım maliyetini artırır.', true, 'Engebe yapım zorluğunu ve maliyeti yükseltir.'],
      ['Doğu Anadolu’da kış koşulları ulaşımı hiç etkilemez.', false, 'Kar ve buzlanma yolları kapatabilir.'],
      ['Yolların kesiştiği yerlerde yerleşmenin büyümesi kolaylaşır.', true, 'Kavşak ticaret ve hizmet olanağı sağlar.'],
      ['Boğazlardan geçiş 1936 Montrö Sözleşmesi ile düzenlenir.', true, 'Montrö, Boğazlardaki geçiş rejimini belirler.'],
      ['Nüfusun seyrek olduğu bölgelerde ulaşım ağı genellikle çok sıktır.', false, 'Ağ, nüfus ve sanayinin yoğun olduğu yerde sıklaşır.'],
      ['Liman çevresinde sanayi kurulması ulaşım ile ekonomi ilişkisine örnektir.', true, 'Hammadde ve ürün taşıması limanla kolaylaşır.'],
    ],
    secimler: [
      ['Boğazlardan geçişi düzenleyen sözleşme?', 'Montrö', 'Lozan', 'Montrö Boğazlar Sözleşmesi 1936’dır.'],
      ['Kışın Doğu Anadolu’da ulaşımı en çok engelleyen etken?', 'Kar ve buzlanma', 'Sıcak hava', 'Kış koşulları yolları kapatabilir.'],
      ['Ulaşım hatlarının buluştuğu yere ne denir?', 'Kavşak', 'Delta', 'Kavşak ticareti ve yerleşmeyi destekler.'],
      ['Tünel ve viyadük hangi etkene karşı yapılır?', 'Engebeli yer şekli', 'Düz ova', 'Dağlar engeli aşmak için tünel gerektirir.'],
    ],
    kontroller: [['Dağlık alanda ulaşım maliyeti neden artar?', 'Tünel ve viyadük gerekir', 'Düz arazi fazladır', 'Engebe yapım maliyetini artırır.', 2]],
  }),
  cografya12Konusu({
    id: 'cog12-ulasim-turkiye',
    ad: 'Türkiye’de Ulaşım Sisteminin Gelişimi',
    kartlar: [
      ['Osmanlı demiryolları', 'İlk demiryolu imtiyazı 1856’da İzmir-Aydın hattı için verildi.\nHatlar çoğunlukla yabancı sermayeyle ve ihracat limanlarına doğru döşendi.'],
      ['Cumhuriyet’te demiryolu', 'Cumhuriyet’in ilk yıllarında demiryolu ağı Anadolu’yu Ankara’ya bağlayacak biçimde genişletildi.\nYatırımların öncelikli alanı demiryoluydu.'],
      ['1950 sonrası karayolu', '1950’de Karayolları Genel Müdürlüğü kuruldu ve karayolu öncelik kazandı.\nOtomobil, kamyon ve otobüs taşımacılığı hızla büyüdü.'],
      ['Karayolunun bugünkü yeri', 'Yolcu ve yük taşımacılığının büyük bölümü karayoluyla yapılır.\nOtoyol ve bölünmüş yol ağı genişlemeye devam eder.'],
      ['Hızlı tren', 'Ankara-Eskişehir hızlı treni 2009’da, Ankara-Konya hattı 2011’de açıldı.\nAnkara-İstanbul hattı 2014’te hizmete girdi.'],
      ['Denizyolu', 'Türkiye üç tarafı denizlerle çevrilidir.\nDış ticaretin tonaj olarak büyük kısmı limanlardan yapılır: Ambarlı, İzmir, Mersin, İskenderun.'],
      ['Havayolu', 'Uzun mesafede zaman kazandırır, turizme hizmet eder.\nİstanbul Havalimanı 2018’de açıldı ve uluslararası aktarma merkezi olmayı hedefler.'],
      ['Boğaz ve Körfez geçişleri', '- **Boğaziçi (1973), Fatih Sultan Mehmet (1988)** köprüleri\n- **Marmaray (2013) ve Avrasya Tüneli (2016)**\n- **Osmangazi, Yavuz Sultan Selim (2016), 1915 Çanakkale (2022)**'],
    ],
    not: 'Dönemleri ayır: Osmanlı demiryolu, 1923-1950 demiryolu, 1950 sonrası karayolu, 2000 sonrası hızlı tren.',
    notKarti: 3,
    iddialar: [
      ['1950 sonrası Türkiye’de ulaşım yatırımlarında karayolu öncelik kazandı.', true, 'Karayolları Genel Müdürlüğü 1950’de kuruldu.'],
      ['İlk Osmanlı demiryolu imtiyazı İstanbul-Ankara hattı için verildi.', false, 'İlk imtiyaz 1856’da İzmir-Aydın hattı içindir.'],
      ['Ankara-İstanbul hızlı tren hattı 2014’te hizmete girdi.', true, 'Ankara-Eskişehir 2009’da, İstanbul hattı 2014’te açıldı.'],
      ['Marmaray, Boğaz’ı köprüyle geçer.', false, 'Marmaray denizin altından geçen raylı tüptür.'],
      ['Dış ticaretin tonaj olarak büyük kısmı denizyoluyla yapılır.', true, 'Türkiye’nin üç yanı denizdir; limanlar ağır yük taşır.'],
      ['Fatih Sultan Mehmet Köprüsü, Boğaziçi Köprüsü’nden önce açıldı.', false, 'Boğaziçi 1973, Fatih Sultan Mehmet 1988’dedir.'],
    ],
    secimler: [
      ['Karayolları Genel Müdürlüğü ne zaman kuruldu?', '1950', '1923', '1950’den sonra karayolu öne çıktı.'],
      ['Marmaray hangi yıl hizmete açıldı?', '2013', '1988', 'Marmaray 29 Ekim 2013’te açıldı.'],
      ['İlk demiryolu imtiyazı hangi hat içindir?', 'İzmir-Aydın', 'Ankara-Sivas', '1856’da İzmir-Aydın hattı için verildi.'],
      ['2018’de açılan büyük ulaşım yapısı?', 'İstanbul Havalimanı', 'Avrasya Tüneli', 'Avrasya Tüneli 2016’dadır.'],
    ],
    kontroller: [['Hızlı tren Türkiye’de ilk hangi hatta işledi?', 'Ankara-Eskişehir', 'İzmir-Aydın', 'YHT ilk olarak 2009’da bu hatta işledi.', 5]],
  }),
  cografya12Konusu({
    id: 'cog12-dunya-ticaret',
    ad: 'Dünya Ticaret Merkezleri ve Ağları',
    kartlar: [
      ['Ticaret merkezi', 'Mal, para ve hizmet akışının toplandığı yerdir.\nLiman, borsa, havalimanı ve finans kuruluşları merkezi güçlendirir.'],
      ['Finans merkezleri', 'New York (NYSE), Londra (City), Tokyo, Şanghay, Hong Kong ve Singapur dünyanın başlıca finans merkezleridir.\nBorsalar sermaye akışını yönlendirir.'],
      ['Liman merkezleri', 'Rotterdam Avrupa’nın en büyük limanıdır; Ren’in ağzında yer alır.\nSingapur, Şanghay ve Cebelialî (Dubai) küresel konteyner ağlarının önemli düğümleridir.'],
      ['Üç kutup', 'Kuzey Amerika, Avrupa ve Doğu Asya dünya ticaretinin ağırlık merkezleridir.\nGelişmiş sanayi, nüfus ve alım gücü buralarda toplanır.'],
      ['Ana deniz yolları', 'Asya-Avrupa hattı Malakka Boğazı, Hint Okyanusu, Süveyş Kanalı ve Akdeniz üzerinden geçer.\nKonteyner gemileri bu yoldan mal taşır.'],
      ['Ticaret blokları', 'Aralarında gümrük vergisini azaltan ülke grupları: AB, USMCA ve ASEAN gibi.\nTürkiye ile AB arasında Gümrük Birliği 1996’da yürürlüğe girdi.'],
      ['Saat dilimi ve 24 saat', 'Tokyo, Londra ve New York borsaları farklı saatlerde açılır.\nBu sıra finansal ağın günde 24 saat işlemesini sağlar.'],
      ['Merkezi kuran etkenler', 'Elverişli liman ve konum, gelişmiş altyapı, siyasi istikrar ve nitelikli iş gücü.\nKonum tek başına yetmez; ağlara bağlanmak gerekir.'],
    ],
    not: 'Merkezleri üçe ayır: finans (New York, Londra), liman (Rotterdam, Singapur), blok (AB, ASEAN); ağları karıştırma.',
    notKarti: 3,
    iddialar: [
      ['Rotterdam, Avrupa’nın en büyük limanıdır.', true, 'Ren’in ağzındaki liman Avrupa’nın en büyüğüdür.'],
      ['New York ve Londra dünyanın başlıca finans merkezleri arasındadır.', true, 'NYSE ve City küresel sermaye akışını yönlendirir.'],
      ['Türkiye-AB Gümrük Birliği 2010’da yürürlüğe girdi.', false, 'Gümrük Birliği 1996’da yürürlüğe girdi.'],
      ['Dünya ticaretinin ağırlık merkezleri Kuzey Amerika, Avrupa ve Doğu Asya’dır.', true, 'Sanayi, nüfus ve alım gücü buralarda toplanır.'],
      ['Singapur, Malakka Boğazı’nın yakınında önemli bir liman merkezidir.', true, 'Konumu Asya-Avrupa yolunu denetler.'],
      ['Ticaret merkezi olmak için yalnızca nüfusun fazla olması yeterlidir.', false, 'Liman, altyapı, istikrar ve ağ bağlantısı da gerekir.'],
    ],
    secimler: [
      ['Avrupa’nın en büyük limanı hangisidir?', 'Rotterdam', 'Hamburg', 'Rotterdam Avrupa’nın en büyük limanıdır.'],
      ['Gümrük vergisini azaltan ülke grubuna ne denir?', 'Ticaret bloğu', 'Ada ülkesi', 'Blok içinde ticaret kolaylaşır.'],
      ['Asya-Avrupa deniz yolunun bağlandığı kanal?', 'Süveyş', 'Panama', 'Hint Okyanusu ile Akdeniz’i bağlar.'],
      ['New York borsasının kısa adı?', 'NYSE', 'NATO', 'New York Stock Exchange.'],
    ],
    kontroller: [['Ticaretin üç ağırlık merkezi hangisini içermez?', 'Güney Amerika', 'Doğu Asya', 'Merkezler: Kuzey Amerika, Avrupa, Doğu Asya.', 4]],
  }),
  cografya12Konusu({
    id: 'cog12-turkiye-ticaret',
    ad: 'Türkiye’de Ticaret Merkezleri ve Dış Ticaret',
    kartlar: [
      ['Ticaret merkezleri', 'İstanbul ülkenin ticaret ve finans merkezidir.\nİzmir Ege’nin, Mersin Çukurova’nın, Gaziantep Güneydoğu’nun ticaret merkezidir.'],
      ['Akış yönleri', 'Ürün üretildiği yerden pazara ve limana akar.\nEge ürünleri İzmir’den, Çukurova pamuğu ve narenciyesi Mersin’den dışarı gider.'],
      ['Sınır kapıları', 'Kara ticareti sınır kapılarından yürür.\nKapıkule (Bulgaristan), Gürbulak (İran), Habur (Irak) ve Sarp (Gürcistan) önemlidir.'],
      ['Dış ticaret açığı', 'Türkiye’nin ithalatı çoğunlukla ihracatından fazladır.\nBu fark dış ticaret açığı olarak yıllardır sürer.'],
      ['İhracat ürünleri', 'Başlıca sanayi ürünleri: otomotiv, makine, hazır giyim ve demir-çelik.\nTarımda fındık ve kuru meyve önemlidir.'],
      ['İthalat ürünleri', 'Petrol ve doğal gaz gibi enerji ile altın ve ara malı ithalatın başında gelir.\nÜretim için gerekli hammadde dışarıdan alınır.'],
      ['Ticaret ortakları', 'AB, Türkiye’nin en önemli ticaret ortağıdır; Almanya başlıca ihracat pazarlarındandır.\nÇin ve Rusya başlıca ithalat kaynakları arasındadır.'],
      ['Dış ticaretin mekânı', 'Dış ticaret denizyolu ve sınır kapılarıyla yapılır.\nLimanlar ve OSB’ler ihracata yönelik sanayi kümeleri kurar.'],
    ],
    not: 'Dış ticareti üç soruya böl: ne satıyoruz, ne alıyoruz, kime ve nereden? Açık enerji ve ara malından gelir.',
    notKarti: 4,
    iddialar: [
      ['İstanbul, Türkiye’nin ticaret ve finans merkezidir.', true, 'En büyük ticaret ve finans yoğunluğu İstanbul’dadır.'],
      ['Habur Sınır Kapısı, Türkiye’yi Gürcistan’a bağlar.', false, 'Habur Irak sınırındadır; Gürcistan’a Sarp açılır.'],
      ['Türkiye çoğunlukla ihracat fazlası veren bir ülkedir.', false, 'İthalat çoğunlukla ihracatı aşar; dış ticaret açığı vardır.'],
      ['Petrol ve doğal gaz Türkiye’nin ithalatında önemli yer tutar.', true, 'Enerji büyük ölçüde dışarıdan karşılanır.'],
      ['Otomotiv ve makine Türkiye’nin ihracat kalemleri arasındadır.', true, 'Sanayi ürünleri ihracatın büyük bölümünü oluşturur.'],
      ['Dış ticaretin tamamı sınır kapılarından, denizyolu kullanılmadan yapılır.', false, 'Denizyolu ve limanlar dış ticarette çok önemlidir.'],
    ],
    secimler: [
      ['Irak sınırındaki önemli kara ticaret kapısı?', 'Habur', 'Sarp', 'Habur Irak’a açılır.'],
      ['İthalatın ihracattan fazla olması?', 'Dış ticaret açığı', 'Dış ticaret fazlası', 'İthalat > ihracat ise açık vardır.'],
      ['Çukurova ürünlerinin başlıca çıkış limanı?', 'Mersin', 'Trabzon', 'Mersin Çukurova’nın limanıdır.'],
      ['Bulgaristan sınırındaki kapı?', 'Kapıkule', 'Gürbulak', 'Gürbulak İran sınırıdır.'],
    ],
    kontroller: [['Türkiye’de ithalatı yüksek tutan kalem?', 'Enerji', 'Fındık', 'Petrol ve doğal gaz dışarıdan alınır.', 6]],
  }),
  cografya12Konusu({
    id: 'cog12-ticaret-yollari',
    ad: 'Tarihî Ticaret Yolları ve Türkiye’nin Konumu',
    kartlar: [
      ['İpek Yolu', 'Çin’den Avrupa’ya uzanan, Orta Asya ve Anadolu’dan geçen kervan yoludur.\nİpek, porselen ve baharat taşınırdı.'],
      ['Baharat Yolu', 'Hindistan ve Güneydoğu Asya’nın baharatını Basra Körfezi ve Kızıldeniz üzerinden Akdeniz’e getirirdi.\nVarış noktaları Suriye ve Mısır limanlarıydı.'],
      ['Kral Yolu', 'Pers Ahameniş Devleti’nin Sardes’ten Susa’ya uzanan yoluydu.\nAnadolu’yu geçerek Mezopotamya ve İran’a bağlanırdı.'],
      ['Anadolu’nun konumu', 'Anadolu iki kıtanın, üç denizin kavşağıdır.\nSelçuklu ve Osmanlı kervansarayları yol boyunca ticareti güvenceye aldı.'],
      ['Coğrafi keşifler', '1498’de Vasco da Gama Ümit Burnu’nu dolaşarak Hindistan’a deniz yolu açtı.\nAkdeniz ve Anadolu üzerinden geçen yolların önemi azaldı.'],
      ['Süveyş ve Panama', 'Süveyş Kanalı 1869’da, Panama Kanalı 1914’te açıldı.\nSüveyş Akdeniz’i Kızıldeniz’e bağlayıp Avrupa-Asya yolunu kısalttı.'],
      ['Boğazlar', 'İstanbul ve Çanakkale Boğazları Karadeniz’i Akdeniz’e bağlar.\nBoğazların rejimi Montrö Sözleşmesi ile düzenlenir.'],
      ['Yeni yollar', 'Bakü-Tiflis-Kars demiryolu 2017’de açıldı; Orta Koridor Asya’yı Anadolu’ya bağlar.\nÇin’in Kuşak ve Yol girişimi eski İpek Yolu’nu canlandırmayı hedefler.'],
    ],
    not: 'Yolların çağını hatırla: keşifler Anadolu yollarını geriletti, Süveyş ve yeni koridorlar yeniden öne çıkardı.',
    notKarti: 5,
    iddialar: [
      ['İpek Yolu Çin’den Avrupa’ya uzanan ve Anadolu’dan geçen bir ticaret yoludur.', true, 'Orta Asya ve Anadolu üzerinden Avrupa’ya ulaşırdı.'],
      ['Coğrafi keşifler Akdeniz ticaret yollarının önemini artırdı.', false, 'Ümit Burnu yolu açılınca Akdeniz yolları gerilemiştir.'],
      ['Süveyş Kanalı 1869’da açıldı.', true, 'Süveyş Akdeniz ile Kızıldeniz’i bağlar.'],
      ['Panama Kanalı 1869’da Akdeniz’i Kızıldeniz’e bağladı.', false, 'Panama Atlantik ile Pasifik’i bağlar, 1914’te açıldı.'],
      ['Kral Yolu Pers Devleti’ne ait ve Anadolu’dan geçen bir yoldur.', true, 'Sardes’ten Susa’ya uzanırdı.'],
      ['Bakü-Tiflis-Kars demiryolu 2017’de hizmete girdi.', true, 'Hat Azerbaycan, Gürcistan ve Türkiye’yi bağlar.'],
    ],
    secimler: [
      ['Hindistan’a Ümit Burnu yolunu açan denizci?', 'Vasco da Gama', 'Marco Polo', 'Vasco da Gama 1498’de Hindistan’a ulaştı.'],
      ['Akdeniz’i Kızıldeniz’e bağlayan kanal?', 'Süveyş', 'Panama', 'Süveyş 1869’da açıldı.'],
      ['Baharat ticaretinin ana ürünü?', 'Baharat', 'Petrol', 'Yol baharat ve ipek taşırdı.'],
      ['2017’de açılan demiryolu?', 'Bakü-Tiflis-Kars', 'Hicaz', 'BTK Hattı 2017’de açıldı.'],
    ],
    kontroller: [['Süveyş Kanalı hangi iki deniz arasındadır?', 'Akdeniz-Kızıldeniz', 'Karadeniz-Ege', 'Süveyş bu iki denizi birbirine bağlar.', 6]],
  }),
  cografya12Konusu({
    id: 'cog12-turizm-sembol',
    ad: 'Doğal-Kültürel Semboller ve Turizm Potansiyeli',
    kartlar: [
      ['Doğal semboller', 'Ağrı Dağı (5137 m), Van Gölü, Kapadokya peri bacaları ve Pamukkale travertenleri doğal sembollerdir.\nYere kimlik kazandırırlar.'],
      ['Kültürel semboller', 'Ayasofya, Efes, Göbeklitepe, Anıtkabir ve Gelibolu Yarımadası kültürel sembollerdir.\nTarih ve toplumun ortak hafızasını taşırlar.'],
      ['Sembol ve mekân', 'Simge, yerin adıyla anılmasını sağlar: Kapadokya denince balon, Pamukkale denince travertenler akla gelir.\nSemboller turist çeker.'],
      ['Doğal potansiyel', 'Dört mevsim, uzun kıyı şeridi, dağ, göl ve zengin bitki örtüsü turizm çeşitliliği doğurur.\nYükselti ve iklim farkı kayak ile deniz turizmine imkân verir.'],
      ['Kültürel potansiyel', 'Anadolu’da pek çok uygarlığın izi vardır.\nUNESCO listesinde İstanbul’un Tarihi Alanları (1985), Efes (2015) ve Göbeklitepe (2018) yer alır.'],
      ['Turizm türleri', '- **Deniz-kum-güneş:** Antalya, Muğla\n- **Kış:** Uludağ, Erciyes, Palandöken\n- **Termal:** Pamukkale, Bursa, Afyon\n- **İnanç ve kültür:** Konya, İstanbul, Efes'],
      ['Mevsimsellik', 'Kıyı turizmi yaz aylarında yoğunlaşır.\nSezonu uzatmak için kış, termal, kongre ve sağlık turizmi desteklenir.'],
      ['Dağılışın eşitsizliği', 'Turizm kıyılarda toplanmıştır.\nİç ve doğu bölgelerinin turizm potansiyeli yeterince kullanılamamaktadır.'],
    ],
    not: 'Sembolleri haritaya iliştir: Ağrı-Doğu, Kapadokya-İç Anadolu, Pamukkale-Ege; sorular genelde bunu yoklar.',
    notKarti: 1,
    iddialar: [
      ['Ağrı Dağı, Türkiye’nin en yüksek dağıdır.', true, 'Yüksekliği 5137 metredir.'],
      ['Van Gölü, Türkiye’nin en büyük gölüdür.', true, 'Yüzölçümü bakımından en büyük göl Van Gölü’dür.'],
      ['Kapadokya peri bacaları Karadeniz kıyısında yer alır.', false, 'Kapadokya İç Anadolu’dadır (Nevşehir çevresi).'],
      ['Göbeklitepe UNESCO Dünya Mirası Listesi’ne 2018’de girdi.', true, 'Göbeklitepe Şanlıurfa’dadır.'],
      ['Termal turizm Pamukkale ve Bursa gibi merkezlerde gelişmiştir.', true, 'Jeotermal kaynaklar termal turizmi destekler.'],
      ['Türkiye’de turizm eşit biçimde bütün bölgelere yayılmıştır.', false, 'Turizm kıyı kuşağında yoğunlaşmıştır.'],
    ],
    secimler: [
      ['Travertenleriyle ünlü doğal sembol?', 'Pamukkale', 'Ağrı', 'Pamukkale travertenleri Denizli’dedir.'],
      ['Kış turizmi merkezi hangisidir?', 'Erciyes', 'Bodrum', 'Erciyes kayak merkezidir.'],
      ['Göbeklitepe hangi ilimizdedir?', 'Şanlıurfa', 'Nevşehir', 'Şanlıurfa’da yer alır.'],
      ['Deniz-kum-güneş turizminin merkezi?', 'Antalya', 'Kars', 'Akdeniz kıyısındadır.'],
    ],
    kontroller: [['Ağrı Dağı’nın yüksekliği kaç metredir?', '5137', '3917', 'Ağrı Dağı 5137 m ile en yüksek dağdır.', 1]],
  }),
  cografya12Konusu({
    id: 'cog12-turizm-ekonomi',
    ad: 'Turizm Politikaları ve Ekonomideki Yeri',
    kartlar: [
      ['Turizm politikası', 'Devlet turizmi teşvik kanunları ve planlarla yönlendirir.\n2634 sayılı Turizmi Teşvik Kanunu (1982) turizm bölgelerini ve yatırımları destekler.'],
      ['Turizm merkezleri', 'Belek gibi turizm merkezleri ilan edilir.\nArazi tahsisi, altyapı ve teşvik yatırımı kolaylaştırır.'],
      ['Çevresel etki', 'Kıyıda yapılaşma, su tüketimi ve atık artar.\nKıyı Kanunu (1990) kıyı şeridini korumaya çalışır; Mavi Bayrak temizliği belgeler.'],
      ['Kültürel etki', 'Turizm el sanatlarını ve geleneği canlandırabilir.\nAşırı ticarileşme yerel kültürü bozabilir.'],
      ['Ekonomik etki', 'Döviz girdisi sağlar, istihdam yaratır ve cari açığı azaltır.\nUlaşım, inşaat, ticaret ve tarımı da canlandırır.'],
      ['Mevsimsellik', 'Gelir ve istihdam yazın yoğunlaşır.\nSezonu 12 aya yaymak için kış, termal, inanç ve kongre turizmi geliştirilir.'],
      ['Dış etkilere duyarlılık', 'Güvenlik sorunları, salgın ve kur dalgalanması turist sayısını hızla düşürür.\nCOVID-19 salgını 2020’de turizmi sert vurdu.'],
      ['Sürdürülebilir turizm', 'Bölgenin taşıma kapasitesi aşılmamalı, doğa ve yerel halk gözetilmelidir.\nEkoturizm ve kırsal turizm yükü dağıtır.'],
    ],
    not: 'Turizmin iki yüzü var: aynı faaliyet döviz getirir, ama kıyı yapılaşması, su tüketimi ve mevsimsellik de getirir.',
    notKarti: 3,
    iddialar: [
      ['Turizm gelirleri cari açığı azaltmaya katkı sağlar.', true, 'Yabancı ziyaretçi döviz getirir.'],
      ['Turizmin çevre üzerinde hiçbir olumsuz etkisi yoktur.', false, 'Kıyı yapılaşması, su tüketimi ve atık artar.'],
      ['Turizm gelirleri güvenlik ve salgın gibi dış etkenlerden bağımsızdır.', false, 'Dış gelişmelerde turist sayısı hızla düşebilir.'],
      ['Sezonu uzatmak için kış ve termal turizm geliştirilir.', true, 'Mevsimselliği azaltmayı amaçlar.'],
      ['Turizmi Teşvik Kanunu 1982’de çıkarılmıştır.', true, '2634 sayılı kanun turizm yatırımlarını destekler.'],
      ['Sürdürülebilir turizmde taşıma kapasitesi göz ardı edilir.', false, 'Taşıma kapasitesi aşılmaması esastır.'],
    ],
    secimler: [
      ['Turizmin cari açık üzerindeki etkisi?', 'Azaltıcı', 'Artırıcı', 'Döviz girdisi açığı kapatır.'],
      ['Turizm sezonunu uzatan tür?', 'Kış turizmi', 'Deniz turizmi', 'Kış turizmi yaz dışında talep yaratır.'],
      ['Kıyı şeridini korumayı amaçlayan kanun?', 'Kıyı Kanunu', 'Orman Kanunu', 'Kıyı Kanunu 1990’da çıktı.'],
      ['Turizmin doğaya olumsuz etkisi?', 'Su tüketimi ve atık', 'Toprak verimi', 'Su kullanımı ve atık artar.'],
    ],
    kontroller: [['Turizm gelirinin cari açığa etkisi nedir?', 'Azaltır', 'Büyütür', 'Döviz girdisi cari açığı kapatmaya yardım eder.', 5]],
  }),
]
