import { cografya12Konusu } from './12-cografya-yardimci'

/** 12. sınıf Coğrafya, 1. ve 2. ünite (ilk yarı): Doğal Sistemler; Beşerî Sistemler (2018 programı 12.1, 12.2.1-12.2.5). */
export const cografya12Dogal = [
  cografya12Konusu({
    id: 'cog12-ekstrem',
    ad: 'Ekstrem Doğa Olayları ve Etkileri',
    kartlar: [
      ['Ekstrem olay nedir?', 'Bir yerin olağan değerlerinden çok uzaklaşan doğa olayıdır.\nÇok yüksek sıcaklık, çok az yağış ya da çok şiddetli rüzgâr buna örnektir.'],
      ['Kuraklık', 'Yağışın uzun süre ortalamanın altında kalmasıdır.\nSonuçları: ürün kaybı, su kıtlığı ve orman yangını riskinin artması.'],
      ['Sel ve taşkın', 'Kısa sürede düşen aşırı yağış akarsuyu yatağından taşırır.\nGeçirimsiz yüzey ve dere yatağına yapılaşma zararı büyütür.'],
      ['Sıcak ve soğuk dalgası', 'Ardışık günlerde olağan değerlerin çok üstünde ya da altında seyreden sıcaklıktır.\nSağlığı, enerji tüketimini ve tarımı etkiler.'],
      ['Hortum ve tropikal siklon', '- **Hortum:** dar bir alanda dönen, buluttan yere uzanan hava sütunu\n- **Tropikal siklon:** sıcak okyanus üzerinde oluşan geniş alçak basınç; kıyıda yıkım yapar'],
      ['Çığ ve heyelan', 'Dik yamaçta kar kütlesinin kayması çığ, toprağın kayması heyelandır.\nEğim, yağış ve bitki örtüsünün azlığı heyelan riskini artırır.'],
      ['Orman yangını', 'Sıcak, kurak ve rüzgârlı havada hızla yayılır.\nAkdeniz ikliminin kızılçam ve maki alanlarında yaz aylarında risk yüksektir.'],
      ['Etkiyi büyüten insan faktörü', 'Aynı olay yerleşime ve altyapıya göre farklı zarar verir.\nRiskli alanda yapılaşma ve ormansızlaşma etkiyi büyütür.'],
    ],
    not: 'Ekstrem olayı “ortalamadan sapma” diye oku; sel, kuraklık ve hortumu aynı kategoride değil, nedenleriyle ayır.',
    notKarti: 1,
    iddialar: [
      ['Ekstrem doğa olayı, bir yerin olağan değerlerinden çok uzaklaşan olaydır.', true, 'Ortalamadan büyük sapma ekstremin ölçütüdür.'],
      ['Kuraklık, kısa sürede düşen aşırı yağışın sonucudur.', false, 'Kuraklık yağışın uzun süre ortalamanın altında kalmasıdır.'],
      ['Tropikal siklonlar sıcak okyanus yüzeyi üzerinde oluşur.', true, 'Sıcak deniz suyu siklonun enerji kaynağıdır.'],
      ['Heyelan riski eğim arttıkça ve bitki örtüsü azaldıkça düşer.', false, 'Eğim artıp bitki örtüsü azaldıkça heyelan riski artar.'],
      ['Aynı yağış, geçirimsiz yüzeyin çok olduğu kentte daha büyük taşkın doğurabilir.', true, 'Su sızamayınca yüzey akışı artar.'],
      ['Orman yangınları en çok serin ve yağışlı mevsimde yayılır.', false, 'Sıcak, kurak ve rüzgârlı hava yangını yayar.'],
    ],
    secimler: [
      ['Dar alanda dönen, buluttan yere uzanan hava sütunu?', 'Hortum', 'Çığ', 'Hortum dar alanda dönen hava sütunudur.'],
      ['Yağışın uzun süre ortalamanın altında kalması?', 'Kuraklık', 'Taşkın', 'Uzun süreli yağış azlığı kuraklıktır.'],
      ['Akdeniz ikliminde yaz mevsiminde en belirgin ekstrem risk?', 'Orman yangını', 'Çığ', 'Sıcak ve kurak yaz yangını yayar.'],
      ['Dik yamaçta kar kütlesinin kayması?', 'Çığ', 'Heyelan', 'Karın kayması çığ, toprağın kayması heyelandır.'],
    ],
    kontroller: [['Ekstrem olayı tanımlayan ölçüt hangisi?', 'Olağan değerden sapma', 'Yalnız can kaybı', 'Ekstrem, ortalamadan büyük sapmadır; kayıp afeti belirler.', 1]],
  }),
  cografya12Konusu({
    id: 'cog12-doga-degisim',
    ad: 'Doğal Sistemlerdeki Değişimler ve Gelecek',
    kartlar: [
      ['Doğal sistemler değişir', 'İklim, buzul, deniz seviyesi ve bitki örtüsü zamanla değişir.\nBazı değişimler binlerce yıl sürer, bazıları onlarca yılda görülür.'],
      ['Buzulların geri çekilmesi', 'Isınma dağ buzullarını ve kutup buz örtüsünü eritir.\nAkarsu akışı değişir; Ağrı ve Cilo dağlarındaki buzullar küçülmektedir.'],
      ['Deniz seviyesi yükselmesi', 'Eriyen kara buzu ve ısınan suyun genleşmesi seviyeyi yükseltir.\nKıyı ovaları, deltalar ve alçak adalar risk altındadır.'],
      ['Çölleşme', 'Kurak ve yarı kurak alanda toprağın verimini yitirmesidir.\nAşırı otlatma, yanlış sulama ve kuraklık nedenlerindendir.'],
      ['Göl ve sulak alanların küçülmesi', 'Aral Gölü, akarsularının sulamaya yönlendirilmesiyle çekildi.\nKonya Havzası’nda yer altı suyu çekimi obrukları artırdı.'],
      ['Biyoçeşitlilik ve yaşam alanı', 'Sıcaklık değişince türler daha serin yüksek enlem ya da yükseltiye kayar.\nYaşam alanını kaybeden türlerin sayısı azalır.'],
      ['Doğal ve insan kaynaklı değişim', 'Doğal döngüler çok uzun sürede iklimi değiştirir.\nSera gazı salımı ise değişimi çok daha kısa sürede hızlandırır.'],
      ['Gelecek hakkında çıkarım', 'Geçmiş ve bugünkü veriden eğilim çıkarılır; uydu ve modellerden senaryo kurulur.\nÇıkarım kesin tahmin değil, olasılıktır.'],
    ],
    not: 'Çıkarım kuran biri “şu olacak” demez, “şu varsayımla şu olabilir” der; kartı bu cümleyle oku.',
    notKarti: 8,
    iddialar: [
      ['Eriyen kara buzulları deniz seviyesinin yükselmesine katkı yapar.', true, 'Kara buzu erirse okyanusa su eklenir.'],
      ['Çölleşme yalnızca sıcak çöllerin kenarında doğal nedenlerle gerçekleşir.', false, 'Aşırı otlatma ve yanlış sulama gibi insan etkileri de çölleşmeyi hızlandırır.'],
      ['Aral Gölü’nün küçülmesinde akarsularının sulamaya yönlendirilmesi etkili oldu.', true, 'Göle ulaşan su azalınca göl çekildi.'],
      ['Yüzey sıcaklığı artınca tüm türler daha sıcak alanlara yayılır.', false, 'Birçok tür serin alanlara kayar; yaşam alanı daralan türler azalır.'],
      ['Gelecek senaryoları varsayımlar değişirse farklı sonuç verebilir.', true, 'Çıkarım, seçilen varsayıma bağlıdır.'],
      ['Deniz seviyesi yükselmesi yalnızca suyun buharlaşmasıyla ilgilidir.', false, 'Kara buzunun erimesi ve ısınan suyun genleşmesi başlıca nedenlerdir.'],
    ],
    secimler: [
      ['Isınan okyanus suyunun hacmini artırması?', 'Genleşme', 'Çökelme', 'Isınan su genleşir ve seviyeyi yükseltir.'],
      ['Konya Havzası’nda yer altı suyu çekimi hangi oluşumu artırdı?', 'Obruk', 'Delta', 'Yer altı suyu azalınca çöküntüler (obruk) arttı.'],
      ['Aşırı otlatma hangi sürece yol açabilir?', 'Çölleşme', 'Buzullaşma', 'Bitki örtüsü azalır, toprak verimi düşer.'],
      ['Gelecek için en doğru ifade?', 'Senaryo ve olasılık', 'Kesin tahmin', 'Değişkenler olasılık içerir.'],
    ],
    kontroller: [['Çölleşmeyi hızlandıran bir insan etkisi?', 'Aşırı otlatma', 'Buzul erimesi', 'Aşırı otlatma bitki örtüsünü yok eder.', 4]],
  }),
]

export const cografya12BeseriA = [
  cografya12Konusu({
    id: 'cog12-baskin-faaliyet',
    ad: 'Baskın Ekonomik Faaliyet ve Yaşam',
    kartlar: [
      ['Baskın faaliyet', 'Bir bölgede çalışanların çoğunun ve gelirin büyük kısmının dayandığı faaliyettir.\nİş takvimi, gelir ve toplumsal yaşam buna göre biçimlenir.'],
      ['Tarım ve hasat takvimi', 'Ova köylerinde yaşam ekim ve hasat dönemine göre akar.\nDüğün ve şenlikler çoğunlukla hasattan sonra yapılır.'],
      ['Hayvancılık ve yaylacılık', 'Yaz aylarında sürüler yaylaya çıkar; aileler yer değiştirir.\nArtvin’deki Kafkasör Boğa Güreşleri bu kültürün bir ürünüdür.'],
      ['Balıkçılık', 'Karadeniz kıyısında hamsi avı kıyı kültürünün merkezindedir.\nTekne yapımı, hamsi yemekleri ve festivaller bu yaşamla gelişti.'],
      ['Madencilik', 'Zonguldak, taşkömürü madenciliğiyle kurulan bir madenci kentidir.\nMaden kapanınca işsizlik ve dışa göç görülür.'],
      ['Turizm', 'Antalya ve Muğla’da yaşam turizm sezonuna göre dönüşür.\nMevsimlik iş, yabancı dil ve el sanatları öne çıkar; kış aylarında nüfus azalır.'],
      ['Sanayi', 'Kocaeli ve Bursa gibi sanayi merkezleri işçi göçü alır.\nVardiyalı çalışma ve farklı yörelerden gelenlerle karma bir kültür oluşur.'],
      ['Tek faaliyete bağımlılık', 'Bölge tek faaliyete bağlıysa o faaliyet zayıfladığında geçim sarsılır.\nİşsizlik ve göç artar; çeşitlendirme riski azaltır.'],
    ],
    not: 'Bir faaliyeti yalnızca “ne üretir” diye değil, insanların günü, mevsimi ve göçünü nasıl biçimlendirdiğiyle oku.',
    notKarti: 8,
    iddialar: [
      ['Yaylacılık, hayvancılığın yaşam biçimini mevsime göre değiştirdiği bir örnektir.', true, 'Yaz aylarında sürüler ve aileler yaylaya çıkar.'],
      ['Zonguldak’ın kent dokusu bakır madenciliğine göre biçimlendi.', false, 'Zonguldak taşkömürü madenciliğiyle gelişti.'],
      ['Turizm bölgelerinde mevsimlik iş ve nüfus değişimi görülebilir.', true, 'Sezonda nüfus ve istihdam artar, kışın azalır.'],
      ['Sanayi merkezleri çevreden hiç göç almaz.', false, 'İş olanakları nedeniyle işçi göçü alır.'],
      ['Tek faaliyete bağımlı bölge, o faaliyetin zayıflamasından daha az etkilenir.', false, 'Bağımlı bölge daha çok etkilenir; işsizlik ve göç artar.'],
      ['Hamsi avı Karadeniz kıyı kültürünün parçasıdır.', true, 'Tekne, yemek ve festival kültürünü etkiler.'],
    ],
    secimler: [
      ['Zonguldak hangi faaliyetle kurulmuş bir kenttir?', 'Taşkömürü madenciliği', 'Tarım', 'Zonguldak havzası taşkömürü ile bilinir.'],
      ['Yaz aylarında sürülerle dağlara çıkma?', 'Yaylacılık', 'Mevsimlik tarım', 'Hayvanlar yaz mevsimini yaylada geçirir.'],
      ['Tek faaliyete bağımlılığın riski azaltılırsa ne gerekir?', 'Faaliyet çeşitlendirme', 'Yalnız nüfus artırma', 'Farklı gelir kaynakları riski dağıtır.'],
      ['Kafkasör Boğa Güreşleri hangi yaşamın ürünüdür?', 'Hayvancılık ve yayla', 'Balıkçılık', 'Artvin yayla ve hayvancılık kültüründen doğdu.'],
    ],
    kontroller: [['Kış aylarında nüfusu azalan bölge hangisidir?', 'Turizm bölgesi', 'Maden kenti', 'Turizm sezonluk istihdama dayanır.', 6]],
  }),
  cografya12Konusu({
    id: 'cog12-sehirlesme-goc',
    ad: 'Şehirleşme, Göç ve Sanayileşme',
    kartlar: [
      ['Şehirleşme nedir?', 'Kentlerin sayısının ve kentte yaşayan nüfus oranının artmasıdır.\nKentsel yerleşmelerin alan olarak büyümesini de kapsar.'],
      ['Sanayileşme ve kent', 'Fabrikalar işçi çeker; işçi gelince konut, ticaret ve hizmet kurulur.\nSanayi kenti büyür, yeni yerleşme alanları açılır.'],
      ['İtici ve çekici etkenler', 'Kırdan kente göçte iki kuvvet birlikte çalışır.\nİş ve eğitim olanakları çeker; toprak yetersizliği ve geçim sıkıntısı iter.', { tur: 'tablo', basliklar: ['İtici (kır)', 'Çekici (kent)'], satirlar: [['Toprak yetersizliği', 'İş olanağı'], ['Düşük gelir', 'Eğitim ve sağlık'], ['Hizmetin azlığı', 'Sosyal çevre']] }],
      ['Göç türleri', '- **İç göç:** ülke içinde\n- **Dış göç:** ülke dışına ya da dışından\n- **Zorunlu göç:** afet, savaş ya da baskı\n- **Mevsimlik göç:** tarım işçilerinin geçici yer değiştirmesi'],
      ['Türkiye’de kırdan kente göç', '1950’lerden sonra tarımda makineleşme kırda iş gücü fazlası doğurdu.\nKarayolu ağının gelişmesi göçü kolaylaştırdı.'],
      ['Gecekondu ve plansız yapılaşma', 'Hızlı göç konut üretimini aşınca kent çeperinde gecekondu bölgeleri doğdu.\nAltyapı ve hizmetler yetişemedi.'],
      ['Toplumsal etkiler', 'Kentte konut, trafik ve altyapı baskısı artar.\nKırda genç nüfus azalır, nüfus yaşlanır; farklı kültürler kentte karşılaşır.'],
      ['Planlı kentleşme', 'Kentsel dönüşüm, toplu taşıma ve orta ölçekli kentlerin güçlendirilmesi baskıyı azaltır.\nKırsal kalkınma göçün itici etkenlerini zayıflatır.'],
    ],
    not: 'Şehirleşme, göç ve sanayileşmeyi tek bir zincirin halkaları gibi oku: sanayi çeker, göç gelir, kent büyür.',
    notKarti: 2,
    iddialar: [
      ['Kırda toprak yetersizliği, göçün itici etkenlerinden biridir.', true, 'Geçim sıkıntısı insanı kırdan iter.'],
      ['Sanayi merkezleri çevresine işçi çekerek kentin büyümesine yol açabilir.', true, 'Fabrika işçi ve hizmet ihtiyacını artırır.'],
      ['Zorunlu göç yalnızca ekonomik nedenlerle gönüllü yapılır.', false, 'Zorunlu göç afet, savaş ya da baskı nedeniyledir.'],
      ['Türkiye’de kırdan kente göç 1950’lerden sonra belirgin biçimde hızlandı.', true, 'Tarımda makineleşme ve karayolları göçü hızlandırdı.'],
      ['Gecekondu bölgelerinde altyapı genellikle göçle aynı hızda gelişti.', false, 'Altyapı göçün hızına yetişemedi.'],
      ['Mevsimlik tarım işçiliği iç göç örneği olabilir.', true, 'İşçiler geçici olarak başka bir ilde çalışır.'],
    ],
    secimler: [
      ['Kentteki iş olanakları göçte hangi etkendir?', 'Çekici etken', 'İtici etken', 'Kenti cazip kılan etkendir.'],
      ['Savaş nedeniyle yer değiştirme hangi göçtür?', 'Zorunlu göç', 'Gönüllü göç', 'Kişi yerinden edilmiştir.'],
      ['Kentsel çeperde plansız konut bölgeleri?', 'Gecekondu', 'Metropol', 'Göç hızlı, planlı konut yetersiz kalmıştır.'],
      ['Göçün kırdaki yaygın demografik sonucu?', 'Yaşlı nüfus oranının artması', 'Genç nüfus artışı', 'Genç nüfus kente taşınır.'],
    ],
    kontroller: [['Toprak yetersizliği hangi etkendir?', 'İtici etken', 'Çekici etken', 'Kırdan çıkışı hızlandıran etkendir.', 3]],
  }),
  cografya12Konusu({
    id: 'cog12-gelecek-nufus',
    ad: 'Nüfus ve Ekonomide Gelecek Değişimler',
    kartlar: [
      ['Çıkarımın dayanağı', 'Geçmiş ve bugünkü veriden eğilimler çıkarılır.\nNüfus piramidi, doğum ve ölüm hızları geleceğe ışık tutar.'],
      ['Yaşlanan nüfus', 'Doğurganlık düşünce yaşlı nüfusun payı artar.\nTürkiye’de doğurganlık hızı yenilenme düzeyi olan 2,1’in altına indi.'],
      ['Kentleşme eğilimi', 'Dünya nüfusunun yarısından fazlası kentte yaşıyor.\nBM, yüzyılın ortasında oranın yaklaşık üçte ikiye çıkacağını öngörüyor.'],
      ['Büyük kentler', 'Nüfusu on milyonu aşan megakentler çoğalıyor.\nKonut, su ve ulaşım hizmeti bu kentlerde en büyük sınavdır.'],
      ['Yerleşme değişimi', 'Uzaktan çalışma kırsal yerleşmeye dönüşü kolaylaştırabilir.\nİklim riski taşıyan kıyılarda yerleşme azalabilir.'],
      ['Üretimde değişim', 'Otomasyon ve yapay zekâ fabrika ve büro işlerini değiştiriyor.\nE-ticaret ticareti, hassas tarım ise üretimi dönüştürüyor.'],
      ['Enerji dönüşümü', 'Güneş ve rüzgâr gibi yenilenebilir kaynakların payı artıyor.\nBu geçiş yeni iş alanları açıp bazı bölgelerin geçimini sarsabilir.'],
      ['Çıkarım kesin değil', 'Gelecek tahminleri varsayımlara bağlıdır.\nPolitika, teknoloji ve iklim değişirse sonuç da değişir.'],
    ],
    not: 'Doğurganlığı gelecek tahmininin anahtarı olarak oku: yaşlanma, bağımlılık oranı ve kamu harcaması hep oradan çıkar.',
    notKarti: 2,
    iddialar: [
      ['Doğurganlık hızı düşünce yaşlı nüfusun payı artabilir.', true, 'Doğan sayı azalırsa yaşlıların oranı yükselir.'],
      ['Türkiye’nin doğurganlık hızı yenilenme düzeyi olan 2,1’in üzerindedir.', false, 'Doğurganlık hızı 2,1’in altındadır.'],
      ['Dünya nüfusunun yarısından fazlası kentte yaşamaktadır.', true, 'Kentli nüfus yarıyı aşmıştır.'],
      ['Uzaktan çalışma kentten kırsala dönüşü hiçbir şekilde etkilemez.', false, 'İş yerinden bağımsız çalışma kırsala dönüşü kolaylaştırabilir.'],
      ['Yenilenebilir enerji payı artarsa fosil yakıta bağlı bölgelerin geçimi etkilenebilir.', true, 'Üretim yapısı değişir; yeni ve eski iş alanı oluşur.'],
      ['Gelecek çıkarımları varsayımlardan bağımsız, kesin sonuçlardır.', false, 'Çıkarımlar varsayımlara bağlıdır.'],
    ],
    secimler: [
      ['Yenilenme düzeyindeki doğurganlık hızı?', '2,1', '1,1', 'Nüfusun kendini yenilemesi için hız yaklaşık 2,1 olmalıdır.'],
      ['Nüfusu on milyonu aşan kentlere ne denir?', 'Megakent', 'Köy kent', 'Çok büyük kentler megakent diye anılır.'],
      ['Hassas tarım hangi alandaki bir değişimdir?', 'Üretim', 'Göç', 'Tarımda teknolojiyle üretimi dönüştürür.'],
      ['Gelecekte kent nüfusu için BM öngörüsü?', 'Artış', 'Azalış', 'Kentleşme eğilimi sürüyor.'],
    ],
    kontroller: [['Doğurganlık düşerse yaşlı nüfus payı ne olur?', 'Artar', 'Azalır', 'Doğan sayı azalınca yaşlıların oranı yükselir.', 2]],
  }),
  cografya12Konusu({
    id: 'cog12-islevsel-bolge',
    ad: 'İşlevsel Bölgeler',
    kartlar: [
      ['Biçimsel ve işlevsel bölge', 'Biçimsel bölgede ortak özellik (iklim, bitki) belirleyicidir.\nİşlevsel bölgede bir merkeze bağlı akışlar belirleyicidir.'],
      ['Merkez ve çevre', 'İşlevsel bölgenin bir merkezi ve ona bağlı çevresi vardır.\nİnsan, mal, para ve bilgi akışı merkezle çevre arasında olur.'],
      ['Örnekler', 'Kente her gün işe gelenlerin yaşadığı alan, hastanenin hizmet alanı ve limanın art alanı örnektir.\nBölge sınırı akışın yoğunluğuna göre çizilir.'],
      ['Uzaklık ve etkileşim', 'Merkezden uzaklaştıkça etkileşim azalır.\nSınır keskin değil, geçiş kuşağı biçimindedir.'],
      ['Ulaşımın rolü', 'Otoyol ve hızlı tren gibi yeni ulaşım hatları işlevsel bölgeyi genişletir.\nMerkez ile çevre zaman olarak yakınlaşır.'],
      ['Marmara örneği', 'İstanbul, Kocaeli, Sakarya, Bursa ve Tekirdağ arasında yoğun iş gücü ve mal akışı vardır.\nBu aks, Türkiye’nin en yoğun etkileşim alanlarından biridir.'],
      ['İBBS bölgeleri', 'Türkiye, AB uyumu için İstatistiki Bölge Birimleri Sınıflaması’na ayrıldı.\n12 Düzey-1, 26 Düzey-2 ve 81 Düzey-3 bölgesi vardır.'],
      ['Kalkınma ajansları', 'Bölgesel planlama için 26 Düzey-2 bölgesinde kalkınma ajansı kuruldu.\nAjanslar bölgenin yerel potansiyelini planlamada kullanır.'],
    ],
    not: 'Haritada işlevsel bölge ararken sınırı değil akışı ara: kim kime gidiyor, ne taşınıyor, hangi merkeze bağlanıyor?',
    notKarti: 3,
    iddialar: [
      ['İşlevsel bölgenin belirleyici ölçütü merkeze bağlı akışlardır.', true, 'İnsan, mal ve bilgi akışı merkez ile çevreyi bağlar.'],
      ['Aynı iklime sahip alanlar işlevsel bölgeye örnektir.', false, 'Ortak özelliğe göre ayrılan bölge biçimsel bölgedir.'],
      ['Yeni otoyol, işlevsel bölgenin etki alanını genişletebilir.', true, 'Ulaşım süresi kısalır, etkileşim artar.'],
      ['Merkezden uzaklaştıkça etkileşim artar.', false, 'Uzaklaştıkça etkileşim azalır.'],
      ['Türkiye’de İBBS’ye göre 81 Düzey-3 bölgesi vardır.', true, 'Düzey-3, il sayısına karşılık gelir.'],
      ['Kalkınma ajansları Düzey-1 bölge sayısı kadar, yani 12 tanedir.', false, 'Ajanslar 26 Düzey-2 bölgesinde kurulmuştur.'],
    ],
    secimler: [
      ['Merkeze bağlı akışlarla belirlenen bölge?', 'İşlevsel bölge', 'Biçimsel bölge', 'Akış ölçütüne dayanır.'],
      ['Aynı iklim özelliğine göre ayrılan bölge?', 'Biçimsel bölge', 'İşlevsel bölge', 'Ortak özellik belirleyicidir.'],
      ['Türkiye’de Düzey-2 bölge sayısı?', '26', '12', 'Düzey-1: 12, Düzey-2: 26, Düzey-3: 81.'],
      ['Marmara’nın yoğun sanayi aksı hangi kentlerden geçer?', 'İstanbul-Kocaeli-Sakarya', 'Van-Muş-Bitlis', 'Doğu Marmara sanayi aksı.'],
    ],
    kontroller: [['Hastane hizmet alanı hangi bölge türüne örnektir?', 'İşlevsel bölge', 'Biçimsel bölge', 'Merkeze bağlı akışa dayanır.', 3]],
  }),
  cografya12Konusu({
    id: 'cog12-kalkinma-proje',
    ad: 'Bölgesel Kalkınma Projeleri',
    kartlar: [
      ['Amaç', 'Bölgeler arasındaki gelişmişlik farkını azaltmaktır.\nProjeler tarım, sanayi, ulaşım, eğitim ve sağlığı birlikte kapsar.'],
      ['Gelişmişlik farkı', 'Marmara ve Ege daha gelişmiştir.\nUlaşım, yatırım ve sanayi birikimi doğu ve güneydoğuda daha zayıftır.'],
      ['GAP’ın kapsamı', 'Güneydoğu Anadolu Projesi, Fırat ve Dicle havzasında sulama ve enerji amaçlı kurulmuştur.\nAdıyaman, Batman, Diyarbakır, Gaziantep, Kilis, Mardin, Siirt, Şanlıurfa ve Şırnak’ı içerir.'],
      ['GAP’ın tarıma etkisi', 'Atatürk Barajı ve Şanlıurfa Tüneli, Harran Ovası’nı sulamaya açtı.\nKuru tarımdan sulu tarıma geçildi; pamuk üretimi arttı.'],
      ['GAP’ın sosyal etkisi', 'Tarıma dayalı sanayi, istihdam ve enerji üretimi arttı.\nBaraj gölleri Hasankeyf gibi tarihî alanları su altında bıraktı.'],
      ['DAP', 'Doğu Anadolu Projesi, hayvancılık, kırsal altyapı ve turizm gibi alanlarda geliştirme hedefler.\nİklim ve yükselti nedeniyle tarım sınırlıdır.'],
      ['KOP ve DOKAP', 'KOP, Konya Kapalı Havzası’nda tarım ve su yönetimine odaklanır.\nDOKAP ise Doğu Karadeniz’de ormancılık, balıkçılık ve yayla turizmini destekler.'],
      ['Etki değerlendirmesi', 'Proje dört yönden tartılır:\n- **Ekonomik:** gelir ve istihdam\n- **Sosyal:** göç ve eğitim\n- **Kültürel:** tarihî alanlar\n- **Çevresel:** iklim ve ekosistem'],
    ],
    not: 'Projeyi değerlendirirken önce kazananı, sonra kaybedeni sor: baraj ovayı suladı ama Hasankeyf’i su altında bıraktı.',
    notKarti: 5,
    iddialar: [
      ['GAP, Fırat ve Dicle havzasında sulama ve enerji amaçlı bir projedir.', true, 'GAP bu iki akarsu havzasının kaynaklarını kullanır.'],
      ['Şanlıurfa Tüneli, Harran Ovası’nın sulanmasında etkili olmuştur.', true, 'Atatürk Barajı suyunu ovaya taşır.'],
      ['GAP kapsamındaki baraj gölleri hiçbir tarihî alanı etkilememiştir.', false, 'Hasankeyf gibi alanlar baraj gölü altında kalmıştır.'],
      ['DOKAP, Konya Kapalı Havzası’nın tarımsal kalkınmasını hedefler.', false, 'Konya Havzası’na odaklanan KOP’tur; DOKAP Doğu Karadeniz içindir.'],
      ['Bölgesel kalkınma projeleri gelişmişlik farkını azaltmayı hedefler.', true, 'Amaç bölgeler arası dengedir.'],
      ['GAP yalnızca Karadeniz kıyısını kapsar.', false, 'GAP, Güneydoğu Anadolu’da Fırat ve Dicle havzasındadır.'],
    ],
    secimler: [
      ['Fırat ve Dicle üzerindeki kalkınma projesi?', 'GAP', 'DOKAP', 'GAP: Güneydoğu Anadolu Projesi.'],
      ['Doğu Karadeniz’i kapsayan proje?', 'DOKAP', 'KOP', 'Doğu Karadeniz Projesi.'],
      ['GAP’ta sulamayla artan ürün?', 'Pamuk', 'Çay', 'Harran’da pamuk üretimi arttı.'],
      ['Konya Havzası’nda tarım ve su yönetimini hedefleyen proje?', 'KOP', 'DAP', 'KOP: Konya Ovası Projesi.'],
    ],
    kontroller: [['GAP hangi akarsu havzasındadır?', 'Fırat ve Dicle', 'Kızılırmak', 'GAP Fırat–Dicle havzasındadır.', 3]],
  }),
]
