import { cografya12Konusu } from './12-cografya-yardimci'

/** 12. sınıf Coğrafya, 3. ünite: Küresel Ortam: Bölgeler ve Ülkeler (2018 programı 12.3.1-12.3.11). */
export const cografya12Kuresel = [
  cografya12Konusu({
    id: 'cog12-kita-okyanus',
    ad: 'Kıta ve Okyanusların Değişen Önemi',
    kartlar: [
      ['Konumsal önem', 'Bir kıta ya da okyanusun önemi; ticaret yolu, kaynak ve güç dengesindeki yerine bağlıdır.\nBu yer zamanla değişir.'],
      ['Akdeniz çağı', 'Antik çağ ve Orta Çağ’da uygarlıklar Akdeniz çevresinde toplandı.\nRoma, Venedik ve Cenova ticaret ve siyaseti buradan yönetti.'],
      ['Atlantik’in yükselişi', 'Coğrafi keşifler (Kolomb, 1492) Atlantik’i yeni merkez yaptı.\nSömürge ticareti Avrupa ve Amerika kıyılarını zenginleştirdi.'],
      ['Sanayi Devrimi’nden sonra', '18. ve 19. yüzyılda Avrupa sanayi, ticaret ve donanma gücüyle dünya ekonomisinin merkeziydi.\nHammadde sömürgelerden gelirdi.'],
      ['Pasifik’in yükselişi', '20. yüzyılın sonunda Japonya, Güney Kore ve Çin’in büyümesi Pasifik çevresini ticaretin merkezi yaptı.\nDoğu Asya ağırlık kazandı.'],
      ['Hint Okyanusu', 'Basra Körfezi petrolü Hint Okyanusu ve Malakka Boğazı üzerinden Doğu Asya’ya taşınır.\nBu yol dünya enerji ticaretinin ana damarıdır.'],
      ['Kuzey Kutbu', 'Buzulların erimesi Kuzey Kutbu’nda yeni deniz rotaları açıyor.\nKaynak ve yol rekabeti artıyor.'],
      ['Antarktika', 'Antarktika Antlaşması (1959) kıtayı bilimsel faaliyete ayırır, askerî kullanımı yasaklar.\nKıta hiçbir ülkenin egemenliğinde değildir.'],
    ],
    not: 'Önem sabit değildir: her çağda kıtanın yeri ulaşım teknolojisi, kaynak ve ticaret yoluna göre yeniden yazılır.',
    notKarti: 1,
    iddialar: [
      ['Coğrafi keşiflerle Atlantik, ticaret ve siyasette öne çıktı.', true, 'Yeni Dünya’ya açılan yollar Atlantik çevresini zenginleştirdi.'],
      ['Kıtaların ve okyanusların konumsal önemi her çağda aynı kalmıştır.', false, 'Önem ulaşım, kaynak ve güç dengesine göre değişir.'],
      ['20. yüzyılın sonunda Doğu Asya ekonomilerinin yükselişi Pasifik’in önemini artırdı.', true, 'Pasifik çevresi ticaret hacminde öne çıktı.'],
      ['Basra Körfezi petrolü Malakka Boğazı üzerinden yalnızca Atlantik’e taşınır.', false, 'Petrol Hint Okyanusu ve Malakka’dan Doğu Asya’ya akar.'],
      ['Antarktika Antlaşması kıtayı askerî amaçla kullanıma açar.', false, 'Antlaşma bilimsel faaliyete ayırır, askerî kullanımı yasaklar.'],
      ['Kuzey Kutbu’nda buzulların erimesi yeni deniz rotalarını gündeme getirir.', true, 'Buz azalınca gemi geçişi kolaylaşır.'],
    ],
    secimler: [
      ['Kolomb’un Amerika yolculuğu hangi yılda?', '1492', '1071', 'Coğrafi keşifler 1492’de başladı.'],
      ['Basra petrolünü Doğu Asya’ya taşıyan boğaz?', 'Malakka', 'Çanakkale', 'Malakka Hint Okyanusu ile Pasifik’i bağlar.'],
      ['Antlaşmayla bilime ayrılan kıta?', 'Antarktika', 'Avustralya', 'Antarktika Antlaşması 1959’dadır.'],
      ['20. yüzyıl sonu ağırlık kazanan çevre?', 'Pasifik', 'Akdeniz', 'Doğu Asya büyümesi Pasifik’i öne çıkardı.'],
    ],
    kontroller: [['Atlantik’i öne çıkaran gelişme neydi?', 'Coğrafi keşifler', 'Süveyş Kanalı', 'Yeni Dünya’ya ulaşan yollar Atlantik’i merkez yaptı.', 3]],
  }),
  cografya12Konusu({
    id: 'cog12-konum-etki',
    ad: 'Ülkelerin Konumunun Bölgesel ve Küresel Etkisi',
    kartlar: [
      ['Matematik ve özel konum', 'Matematik konum enlem ve boylamla belirlenir.\nÖzel konum komşular, denizler, boğaz, kanal ve yarımada gibi özelliklerle belirlenir.'],
      ['Boğaz ve kanal ülkeleri', 'Mısır (Süveyş), Panama ve Singapur (Malakka) geçiş yolunu denetler.\nTürkiye, Boğazlar sayesinde Karadeniz’le Akdeniz arasındaki yoldadır.'],
      ['Denize kıyısı olmayan ülkeler', 'İsviçre, Nepal ve Bolivya gibi ülkelerin denize kıyısı yoktur.\nKomşuların limanlarını kullanırlar.'],
      ['Ada ve yarımada ülkeleri', 'Japonya ve Yeni Zelanda ada ülkeleridir; kara sınırları yoktur.\nDeniz yolları ve donanma ticaret ve savunmada belirleyicidir.'],
      ['Komşuluk', 'Çin ve Rusya çok sayıda komşuya sahiptir.\nÇok komşulu ülke fırsat da risk de yaşar: ticaret yolları açık, sınır güvenliği zordur.'],
      ['Geçiş ve tampon ülkeler', 'Büyük güçlerin arasında kalan ülkeler geçiş ya da tampon bölge olur.\nOrta Asya bunun örneğidir.'],
      ['Küresel etki', 'Konum, ülkenin ticaretini, gücünü ve ittifaklarını etkiler.\nKüresel güçler stratejik konumlara üs ve ağ kurar.'],
      ['Konum değişkendir', 'Kanal, havacılık ve uydu gibi teknolojiler bir konumun değerini değiştirir.\nSüveyş 1869’da Mısır’ın önemini artırdı.'],
    ],
    not: 'Konumu yalnızca “nerede?” diye değil, “kimin yolunun üzerinde?” diye de sor; etki buradan doğar.',
    notKarti: 1,
    iddialar: [
      ['Süveyş Kanalı Mısır’ın konumsal önemini artırmıştır.', true, 'Mısır Akdeniz-Kızıldeniz geçişini denetler.'],
      ['Denize kıyısı olmayan ülkeler dış ticarette komşuların limanlarına bağımlı olabilir.', true, 'Mallar komşu limanlardan geçer.'],
      ['Singapur konumu Malakka Boğazı’nın yakınında önemli bir geçiş noktasıdır.', true, 'Asya-Avrupa deniz yolu üzerindedir.'],
      ['Ada ülkelerinde deniz yolları ve donanma ticaret ile savunmada önemsizdir.', false, 'Japonya gibi ada ülkeleri için deniz yolları ve donanma belirleyicidir.'],
      ['Bir ülkenin konumsal değeri teknoloji değişse bile asla değişmez.', false, 'Kanal ve ulaşım teknolojisi değeri değiştirir.'],
      ['Nepal doğrudan okyanusa kıyısı olan bir ülkedir.', false, 'Nepal denize kıyısı olmayan, kara ile çevrili bir ülkedir.'],
    ],
    secimler: [
      ['Panama Kanalı hangi okyanusları bağlar?', 'Atlantik-Pasifik', 'Hint-Pasifik', 'Panama iki okyanusu bağlar.'],
      ['Enlem-boylamla bulunan konum?', 'Matematik konum', 'Özel konum', 'Koordinat matematik konumu verir.'],
      ['Kara ile çevrili ülke hangisi?', 'İsviçre', 'Japonya', 'İsviçre’nin denize kıyısı yoktur.'],
      ['Büyük güçlerin arasında kalan ülke?', 'Tampon ülke', 'Ada ülkesi', 'Güçler arasında geçiş ve denge alanı olur.'],
    ],
    kontroller: [['Özel konuma hangisi örnektir?', 'Boğaz üzerinde olmak', 'Enlem değeri', 'Boğaz, kanal ve komşuluk özel konum özelliğidir.', 1]],
  }),
  cografya12Konusu({
    id: 'cog12-turkiye-jeopolitik',
    ad: 'Türkiye’nin Tarihsel Jeopolitik Konumu',
    kartlar: [
      ['Jeopolitik nedir?', 'Coğrafi konumun devletlerin dış politikasına ve güç dengesine etkisidir.\nKonumun getirdiği fırsat ve riskleri birlikte inceler.'],
      ['Konumun özellikleri', 'Türkiye Asya, Avrupa ve Afrika’nın kavşağındadır.\nÜç yanı denizle çevrili, Boğazlar bölgenin kapısıdır.'],
      ['Osmanlı döneminde', 'Osmanlı Devleti üç kıtada egemen oldu.\nKaradeniz ve Akdeniz ticareti ile Baharat ve İpek Yolu’nun kavşağını elinde tuttu.'],
      ['Montrö (1936)', 'Boğazlardan geçiş Montrö Sözleşmesi’yle düzenlendi.\nSözleşme Türkiye’nin Boğazlardaki egemenlik ve askerî denetim hakkını yeniden tanıdı.'],
      ['Soğuk Savaş', 'Sovyet tehdidine karşı Türkiye ABD’nin Truman Doktrini yardımını aldı (1947) ve NATO’ya katıldı (1952).\nDoğu Bloku’nu çevreleyen kuşakta yer aldı.'],
      ['Soğuk Savaş sonrası', 'SSCB’nin dağılması (1991) Kafkasya ve Orta Asya’yı açtı.\nTürkiye Türk cumhuriyetleriyle yeni ilişkiler kurdu.'],
      ['Kalpgâh ve Kenar Kuşak', 'Mackinder Avrasya’nın iç kısmına Kalpgâh (Heartland), Spykman çevresine Kenar Kuşak (Rimland) dedi.\nTürkiye Kenar Kuşak üzerindedir.'],
      ['Köprü ve enerji koridoru', 'Türkiye doğu-batı ve kuzey-güney ulaşım ağlarının kesişiminde yer alır.\nHazar ve Orta Doğu enerjisini Avrupa’ya bağlayan koridordur.'],
    ],
    not: 'Her dönemi bir cümleyle bağla: Osmanlı = kavşak, Montrö = Boğazlar, Soğuk Savaş = NATO, 1991 sonrası = yeni açılım.',
    notKarti: 4,
    iddialar: [
      ['Boğazlardan geçiş rejimi 1936 Montrö Sözleşmesi ile düzenlenmiştir.', true, 'Montrö, Türkiye’nin Boğazlar üzerindeki denetimini belirler.'],
      ['Türkiye NATO’ya 1952’de katılmıştır.', true, 'Soğuk Savaş’ın ilk yıllarında üye oldu.'],
      ['Spykman’a göre Türkiye Kalpgâh bölgesindedir.', false, 'Türkiye Kenar Kuşak (Rimland) üzerindedir; Kalpgâh Avrasya’nın iç kısmıdır.'],
      ['Soğuk Savaş’ta Türkiye Sovyetler Birliği çevresindeki kuşakta yer almıştır.', true, 'NATO’nun güneydoğu kanadında yer aldı.'],
      ['SSCB’nin dağılması Türkiye’nin Orta Asya ile ilişkilerini azalttı.', false, 'Yeni bağımsız Türk cumhuriyetleriyle ilişkiler arttı.'],
      ['Truman Doktrini 1947’de Türkiye ve Yunanistan’a yardım içerir.', true, 'ABD Sovyet etkisine karşı iki ülkeye yardım etti.'],
    ],
    secimler: [
      ['Boğazlar rejimini düzenleyen sözleşme?', 'Montrö', 'Lozan', 'Montrö Boğazlar Sözleşmesi 1936’dır.'],
      ['Türkiye hangi askerî ittifaka 1952’de girdi?', 'NATO', 'Varşova Paktı', 'NATO’ya 1952’de katıldı.'],
      ['Kenar Kuşak teorisini ortaya koyan?', 'Spykman', 'Mackinder', 'Mackinder Kalpgâh’ı ortaya attı.'],
      ['SSCB’nin dağıldığı yıl?', '1991', '1947', '1991’de dağıldı.'],
    ],
    kontroller: [['Boğazlardan geçişi hangi sözleşme düzenler?', 'Montrö', 'Lozan', 'Montrö (1936) Boğazlar rejimini belirler.', 4]],
  }),
  cografya12Konusu({
    id: 'cog12-jeopolitik-bolge',
    ad: 'Türkiye ve Yakın Jeopolitik Bölgeler',
    kartlar: [
      ['Jeopolitik bölge', 'Konum, kaynak, tarih ve güç ilişkileriyle öne çıkan bölgedir.\nTürkiye birden fazla bölgenin kesişiminde yer alır.'],
      ['Balkanlar', 'Osmanlı mirası ve Türk topluluklarıyla bağ vardır.\nTürkiye için Avrupa’ya açılan kapı ve göç yoludur.'],
      ['Kafkasya', 'Karadeniz ve Hazar arasında enerji ve ulaşım koridorudur.\nBakü-Tiflis-Ceyhan hattı ve Bakü-Tiflis-Kars demiryolu buradan geçer.'],
      ['Orta Doğu', 'Dünya petrol ve doğal gaz rezervlerinin önemli bölümü buradadır.\nÇatışmalar Türkiye’ye göç ve güvenlik sorunu getirdi.'],
      ['Karadeniz', 'Karadeniz Ekonomik İşbirliği Örgütü (KEİ) 1992’de kuruldu.\nBoğazlar bölgenin açık denizlere çıkışıdır.'],
      ['Doğu Akdeniz', 'Doğal gaz yatakları ve deniz yetki alanları bölgenin gündemini belirler.\nEnerji ve ulaşım güzergâhı rekabet alanıdır.'],
      ['Orta Asya ve Türk dünyası', 'Tarihî ve kültürel bağlar vardır.\nOrta Koridor ve enerji hatlarıyla ekonomik ilişkiler güçlenir.'],
      ['Avrupa', 'Türkiye AB’yle Gümrük Birliği (1996) yaptı, adaylık statüsü 1999’da, müzakereler 2005’te başladı.\nAB en büyük ticaret ortağıdır.'],
    ],
    not: 'Bölgeyi iki kelimeyle bağla: Balkanlar = kapı, Kafkasya = koridor, Orta Doğu = enerji ve sorun, Karadeniz = Boğazlar.',
    notKarti: 1,
    iddialar: [
      ['Kafkasya, enerji ve ulaşım koridoru olarak öne çıkar.', true, 'BTC ve BTK hatları Kafkasya’dan geçer.'],
      ['Karadeniz Ekonomik İşbirliği Örgütü 1992’de kuruldu.', true, 'Karadeniz çevresi ülkeleri arasında ekonomik iş birliği içindir.'],
      ['Orta Doğu’da dünya petrol rezervlerinin çok az bir kısmı bulunur.', false, 'Petrol rezervlerinin önemli bölümü Orta Doğu’dadır.'],
      ['Türkiye ile AB arasında Gümrük Birliği 1996’da yürürlüğe girmiştir.', true, 'AB Türkiye’nin en büyük ticaret ortağıdır.'],
      ['Balkanlar Türkiye için Avrupa’ya açılan bir kapı değildir.', false, 'Balkanlar Türkiye’yi Avrupa’ya karadan bağlar.'],
      ['Türkiye’ye AB adaylık statüsü 1999’da verilmiştir.', true, '1999 Helsinki’de aday ülke olarak kabul edildi.'],
    ],
    secimler: [
      ['KEİ hangi denizin çevresinde kuruldu?', 'Karadeniz', 'Ege', 'Karadeniz Ekonomik İşbirliği Örgütü.'],
      ['Enerji koridoru olarak öne çıkan bölge?', 'Kafkasya', 'Antarktika', 'Hazar enerjisini batıya taşıyan hatlar buradan geçer.'],
      ['Türkiye’nin en büyük ticaret ortağı hangisi?', 'AB', 'ASEAN', 'Dış ticaretin çoğu AB ile yapılır.'],
      ['Türkiye’yi karadan Avrupa’ya bağlayan bölge?', 'Balkanlar', 'Kafkasya', 'Trakya üzerinden Balkanlara açılır.'],
    ],
    kontroller: [['Dünya petrol ve gazının önemli kısmı hangi bölgede?', 'Orta Doğu', 'Balkanlar', 'Büyük rezervler Orta Doğu’dadır.', 4]],
  }),
  cografya12Konusu({
    id: 'cog12-turk-kultur-bolge',
    ad: 'Türk Kültür Bölgeleri ve Türkiye',
    kartlar: [
      ['Türk kültür bölgeleri', 'Başlıca bölgeler: Türkistan (Orta Asya), Azerbaycan ve Kafkasya, Kırım, İdil-Ural ve Balkanlar.\nHer birinde ortak miras vardır.'],
      ['Tarihî bağ', 'Türkler Orta Asya’dan batıya göçtü.\n1071 Malazgirt Zaferi ile Anadolu’nun kapıları Türklere açıldı.'],
      ['Ortak dil', 'Türk dilleri ailesi geniş bir coğrafyada konuşulur.\nTürkiye Türkçesi, Azerbaycan Türkçesi ve Türkmence birbirine yakındır.'],
      ['Ortak kültür', 'Nevruz (21 Mart) UNESCO listesindedir (2009).\nDede Korkut Destanı Azerbaycan, Kazakistan ve Türkiye’nin ortak mirasıdır.'],
      ['İş birliği kurumları', 'TİKA (1992) kalkınma yardımı yapar; TÜRKSOY (1993) kültür iş birliği için kuruldu.\nTürk Konseyi 2021’de Türk Devletleri Teşkilatı adını aldı.'],
      ['Eğitim bağı', 'Hoca Ahmet Yesevi Uluslararası Kazak-Türk Üniversitesi Kazakistan’ın Türkistan kentindedir.\nÖğrenci değişimi ve burslar kültürel bağı güçlendirir.'],
      ['Diaspora', 'Balkanlar ve Batı Avrupa’da yaşayan Türk toplulukları kültürü bu bölgelerde sürdürür.\nAlmanya en büyük Türk nüfusunun yaşadığı yabancı ülkedir.'],
      ['Coğrafi sınırlar', 'Hazar’ın ve dağların ulaşımı zorlaştırdığı yerler vardır.\nOrta Koridor ve demiryolu hatları kültürel ve ekonomik bağı güçlendirir.'],
    ],
    not: 'Bağları üç başlıkta topla: tarih (Malazgirt), dil ve kültür (Nevruz, Dede Korkut), kurum (TİKA, TÜRKSOY, TDT).',
    notKarti: 5,
    iddialar: [
      ['Nevruz UNESCO Somut Olmayan Kültürel Miras listesine alınmıştır.', true, 'Çok sayıda Türk ve komşu topluluğun ortak bayramıdır.'],
      ['TÜRKSOY, Türk dünyasında kültür iş birliği için kurulmuş bir kuruluştur.', true, '1993’te kuruldu.'],
      ['TİKA Türk Devletleri Teşkilatı’nın eski adıdır.', false, 'TİKA bir kalkınma ve iş birliği ajansıdır; teşkilatın eski adı Türk Konseyi’dir.'],
      ['1071 Malazgirt Zaferi Anadolu’nun Türklere açılmasında bir dönüm noktasıdır.', true, 'Selçuklular Bizans’ı yendi.'],
      ['Türk dilleri yalnızca Anadolu’da konuşulur.', false, 'Orta Asya, Kafkasya ve Balkanlar’da da konuşulur.'],
      ['Dede Korkut Destanı yalnızca Türkiye’nin mirasıdır.', false, 'Azerbaycan ve Kazakistan’la ortak mirastır.'],
    ],
    secimler: [
      ['Malazgirt Zaferi hangi yılda?', '1071', '1453', 'Anadolu’nun kapılarını açtı.'],
      ['Nevruz hangi tarihte kutlanır?', '21 Mart', '1 Mayıs', 'Baharın başlangıcıdır.'],
      ['Türk kültür iş birliği kuruluşu?', 'TÜRKSOY', 'OPEC', 'OPEC petrol ihraç eden ülkeler birliğidir.'],
      ['Türk Konseyi 2021’de hangi adı aldı?', 'Türk Devletleri Teşkilatı', 'Türk Parlamentosu', 'Teşkilat adı 2021’de değişti.'],
    ],
    kontroller: [['Anadolu’nun kapıları hangi savaşla açıldı?', 'Malazgirt', 'Çaldıran', 'Malazgirt 1071’dedir.', 2]],
  }),
  cografya12Konusu({
    id: 'cog12-teknoloji-etkilesim',
    ad: 'Teknoloji ve Küresel Etkileşim',
    kartlar: [
      ['Mesafe kısalır', 'İletişim uyduları, fiber kablo, internet ve uçak, uzaklığı zaman ve maliyet açısından küçültür.\nİşlem ve haber saniyeler içinde dolaşır.'],
      ['İletişim', 'İnternet ve sosyal medya fikir, haber ve moda yayılmasını hızlandırır.\nUzaktan eğitim ve çalışma sınırsız hale gelir.'],
      ['Ulaşım', 'Konteyner, hızlı tren ve havayolu, malların ve kişilerin dolaşımını kolaylaştırır.\nÜretim ve pazar arasındaki mesafe kısalır.'],
      ['Küresel üretim zinciri', 'Bir ürünün tasarımı, parçası ve montajı farklı ülkelerde yapılabilir.\nBir bölgedeki sorun bütün zinciri aksatır.'],
      ['Kültürel etkileşim', 'Dizi, müzik, yemek ve spor küresel dolaşıma girer.\nBirçok kültür birbirinden etkilenir; yerel kültürün korunması da gündeme gelir.'],
      ['Dijital ekonomi', 'E-ticaret, dijital ödeme ve bulut hizmetleri yeni pazarlar açar.\nKüçük işletmeler dünya pazarına erişir.'],
      ['Sayısal uçurum', 'İnternet ve teknoloji erişimi ülkeler ve kır-kent arasında eşit değildir.\nErişemeyenler fırsatlardan geri kalır.'],
      ['Karşılıklı bağımlılık', 'Teknoloji ekonomileri birbirine bağlar.\n2008 küresel krizi bir ülkeden başlayıp dünyaya yayıldı.'],
    ],
    not: 'Teknolojiyi “hız ve bağlantı” diye oku; ama ilk soru hep şu: kimin erişimi var, kimin yok?',
    notKarti: 7,
    iddialar: [
      ['İnternet, bilgi ve kültürün ülkeler arasında hızla yayılmasını sağlar.', true, 'İletişim teknolojisi etkileşimi hızlandırır.'],
      ['Küresel üretim zincirinde bir ürünün tüm parçaları aynı ülkede üretilir.', false, 'Parçalar genellikle farklı ülkelerde üretilir.'],
      ['Sayısal uçurum, internet erişimindeki eşitsizliği anlatır.', true, 'Ülkeler ve kır-kent arasında erişim farkı vardır.'],
      ['2008 küresel krizi, ekonomilerin birbirine bağlı olduğunu gösterdi.', true, 'Bir ülkeden başlayıp dünyaya yayıldı.'],
      ['Teknoloji ülkeler arasındaki kültürel etkileşimi azaltır.', false, 'Etkileşim iletişim teknolojisiyle artar.'],
      ['E-ticaret küçük işletmelerin dünya pazarına erişmesini zorlaştırır.', false, 'E-ticaret erişimi kolaylaştırır.'],
    ],
    secimler: [
      ['Ülkeler arasındaki internet erişim farkına ne denir?', 'Sayısal uçurum', 'Demografik geçiş', 'Teknolojiye erişim eşitsizliğidir.'],
      ['Ürünün parçalarının farklı ülkelerde üretilmesi?', 'Küresel üretim zinciri', 'Yerel üretim', 'Zincir farklı ülkelere yayılır.'],
      ['Küresel krizin yayılma nedeni?', 'Karşılıklı bağımlılık', 'Yalıtım', 'Ekonomiler birbirine bağlıdır.'],
      ['Malları kolay taşıyan standart kutu?', 'Konteyner', 'Boru hattı', 'Konteyner yükü standartlaştırdı.'],
    ],
    kontroller: [['Uzaktan çalışma hangi teknolojinin sonucu?', 'İletişim', 'Madencilik', 'İnternet mesafeyi kısaltır.', 2]],
  }),
  cografya12Konusu({
    id: 'cog12-gelismislik',
    ad: 'Gelişmişlik Düzeyi ve Ülke Grupları',
    kartlar: [
      ['Göstergeler', 'Kişi başına gelir, bebek ölüm hızı, okuryazarlık, yaşam beklentisi ve internet erişimi gelişmişliği ölçer.\nTek gösterge yeterli değildir.'],
      ['İnsani Gelişme Endeksi', 'İGE (HDI), BM Kalkınma Programı tarafından hesaplanır.\nSağlık (yaşam beklentisi), eğitim ve gelir olmak üzere üç boyutu içerir.'],
      ['Etkili faktörler', 'Doğal kaynak, sanayileşme, eğitim, siyasi istikrar ve konum etkilidir.\nTarihsel süreçte sömürge geçmişi de belirleyici olabilir.'],
      ['Gelişmiş ülkeler', 'Kişi başına gelir yüksek, hizmet ve bilgi ağırlıklıdır.\nNüfus artışı yavaştır, nüfus yaşlıdır, teknoloji ihraç edilir.'],
      ['Gelişmekte olan ülkeler', 'Tarım ve hammadde payı büyük olabilir, nüfus gençtir.\nDış borç ve dışa bağımlılık sorun olabilir.'],
      ['Karşılaştırma', 'Gelişmiş ülkelerde bebek ölümü az, kentleşme ve eğitim düzeyi yüksektir.\nGelişmekte olanlarda bu göstergeler daha zayıftır.', { tur: 'tablo', basliklar: ['Gösterge', 'Gelişmiş', 'Gelişmekte olan'], satirlar: [['Nüfus', 'Yaşlı', 'Genç'], ['Ekonomi', 'Hizmet ağırlıklı', 'Tarım/hammadde'], ['Bebek ölümü', 'Az', 'Fazla']] }],
      ['Orta gelirli ülkeler', 'Türkiye, G20 üyesi bir gelişmekte olan ekonomidir.\nSanayi ve hizmetlerin payı artmakta, kişi başına gelir yükselmektedir.'],
      ['Kuzey-Güney ayrımı', 'Gelişmiş ülkelerin çoğu kuzeyde, gelişmekte olanlar güneyde toplanır.\nAvustralya ve Yeni Zelanda güneyde yer alan gelişmiş ülkelerdir.'],
    ],
    not: 'Gelişmişliği tek sayıya indirme; İGE gibi göstergeler gelir, sağlık ve eğitimi birlikte tartar.',
    notKarti: 2,
    iddialar: [
      ['İnsani Gelişme Endeksi sağlık, eğitim ve gelir boyutlarını içerir.', true, 'Üç boyut birlikte değerlendirilir.'],
      ['İGE yalnızca kişi başına gelire bakar.', false, 'Sağlık ve eğitim de hesaba katılır.'],
      ['Gelişmiş ülkelerde nüfus artış hızı genellikle düşüktür.', true, 'Doğum ve ölüm hızları düşüktür; nüfus yaşlıdır.'],
      ['Gelişmekte olan ülkelerde ekonomi her zaman yalnızca hizmete dayanır.', false, 'Tarım ve hammadde payı büyük olabilir.'],
      ['Avustralya güney yarım kürede yer alan gelişmiş bir ülkedir.', true, 'Kuzey-Güney ayrımının istisnasıdır.'],
      ['Sömürge geçmişi bir ülkenin gelişmişliğini hiçbir şekilde etkilemez.', false, 'Tarihî süreç ekonomik yapıyı belirleyebilir.'],
    ],
    secimler: [
      ['İGE’yi hesaplayan kuruluş?', 'BM Kalkınma Programı', 'OPEC', 'UNDP hesaplar.'],
      ['Gelişmiş ülkelerde nüfus yapısı?', 'Yaşlı', 'Genç', 'Doğum hızı düşüktür.'],
      ['G20 üyesi bir gelişmekte olan ekonomi?', 'Türkiye', 'Nepal', 'Türkiye G20 üyesidir.'],
      ['Bebek ölüm hızı hangi alanın göstergesidir?', 'Sağlık', 'Ulaşım', 'Sağlık hizmetinin düzeyini gösterir.'],
    ],
    kontroller: [['İGE hangi boyutlardan oluşur?', 'Sağlık, eğitim, gelir', 'Nüfus, alan, iklim', 'Üç boyutu vardır.', 2]],
  }),
  cografya12Konusu({
    id: 'cog12-kaynak-iliski',
    ad: 'Doğal Kaynaklar ve Ülkeler Arası İlişkiler',
    kartlar: [
      ['Kaynak potansiyeli', 'Petrol, doğal gaz, maden, su ve verimli toprak ülkelerin gücünü ve ilişkilerini etkiler.\nKaynak zenginliği otomatik refah demek değildir.'],
      ['Orta Doğu ve OPEC', 'Orta Doğu’da dünya petrol rezervlerinin büyük bölümü bulunur.\nOPEC 1960’ta Bağdat’ta kuruldu.'],
      ['Rusya ve Avrupa', 'Rusya, doğal gaz ve petrol ihracatçısıdır.\nAvrupa’nın enerji ihtiyacında Rus gazına bağlılık siyasi ilişkileri etkiledi.'],
      ['Kritik madenler', '- **Lityum:** Şili, Arjantin, Bolivya\n- **Kobalt:** Kongo Demokratik Cumhuriyeti\n- **Nadir toprak elementleri:** Çin'],
      ['Bor', 'Dünya bor rezervlerinin büyük bölümü Türkiye’dedir.\nBor, cam, seramik, tarım ve enerji sanayisinde kullanılır.'],
      ['Sınır aşan sular', 'Fırat ve Dicle Türkiye, Suriye ve Irak’ı; Nil Mısır, Sudan ve Etiyopya’yı ilgilendirir.\nBaraj yapımı anlaşmazlık konusu olabilir.'],
      ['Kaynak bağımlılığı', 'Tek ürüne dayalı ihracat fiyat dalgalanmasında ekonomiyi sarsar.\nÇeşitlendirme gerekir.'],
      ['Enerji güvenliği', 'İthalatçı ülkeler tedarikçilerini ve güzergâhlarını çeşitlendirmeye çalışır.\nİş birliği de rekabet de ilişkileri belirler.'],
    ],
    not: 'Kaynağı üç soruyla oku: nerede, kime satılıyor, hangi yoldan gidiyor? İlişkinin düğümü genelde güzergâhta.',
    notKarti: 4,
    iddialar: [
      ['OPEC 1960’ta Bağdat’ta kurulmuştur.', true, 'Petrol ihraç eden ülkeler örgütüdür.'],
      ['Dünya bor rezervlerinin büyük bölümü Türkiye’dedir.', true, 'Bor Türkiye’nin stratejik madenlerinden biridir.'],
      ['Nadir toprak elementleri üretiminde Güney Amerika öne çıkar.', false, 'Çin nadir toprak elementlerinde öne çıkar.'],
      ['Fırat ve Dicle Türkiye, Suriye ve Irak arasında sınır aşan sulardır.', true, 'Üç ülke bu akarsulardan yararlanır.'],
      ['Doğal kaynak zenginliği her zaman ekonomik refaha dönüşür.', false, 'Bağımlılık ve fiyat dalgalanması riski vardır.'],
      ['Enerji ithalatçıları tedarik çeşitlendirmesine gitmeye çalışır.', true, 'Tek tedarikçiye bağımlılık riski taşır.'],
    ],
    secimler: [
      ['Lityum rezervleriyle öne çıkan ülke?', 'Şili', 'Norveç', 'Şili, Arjantin ve Bolivya lityum üçgenidir.'],
      ['Kobaltta öne çıkan ülke?', 'Kongo Demokratik Cumhuriyeti', 'Japonya', 'Kobalt üretimi Kongo’da yoğundur.'],
      ['Bor rezervi bakımından öne çıkan ülke?', 'Türkiye', 'İsviçre', 'Bor Türkiye’nin stratejik madenidir.'],
      ['Nil Nehri hangi ülkeleri ilgilendirir?', 'Mısır, Sudan, Etiyopya', 'Türkiye, Irak', 'Fırat-Dicle Türkiye, Suriye, Irak arasındadır.'],
    ],
    kontroller: [['OPEC kaç yılında kuruldu?', '1960', '1991', '1960’ta Bağdat’ta kuruldu.', 2]],
  }),
  cografya12Konusu({
    id: 'cog12-enerji-hatlari',
    ad: 'Enerji Nakil Hatları ve Etkileri',
    kartlar: [
      ['Neden nakil hattı?', 'Kaynak ülke ile tüketici ülke genellikle ayrıdır.\nBoru hattı, tanker ve LNG gemisi enerjiyi taşır.'],
      ['Ham petrol hatları', 'Bakü-Tiflis-Ceyhan (BTC, 2006), Azerbaycan petrolünü Gürcistan üzerinden Ceyhan’a taşır.\nKerkük-Yumurtalık hattı Irak petrolünü Türkiye’ye ulaştırmak için 1970’lerde kuruldu.'],
      ['Doğal gaz hatları', '- **Mavi Akım (2003):** Rusya’dan Karadeniz tabanı üzerinden Samsun’a\n- **TürkAkım (2020):** Rusya’dan Karadeniz tabanı üzerinden Trakya’ya\n- **TANAP (2018):** Azerbaycan gazını Türkiye üzerinden Avrupa’ya'],
      ['Türkiye’nin rolü', 'Türkiye Hazar ve Orta Doğu enerjisini Avrupa’ya bağlayan bir koridor ve terminaldir.\nCeyhan petrol terminali bu rolün parçasıdır.'],
      ['Rusya-Avrupa', 'Dostluk (Druzhba) petrol boru hattı Rusya’yı Doğu ve Orta Avrupa’ya bağlar.\nKuzey Akım Rusya’yı Baltık tabanından Almanya’ya bağlıyordu.'],
      ['Boğazlar ve tanker', 'İstanbul Boğazı’ndan çok sayıda tanker geçer; dar geçit kaza ve çevre riski taşır.\nAlternatif boru hatları bu riski azaltır.'],
      ['Enerji deniz yolları', 'Hürmüz (Basra Körfezi çıkışı), Malakka, Süveyş ve Babülmendep petrol akışında kritik geçitlerdir.\nBuralardaki kesinti fiyatları etkiler.'],
      ['Etkileri', 'Geçiş ücreti, siyasi etki ve tedarik güvenliği oluşur.\nHat çeşitlendirmesi ülkelerin bağımlılığını azaltır.'],
    ],
    not: 'Hatları “başlangıç, bitiş, geçiş ülkesi” üçlüsüyle öğren; sorular genelde bunlardan birini değiştirir.',
    notKarti: 3,
    iddialar: [
      ['Bakü-Tiflis-Ceyhan hattı Azerbaycan petrolünü Türkiye’ye taşır.', true, 'Gürcistan’dan geçerek Ceyhan’a ulaşır.'],
      ['TANAP Rusya gazını Türkiye üzerinden Avrupa’ya taşır.', false, 'TANAP Azerbaycan gazını Türkiye üzerinden Avrupa’ya taşır.'],
      ['TürkAkım Rusya’yı Karadeniz tabanından Trakya’ya bağlar.', true, 'Rusya gazı Türkiye’ye ve Avrupa’ya ulaşır.'],
      ['Hürmüz Boğazı Basra Körfezi’nin açık denizlere çıkışında kritik bir geçittir.', true, 'Petrol tankerleri buradan geçer.'],
      ['Kuzey Akım Rusya’yı Karadeniz üzerinden Türkiye’ye bağlar.', false, 'Kuzey Akım Baltık tabanından Almanya’ya uzanıyordu.'],
      ['Mavi Akım 2003’te Rusya gazını Samsun’a ulaştırmıştır.', true, 'Karadeniz tabanından geçen ilk doğal gaz hattıdır.'],
    ],
    secimler: [
      ['Azerbaycan gazını Avrupa’ya taşıyan hat?', 'TANAP', 'Mavi Akım', 'TANAP Türkiye’den geçer.'],
      ['Ham petrolü Ceyhan’a taşıyan hat?', 'BTC', 'TürkAkım', 'BTC petrol hattıdır.'],
      ['Rusya-Almanya Baltık tabanı hattı?', 'Kuzey Akım', 'Mavi Akım', 'Mavi Akım Karadeniz’den Türkiye’ye gelir.'],
      ['Basra Körfezi’nin çıkışı olan boğaz?', 'Hürmüz', 'Malakka', 'Hürmüz Basra Körfezi’ni açık denize bağlar.'],
    ],
    kontroller: [['Mavi Akım Rusya’yı Türkiye’nin hangi limanına bağlar?', 'Samsun', 'Mersin', 'Karadeniz tabanından Samsun’a ulaşır.', 3]],
  }),
  cografya12Konusu({
    id: 'cog12-catisma-alani',
    ad: 'Çatışma Alanları ve Mekânsal Unsurlar',
    kartlar: [
      ['Mekânsal unsurlar', 'Sınır, deniz yetki alanı, su, enerji, geçit ve etnik-dinî dağılış ülkeler arasında sorun doğurabilir.\nÇatışmanın coğrafi bir zemini vardır.'],
      ['Sınır sorunları', 'Sınırlar bazen sömürge dönemi anlaşmalarıyla çizildi.\nBerlin Konferansı (1884-85) Afrika’yı etnik yapıya bakmadan paylaştırdı.'],
      ['Deniz yetki alanları', 'BM Deniz Hukuku Sözleşmesi (1982) karasuyunu 12 mile kadar belirler.\nMünhasır ekonomik bölge 200 mile kadar uzanır.'],
      ['Su kaynakları', 'Nil, Fırat-Dicle, Ürdün ve Amu Derya gibi sınır aşan sular paylaşım sorunu doğurur.\nBaraj yapımı kıyıdaş ülkeleri etkiler.'],
      ['Enerji ve maden', 'Hazar, Doğu Akdeniz ve Güney Çin Denizi’nde petrol ve gaz yatakları yetki rekabeti yaratır.\nKaynak, sınırı önemli kılar.'],
      ['Stratejik geçitler', 'Hürmüz, Malakka, Süveyş ve Boğazlar ticaret ve enerji akışını denetler.\nGeçişi denetleyen ülke güç kazanır.'],
      ['Etnik ve dinî dağılış', 'Siyasi sınırlar etnik ve dinî dağılışla örtüşmediğinde gerilim doğabilir.\nOrta Doğu, Balkanlar ve Kafkasya örnektir.'],
      ['Güncel gerilim alanları', 'Orta Doğu, Doğu Avrupa, Güney Çin Denizi ve Sahel’de gerilimler sürmektedir.\nHer birinde sınır, kaynak ve geçit unsurları iç içedir.'],
    ],
    not: 'Çatışmaya bakarken “kim haklı” diye değil “mekânda ne var?” diye sor: su mu, geçit mi, sınır mı, kaynak mı?',
    notKarti: 1,
    iddialar: [
      ['Sınır aşan sular ülkeler arasında paylaşım sorunu doğurabilir.', true, 'Kıyıdaş ülkelerin ihtiyaçları çakışır.'],
      ['Karasuyu genişliği BM Deniz Hukuku Sözleşmesi’ne göre en fazla 12 mildir.', true, '1982 Sözleşmesi bu sınırı koyar.'],
      ['Münhasır ekonomik bölge karasuyuyla aynı genişliktedir.', false, 'MEB, kıyıdan 200 mile kadar uzanır.'],
      ['Berlin Konferansı Afrika’yı etnik yapıya göre paylaştırmıştır.', false, 'Afrika etnik yapı gözetilmeden paylaşıldı.'],
      ['Hürmüz ve Malakka gibi geçitler enerji akışı bakımından stratejiktir.', true, 'Geçişi denetlemek güç sağlar.'],
      ['Siyasi sınırlar etnik dağılışla örtüşmüyorsa gerilim doğabilir.', true, 'Orta Doğu ve Balkanlar örnektir.'],
    ],
    secimler: [
      ['Karasuyu üst sınırı kaç mildir?', '12', '200', '200 mil MEB sınırıdır.'],
      ['MEB (münhasır ekonomik bölge) kaç mile kadar?', '200', '12', 'MEB kıyıdan 200 mile kadar.'],
      ['Afrika’yı paylaştıran konferans?', 'Berlin', 'Lozan', 'Berlin Konferansı 1884-85’tedir.'],
      ['Sınır aşan su sorunu hangi akarsuda yaşanır?', 'Nil', 'Sakarya', 'Nil birçok ülke arasında paylaşılır.'],
    ],
    kontroller: [['BM Deniz Hukuku Sözleşmesi hangi yılda?', '1982', '1936', '1982’de imzalandı.', 3]],
  }),
]
