import { tarih12Konusu } from './12-tarih-yardimci'

/** 12. sınıf Tarih: iki savaş arası dönem ve II. Dünya Savaşı (2018 programı). */
export const tarih12IkiSavasArasi = [
  tarih12Konusu({
    id: 'trh12-ic-politika',
    ad: 'Atatürk Dönemi İç Politika (1923-1938)',
    kartlar: [
      ['Halk Fırkası', '9 Eylül 1923’te kuruldu; başkanı Mustafa Kemal’di.\n1924’te adı Cumhuriyet Halk Fırkası oldu.'],
      ['Terakkiperver Cumhuriyet Fırkası', '17 Kasım 1924’te Kazım Karabekir, Ali Fuat ve Rauf Orbay gibi isimlerce kuruldu.\nCumhuriyet’in ilk muhalefet partisidir.'],
      ['Şeyh Sait İsyanı', 'Şubat 1925’te Doğu Anadolu’da çıktı.\nHalifeliğin kaldırılmasına ve laikleşmeye tepki vardı.'],
      ['Takrir-i Sükûn', '4 Mart 1925’te Takrir-i Sükûn Kanunu çıkarıldı.\nİstiklal Mahkemeleri yeniden kuruldu, Terakkiperver Fırka Haziran 1925’te kapatıldı.'],
      ['İzmir Suikastı', 'Haziran 1926’da Mustafa Kemal’e İzmir’de suikast planı ortaya çıkarıldı.\nMuhalefetten bazı isimler yargılandı.'],
      ['Nutuk', '15-20 Ekim 1927’de CHF Kurultayı’nda okundu.\nMillî Mücadele’nin ve ilk yılların anlatımıdır.'],
      ['Serbest Cumhuriyet Fırkası', '12 Ağustos 1930’da Fethi Okyar tarafından kuruldu.\nDeneme kısa sürdü; parti 17 Kasım 1930’da kendini feshetti.'],
      ['Menemen Olayı', '23 Aralık 1930’da Menemen’de irticai bir ayaklanma çıktı.\nAsteğmen Kubilay hayatını kaybetti.'],
      ['Ağrı ve Dersim', 'Ağrı isyanı 1927-1930 arasında bastırıldı.\nDersim harekâtı 1937-1938’de yapıldı.'],
      ['Tek parti dönemi', 'Cumhuriyet’in ilk yirmi yılı tek partili düzende geçti.\nÇok partili hayata 1945-1946’da geçildi.'],
    ],
    not: 'İlk muhalefet partisi 1924 TCF; ikincisi 1930 SCF. İkisi de kısa sürede kapandı.',
    notKarti: 2,
    iddialar: [
      ['Terakkiperver Cumhuriyet Fırkası 1924’te kuruldu.', true, '17 Kasım 1924.'],
      ['Şeyh Sait İsyanı 1930’da çıktı.', false, 'Şeyh Sait İsyanı Şubat 1925’te çıktı.'],
      ['Takrir-i Sükûn Kanunu 1925’te çıkarıldı.', true, 'Şeyh Sait İsyanı sonrası.'],
      ['Serbest Cumhuriyet Fırkası’nı Kazım Karabekir kurdu.', false, 'Fethi Okyar kurdu.'],
      ['Nutuk 1927’de okundu.', true, '15-20 Ekim 1927, CHF Kurultayı.'],
      ['Menemen Olayı 1925’te yaşandı.', false, '23 Aralık 1930.'],
      ['Serbest Cumhuriyet Fırkası kendini feshetti.', true, '17 Kasım 1930.'],
    ],
    secimler: [
      ['Serbest Cumhuriyet Fırkası’nı kim kurdu?', 'Fethi Okyar', 'Kazım Karabekir', 'Karabekir TCF’nin önde gelenlerindendi.'],
      ['İstiklal Mahkemeleri’ni yeniden kuran kanun?', 'Takrir-i Sükûn', 'Medeni Kanun', 'Takrir-i Sükûn 1925.'],
      ['İlk muhalefet partisi hangisidir?', 'Terakkiperver Cumhuriyet Fırkası', 'Serbest Cumhuriyet Fırkası', 'TCF 1924, SCF 1930.'],
      ['Nutuk hangi yıl okundu?', '1927', '1935', 'CHF 2. Kurultayı, Ekim 1927.'],
      ['Şeyh Sait İsyanı hangi bölgede çıktı?', 'Doğu Anadolu', 'Ege', 'Genç ve Piran çevresi.'],
    ],
    kontroller: [['Terakkiperver Cumhuriyet Fırkası hangi yıl kuruldu?', '1924', '1930', '1930 SCF yılıdır.', 2]],
  }),

  tarih12Konusu({
    id: 'trh12-dis-politika',
    ad: 'Atatürk Dönemi Türk Dış Politikası',
    kartlar: [
      ['İlke', 'Dış politika, “Yurtta sulh, cihanda sulh” anlayışına dayandı.\nHedef tam bağımsızlık ve toprak bütünlüğüydü.'],
      ['Nüfus mübadelesi', '30 Ocak 1923 sözleşmesiyle Türk-Rum mübadelesi yapıldı.\nİstanbul Rumları ve Batı Trakya Türkleri kapsam dışındaydı.'],
      ['Türk-Sovyet Dostluğu', '17 Aralık 1925’te Dostluk ve Tarafsızlık Antlaşması imzalandı.\nİki ülke ilişkisi 1920’lerde yakındı.'],
      ['Musul meselesi', 'Musul, Lozan’da çözülemedi; Milletler Cemiyeti kararıyla Irak’a verildi.\n5 Haziran 1926 Ankara Antlaşması ile kesinleşti.'],
      ['Türk-Yunan yakınlaşması', '30 Ekim 1930’da Ankara’da Dostluk Antlaşması imzalandı.\nVenizelos ve İnönü ilişkileri düzeltti.'],
      ['Milletler Cemiyeti', 'Türkiye 1932’de Milletler Cemiyeti’ne üye oldu.\nBarışçı politikasını uluslararası alanda sürdürdü.'],
      ['Balkan Antantı', '9 Şubat 1934’te Türkiye, Yunanistan, Romanya ve Yugoslavya arasında kuruldu.\nBulgaristan katılmadı.'],
      ['Montrö Boğazlar Sözleşmesi', '20 Temmuz 1936’da imzalandı.\nTürkiye Boğazlar’da egemenlik ve askerî önlem hakkını geri aldı.'],
      ['Montrö’nün hükümleri', '- Barışta ticaret gemileri serbest geçer.\n- Savaş gemilerinin geçişi tonaj ve bildirimle sınırlıdır.\n- Savaşta Türkiye geçişi sınırlayabilir.'],
      ['Sadabat Paktı', '8 Temmuz 1937’de Türkiye, İran, Irak ve Afganistan imzaladı.\nDoğu sınırında güvenlik amaçlıydı.'],
      ['Hatay', 'İskenderun Sancağı Fransız mandasındaydı.\nBağımsız Hatay Devleti 1938’de kuruldu; Hatay 1939’da Türkiye’ye katıldı.'],
      [
        'Dış politika sırası',
        'Musul’dan Sadabat’a kadar birçok antlaşma imzalandı.\nTarihleri sıralamak sorularda çok sorulur.',
        {
          tur: 'akis',
          dikey: true,
          adimlar: [
            { ad: '1926 Ankara', alt: 'Musul Irak’a' },
            { ad: '1932 Milletler Cemiyeti', alt: 'Türkiye üye oldu' },
            { ad: '1934 Balkan Antantı', alt: 'dört devlet' },
            { ad: '1936 Montrö', alt: 'Boğazlar' },
            { ad: '1937 Sadabat', alt: 'dört devlet' },
          ],
        },
      ],
    ],
    not: 'Balkan Antantı 1934, Montrö 1936, Sadabat 1937. Sıralamada Montrö ortadadır.',
    notKarti: 7,
    iddialar: [
      ['Montrö Boğazlar Sözleşmesi 1936’da imzalandı.', true, '20 Temmuz 1936.'],
      ['Montrö, Boğazların uluslararası komisyon denetimini getirdi.', false, 'Montrö o komisyonu kaldırdı.'],
      ['Balkan Antantı’na Bulgaristan katılmadı.', true, 'Türkiye, Yunanistan, Romanya ve Yugoslavya vardı.'],
      ['Bulgaristan Balkan Antantı’nın kurucusu devletlerdendir.', false, 'Bulgaristan katılmadı.'],
      ['Türkiye 1932’de Milletler Cemiyeti’ne girdi.', true, 'Üyelik Temmuz 1932’de.'],
      ['Musul sorunu Türkiye lehine çözüldü.', false, '1926’da Musul Irak’a bırakıldı.'],
      ['Sadabat Paktı Türkiye, İran, Irak ve Afganistan arasındadır.', true, '8 Temmuz 1937.'],
      ['Hatay 1936’da Türkiye’ye katıldı.', false, 'Hatay 1939’da katıldı.'],
    ],
    secimler: [
      ['Boğazlar Sözleşmesi hangi şehirde imzalandı?', 'Montrö', 'Lozan', 'Montrö, 1936.'],
      ['Türkiye Milletler Cemiyeti’ne hangi yıl girdi?', '1932', '1936', '1936 Montrö yılı.'],
      ['Sadabat Paktı hangi yıl?', '1937', '1934', '1934 Balkan Antantı.'],
      ['Musul hangi antlaşmayla Irak’a bırakıldı?', 'Ankara (1926)', 'Lozan (1923)', 'Lozan’da çözülemedi.'],
      ['Balkan Antantı’na katılmayan devlet?', 'Bulgaristan', 'Romanya', 'Bulgaristan dışarıda kaldı.'],
      ['Hatay hangi yıl Türkiye’ye katıldı?', '1939', '1938', '1938’de bağımsız Hatay Devleti kuruldu.'],
    ],
    kontroller: [
      ['Balkan Antantı hangi yıl kuruldu?', '1934', '1937', '1937 Sadabat Paktı yılıdır.', 7],
      ['Boğazlar Sözleşmesi hangi şehirde yapıldı?', 'Montrö', 'Lozan', 'Lozan 1923; Montrö 1936.', 8],
    ],
  }),

  tarih12Konusu({
    id: 'trh12-iki-savas-dunya',
    ad: 'İki Savaş Arasında Dünya',
    kartlar: [
      ['Paris Barış Konferansı', 'I. Dünya Savaşı’ndan sonra 1919’da toplandı.\nYenilen devletlere ağır barış koşulları getirildi.'],
      ['Versay', '28 Haziran 1919’da Almanya ile imzalandı.\nAlman ordusu sınırlandı; tazminat ve toprak kaybı kabul edildi.'],
      ['Milletler Cemiyeti', '1920’de Cenevre’de kuruldu.\nABD üye olmadı; yaptırım gücü zayıf kaldı.'],
      ['Sovyet Rusya', 'Ekim 1917’de Bolşevik Devrimi oldu, Lenin iktidara geldi.\nSSCB 30 Aralık 1922’de kuruldu.'],
      ['Stalin dönemi', 'Lenin’den sonra Stalin iktidara geldi.\nKalkınma 1928’de Beş Yıllık Planlar ile başladı.'],
      ['Orta Asya', 'Orta Asya Türk toplulukları Sovyet cumhuriyetlerine bölündü.\nSovyet yönetimi Basmacı Hareketi’ni bastırdı.'],
      ['Manda yönetimi', 'Orta Doğu’da Arap toprakları manda yönetimine girdi.\nSuriye ve Lübnan Fransa’ya; Irak, Filistin, Transürdün İngiltere’ye verildi.'],
      ['Japonya', 'Japonya Uzak Doğu’da güçlü bir devlet oldu.\n1931’de Mançurya’yı işgal etti.'],
      ['1929 Büyük Buhran', '24 Ekim 1929’da New York borsası çöktü.\nKriz dünyaya yayıldı; işsizlik ve yoksulluk arttı.'],
      ['New Deal ve totaliter rejimler', 'ABD’de Roosevelt New Deal ile ekonomiye devlet müdahalesini artırdı.\nAvrupa’da bunalım totaliter rejimleri güçlendirdi.'],
      ['Faşizm', 'İtalya’da Mussolini 1922’de iktidara geldi.\nYayılmacılığı ve tek parti yönetimini savundu.'],
      ['Nazizm', 'Almanya’da Hitler 1933’te Şansölye oldu.\nVersay düzeninin yıkılması ve yayılmacılık hedeflendi.'],
    ],
    not: 'Büyük Buhran 1929’da başladı ve 1930’ların totaliter rejimlerinin yükselişini hazırladı.',
    notKarti: 9,
    iddialar: [
      ['Versay Antlaşması 1919’da Almanya ile imzalandı.', true, '28 Haziran 1919.'],
      ['ABD, Milletler Cemiyeti’nin ilk üyesiydi.', false, 'ABD üye olmadı.'],
      ['SSCB 1922’de kuruldu.', true, '30 Aralık 1922.'],
      ['Büyük Buhran 1923’te başladı.', false, '1929’da New York borsası çöktü.'],
      ['Mussolini 1922’de İtalya’da iktidara geldi.', true, 'Roma Yürüyüşü Ekim 1922’de.'],
      ['Hitler 1925’te Almanya’da Şansölye oldu.', false, 'Hitler 1933’te Şansölye oldu.'],
      ['Japonya 1931’de Mançurya’yı işgal etti.', true, 'Uzak Doğu’daki yayılmacılığının başlangıcıdır.'],
      ['Irak ve Filistin Fransız mandasına verildi.', false, 'İngiliz mandasına verildi.'],
    ],
    secimler: [
      ['Büyük Buhran hangi yıl başladı?', '1929', '1933', '1933’te Hitler Şansölye oldu.'],
      ['Suriye ve Lübnan hangi devletin mandasındaydı?', 'Fransa', 'İngiltere', 'Fransa.'],
      ['Milletler Cemiyeti’nin merkezi neresiydi?', 'Cenevre', 'Paris', 'Cenevre.'],
      ['SSCB kuruluş yılı?', '1922', '1917', '1917 Bolşevik Devrimi’dir.'],
      ['Hitler hangi yıl Şansölye oldu?', '1933', '1929', '1929 Büyük Buhran yılı.'],
      ['Versay Antlaşması hangi devletle imzalandı?', 'Almanya', 'Avusturya', 'Almanya.'],
    ],
    kontroller: [
      ['SSCB hangi yıl kuruldu?', '1922', '1917', '1917 Bolşevik Devrimi’dir.', 4],
      ['Büyük Buhran hangi şehirde başladı?', 'New York', 'Londra', '24 Ekim 1929 New York borsası.', 9],
    ],
  }),
]

/** II. Dünya Savaşı grubu. */
export const tarih12IkinciDunya = [
  tarih12Konusu({
    id: 'trh12-ikinci-seyir',
    ad: 'II. Dünya Savaşı’nın Nedenleri ve Seyri',
    kartlar: [
      ['Nedenler', 'Versay’ın ağırlığı, 1929 Krizi, totaliter rejimler ve Milletler Cemiyeti’nin güçsüzlüğü savaşı hazırladı.\nYatıştırma politikası da etkiliydi.'],
      ['Yatıştırma politikası', 'İngiltere ve Fransa Hitler’e taviz verdi.\n29-30 Eylül 1938 Münih Anlaşması Südetler’i Almanya’ya bıraktı.'],
      ['Anschluss ve Çekoslovakya', '1938’de Avusturya Almanya’ya katıldı.\nMart 1939’da Almanya Çekoslovakya’yı işgal etti.'],
      ['Mihver Devletleri', 'Almanya, İtalya ve Japonya Mihver’i oluşturdu.\n1936’da Anti-Komintern, 1940’ta Üçlü Pakt imzalandı.'],
      ['Saldırmazlık Paktı', '23 Ağustos 1939’da Almanya ve SSCB saldırmazlık paktı imzaladı.\nPolonya, gizli protokolle paylaşıldı.'],
      ['Savaşın başlaması', '1 Eylül 1939’da Almanya Polonya’ya saldırdı.\n3 Eylül’de İngiltere ve Fransa Almanya’ya savaş ilan etti.'],
      ['Şimşek savaşı', '1940’ta Almanya Danimarka, Norveç, Hollanda, Belçika ve Fransa’yı ele geçirdi.\nParis Haziran 1940’ta düştü.'],
      ['Savaşın genişlemesi', 'İtalya Haziran 1940’ta savaşa girdi.\nAlmanya 22 Haziran 1941’de SSCB’ye saldırdı (Barbarossa).'],
      ['Pearl Harbor', '7 Aralık 1941’de Japonya Pearl Harbor’a saldırdı.\nABD savaşa girdi ve savaş küresel hâle geldi.'],
      ['Dönüm noktaları', 'Stalingrad (1942-1943) ve El-Alamein (1942) Mihver ilerleyişini durdurdu.\nAlmanya doğu cephesinde gerilemeye başladı.'],
      ['Normandiya', '6 Haziran 1944’te Müttefikler Normandiya’ya çıktı.\nBatı cephesi açıldı, Fransa kurtarıldı.'],
      ['Savaşın sonu', 'Almanya 8 Mayıs 1945’te teslim oldu.\nHiroşima 6, Nagasaki 9 Ağustos’ta bombalandı; Japonya 2 Eylül’de teslim oldu.'],
    ],
    not: 'Savaş 1 Eylül 1939 (Polonya) ile başladı; 22 Haziran 1941 ve 7 Aralık 1941 savaşı genişletti.',
    notKarti: 6,
    iddialar: [
      ['Münih Anlaşması 1938’de imzalandı.', true, 'Südetler Almanya’ya bırakıldı.'],
      ['Pearl Harbor saldırısı 1940’ta yaşandı.', false, '7 Aralık 1941.'],
      ['Almanya SSCB’ye 22 Haziran 1941’de saldırdı.', true, 'Barbarossa Harekâtı.'],
      ['II. Dünya Savaşı 1 Eylül 1938’de başladı.', false, '1 Eylül 1939, Polonya saldırısı.'],
      ['Normandiya çıkarması 1944’te gerçekleşti.', true, '6 Haziran 1944.'],
      ['Almanya 8 Mayıs 1944’te teslim oldu.', false, '8 Mayıs 1945’te teslim oldu.'],
      ['ABD, Pearl Harbor saldırısının ardından savaşa girdi.', true, 'Japonya’nın saldırısı ABD’yi savaşa soktu.'],
      ['İtalya savaşa Aralık 1941’de girdi.', false, 'İtalya Haziran 1940’ta girdi.'],
    ],
    secimler: [
      ['Savaşı fiilen başlatan saldırı hangi ülkeye yapıldı?', 'Polonya', 'Fransa', '1 Eylül 1939.'],
      ['Pearl Harbor’a hangi devlet saldırdı?', 'Japonya', 'İtalya', 'Japonya.'],
      ['Almanya’nın SSCB saldırısının kod adı?', 'Barbarossa', 'Overlord', 'Overlord Normandiya’dır.'],
      ['Normandiya çıkarması hangi yılda?', '1944', '1942', '1944.'],
      ['Münih Anlaşması hangi bölgeyi Almanya’ya bıraktı?', 'Südetler', 'Alsace', 'Çekoslovakya’daki Südetler.'],
      ['Atom bombası atılan şehirler?', 'Hiroşima ve Nagasaki', 'Tokyo ve Osaka', 'Ağustos 1945.'],
    ],
    kontroller: [
      ['Savaş hangi tarihte başladı?', '1 Eylül 1939', '23 Ağustos 1939', '23 Ağustos Saldırmazlık Paktı’dır.', 6],
      ['ABD savaşa hangi olayla girdi?', 'Pearl Harbor', 'Normandiya', 'Normandiya 1944’tür.', 9],
    ],
  }),

  tarih12Konusu({
    id: 'trh12-ikinci-turkiye',
    ad: 'II. Dünya Savaşı’nda Türkiye',
    kartlar: [
      ['Savaşa girmeme', 'Türkiye savaşa girmedi; amaç toprak bütünlüğünü korumaktı.\nİsmet İnönü Cumhurbaşkanıydı.'],
      ['Üçlü İttifak (1939)', '19 Ekim 1939’da İngiltere ve Fransa ile imzalandı.\nProtokol, Türkiye’yi SSCB’ye karşı yükümlülükten korudu.'],
      ['Savaş dışı statü', 'Haziran 1940’ta Fransa’nın düşmesiyle Türkiye “savaş dışı” statüye geçti.\nDengeli bir politika izlendi.'],
      ['Türk-Alman Antlaşması', '18 Haziran 1941’de imzalandı.\nAlmanya’nın SSCB’ye saldırısından dört gün önce yapıldı.'],
      ['Millî Korunma Kanunu', '18 Ocak 1940’ta çıktı.\nDevlete ekonomiye müdahale yetkisi verdi.'],
      ['Varlık Vergisi', '11 Kasım 1942’de çıktı.\nGayrimüslimlere ağır uygulandı; 1944’te kaldırıldı.'],
      ['Toprak Mahsulleri Vergisi', '1944’te çiftçiden ürünün bir bölümü alındı.\nKırsalda hoşnutsuzluk doğurdu.'],
      ['Adana Görüşmesi', 'Ocak 1943’te Churchill ve İnönü Adana’da görüştü.\nİngiltere Türkiye’yi savaşa sokmak istedi.'],
      ['Kahire Konferansı', 'Aralık 1943’te Churchill, Roosevelt ve İnönü Kahire’de görüştü.\nTürkiye savaşa girmeye yine razı olmadı.'],
      ['Savaş ilanı', '23 Şubat 1945’te Türkiye Almanya ve Japonya’ya savaş ilan etti.\nAmaç Birleşmiş Milletler’in kurucu üyesi olmaktı.'],
    ],
    not: 'Türkiye fiilen savaşmadı; 1945’teki savaş ilanı BM kurucu üyeliği içindi.',
    notKarti: 10,
    iddialar: [
      ['Üçlü İttifak Antlaşması 1939’da imzalandı.', true, '19 Ekim 1939, İngiltere ve Fransa ile.'],
      ['Varlık Vergisi 1930’da çıkarıldı.', false, '11 Kasım 1942.'],
      ['Türk-Alman Saldırmazlık Antlaşması Haziran 1941’de imzalandı.', true, 'Almanya’nın SSCB saldırısından dört gün önce.'],
      ['Adana Görüşmesi’nde Türkiye savaşa girmeyi kabul etti.', false, 'Türkiye savaşa girmeyi reddetti.'],
      ['Millî Korunma Kanunu devlete ekonomiye müdahale yetkisi verdi.', true, '18 Ocak 1940.'],
      ['Türkiye 1939’da Almanya’ya savaş açtı.', false, 'Savaş ilanı 1945’te yapıldı.'],
      ['Türkiye 1945’te Almanya ve Japonya’ya savaş ilan etti.', true, 'BM kurucu üyeliği için.'],
    ],
    secimler: [
      ['Varlık Vergisi hangi yıl çıktı?', '1942', '1930', '1942.'],
      ['Türkiye neden 1945’te savaş ilan etti?', 'BM kurucu üyesi olmak', 'Boğazları korumak', 'Savaş ilanı şartı Yalta’daydı.'],
      ['Adana’da Churchill ile kim görüştü?', 'İsmet İnönü', 'Adnan Menderes', 'İnönü.'],
      ['Üçlü İttifak hangi devletlerle yapıldı?', 'İngiltere ve Fransa', 'Almanya ve İtalya', 'İngiltere ve Fransa ile.'],
      ['Toprak Mahsulleri Vergisi hangi yıl?', '1944', '1942', '1944.'],
    ],
    kontroller: [['Üçlü İttifak hangi yıl imzalandı?', '1939', '1945', '1945 sembolik savaş ilanı yılıdır.', 2]],
  }),

  tarih12Konusu({
    id: 'trh12-ikinci-sonuc',
    ad: 'II. Dünya Savaşı’nın Sonuçları',
    kartlar: [
      ['İnsan kaybı', 'Savaşta tahminen 50-60 milyon insan öldü.\nHolokost’ta yaklaşık altı milyon Yahudi katledildi.'],
      ['Atlantik Bildirisi', 'Ağustos 1941’de Churchill ve Roosevelt yayımladı.\nSavaş sonrası düzende halkların kendi geleceğini belirlemesi öngörüldü.'],
      ['Savaş konferansları', 'Kazablanka, Tahran, Yalta ve Potsdam toplantıları savaşı ve savaş sonrasını belirledi.'],
      ['Yalta', 'Şubat 1945’te Roosevelt, Churchill ve Stalin toplandı.\nAlmanya işgal bölgelerine ayrılacak, BM kurulacaktı.'],
      ['Potsdam', 'Temmuz-Ağustos 1945’te toplandı.\nAlmanya’nın yönetimi ve Doğu Avrupa sınırları ele alındı.'],
      ['Birleşmiş Milletler', '24 Ekim 1945’te kuruldu; Milletler Cemiyeti’nin yerini aldı.\nGüvenlik Konseyi’nin beş daimi üyesi vardır.'],
      ['Nürnberg', '1945-1946’da Nürnberg’de Nazi liderleri yargılandı.\nSavaş suçlarının uluslararası yargıya taşınması bakımından ilk büyük örnektir.'],
      ['Almanya’nın bölünmesi', 'Almanya dört işgal bölgesine ayrıldı.\n1949’da Batı ve Doğu Almanya kuruldu.'],
      ['Güç dengesi', 'Avrupa devletlerinin gücü azaldı.\nABD ve SSCB iki süper güç oldu.'],
      ['Sömürgeler', 'Sömürge halkları bağımsızlık istedi.\nAsya ve Afrika’da bağımsızlık hareketleri hızlandı.'],
    ],
    not: 'BM 1945’te kuruldu; yerini aldığı Milletler Cemiyeti ise 1920’de. İkisini karıştırma.',
    notKarti: 6,
    iddialar: [
      ['Birleşmiş Milletler 1945’te kuruldu.', true, '24 Ekim 1945.'],
      ['Birleşmiş Milletler 1920’de kuruldu.', false, '1920 Milletler Cemiyeti’dir.'],
      ['Nazi liderleri 1945-1946’da Nürnberg’de yargılandı.', true, 'Savaş suçları mahkemesi.'],
      ['Yalta Konferansı 1943’te toplandı.', false, 'Şubat 1945.'],
      ['Savaş sonrası ABD ve SSCB süper güç oldu.', true, 'Avrupa’nın gücü azaldı.'],
      ['Almanya savaştan sonra tek devlet olarak kaldı.', false, 'Önce dört bölge, sonra 1949’da iki devlet.'],
      ['Atlantik Bildirisi’ni Churchill ve Roosevelt yayımladı.', true, 'Ağustos 1941.'],
    ],
    secimler: [
      ['BM hangi yıl kuruldu?', '1945', '1919', '1919 Versay.'],
      ['Nazi liderleri hangi şehirde yargılandı?', 'Nürnberg', 'Cenevre', 'Nürnberg.'],
      ['Yalta’ya katılan lider kim?', 'Stalin', 'Hitler', 'Stalin.'],
      ['BM hangi kuruluşun yerini aldı?', 'Milletler Cemiyeti', 'NATO', 'Milletler Cemiyeti.'],
      ['Süper güç ikilisi hangisi?', 'ABD ve SSCB', 'İngiltere ve Fransa', 'ABD ve SSCB.'],
    ],
    kontroller: [['BM hangi yıl kuruldu?', '1945', '1920', '1920 Milletler Cemiyeti’dir.', 6]],
  }),
]
