import { tarih12Konusu } from './12-tarih-yardimci'

/** 12. sınıf Tarih: II. Dünya Savaşı sonrası ve toplumsal devrim çağı (2018 programı). */
export const tarih12SogukSavas = [
  tarih12Konusu({
    id: 'trh12-bloklar',
    ad: 'Blokların Kuruluşu ve Soğuk Savaş',
    kartlar: [
      ['Soğuk Savaş', 'ABD ve SSCB arasında doğrudan savaşa dönüşmeyen yarım yüzyıllık rekabettir.\nTaraflar kapitalizm ve komünizmi temsil etti.'],
      ['Demirperde', 'Churchill 1946’da “demir perde” konuşmasını yaptı.\nAvrupa’nın ikiye bölündüğünü anlattı.'],
      ['Truman Doktrini', '12 Mart 1947’de ilan edildi.\nKomünizmin yayılmasını önlemek için Türkiye ve Yunanistan’a yardım verildi.'],
      ['Marshall Planı', 'ABD Avrupa’nın ekonomik kalkınması için yardım planı açıkladı (1947).\nDoğu Bloku reddetti; Türkiye plana dâhil oldu.'],
      ['Kominform ve Comecon', 'SSCB 1947’de Kominform’u, 1949’da Comecon’u kurdu.\nDoğu Avrupa ülkeleri Sovyet etkisine girdi.'],
      ['Berlin Ablukası', 'SSCB Haziran 1948’de Batı Berlin’i kuşattı.\nBatılılar hava köprüsüyle yardım etti; abluka Mayıs 1949’da kalktı.'],
      ['Almanya’nın bölünmesi', 'Mayıs 1949’da Federal Almanya (Batı) kuruldu.\nEkim 1949’da Demokratik Almanya (Doğu) kuruldu.'],
      ['NATO', '4 Nisan 1949’da Washington’da 12 ülkeyle kuruldu.\nTürkiye ve Yunanistan 1952’de üye oldu.'],
      ['Varşova Paktı', 'Mayıs 1955’te SSCB önderliğinde kuruldu.\nBatı Almanya’nın NATO’ya girmesine karşılık oldu.'],
      ['Berlin Duvarı', '13 Ağustos 1961’de Doğu Almanya Berlin Duvarı’nı yaptı.\nSoğuk Savaş’ın simgesi oldu, 1989’da yıkıldı.'],
      ['Silahlanma yarışı', 'SSCB 1949’da atom bombası denedi, 1957’de Sputnik’i fırlattı.\nİki taraf nükleer silah ve uzay yarışına girdi.'],
      [
        'Blokların zaman çizgisi',
        'Doktrin, plan ve paktlar birbirine karşılık olarak kuruldu.',
        {
          tur: 'akis',
          dikey: true,
          adimlar: [
            { ad: '1947 Truman', alt: 'Türkiye, Yunanistan' },
            { ad: '1948 Marshall', alt: 'Avrupa’ya yardım' },
            { ad: '1949 NATO', alt: 'Batı bloku' },
            { ad: '1955 Varşova', alt: 'Doğu bloku' },
            { ad: '1961 Berlin Duvarı', alt: 'bölünme simgesi' },
          ],
        },
      ],
    ],
    not: 'NATO 1949’da kuruldu, Türkiye 1952’de girdi; Varşova Paktı ise 1955’te kuruldu.',
    notKarti: 8,
    iddialar: [
      ['Truman Doktrini 1947’de ilan edildi.', true, '12 Mart 1947.'],
      ['Marshall Planı’nı SSCB hazırladı.', false, 'ABD hazırladı.'],
      ['NATO 1949’da kuruldu.', true, '4 Nisan 1949.'],
      ['Varşova Paktı 1949’da kuruldu.', false, 'Varşova Paktı 1955’tedir.'],
      ['Berlin Duvarı 1961’de örüldü.', true, '13 Ağustos 1961.'],
      ['Comecon, NATO’nun ekonomik kuruluşudur.', false, 'Comecon Doğu Bloku’nun ekonomik örgütüdür.'],
      ['Churchill 1946’da “demir perde” konuşmasını yaptı.', true, 'Avrupa’nın bölünmesini anlattı.'],
      ['Türkiye NATO’ya 1949’da girdi.', false, 'Türkiye 1952’de üye oldu.'],
    ],
    secimler: [
      ['Türkiye ve Yunanistan’a yardım için ilan edilen doktrin?', 'Truman Doktrini', 'Marshall Planı', 'Truman Doktrini 1947.'],
      ['Türkiye NATO’ya hangi yıl girdi?', '1952', '1949', 'NATO 1949, Türkiye 1952.'],
      ['Doğu Bloku’nun askerî ittifakı hangisidir?', 'Varşova Paktı', 'Comecon', 'Comecon ekonomiktir.'],
      ['Berlin Duvarı hangi yıl yapıldı?', '1961', '1948', '1948 Berlin Ablukası.'],
      ['Berlin Ablukası’nı kim uyguladı?', 'SSCB', 'ABD', 'SSCB.'],
      ['Avrupa’nın kalkınması için yardım planı?', 'Marshall Planı', 'Truman Doktrini', 'Marshall Planı.'],
    ],
    kontroller: [
      ['Truman Doktrini hangi yıl ilan edildi?', '1947', '1949', '1949 NATO’nun kuruluşudur.', 3],
      ['Varşova Paktı hangi yıl kuruldu?', '1955', '1949', '1949 NATO ve Comecon yılı.', 9],
    ],
  }),

  tarih12Konusu({
    id: 'trh12-sogukdogu',
    ad: 'Orta Doğu, Uzak Doğu ve Sömürgelerin Çözülmesi',
    kartlar: [
      ['İsrail’in kuruluşu', 'BM 1947’de Filistin’in bölünmesini önerdi.\n14 Mayıs 1948’de İsrail devleti ilan edildi.'],
      ['1948 Arap-İsrail Savaşı', 'İsrail’in ilanından sonra Arap devletleri saldırdı.\nİsrail kazandı; çok sayıda Filistinli yurdunu terk etti.'],
      ['Çin', '1 Ekim 1949’da Mao liderliğinde Çin Halk Cumhuriyeti kuruldu.\nMilliyetçiler Tayvan’a çekildi.'],
      ['Kore Savaşı', 'Haziran 1950’de Kuzey Kore Güney Kore’ye saldırdı.\nBM bayrağı altında Türkiye de asker gönderdi; ateşkes 1953’te yapıldı.'],
      ['Kore’nin bölünmesi', 'Savaştan sonra 38. paralel sınır olarak kaldı.\nGüney ABD’nin, kuzey SSCB ve Çin’in desteğindeydi.'],
      ['Vietnam’da bölünme', '1954’te Dien Bien Phu yenilgisiyle Fransa Vietnam’dan çekildi.\nCenevre Konferansı Vietnam’ı 17. paralelden ikiye böldü.'],
      ['ABD’nin Vietnam müdahalesi', 'ABD 1960’larda Güney Vietnam’a asker yığdı.\n1973 Paris Anlaşması ile çekildi; Saygon 1975’te düştü.'],
      ['Hindistan', 'Hindistan ve Pakistan 1947’de bağımsız oldu.\nGandi’nin şiddetsiz direnişi etkili oldu.'],
      ['Bandung (1955)', 'Asya ve Afrika ülkeleri Bandung’da toplandı.\nBlok dışı politika ve sömürgeciliğe karşı ortak tutum benimsendi.'],
      ['Cezayir', 'Cezayir 1954’te Fransa’ya karşı bağımsızlık savaşı başlattı.\n1962’de bağımsız oldu.'],
      ['Süveyş Krizi', 'Nasır 1956’da Süveyş Kanalı’nı millîleştirdi.\nİngiltere, Fransa ve İsrail saldırdı; ABD ve SSCB baskısıyla çekildiler.'],
      ['Afrika Yılı', '1960’ta Afrika’da 17 ülke bağımsızlığını kazandı.\nSömürgecilik büyük ölçüde çözüldü.'],
    ],
    not: 'Kore ateşkesi 1953, Vietnam’ın bölünmesi 1954, Bandung 1955. Üç yılı art arda hatırla.',
    notKarti: 9,
    iddialar: [
      ['İsrail devleti 1948’de ilan edildi.', true, '14 Mayıs 1948.'],
      ['Çin Halk Cumhuriyeti 1947’de kuruldu.', false, 'Çin Halk Cumhuriyeti 1949’da kuruldu.'],
      ['Kore Savaşı 1950’de başladı.', true, 'Haziran 1950.'],
      ['Hindistan 1950’de bağımsız oldu.', false, 'Hindistan 1947’de bağımsız oldu.'],
      ['Süveyş Kanalı’nı Nasır millîleştirdi.', true, '1956.'],
      ['Cezayir İngiltere’ye karşı bağımsızlık savaşı verdi.', false, 'Cezayir Fransa’ya karşı savaştı.'],
      ['Bandung Konferansı 1955’te toplandı.', true, 'Asya ve Afrika ülkeleri.'],
      ['Saygon 1965’te düştü.', false, '1975’te düştü.'],
    ],
    secimler: [
      ['Kore’yi ikiye bölen paralel hangisidir?', '38. paralel', '17. paralel', '17. paralel Vietnam’dır.'],
      ['Vietnam’ı ikiye bölen konferans?', 'Cenevre', 'Yalta', 'Cenevre, 1954.'],
      ['Süveyş Kanalı’nı millîleştiren lider?', 'Nasır', 'Mao', 'Nasır, Mısır.'],
      ['Cezayir hangi devlete karşı savaştı?', 'Fransa', 'İtalya', 'Fransa.'],
      ['Çin Halk Cumhuriyeti’nin kurucu lideri?', 'Mao', 'Çan Kay-şek', 'Mao.'],
      ['Bandung Konferansı hangi yıl?', '1955', '1948', '1948 İsrail’in kuruluşu.'],
    ],
    kontroller: [
      ['İsrail hangi yıl kuruldu?', '1948', '1956', '1956 Süveyş Krizi’dir.', 1],
      ['Süveyş Krizi hangi yıl yaşandı?', '1956', '1962', '1962 Cezayir’in bağımsızlığıdır.', 11],
    ],
  }),

  tarih12Konusu({
    id: 'trh12-tr-1945-1960',
    ad: 'Türkiye: 1945-1960',
    kartlar: [
      ['Sovyet talepleri', 'Mart 1945’te SSCB 1925 Dostluk Antlaşması’nı feshetti.\nBoğazlarda üs ve doğuda toprak istedi.'],
      ['Batı’ya yönelme', 'Sovyet talepleri Türkiye’yi Batı’ya yöneltti.\n1947 Truman Doktrini ve Marshall Planı yardım getirdi.'],
      ['Çok partili hayat', '7 Haziran 1945 Dörtlü Takrir’in ardından Demokrat Parti 7 Ocak 1946’da kuruldu.\nKurucular: Bayar, Menderes, Köprülü, Koraltan.'],
      ['1946 seçimleri', '21 Temmuz 1946’da açık oy, gizli sayımla yapıldı.\nCHP kazandı; DP muhalefette kaldı.'],
      ['1950 seçimi', '14 Mayıs 1950’de DP iktidara geldi.\nCelal Bayar Cumhurbaşkanı, Adnan Menderes Başbakan oldu.'],
      ['NATO üyeliği', 'Kore’ye asker gönderen Türkiye 1952’de NATO’ya girdi.\nBatı bloğuna bağlılık güçlendi.'],
      ['Bölgesel paktlar', 'Balkan Paktı (1953-1954) kuruldu.\nTürkiye ve Irak Bağdat Paktı’nı (1955) imzaladı; sonra İngiltere, Pakistan ve İran katıldı.'],
      ['DP ekonomisi', 'Tarım makineleşti, karayolları yaygınlaştı.\nDış borç ve enflasyon arttı.'],
      ['Dinî politikalar', 'Ezanın Arapça okunmasına izin verildi (1950).\nİmam Hatip okulları 1951’de açıldı.'],
      ['Kıbrıs', '1950’lerde Rumlar EOKA ile Yunanistan’la birleşmeyi (Enosis) savundu.\nTürkiye taksim fikrini öne çıkardı.'],
      ['27 Mayıs 1960', 'Ordu 27 Mayıs 1960’ta yönetime el koydu.\nMillî Birlik Komitesi’nin başkanı Cemal Gürsel’di.'],
      ['Yassıada', 'Yassıada yargılamalarında Menderes ve iki bakan idam edildi (1961).\nCelal Bayar’ın cezası hafifletildi.'],
    ],
    not: 'Türkiye 1946 seçiminde “açık oy, gizli sayım”, 1950’de ise gizli oy, açık sayım uygulandı.',
    notKarti: 4,
    iddialar: [
      ['Demokrat Parti 1946’da kuruldu.', true, '7 Ocak 1946.'],
      ['1946 seçimi gizli oy, açık sayımla yapıldı.', false, '1946’da açık oy, gizli sayım uygulandı.'],
      ['Adnan Menderes 1950’de Başbakan oldu.', true, 'DP 14 Mayıs 1950’de iktidara geldi.'],
      ['Türkiye NATO’ya 1949’da girdi.', false, '1952’de girdi.'],
      ['Askerî müdahale 27 Mayıs 1960’ta yapıldı.', true, 'Millî Birlik Komitesi.'],
      ['Menderes Yassıada’da beraat etti.', false, 'Menderes idam edildi.'],
      ['Bağdat Paktı 1955’te kuruldu.', true, 'Türkiye ve Irak ilk imzacılar.'],
      ['Sovyetler 1945’te Türkiye’ye yardım teklif etti.', false, '1945’te Boğazlarda üs ve toprak istedi.'],
    ],
    secimler: [
      ['DP’nin kurucularından biri kimdir?', 'Celal Bayar', 'İsmet İnönü', 'İnönü CHP’liydi.'],
      ['Türkiye NATO’ya hangi yıl katıldı?', '1952', '1949', '1949 NATO’nun kuruluşu.'],
      ['1950 seçimini hangi parti kazandı?', 'DP', 'CHP', 'DP.'],
      ['Millî Birlik Komitesi’nin başkanı kimdi?', 'Cemal Gürsel', 'Celal Bayar', 'Cemal Gürsel.'],
      ['Türkiye hangi savaşa asker gönderdi?', 'Kore', 'Vietnam', 'Kore Savaşı.'],
      ['Bağdat Paktı hangi yıl kuruldu?', '1955', '1952', '1952 NATO üyeliğidir.'],
    ],
    kontroller: [
      ['Demokrat Parti hangi yıl kuruldu?', '1946', '1950', '1950 DP’nin iktidara geldiği yıldır.', 3],
      ['Türkiye NATO’ya hangi yıl girdi?', '1952', '1949', 'NATO 1949’da kuruldu.', 6],
    ],
  }),
]

/** Toplumsal devrim çağı: yumuşama, Orta Doğu ve 1960-1980 Türkiye. */
export const tarih12Yumusama = [
  tarih12Konusu({
    id: 'trh12-yumusama',
    ad: 'Yumuşama Dönemi',
    kartlar: [
      ['Barış içinde bir arada yaşama', 'Stalin 1953’te öldü, Kruşçev iktidara geldi.\n“Barış içinde bir arada yaşama” politikası benimsendi.'],
      ['Macaristan (1956)', 'SSCB 1956’da Macaristan ayaklanmasını bastırdı.\nDoğu Bloku’nda ayrılığa izin verilmedi.'],
      ['Küba Krizi', 'Ekim 1962’de SSCB Küba’ya füze yerleştirince kriz çıktı.\nKennedy ve Kruşçev anlaştı; nükleer savaş önlendi.'],
      ['Krizin sonucu', 'Washington ile Moskova arasında “kırmızı telefon” hattı kuruldu (1963).\nİki taraf iletişimi güçlendirdi.'],
      ['Nükleer anlaşmalar', '1963 Kısmi Nükleer Deneme Yasağı yapıldı.\n1968 NPT ve 1972 SALT I silahları sınırladı.'],
      ['Prag Baharı (1968)', 'Çekoslovakya’daki reform hareketi 1968’de Varşova Paktı güçlerince bastırıldı.\nSovyet kontrolü sürdü.'],
      ['ABD-Çin yakınlaşması', 'Nixon 1972’de Çin’i ziyaret etti.\nÇin-ABD yakınlaşması Sovyetler karşısında dengeyi değiştirdi.'],
      ['Avrupa’da yumuşama', 'Batı Almanya Doğu Almanya ile 1972’de Temel Antlaşma yaptı.\nBu politikaya Ostpolitik denir.'],
      ['Helsinki (1975)', 'Avrupa Güvenlik ve İşbirliği Konferansı Nihai Senedi 1975’te imzalandı.\nSınırların dokunulmazlığı ve insan hakları ilke edildi.'],
      ['Yumuşamanın sonu', 'SSCB’nin Aralık 1979’da Afganistan’ı işgali yumuşamayı bitirdi.\nSilahlanma yarışı yeniden hızlandı.'],
    ],
    not: 'Yumuşamanın doruğu Helsinki (1975), sonu Afganistan işgali (1979) olarak bilinir.',
    notKarti: 9,
    iddialar: [
      ['Küba Krizi 1962’de yaşandı.', true, 'Ekim 1962.'],
      ['Küba Krizi 1972’de yaşandı.', false, 'Kriz 1962’dedir.'],
      ['Prag Baharı 1968’de bastırıldı.', true, 'Varşova Paktı güçleri müdahale etti.'],
      ['Helsinki Nihai Senedi 1985’te imzalandı.', false, '1975’te imzalandı.'],
      ['SSCB Afganistan’ı 1979’da işgal etti.', true, 'Yumuşamanın sonu sayılır.'],
      ['NPT 1963’te imzalandı.', false, 'NPT 1968’dedir; 1963 Kısmi Deneme Yasağı’dır.'],
      ['Nixon 1972’de Çin’i ziyaret etti.', true, 'ABD-Çin yakınlaşması başladı.'],
    ],
    secimler: [
      ['Kırmızı telefon hattı hangi krizden sonra kuruldu?', 'Küba Krizi', 'Kore Savaşı', 'Küba Krizi.'],
      ['Helsinki Nihai Senedi hangi yıl?', '1975', '1962', '1962 Küba Krizi.'],
      ['Prag Baharı’nı kim bastırdı?', 'Varşova Paktı', 'NATO', 'Varşova Paktı güçleri.'],
      ['Yumuşamayı bitiren olay?', 'Afganistan işgali', 'Prag Baharı', 'Aralık 1979.'],
      ['“Barış içinde bir arada yaşama” hangi liderle anılır?', 'Kruşçev', 'Stalin', 'Kruşçev.'],
    ],
    kontroller: [['Küba Krizi hangi yıl yaşandı?', '1962', '1975', '1975 Helsinki Nihai Senedi.', 3]],
  }),

  tarih12Konusu({
    id: 'trh12-ortadogu-petrol',
    ad: 'Arap-İsrail Savaşları, Petrol ve İran-Irak Savaşı',
    kartlar: [
      ['1967 Altı Gün Savaşı', 'İsrail Haziran 1967’de Mısır, Suriye ve Ürdün’e saldırdı.\nSina, Gazze, Golan ve Doğu Kudüs işgal edildi.'],
      ['1973 Savaşı', 'Ekim 1973’te Mısır ve Suriye İsrail’e saldırdı.\nSavaş sonrası barış görüşmelerinin zemini hazırlandı.'],
      ['Petrol ambargosu', '1973’te Arap üreticiler Batı’ya petrol satışını kısıtladı.\nFiyatlar yükseldi, dünya ekonomisi bunalıma girdi.'],
      ['OPEC', '1960’ta kuruldu.\nPetrol üretici ülkeler fiyat ve üretim üzerinde etkili hâle geldi.'],
      ['Camp David', '1978 Camp David görüşmeleri, 1979 Mısır-İsrail Barış Antlaşması.\nMısır İsrail’i tanıyan ilk Arap devleti oldu.'],
      ['İran İslam Devrimi', '1979’da Şah Rıza Pehlevi devrildi, Humeyni liderliğinde yeni rejim kuruldu.\nBölgesel dengeler değişti.'],
      ['İran-Irak Savaşı', '22 Eylül 1980’de Irak İran’a saldırdı.\nSavaş 1988’de BM ateşkesiyle bitti.'],
      ['Savaşın etkisi', 'Savaş sekiz yıl sürdü, iki ülke ağır kayıp verdi.\nTürkiye tarafsız kaldı.'],
      ['Filistin sorunu', 'Filistin Kurtuluş Örgütü (FKÖ) 1964’te kuruldu.\nİntifada 1987’de başladı.'],
      ['Afganistan işgali', 'Aralık 1979’da SSCB Afganistan’ı işgal etti.\nDirenişçiler (Mücahitler) ABD ve Pakistan desteği aldı.'],
    ],
    not: 'Petrol şoku 1973 savaşının sonucudur; OPEC ise 1960’ta kurulmuştu. İkisini karıştırma.',
    notKarti: 3,
    iddialar: [
      ['OPEC 1960’ta kuruldu.', true, 'Petrol üreticilerinin örgütüdür.'],
      ['İran Devrimi 1975’te yaşandı.', false, 'İran Devrimi 1979’dadır.'],
      ['Mısır-İsrail Barış Antlaşması 1979’da imzalandı.', true, 'Camp David sürecinin sonucu.'],
      ['İran-Irak Savaşı 1973’te başladı.', false, '1980’de başladı.'],
      ['İsrail 1967’de Sina Yarımadası’nı işgal etti.', true, 'Altı Gün Savaşı.'],
      ['Camp David’de Suriye ile barış yapıldı.', false, 'Mısır ile barış yapıldı.'],
      ['SSCB Afganistan’ı 1979’da işgal etti.', true, 'Aralık 1979.'],
    ],
    secimler: [
      ['İran Devrimi’nin lideri kimdir?', 'Humeyni', 'Şah Rıza Pehlevi', 'Şah devrildi.'],
      ['İran-Irak Savaşı hangi yıl başladı?', '1980', '1973', '1973 Arap-İsrail Savaşı.'],
      ['1967’de hangi savaş yaşandı?', 'Altı Gün Savaşı', 'Kore Savaşı', 'Altı Gün Savaşı.'],
      ['Camp David ile kim barış yaptı?', 'Mısır', 'Suriye', 'Mısır-İsrail.'],
      ['FKÖ hangi yıl kuruldu?', '1964', '1948', '1948 İsrail’in kuruluşu.'],
    ],
    kontroller: [['İran-Irak Savaşı hangi yıl başladı?', '1980', '1973', '1973 petrol ambargosu yılıdır.', 7]],
  }),

  tarih12Konusu({
    id: 'trh12-tr-1960-1980',
    ad: 'Türkiye: 1960-1980',
    kartlar: [
      ['1961 Anayasası', '9 Temmuz 1961’de halk oylamasıyla kabul edildi.\nKuvvetler ayrılığı, Anayasa Mahkemesi ve Senato getirdi.'],
      ['Hak ve özgürlükler', 'Sendika, grev ve toplu sözleşme hakları tanındı.\nÜniversitelere özerklik verildi; TRT 1964’te kuruldu.'],
      ['Planlı kalkınma', 'Devlet Planlama Teşkilatı 1960’ta kuruldu.\nBeş yıllık kalkınma planları 1963’te başladı.'],
      ['Siyasi dengesizlik', '1960-1971 arasında koalisyon hükümetleri kuruldu.\nAdalet Partisi (Demirel) ve CHP öne çıktı.'],
      ['Ankara Anlaşması (1963)', '12 Eylül 1963’te AET ile Ortaklık Anlaşması imzalandı.\nTam üyelik hedefi başladı.'],
      ['Kıbrıs 1963-1964', 'Aralık 1963’te adada Türk-Rum çatışmaları çıktı.\n1964 Johnson Mektubu Türkiye’yi müdahaleden vazgeçirdi.'],
      ['Dış politikada çeşitlenme', '1960’lardan sonra Türkiye SSCB ve Üçüncü Dünya ile ilişkiyi geliştirdi.\nABD’ye bağımlılık sorgulandı.'],
      ['12 Mart 1971', 'Silahlı Kuvvetler 12 Mart 1971’de muhtıra verdi.\nDemirel hükümeti istifa etti.'],
      ['Kıbrıs Barış Harekâtı', '20 Temmuz 1974’te yapıldı.\nBaşbakan Bülent Ecevit’ti; ada fiilen ikiye ayrıldı.'],
      ['ABD ambargosu', 'ABD Şubat 1975’te Türkiye’ye silah ambargosu koydu.\nAmbargo 1978’de kaldırıldı.'],
      ['Bunalım yılları', '1970’lerde ekonomik sıkıntı, enflasyon ve siyasi şiddet arttı.\nKoalisyonlar kısa sürdü.'],
      ['12 Eylül 1980', 'Ordu yönetime el koydu; Kenan Evren Millî Güvenlik Konseyi’nin başına geçti.\nTBMM kapatıldı, partiler feshedildi.'],
    ],
    not: 'Johnson Mektubu (1964) Kıbrıs’a müdahaleyi engelledi; müdahale ise ancak 1974’te yapıldı.',
    notKarti: 6,
    iddialar: [
      ['1961 Anayasası halk oylamasıyla kabul edildi.', true, '9 Temmuz 1961.'],
      ['Kıbrıs Barış Harekâtı 1964’te yapıldı.', false, '1974’te yapıldı.'],
      ['Ankara Anlaşması 1963’te imzalandı.', true, 'AET ile Ortaklık Anlaşması.'],
      ['12 Mart muhtırası 1980’de verildi.', false, '12 Mart 1971’de verildi.'],
      ['12 Eylül 1980’de ordu yönetime el koydu.', true, 'Kenan Evren başkanlığında.'],
      ['ABD silah ambargosu 1960’ta konuldu.', false, 'Ambargo Şubat 1975’te konuldu.'],
      ['Johnson Mektubu 1964’te gönderildi.', true, 'Kıbrıs müdahalesine ABD itirazı.'],
      ['Devlet Planlama Teşkilatı 1980’de kuruldu.', false, '1960’ta kuruldu.'],
    ],
    secimler: [
      ['Aşağıdakilerden hangisi 1961 Anayasası’nın kurumudur?', 'Anayasa Mahkemesi', 'Şûra-yı Devlet', 'Şûra-yı Devlet Osmanlı’dır.'],
      ['Kıbrıs Barış Harekâtı’nda Başbakan kimdi?', 'Bülent Ecevit', 'Süleyman Demirel', 'Ecevit.'],
      ['Johnson Mektubu hangi yıl gönderildi?', '1964', '1974', 'Barış Harekâtı 1974.'],
      ['Ortaklık Anlaşması hangi örgütle yapıldı?', 'AET', 'NATO', 'AET.'],
      ['1971 muhtırasından sonra istifa eden başbakan?', 'Süleyman Demirel', 'Bülent Ecevit', 'Demirel.'],
      ['Silah ambargosunu hangi ülke uyguladı?', 'ABD', 'İngiltere', 'ABD, 1975.'],
    ],
    kontroller: [
      ['1961 Anayasası nasıl kabul edildi?', 'Halk oylamasıyla', 'Meclis kararıyla', 'Referandumla kabul edildi.', 1],
      ['Kıbrıs Barış Harekâtı hangi yıl yapıldı?', '1974', '1964', '1964 Johnson Mektubu yılıdır.', 9],
    ],
  }),
]
