import { tarih12Konusu } from './12-tarih-yardimci'

/** 12. sınıf Tarih, Atatürkçülük ve Türk İnkılabı grubu (2018 programı). */
export const tarih12Inkilap = [
  tarih12Konusu({
    id: 'trh12-ilkeler',
    ad: 'Atatürk İlkeleri',
    kartlar: [
      ['Altı ilke', 'Cumhuriyetçilik, milliyetçilik, halkçılık, devletçilik, laiklik, inkılapçılık.\nCHF programına 1931’de, Anayasa’ya 1937’de girdi.'],
      ['Cumhuriyetçilik', 'Yönetim biçimi, egemenliği millete dayandıran cumhuriyettir.\nSaltanat ve hilafet bu ilkeyle bağdaşmaz.'],
      ['Milliyetçilik', 'Ortak tarih, dil, kültür ve ülkü birliğine dayanır.\n“Ne mutlu Türküm diyene” sözü 1933’te söylendi.'],
      ['Halkçılık', 'Sınıf ve ayrıcalık tanımaz.\nHukuk önünde eşitlik ve halk için hizmet esastır.'],
      ['Devletçilik', 'Özel girişimi dışlamaz; özel sektörün yapamadığı alanlarda devlet üretime girer.\n1929 Krizi’nden sonra benimsendi.'],
      ['Laiklik', 'Din ve devlet işlerinin birbirinden ayrılmasıdır.\nHalifelik kaldırıldı; laiklik 1937’de Anayasa’ya girdi.'],
      ['İnkılapçılık', 'Toplumu çağdaş uygarlık düzeyine çıkarmak için yenilik yapmaktır.\nYenilikler akıl ve bilime dayanır.'],
      ['Millî egemenlik', '“Egemenlik kayıtsız şartsız milletindir.”\nYönetimin meşruiyeti millet iradesinden gelir.'],
      ['Millî bağımsızlık', 'Siyasi, ekonomik, adli ve kültürel alanda tam bağımsızlıktır.\nKapitülasyonların kaldırılması bu ilkeye dayanır.'],
      ['Barışçılık', '“Yurtta sulh, cihanda sulh” sözüyle özetlenir.\nSavaş yalnızca zorunlu savunmada kabul edilir.'],
    ],
    not: 'İlkelerin Anayasa’ya girişi 1937; CHF programına girişi ise 1931’dir. İki tarihi karıştırma.',
    notKarti: 1,
    iddialar: [
      ['Altı ilke Anayasa’ya 1937’de girdi.', true, '5 Şubat 1937’de Anayasa’ya eklendi.'],
      ['Laiklik, din ile devlet işlerini birleştirmeyi öngörür.', false, 'Laiklik din ve devlet işlerini ayırır.'],
      ['Devletçilik özel girişimi tümüyle yasaklar.', false, 'Özel girişim sürer; devlet boşluğu doldurur.'],
      ['“Ne mutlu Türküm diyene” sözü 1933’te söylendi.', true, 'Cumhuriyet’in 10. yılında söylendi.'],
      ['Halkçılık sınıf ayrıcalıklarını savunur.', false, 'Halkçılık sınıf ve ayrıcalık tanımaz.'],
      ['Devletçilik 1929 Dünya Krizi’nin etkisiyle benimsendi.', true, '1930’ların başında ekonomide devletçilik öne çıktı.'],
      ['Altı ilke ilk kez 1923 Anayasası’nda yer aldı.', false, 'Önce 1931 CHF programı, sonra 1937 Anayasa.'],
    ],
    secimler: [
      ['Devletçilik hangi olayın ardından benimsendi?', '1929 Dünya Ekonomik Krizi', 'Lozan Antlaşması', 'Kriz devletin rolünü artırdı.'],
      ['Din ve devlet işlerini ayıran ilke hangisidir?', 'Laiklik', 'Halkçılık', 'Laiklik ayrıdır.'],
      ['Sınıf ayrıcalığını reddeden ilke hangisidir?', 'Halkçılık', 'Milliyetçilik', 'Halkçılık eşitliği öne çıkarır.'],
      ['İlkelerin Anayasa’ya girdiği yıl?', '1937', '1928', '1928’de din maddesi çıkarıldı.'],
      ['“Yurtta sulh, cihanda sulh” hangi ilkeyle ilişkilidir?', 'Barışçılık', 'Devletçilik', 'Barışçı dış politika vurgusu.'],
    ],
    kontroller: [['İlkeler CHF programına hangi yıl girdi?', '1931', '1923', 'Anayasa’ya girişi 1937’dir.', 1]],
  }),

  tarih12Konusu({
    id: 'trh12-siyasi',
    ad: 'Siyasi Alandaki İnkılaplar',
    kartlar: [
      ['Saltanatın kaldırılması', 'TBMM 1 Kasım 1922’de saltanatı kaldırdı.\nOsmanlı hanedanının yönetim hakkı sona erdi.'],
      ['Vahdettin ve Abdülmecid', 'Vahdettin 17 Kasım 1922’de ülkeden ayrıldı.\nHalifeliğe Abdülmecid seçildi; yetkileri yalnız dinîydi.'],
      ['Ankara başkent', '13 Ekim 1923’te Ankara başkent ilan edildi.\nBu karar Cumhuriyet’ten önce alındı.'],
      ['Cumhuriyet’in ilanı', '29 Ekim 1923’te Cumhuriyet ilan edildi.\nİlk Cumhurbaşkanı Mustafa Kemal, ilk Başbakan İsmet İnönü oldu.'],
      ['Halifeliğin kaldırılması', '3 Mart 1924’te halifelik kaldırıldı.\nOsmanlı hanedanı yurt dışına çıkarıldı.'],
      ['Aynı gün çıkan kanun', '3 Mart 1924’te Tevhid-i Tedrisat da kabul edildi.\nEğitim tek elde toplandı.'],
      ['1924 Anayasası', '20 Nisan 1924’te kabul edildi.\nKuvvetler birliği esastı; yasama ve yürütme TBMM’deydi.'],
      ['Laikleşme adımları', '1928’de “devletin dini İslamdır” maddesi Anayasa’dan çıkarıldı.\n1937’de laiklik Anayasa’ya girdi.'],
      ['Kadın hakları', '1930’da belediye seçimlerinde seçme ve seçilme hakkı verildi.\n1934’te milletvekili seçme ve seçilme hakkı tanındı.'],
      ['İlk kadın milletvekilleri', '1935 seçimlerinde 18 kadın milletvekili Meclis’e girdi.\nTürkiye birçok Avrupa ülkesinden önce bu hakkı verdi.'],
      [
        'Sıralamayı çiz',
        'Saltanat, Cumhuriyet ve halifelik ayrı tarihlerde kaldırıldı.\nLaiklik ise Anayasa’ya ancak 1937’de girdi.',
        {
          tur: 'akis',
          dikey: true,
          adimlar: [
            { ad: '1922 Saltanat', alt: 'kaldırıldı' },
            { ad: '1923 Cumhuriyet', alt: 'ilan edildi' },
            { ad: '1924 Halifelik', alt: 'kaldırıldı' },
            { ad: '1928 Din maddesi', alt: 'Anayasa’dan çıktı' },
            { ad: '1937 Laiklik', alt: 'Anayasa’ya girdi' },
          ],
        },
      ],
      ['Cumhurbaşkanlığı', 'Mustafa Kemal 1923’ten ölümüne (10 Kasım 1938) kadar Cumhurbaşkanıydı.\n1923, 1927, 1931 ve 1935’te yeniden seçildi.'],
    ],
    not: 'Saltanat (1922) halifelikten (1924) önce kalktı. Sırayı değiştirme.',
    notKarti: 1,
    iddialar: [
      ['Saltanat 1 Kasım 1922’de kaldırıldı.', true, 'Kurtuluş Savaşı’nın hemen ardından.'],
      ['Halifelik saltanattan önce kaldırıldı.', false, 'Saltanat 1922’de, halifelik 1924’te kaldırıldı.'],
      ['1924 Anayasası kuvvetler birliğini esas aldı.', true, 'Yasama ve yürütme Meclis’te toplanmıştı.'],
      ['Cumhuriyet 29 Ekim 1922’de ilan edildi.', false, 'Cumhuriyet 29 Ekim 1923’te ilan edildi.'],
      ['Ankara, Cumhuriyet’ten önce başkent oldu.', true, '13 Ekim 1923.'],
      ['Kadınlara milletvekili seçme ve seçilme hakkı 1930’da verildi.', false, '1930 belediye, 1934 milletvekilliği.'],
      ['Laiklik ilkesi 1937’de Anayasa’ya girdi.', true, '1928’de din maddesi çıkmış, 1937’de laiklik girmişti.'],
      ['Cumhuriyet’in ilk Başbakanı Rauf Orbay’dır.', false, 'İlk Başbakan İsmet İnönü’dür.'],
    ],
    secimler: [
      ['Saltanat hangi tarihte kaldırıldı?', '1 Kasım 1922', '3 Mart 1924', '3 Mart 1924 halifeliğin kaldırıldığı tarihtir.'],
      ['Halifelik hangi yıl kaldırıldı?', '1924', '1923', '1923’te Cumhuriyet ilan edildi.'],
      ['Kadınlara milletvekili hakkı hangi yıl verildi?', '1934', '1930', '1930’da yalnız belediye hakkı verildi.'],
      ['“Devletin dini İslamdır” maddesi hangi yıl çıkarıldı?', '1928', '1937', '1937’de laiklik girdi.'],
      ['Hangisi Cumhuriyet’ten önce gerçekleşti?', 'Ankara’nın başkent olması', 'Halifeliğin kaldırılması', 'Halifelik 1924’te kalktı.'],
      ['1924 Anayasası hangi ilkeyi esas aldı?', 'Kuvvetler birliği', 'Kuvvetler ayrılığı', 'TBMM yasama ve yürütmeyi birlikte taşıyordu.'],
    ],
    kontroller: [
      ['Cumhuriyet hangi tarihte ilan edildi?', '29 Ekim 1923', '1 Kasım 1922', '1 Kasım 1922 saltanatın kalktığı gündür.', 4],
      ['Halifelik hangi yıl kaldırıldı?', '1924', '1928', '1928’de Anayasa’dan din maddesi çıktı.', 5],
    ],
  }),

  tarih12Konusu({
    id: 'trh12-hukuk',
    ad: 'Hukuk Alanındaki İnkılaplar',
    kartlar: [
      ['Amaç', 'Dinî hukuktan çağdaş, laik hukuka geçmek.\nTek hukuk, kadın-erkek eşitliği ve hukuki güvence hedeflendi.'],
      ['Mahkemelerin birleştirilmesi', '8 Nisan 1924’te Şer’iye mahkemeleri kaldırıldı.\nMahkemeler birleştirilerek hukuk birliği başladı.'],
      ['Mecelle', 'Osmanlı’nın İslam hukukuna dayanan medeni hukuk derlemesiydi.\n1926’da yürürlükten kalktı.'],
      ['Medeni Kanun', '17 Şubat 1926’da İsviçre Medeni Kanunu’ndan uyarlanarak kabul edildi.\nAile, miras ve kişi hukukunu yeniledi.'],
      ['Medeni Kanun’un yenilikleri', '- **Evlilik:** Resmî nikâh zorunlu oldu.\n- **Çok eşlilik:** Yasaklandı.\n- **Miras:** Kadın ve erkek eşit.\n- **Boşanma:** Mahkeme kararıyla.'],
      ['Diğer kanunlar', '- **Borçlar Kanunu:** İsviçre\n- **Ceza Kanunu:** İtalya\n- **Ceza Muhakemeleri:** Almanya'],
      [
        'Hukuk inkılabının sırası',
        '1924’te mahkemeler birleştirildi.\n1926’da Mecelle’nin yerini Medeni Kanun aldı.',
        {
          tur: 'akis',
          dikey: true,
          adimlar: [
            { ad: '1924', alt: 'Mahkemeler birleşti' },
            { ad: '1926', alt: 'Medeni Kanun' },
            { ad: '1926', alt: 'Ceza, Borçlar kanunu' },
          ],
        },
      ],
      ['Kadının hukuki durumu', 'Medeni Kanun’la kadın, boşanma ve mirasta erkekle eşit oldu.\nSiyasi haklar ise 1930-1934’te ayrıca verildi.'],
      ['Kapitülasyonlar', 'Kapitülasyonlar yabancılara yargı ayrıcalığı tanıyordu.\nLozan’la kalkınca adli bağımsızlık sağlandı.'],
      ['Hukuk birliği', 'Dinî cemaatlere göre değişen hukuk uygulaması kalktı.\nHerkes aynı yasalara bağlandı.'],
    ],
    not: 'Medeni ve Borçlar İsviçre’den, Ceza Kanunu İtalya’dan alındı. Ezberlerken karıştırma.',
    notKarti: 6,
    iddialar: [
      ['Medeni Kanun 1926’da İsviçre’den uyarlanarak kabul edildi.', true, '17 Şubat 1926.'],
      ['Medeni Kanun İtalya’dan alınmıştır.', false, 'Medeni Kanun İsviçre’den uyarlandı.'],
      ['Şer’iye mahkemeleri 1924’te kaldırıldı.', true, 'Mahkemelerin Birleştirilmesi Kanunu.'],
      ['Medeni Kanun’la çok eşlilik serbest bırakıldı.', false, 'Çok eşlilik yasaklandı.'],
      ['Resmî nikâh Medeni Kanun’la zorunlu hâle geldi.', true, 'Evlilik devlet önünde yapılır oldu.'],
      ['Ceza Kanunu İsviçre’den alınmıştır.', false, 'Ceza Kanunu İtalya’dan alındı.'],
      ['Mecelle, Medeni Kanun’un kabulüyle yürürlükten kalktı.', true, 'Mecelle’nin yerini Medeni Kanun aldı.'],
    ],
    secimler: [
      ['Medeni Kanun hangi ülkenin kanunundan alındı?', 'İsviçre', 'Almanya', 'İsviçre Medeni Kanunu uyarlandı.'],
      ['Mecelle’nin yerini hangi kanun aldı?', 'Medeni Kanun', 'Tevhid-i Tedrisat', 'Medeni Kanun 1926.'],
      ['Ceza Kanunu hangi ülkeden alındı?', 'İtalya', 'İsviçre', 'Ceza Kanunu İtalyan modelidir.'],
      ['Şer’iye mahkemeleri hangi yıl kapandı?', '1924', '1928', '1924’te mahkemeler birleştirildi.'],
      ['Hukuk birliğini sağlayan düzenleme?', 'Mahkemelerin birleştirilmesi', 'Soyadı Kanunu', 'Şer’iye mahkemeleri kaldırıldı.'],
    ],
    kontroller: [['Medeni Kanun hangi yıl kabul edildi?', '1926', '1924', '1924’te Şer’iye mahkemeleri kapandı.', 4]],
  }),

  tarih12Konusu({
    id: 'trh12-egitim',
    ad: 'Eğitim ve Kültür Alanındaki İnkılaplar',
    kartlar: [
      ['Tevhid-i Tedrisat', '3 Mart 1924’te tüm okullar Millî Eğitim Bakanlığı’na bağlandı.\nMedreseler kapatıldı.'],
      ['Harf İnkılabı', 'Yeni Türk Harfleri Kanunu 1 Kasım 1928’de kabul edildi.\nLatin esaslı alfabe okuma yazmayı kolaylaştırdı.'],
      ['Millet Mektepleri', 'Halka yeni harfleri öğretmek için açıldı.\nMustafa Kemal “Başöğretmen” unvanını aldı.'],
      ['Türk Tarih Kurumu', '1931’de Türk Tarihi Tetkik Cemiyeti kuruldu.\n1935’te adı Türk Tarih Kurumu oldu.'],
      ['Türk Dil Kurumu', '1932’de Türk Dili Tetkik Cemiyeti kuruldu.\n1936’da adı Türk Dil Kurumu oldu.'],
      ['Halkevleri', 'Türk Ocakları’nın yerine 19 Şubat 1932’de açıldı.\nHalk eğitimini kent ve köylere yaydı.'],
      ['Üniversite reformu', '1933’te Darülfünun kapatılıp İstanbul Üniversitesi kuruldu.\nYabancı bilim insanları üniversitede görev aldı.'],
      ['Ankara’da yüksek öğretim', 'Ankara Dil ve Tarih-Coğrafya Fakültesi 1935’te açıldı.\nTürk tarihi ve dil araştırmaları burada kurumsallaştı.'],
      ['Sanat eğitimi', 'Ankara Devlet Konservatuvarı 1936’da kuruldu.\nSanat, çağdaşlaşmanın parçası sayıldı.'],
      ['Kongre ve kurultay', 'İlk Türk Tarih Kongresi ve ilk Dil Kurultayı 1932’de toplandı.\nİki alanda da resmî bilimsel politika belirlendi.'],
      ['Okuryazarlık', '1927’de okuryazar oranı yaklaşık yüzde 11’di.\nHarf İnkılabı ve Millet Mektepleri bu oranı yükseltmeyi amaçladı.'],
    ],
    not: 'Tevhid-i Tedrisat 1924, Harf İnkılabı 1928, TDK ve Halkevleri 1932, üniversite reformu 1933.',
    notKarti: 3,
    iddialar: [
      ['Tevhid-i Tedrisat Kanunu 3 Mart 1924’te kabul edildi.', true, 'Medreseler kapandı; okullar Maarif’e bağlandı.'],
      ['Harf İnkılabı 1924’te yapıldı.', false, 'Yeni Türk Harfleri Kanunu 1928’de çıktı.'],
      ['Millet Mektepleri yeni harfleri öğretmek için açıldı.', true, 'Mustafa Kemal Başöğretmen oldu.'],
      ['Halkevleri 1923’te açıldı.', false, 'Halkevleri 19 Şubat 1932’de açıldı.'],
      ['Darülfünun 1933’te İstanbul Üniversitesi’ne dönüştürüldü.', true, 'Üniversite reformu 1933’tedir.'],
      ['Türk Dil Kurumu’nun ilk adı olan cemiyet 1931’de kuruldu.', false, 'Türk Dili Tetkik Cemiyeti 1932’de kuruldu.'],
      ['Latin esaslı Türk alfabesi 1928’de kabul edildi.', true, '1 Kasım 1928.'],
    ],
    secimler: [
      ['Medreseleri kapatan düzenleme hangisidir?', 'Tevhid-i Tedrisat', 'Harf Kanunu', '1924 Tevhid-i Tedrisat.'],
      ['Millet Mektepleri neyi öğretmek için açıldı?', 'Yeni harfleri', 'Yabancı dili', 'Latin alfabesi öğretildi.'],
      ['Millet Mektepleri’nin “Başöğretmeni” kimdi?', 'Mustafa Kemal', 'İsmet İnönü', 'Başöğretmen Mustafa Kemal’dir.'],
      ['Darülfünun hangi yıl kapatıldı?', '1933', '1928', '1933 üniversite reformu.'],
      ['Halkevleri hangi kurumun yerine açıldı?', 'Türk Ocakları', 'Millet Mektepleri', 'Türk Ocakları kapandı.'],
      ['Türk Dili Tetkik Cemiyeti hangi yıl kuruldu?', '1932', '1935', '1935 Tarih Kurumu’nun adıdır.'],
    ],
    kontroller: [
      ['Yeni Türk harfleri hangi yıl kabul edildi?', '1928', '1924', '1924 Tevhid-i Tedrisat’tır.', 2],
      ['Üniversite reformu hangi yıl yapıldı?', '1933', '1932', '1932 TDK ve Halkevleri yılıdır.', 7],
    ],
  }),

  tarih12Konusu({
    id: 'trh12-toplumsal',
    ad: 'Toplumsal Alandaki İnkılaplar ve Sağlık',
    kartlar: [
      ['Şapka Kanunu', '25 Kasım 1925’te kabul edildi.\nMustafa Kemal Kastamonu gezisinde (Ağustos 1925) şapka giymişti.'],
      ['Tekke ve zaviyeler', '30 Kasım 1925’te tekke, zaviye ve türbeler kapatıldı.\nTarikat unvanları kaldırıldı.'],
      ['Takvim ve saat', 'Miladi takvim ve uluslararası saat 1925 sonunda kabul edildi.\nUygulama 1 Ocak 1926’da başladı.'],
      ['Ölçüler', 'Metre, kilogram ve litre sistemi 1931’de kanunlaştı.\nArşın ve okka gibi eski ölçüler kalktı.'],
      ['Soyadı Kanunu', '21 Haziran 1934’te kabul edildi.\nTBMM Mustafa Kemal’e 24 Kasım 1934’te “Atatürk” soyadını verdi.'],
      ['Lakap ve unvanlar', '26 Kasım 1934’te efendi, bey, paşa gibi lakap ve unvanlar kaldırıldı.\nHerkes hukuken eşit sayıldı.'],
      ['Kıyafet düzenlemesi', '1934’te din adamlarının ibadet yeri dışında ruhani kıyafet giymesi yasaklandı.\nKıyafette çağdaşlık esas alındı.'],
      ['Hafta tatili', 'Hafta tatili 1935’te Cuma yerine Pazar günü oldu.\nÇalışma hayatı Avrupa ile uyumlandı.'],
      ['Sağlıkta ilk adım', '1920’de Sıhhiye ve Muavenet-i İçtimaiye Vekâleti kuruldu.\nSağlık Bakanlığı Millî Mücadele sırasında doğdu.'],
      ['Umumi Hıfzıssıhha', '1930’da Umumi Hıfzıssıhha Kanunu çıktı.\nKoruyucu hekimlik ve salgınla mücadele yasal dayanağa kavuştu.'],
      ['Salgınlarla mücadele', 'Sıtma, verem ve trahomla mücadele programları yürütüldü.\nSağlık Bakanı Refik Saydam bu çalışmalarda öne çıktı.'],
    ],
    not: 'Kıyafet ve ibadet dışında ruhani giyim yasağı 1934; Şapka Kanunu ise 1925’tir.',
    notKarti: 7,
    iddialar: [
      ['Şapka Kanunu 1925’te kabul edildi.', true, '25 Kasım 1925.'],
      ['Tekke ve zaviyeler 1923’te kapatıldı.', false, '30 Kasım 1925’te kapatıldı.'],
      ['Soyadı Kanunu 1934’te çıktı.', true, '21 Haziran 1934.'],
      ['Hafta tatili Pazar günü yerine Cuma günü yapıldı.', false, '1935’te Cuma yerine Pazar oldu.'],
      ['Atatürk soyadı TBMM tarafından verildi.', true, '24 Kasım 1934.'],
      ['Lakap ve unvanlar 1925’te kaldırıldı.', false, '26 Kasım 1934’te kaldırıldı.'],
      ['Sağlık Bakanlığı 1920’de kuruldu.', true, 'Sıhhiye ve Muavenet-i İçtimaiye Vekâleti 1920’de açıldı.'],
    ],
    secimler: [
      ['Şapka Kanunu hangi yıl çıktı?', '1925', '1934', '1934 Soyadı Kanunu’dur.'],
      ['“Atatürk” soyadını kim verdi?', 'TBMM', 'Millet Mektepleri', '24 Kasım 1934 TBMM kararı.'],
      ['Umumi Hıfzıssıhha Kanunu hangi yıl?', '1930', '1920', '1920’de Sağlık Bakanlığı kuruldu.'],
      ['Hafta tatili hangi güne taşındı?', 'Pazar', 'Cuma', '1935’te Cuma yerine Pazar.'],
      ['Lakap ve unvanlar hangi yıl kaldırıldı?', '1934', '1925', '1925 Şapka Kanunu yılı.'],
      ['Tekke ve zaviyeleri kapatan yıl hangisi?', '1925', '1934', '1934 soyadı ve unvan yılı.'],
    ],
    kontroller: [
      ['Tekke ve zaviyeler hangi yıl kapatıldı?', '1925', '1934', '1934: Soyadı ve unvanlar.', 2],
      ['Soyadı Kanunu hangi yıl çıktı?', '1934', '1925', '1925 Şapka Kanunu.', 5],
    ],
  }),

  tarih12Konusu({
    id: 'trh12-ekonomi',
    ad: 'Ekonomik Alandaki Gelişmeler',
    kartlar: [
      ['İzmir İktisat Kongresi', '17 Şubat-4 Mart 1923’te toplandı.\nMisak-ı İktisadi ile tam bağımsız bir ekonomi hedefi ilan edildi.'],
      ['Kongrenin yönü', 'Yerli üretim ve girişimcilik desteklenecekti.\nKapitülasyon dönemi ekonomik bağımlılığı bitirilecekti.'],
      ['Aşar vergisi', '17 Şubat 1925’te aşar (öşür) vergisi kaldırıldı.\nÇiftçinin yükü hafifledi.'],
      ['İş Bankası', 'Türkiye İş Bankası 26 Ağustos 1924’te kuruldu.\nÖzel girişim ve sermaye birikimi desteklendi.'],
      ['Teşvik-i Sanayi', '1927 Teşvik-i Sanayi Kanunu özel sanayiye arazi ve vergi muafiyeti sağladı.\nYerli sanayi kurulmaya çalışıldı.'],
      ['Kabotaj Kanunu', '1926 tarihli kanunla kıyı ticareti Türk gemilerine ayrıldı.\nKabotaj Bayramı 1 Temmuz’dur.'],
      ['1929 Krizi’nin etkisi', 'Tarım ürünlerinin fiyatları düştü, dış ticaret zorlaştı.\nDevletin ekonomideki rolü arttı.'],
      ['Devletçilik', '1930’ların başında devletçilik ilkesi benimsendi.\n1931’de CHF programına, 1937’de Anayasa’ya girdi.'],
      ['Merkez Bankası ve Sümerbank', 'Merkez Bankası 1930’da kuruldu.\nSümerbank 1933’te kuruldu.'],
      ['I. Beş Yıllık Sanayi Planı', 'Plan 1934’te başladı ve 1938’e kadar sürdü.\nTekstil, şeker ve demir-çelik gibi sanayiler öne çıktı.'],
      ['Demiryolu', 'Yabancı demiryolları satın alındı, yeni hatlar devlet eliyle yapıldı.\nUlaşım, ekonomik bütünleşmenin aracı oldu.'],
      ['II. Beş Yıllık Plan', '1936’da hazırlanan plan II. Dünya Savaşı yüzünden uygulanamadı.\nSavaş ekonominin yönünü değiştirdi.'],
    ],
    not: 'Devletçilik 1929 Krizi’nin sonucudur; 1927 Teşvik-i Sanayi ise özel sanayiyi destekler.',
    notKarti: 8,
    iddialar: [
      ['İzmir İktisat Kongresi 1923’te toplandı.', true, 'Misak-ı İktisadi bu kongrede ilan edildi.'],
      ['Aşar vergisi 1923’te kaldırıldı.', false, '17 Şubat 1925’te kaldırıldı.'],
      ['Teşvik-i Sanayi Kanunu 1927’de çıktı.', true, 'Özel sanayi teşvik edildi.'],
      ['I. Beş Yıllık Sanayi Planı 1923’te uygulandı.', false, 'Plan 1934’te başladı.'],
      ['Sümerbank 1933’te kuruldu.', true, 'Devlet sanayiciliğinin simgesidir.'],
      ['Devletçilik 1923’te benimsendi.', false, '1930’ların başında, kriz sonrasında benimsendi.'],
      ['Kabotaj Kanunu kıyı ticaretini Türklere bıraktı.', true, 'Yabancı gemilerin kıyı ticareti kalktı.'],
      ['Merkez Bankası 1924’te kuruldu.', false, 'Merkez Bankası 1930’da kuruldu.'],
    ],
    secimler: [
      ['Misak-ı İktisadi hangi kongrede ilan edildi?', 'İzmir İktisat Kongresi', 'Sivas Kongresi', 'Şubat 1923’te İzmir’de.'],
      ['Aşar vergisini kaldıran yıl?', '1925', '1930', '1930’da Merkez Bankası kuruldu.'],
      ['İş Bankası hangi yıl kuruldu?', '1924', '1933', '1933 Sümerbank yılı.'],
      ['Devletçiliği öne çıkaran olay?', '1929 Dünya Krizi', 'Lozan Antlaşması', 'Kriz sonrası devlet ekonomiye girdi.'],
      ['I. Beş Yıllık Sanayi Planı hangi yıl başladı?', '1934', '1927', '1927 Teşvik-i Sanayi yılıdır.'],
      ['Kıyı ticaretini Türk gemilerine bırakan kanun?', 'Kabotaj Kanunu', 'Teşvik-i Sanayi', 'Kabotaj 1926.'],
    ],
    kontroller: [
      ['Misak-ı İktisadi nerede ilan edildi?', 'İzmir', 'Ankara', 'İzmir İktisat Kongresi 1923.', 1],
      ['Devletçiliğin benimsenme nedeni?', '1929 Dünya Krizi', 'Balkan Savaşları', 'Kriz sonrası devlet ekonomiye girdi.', 8],
    ],
  }),
]
