import { tarih12Konusu } from './12-tarih-yardimci'

/** 12. sınıf Tarih: XXI. yüzyılın eşiğinde Türkiye ve dünya (2018 programı). */
export const tarih12Kuresel = [
  tarih12Konusu({
    id: 'trh12-sscb',
    ad: 'SSCB’nin Dağılması ve Yeni Devletler',
    kartlar: [
      ['Gorbaçov', 'Mart 1985’te Sovyet lideri oldu.\n“Glasnost” (açıklık) ve “perestroyka” (yeniden yapılanma) politikalarını başlattı.'],
      ['Ekonomik bunalım', 'Silahlanma yarışı ve verimsiz planlı ekonomi SSCB’yi yordu.\nAfganistan savaşı da yük oldu.'],
      ['Afganistan’dan çekilme', 'Sovyet birlikleri Şubat 1989’da Afganistan’dan çekildi.\nSavaş Sovyetler için ağır bir kayıp oldu.'],
      ['Doğu Avrupa devrimleri', '1989’da Polonya, Macaristan, Çekoslovakya, Romanya ve Bulgaristan’da komünist rejimler çöktü.\nSovyet müdahalesi gelmedi.'],
      ['Berlin Duvarı', '9 Kasım 1989’da Berlin Duvarı açıldı.\nAlmanya 3 Ekim 1990’da birleşti.'],
      ['Varşova Paktı', 'Varşova Paktı 1 Temmuz 1991’de feshedildi.\nComecon da dağıldı.'],
      ['Ağustos 1991 darbe girişimi', 'Gorbaçov’a karşı darbe girişimi başarısız oldu.\nYeltsin öne çıktı; Baltık ülkeleri bağımsız oldu.'],
      ['SSCB’nin sonu', '8 Aralık 1991’de Rusya, Ukrayna ve Belarus Bağımsız Devletler Topluluğu’nu (BDT) kurdu.\n25 Aralık 1991’de Gorbaçov istifa etti, SSCB sona erdi.'],
      ['Türk cumhuriyetleri', 'Azerbaycan, Kazakistan, Kırgızistan, Özbekistan ve Türkmenistan 1991’de bağımsızlığını ilan etti.\nTürkiye bu devletleri ilk tanıyan ülkeler arasındaydı.'],
      ['Türkiye’nin girişimleri', 'TİKA 1992’de kuruldu.\nKaradeniz Ekonomik İşbirliği Örgütü de 1992’de oluşturuldu.'],
      ['Karabağ', 'Dağlık Karabağ sorunu 1988’de başladı.\n1994’te ateşkes yapıldı; sorun bağımsız Azerbaycan’ın temel meselesi oldu.'],
      ['Yeni dünya düzeni', 'Soğuk Savaş bitti; ABD tek süper güç olarak kaldı.\n“Yeni dünya düzeni” kavramı bu dönemde yaygınlaştı.'],
    ],
    not: 'Berlin Duvarı 1989, Almanya’nın birleşmesi 1990, SSCB’nin dağılması 1991. Üç yıl art arda.',
    notKarti: 5,
    iddialar: [
      ['Berlin Duvarı 1989’da yıkıldı.', true, '9 Kasım 1989.'],
      ['Almanya 1989’da birleşti.', false, '3 Ekim 1990’da birleşti.'],
      ['Varşova Paktı 1991’de feshedildi.', true, '1 Temmuz 1991.'],
      ['SSCB 1989’da dağıldı.', false, 'SSCB 25 Aralık 1991’de sona erdi.'],
      ['Gorbaçov “glasnost” ve “perestroyka” politikalarını başlattı.', true, 'Açıklık ve yeniden yapılanma.'],
      ['BDT’yi Gorbaçov kurdu.', false, 'Rusya, Ukrayna ve Belarus liderleri kurdu.'],
      ['Türkiye yeni Türk cumhuriyetlerini ilk tanıyan ülkeler arasındaydı.', true, '1991’de tanıdı.'],
      ['TİKA 1980’de kuruldu.', false, '1992’de kuruldu.'],
    ],
    secimler: [
      ['Berlin Duvarı hangi yıl yıkıldı?', '1989', '1991', '1991 SSCB’nin dağılma yılı.'],
      ['Almanya hangi yıl birleşti?', '1990', '1989', '1989 Duvar yılı.'],
      ['“Glasnost” ne demektir?', 'Açıklık', 'Yeniden yapılanma', 'Yeniden yapılanma perestroykadır.'],
      ['SSCB hangi tarihte sona erdi?', '25 Aralık 1991', '9 Kasım 1989', '9 Kasım Duvar’ın açıldığı gündür.'],
      ['SSCB’nin dağılmasıyla hangi topluluk kuruldu?', 'BDT', 'NATO', 'BDT.'],
      ['TİKA hangi yıl kuruldu?', '1992', '1985', '1992.'],
    ],
    kontroller: [
      ['Glasnost ne anlama gelir?', 'Açıklık', 'Yeniden yapılanma', 'Yeniden yapılanma perestroyka’dır.', 1],
      ['SSCB hangi yıl dağıldı?', '1991', '1989', '1989’da Berlin Duvarı yıkıldı.', 8],
    ],
  }),

  tarih12Konusu({
    id: 'trh12-asya-kuresel',
    ad: 'Asya’da Yeni Yapılanma ve Küreselleşme',
    kartlar: [
      ['Çin’de reformlar', '1978’de Deng Xiaoping reformları başladı.\nÇin dışa açıldı ve hızlı ekonomik büyüme yaşadı.'],
      ['Hong Kong', 'Hong Kong 1997’de İngiltere’den Çin’e devredildi.\n“Bir ülke, iki sistem” ilkesi benimsendi.'],
      ['Asya Kaplanları', 'Güney Kore, Tayvan, Singapur ve Hong Kong ihracata dayalı hızla sanayileşti.\nBu ülkelere Asya Kaplanları denir.'],
      ['Asya krizi', 'Temmuz 1997’de Tayland’da başlayan mali kriz bölgeye yayıldı.\nPara birimleri değer kaybetti.'],
      ['Küreselleşme', 'Ticaret, iletişim ve sermaye hareketleri sınırları aştı.\nİnternet bilgiyi hızla yaydı.'],
      ['Dünya Ticaret Örgütü', '1995’te GATT’ın yerine kuruldu.\nUluslararası ticaretin kurallarını belirler.'],
      ['Bölgesel birlikler', 'ASEAN 1967, APEC 1989 ve NAFTA 1994’te işlerlik kazandı.\nBölgesel ekonomik bütünleşme hız kazandı.'],
      ['Çevre antlaşmaları', 'BM Rio Zirvesi 1992’de toplandı.\nKyoto Protokolü 1997’de iklim değişikliğine karşı imzalandı.'],
      ['Küresel sorunlar', 'İklim değişikliği, çevre kirliliği, terör, göç ve açlık ulusal sınırları aşan sorunlardır.\nÇözüm uluslararası iş birliği gerektirir.'],
      ['Binyıl hedefleri', 'BM 2000’de Binyıl Kalkınma Hedefleri’ni açıkladı.\nHedefler arasında yoksulluğun azaltılması vardı.'],
    ],
    not: 'Rio Zirvesi 1992, Kyoto Protokolü 1997’dir. İkisini aynı yılda hatırlama.',
    notKarti: 8,
    iddialar: [
      ['Dünya Ticaret Örgütü 1995’te kuruldu.', true, 'GATT’ın yerini aldı.'],
      ['Kyoto Protokolü 1992’de imzalandı.', false, 'Kyoto 1997; Rio Zirvesi 1992’dedir.'],
      ['Hong Kong 1997’de Çin’e devredildi.', true, 'İngiltere devretti.'],
      ['Asya krizi 1987’de başladı.', false, 'Kriz Temmuz 1997’de Tayland’da başladı.'],
      ['Çin’de reformlar 1978’de başladı.', true, 'Deng Xiaoping dönemi.'],
      ['Dünya Ticaret Örgütü GATT’tan önce kuruldu.', false, 'GATT önceydi, DTÖ 1995’te onun yerine kuruldu.'],
      ['Güney Kore, Asya Kaplanları arasında sayılır.', true, 'İhracata dayalı sanayileşme.'],
    ],
    secimler: [
      ['Dünya Ticaret Örgütü hangi yıl kuruldu?', '1995', '1989', '1995.'],
      ['Hong Kong hangi devlete devredildi?', 'Çin', 'Japonya', 'Çin.'],
      ['BM Rio Zirvesi hangi yıl toplandı?', '1992', '1997', '1997 Kyoto.'],
      ['Çin’de reformları kim başlattı?', 'Deng Xiaoping', 'Mao', 'Deng.'],
      ['Asya Kaplanları hangi özelliğiyle bilinir?', 'İhracata dayalı büyüme', 'İthal ikamesi', 'İhracat.'],
    ],
    kontroller: [['Hong Kong hangi yıl Çin’e devredildi?', '1997', '1978', '1978 Çin’in reform yılıdır.', 2]],
  }),

  tarih12Konusu({
    id: 'trh12-balkan-ortadogu',
    ad: 'Balkanlar ve Orta Doğu’da Yeni Dönem',
    kartlar: [
      ['Yugoslavya’nın dağılması', 'Slovenya ve Hırvatistan 1991’de bağımsızlığını ilan etti.\nÇatışmalar 1990’lar boyunca sürdü.'],
      ['Bosna Savaşı', '1992-1995 arasında sürdü.\nBosnalı Müslümanlara karşı soykırıma varan saldırılar yapıldı.'],
      ['Srebrenitsa', 'Temmuz 1995’te Srebrenitsa’da yaklaşık 8 bin Boşnak katledildi.\nOlay soykırım olarak kabul edilir.'],
      ['Dayton Antlaşması', 'Kasım 1995’te Dayton’da parafe edildi, Aralık 1995’te Paris’te imzalandı.\nBosna-Hersek tek devlet olarak korundu.'],
      ['Kosova', '1998-1999 arasında çatışmalar çıktı.\nNATO 1999’da Sırbistan’ı bombaladı; Kosova 2008’de bağımsızlığını ilan etti.'],
      ['Türkiye ve Balkanlar', 'Türkiye 1990’larda Bosna’ya insani ve diplomatik destek verdi.\nBM barış gücüne katkı sağladı.'],
      ['Körfez Savaşı', '2 Ağustos 1990’da Irak Kuveyt’i işgal etti.\nOcak 1991’de ABD önderliğindeki koalisyon Irak’ı Kuveyt’ten çıkardı.'],
      ['Barış girişimleri', '1991’de Madrid Konferansı toplandı.\n1993 Oslo Anlaşmaları İsrail-Filistin barışını hedefledi.'],
      ['Afganistan', 'Sovyet çekilişinden sonra iç savaş çıktı.\nTaliban 1996’da Kabil’i aldı.'],
      ['11 Eylül 2001', 'ABD’de ikiz kulelere saldırı düzenlendi.\nABD “terörle mücadele” adıyla Ekim 2001’de Afganistan’a girdi.'],
      ['Irak’ın işgali', 'Mart 2003’te ABD ve müttefikleri Irak’a girdi.\nTürkiye Meclisi tezkereyi reddetti.'],
    ],
    not: 'Bosna Savaşı 1992-1995, Kosova çatışması 1998-1999. Dayton ise Bosna’yı bitirir.',
    notKarti: 4,
    iddialar: [
      ['Bosna Savaşı 1992-1995 arasında sürdü.', true, 'Dayton ile sona erdi.'],
      ['Dayton Antlaşması 1991’de imzalandı.', false, 'Dayton 1995’tir.'],
      ['Irak 1990’da Kuveyt’i işgal etti.', true, '2 Ağustos 1990.'],
      ['Taliban 1996’da Bağdat’ı aldı.', false, 'Taliban Kabil’i aldı.'],
      ['İkiz kulelere saldırı 2001’de yapıldı.', true, '11 Eylül 2001.'],
      ['Türkiye Meclisi 2003’te ABD tezkeresini kabul etti.', false, 'Tezkere reddedildi.'],
      ['Kosova 2008’de bağımsızlığını ilan etti.', true, '17 Şubat 2008.'],
    ],
    secimler: [
      ['Dayton Antlaşması hangi savaşı sona erdirdi?', 'Bosna Savaşı', 'Kosova çatışması', 'Bosna Savaşı.'],
      ['Srebrenitsa katliamı hangi yıl yaşandı?', '1995', '1992', '1992 Bosna Savaşı’nın başlangıcı.'],
      ['Körfez Savaşı’nın nedeni nedir?', 'Irak’ın Kuveyt’i işgali', 'İran Devrimi', 'Irak.'],
      ['Taliban Kabil’i hangi yıl aldı?', '1996', '2001', '2001 ABD müdahalesi.'],
      ['ABD Afganistan’a hangi yıl girdi?', '2001', '2003', '2003 Irak.'],
      ['Oslo Anlaşmaları hangi taraflar arasındadır?', 'İsrail ve Filistin', 'Mısır ve İsrail', 'Oslo, 1993.'],
    ],
    kontroller: [
      ['Bosna Savaşı hangi yıllar arasında sürdü?', '1992-1995', '1998-1999', '1998-1999 Kosova’dır.', 4],
      ['11 Eylül saldırıları hangi yıl yapıldı?', '2001', '2003', '2003 Irak’ın işgalidir.', 10],
    ],
  }),

  tarih12Konusu({
    id: 'trh12-ab-turkiye',
    ad: 'Türkiye ve Avrupa Birliği',
    kartlar: [
      ['Roma Antlaşması', '1957’de Avrupa Ekonomik Topluluğu (AET) kuruldu.\nAB’nin temeli bu topluluktur.'],
      ['Ankara Anlaşması', 'Türkiye 1959’da AET’ye ortaklık başvurusu yaptı.\n12 Eylül 1963’te Ankara Anlaşması imzalandı.'],
      ['Katma Protokol', '1970 Katma Protokolü gümrük birliği takvimini belirledi.\nTürkiye adım adım bütünleşmeyi kabul etti.'],
      ['Tam üyelik başvurusu', 'Türkiye 14 Nisan 1987’de tam üyelik başvurusu yaptı.\nKıbrıs ve insan hakları sorunları süreci zorlaştırdı.'],
      ['Maastricht', '1992 Maastricht Antlaşması ile AB kuruldu (yürürlük 1993).\nOrtak para ve ortak politikalar öngörüldü.'],
      ['Kopenhag Kriterleri', '1993’te belirlendi.\nDemokrasi, hukuk devleti, insan hakları ve işleyen piyasa ekonomisi şartı getirdi.'],
      ['Gümrük Birliği', 'Türkiye-AB Gümrük Birliği 1 Ocak 1996’da yürürlüğe girdi.\nTürkiye üye olmadan gümrük birliğine giren ilk ülke oldu.'],
      ['Lüksemburg (1997)', '1997 Lüksemburg Zirvesi Türkiye’yi aday ilan etmedi.\nİlişkiler bir süre gerildi.'],
      ['Helsinki (1999)', 'Aralık 1999 Helsinki Zirvesi Türkiye’ye adaylık statüsü verdi.\nKopenhag Kriterleri uygulanacaktı.'],
      ['Müzakere süreci', '3 Ekim 2005’te katılım müzakereleri başladı.\nÜyelik hedefi sürdü.'],
    ],
    not: 'Aday ilan edilme: Lüksemburg (1997) hayır, Helsinki (1999) evet. İkisini yer değiştirme.',
    notKarti: 8,
    iddialar: [
      ['Ankara Anlaşması 1963’te imzalandı.', true, '12 Eylül 1963.'],
      ['Roma Antlaşması 1963’te imzalandı.', false, 'Roma Antlaşması 1957’dir.'],
      ['Gümrük Birliği 1996’da yürürlüğe girdi.', true, '1 Ocak 1996.'],
      ['Türkiye Lüksemburg’da (1997) aday ilan edildi.', false, 'Aday ilan edilmesi Helsinki’de (1999).'],
      ['Helsinki Zirvesi Türkiye’ye adaylık statüsü verdi.', true, 'Aralık 1999.'],
      ['Maastricht Antlaşması 1957’de imzalandı.', false, 'Maastricht 1992’dir.'],
      ['Kopenhag Kriterleri demokrasi ve hukuk devleti şartı getirir.', true, '1993.'],
    ],
    secimler: [
      ['Türkiye tam üyelik başvurusunu hangi yıl yaptı?', '1987', '1963', '1963 Ankara Anlaşması.'],
      ['Aday statüsü hangi zirvede verildi?', 'Helsinki', 'Lüksemburg', 'Helsinki, 1999.'],
      ['Gümrük Birliği hangi yıl yürürlüğe girdi?', '1996', '1987', '1996.'],
      ['Ankara Anlaşması hangi topluluğa ortaklık sağladı?', 'AET', 'NATO', 'AET.'],
      ['Maastricht Antlaşması neyi kurdu?', 'AB’yi', 'NATO’yu', 'AB.'],
    ],
    kontroller: [['Ankara Anlaşması hangi yıl imzalandı?', '1963', '1987', '1987 tam üyelik başvurusu yılıdır.', 2]],
  }),

  tarih12Konusu({
    id: 'trh12-tr-1980-sonrasi',
    ad: 'Türkiye: 1980 Sonrası',
    kartlar: [
      ['24 Ocak 1980 kararları', 'Turgut Özal’ın hazırladığı istikrar programıdır.\nİthal ikamesinden dışa açık, piyasa ekonomisine geçildi.'],
      ['12 Eylül yönetimi', 'Millî Güvenlik Konseyi (Kenan Evren) 1980-1983 arasında yönetti.\nSiyasi partiler kapatıldı.'],
      ['1982 Anayasası', '7 Kasım 1982’de halk oylamasıyla kabul edildi.\nKenan Evren Cumhurbaşkanı oldu.'],
      ['1983 seçimleri', '6 Kasım 1983’te ANAP birinci oldu.\nTurgut Özal Başbakan oldu.'],
      ['KKTC', '15 Kasım 1983’te Kuzey Kıbrıs Türk Cumhuriyeti ilan edildi.\nYalnızca Türkiye tarafından tanınır.'],
      ['Dışa açılma', 'İhracata dayalı büyüme, dış ticaretin serbestleşmesi ve özelleştirme başladı.\nSerbest piyasa ekonomisi ağırlık kazandı.'],
      ['AET başvurusu', 'Türkiye 1987’de AET’ye tam üyelik başvurusu yaptı.\nKıbrıs sorunu süreci zorladı.'],
      ['Özal Cumhurbaşkanı', 'Özal 9 Kasım 1989’da Cumhurbaşkanı seçildi.\nKörfez Krizi’nde etkin bir dış politika izledi.'],
      ['Körfez Savaşı etkisi', 'Türkiye Irak’a ambargo uyguladı.\nKuzey Irak’tan Türkiye’ye büyük göç yaşandı.'],
      ['1990’lar', 'Koalisyon hükümetleri ve istikrarsızlık dönemiydi.\nTerör, enflasyon ve 1994 ile 2001 ekonomik krizleri yaşandı.'],
    ],
    not: '24 Ocak 1980 kararları ile 12 Eylül 1980 darbesi iki ayrı olay ve iki ayrı tarihtir.',
    notKarti: 1,
    iddialar: [
      ['24 Ocak 1980 kararları dışa açık ekonomiyi hedefledi.', true, 'İthal ikamesi terk edildi.'],
      ['1982 Anayasası 1980’de kabul edildi.', false, '7 Kasım 1982’de halk oylamasıyla kabul edildi.'],
      ['KKTC 1983’te ilan edildi.', true, '15 Kasım 1983.'],
      ['Özal 1983’te Cumhurbaşkanı seçildi.', false, '1983’te Başbakan, 1989’da Cumhurbaşkanı oldu.'],
      ['Türkiye AET’ye tam üyelik başvurusunu 1987’de yaptı.', true, '14 Nisan 1987.'],
      ['Millî Güvenlik Konseyi 1987’ye kadar yönetti.', false, '1983’e kadar yönetti.'],
      ['1982 Anayasası halk oylamasıyla kabul edildi.', true, '7 Kasım 1982.'],
    ],
    secimler: [
      ['24 Ocak kararlarının mimarı kimdir?', 'Turgut Özal', 'Süleyman Demirel', 'Özal.'],
      ['KKTC hangi yıl ilan edildi?', '1983', '1974', '1974 Barış Harekâtı yılıdır.'],
      ['Özal hangi yıl Cumhurbaşkanı oldu?', '1989', '1983', '1983 Başbakanlık.'],
      ['1982 Anayasası ile Cumhurbaşkanı kim oldu?', 'Kenan Evren', 'Cemal Gürsel', 'Evren.'],
      ['24 Ocak 1980 ile terk edilen model?', 'İthal ikamesi', 'İhracata dayalı büyüme', 'İthal ikamesi.'],
    ],
    kontroller: [['24 Ocak 1980 kararlarının hedefi?', 'Dışa açık ekonomi', 'İthal ikamesi', 'İthal ikamesi eski modeldir.', 1]],
  }),
]
