import { tarih12Konusu } from './12-tarih-yardimci'

/** 12. sınıf Tarih, 1. ünite grubu: Mustafa Kemal’in hayatı ve Millî Mücadele (2018 programı). */
export const tarih12Mucadele = [
  tarih12Konusu({
    id: 'trh12-genclik',
    ad: 'Mustafa Kemal’in Hayatı (1881-1918)',
    kartlar: [
      ['Doğum ve aile', 'Selanik’te doğdu.\nBabası Ali Rıza Efendi, annesi Zübeyde Hanım’dır; ilk okulu Şemsi Efendi Mektebi’dir.'],
      ['Askerî okullar', '- **Selanik Askerî Rüştiyesi:** 1893\n- **Manastır Askerî İdadisi:** 1895\n- **Harp Okulu (İstanbul):** 1899\n- **Harp Akademisi:** 1902'],
      ['Mustafa Kemal adı', 'Rüştiye yıllarında matematik öğretmeni Mustafa Bey ona “Kemal” adını verdi.\nBaşarısı ve olgunluğu bu adın nedeni sayılır.'],
      ['Subaylığa başlangıç', '1905’te kurmay yüzbaşı olarak Harp Akademisi’nden mezun oldu.\nGörev yeri Şam’daki Beşinci Ordu’ydu.'],
      ['Vatan ve Hürriyet', 'Şam’da gizli Vatan ve Hürriyet cemiyetini kurdu.\nAmaç, II. Abdülhamid’in baskı yönetimine karşı çıkmaktı.'],
      ['Trablusgarp ve Balkanlar', '1911’de Trablusgarp’ta İtalyanlara karşı savaştı; Tobruk ve Derne’de görev aldı.\n1912-1913’te Balkan Savaşı’nda Gelibolu ve Bolayır’da bulundu.'],
      ['Sofya ataşeliği', '1913-1915 arasında Sofya’da askerî ataşe olarak görev yaptı.\nI. Dünya Savaşı’nın başlangıcını bu görevden izledi.'],
      ['Çanakkale (1915)', '19. Tümen Komutanı olarak Arıburnu ve Conkbayırı’nda çıkarmayı durdurdu.\nAğustos 1915’te Anafartalar Grup Komutanı oldu.'],
      ['Kafkas ve Suriye', '1916’da 16. Kolordu Komutanı olarak Muş ve Bitlis’i geri aldı; aynı yıl general (paşa) oldu.\n1918’de Yedinci Ordu Komutanı olarak Suriye’de görev yaptı.'],
      ['İstanbul’a dönüş', 'Mondros Ateşkesi’nden sonra 13 Kasım 1918’de İstanbul’a geldi.\nİşgalin başladığı bu günlerde millî direniş fikrini olgunlaştırdı.'],
    ],
    not: 'Cepheleri sırala: Trablusgarp (1911), Balkanlar (1912), Çanakkale (1915), Kafkaslar (1916), Suriye (1918).',
    notKarti: 6,
    iddialar: [
      ['Mustafa Kemal 1905’te Harp Akademisi’nden kurmay yüzbaşı olarak mezun oldu.', true, 'Mezuniyet yılı 1905’tir.'],
      ['Mustafa Kemal Trablusgarp’ta Fransızlara karşı savaştı.', false, '1911-1912’de Trablusgarp’ı işgal eden İtalyanlara karşı savaştı.'],
      ['Mustafa Kemal bir dönem Sofya’da askerî ataşe olarak görev yaptı.', true, '1913-1915 arasında Sofya’daydı.'],
      ['Vatan ve Hürriyet cemiyeti İstanbul’da kuruldu.', false, 'Mustafa Kemal cemiyeti Şam’da kurdu.'],
      ['Muş ve Bitlis’i geri alan Mustafa Kemal 16. Kolordu Komutanı’ydı.', true, '1916’da Kafkas cephesinde bu görevdeydi.'],
      ['Mustafa Kemal 1893’te Harp Okulu’na girdi.', false, '1893 Selanik Askerî Rüştiyesi’dir; Harp Okulu’na 1899’da girdi.'],
      ['Mustafa Kemal Anafartalar Grup Komutanlığı yaptı.', true, 'Çanakkale’de Ağustos 1915’te bu göreve getirildi.'],
    ],
    secimler: [
      ['Mustafa Kemal Trablusgarp’ta hangi devletin ordusuna karşı savaştı?', 'İtalya', 'Fransa', '1911 Trablusgarp Savaşı İtalya’yla yapıldı.'],
      ['Gizli Vatan ve Hürriyet cemiyeti hangi kentte kuruldu?', 'Şam', 'Manastır', 'Mustafa Kemal cemiyeti Şam’da kurdu.'],
      ['Mustafa Kemal 1915’te hangi cephede ün kazandı?', 'Çanakkale', 'Sarıkamış', 'Arıburnu ve Anafartalar Çanakkale’dedir.'],
      ['Muş ve Bitlis hangi cephede geri alındı?', 'Kafkas', 'Irak', '1916 Kafkas cephesi: 16. Kolordu.'],
      ['Mustafa Kemal İstanbul’a hangi tarihte geldi?', '13 Kasım 1918', '30 Ekim 1918', '30 Ekim 1918 Mondros’un imza günüdür.'],
    ],
    kontroller: [['Mustafa Kemal 1905’te hangi okuldan mezun oldu?', 'Harp Akademisi', 'Harp Okulu', 'Harp Okulu 1899’da bitti; kurmaylık 1905’te.', 4]],
  }),

  tarih12Konusu({
    id: 'trh12-mondros',
    ad: 'Mondros Ateşkesi ve İşgaller',
    kartlar: [
      ['Mondros Ateşkesi', '30 Ekim 1918’de Limni Adası’ndaki Mondros Limanı’nda imzalandı.\nOsmanlı adına Bahriye Nazırı Rauf Orbay imzaladı.'],
      ['Ağır maddeler', '- **1. madde:** Boğazlar açıldı, istihkâmlar İtilaf’a geçti.\n- **7. madde:** İtilaf stratejik yerleri işgal edebilecekti.\n- **24. madde:** Altı vilayette karışıklıkta işgal hakkı.'],
      ['İtilaf’ın niyeti', 'Ateşkes süresiz ve belirsiz maddelerle yazılmıştı.\nİtilaf Devletleri bu maddeleri işgal gerekçesi yaptı.'],
      ['Gizli paylaşım planları', 'Savaş sırasında Sykes-Picot (1916) ve Saint-Jean-de-Maurienne (1917) gibi gizli anlaşmalar yapılmıştı.\nOsmanlı toprakları paylaşılacaktı.'],
      ['İngiliz ve Fransız işgali', 'İngilizler Musul, Urfa, Maraş ve Antep’e girdi.\nFransızlar Adana ve Kilikya’yı, İstanbul’u ise İtilaf donanması işgal etti.'],
      ['İtalyan işgali', 'İtalya Antalya, Konya ve Muğla çevresini işgal etti.\nİtalya, Londra Antlaşması’yla (1915) bu bölgelere söz almıştı.'],
      ['İzmir’in işgali', '15 Mayıs 1919’da Yunan ordusu İzmir’e çıktı.\nİşgale ilk kurşunu gazeteci Hasan Tahsin sıktı.'],
      ['Wilson İlkeleri', 'ABD Başkanı Wilson 1918’de 14 madde yayımladı.\n12. madde, Türk çoğunluklu bölgelerin egemenliğini güvence altına alıyordu.'],
      ['Millî cemiyetler', 'İzmir Müdafaa-i Hukuk, Kilikyalılar ve Trakya-Paşaeli cemiyetleri işgale yerel tepkiyi örgütledi.\nBu cemiyetler daha sonra tek çatıda birleşti.'],
      ['Kuvayımilliye', 'Düzensiz yerel direniş birlikleri Kuvayımilliye adını aldı.\nAydın, Ayvalık, Antep, Maraş ve Urfa’daki direnişler örnektir.'],
    ],
    not: 'Madde 7 ile 24’ü karıştırma: 7 genel işgal hakkı, 24 yalnız altı vilayet için işgal hakkıdır.',
    notKarti: 2,
    iddialar: [
      ['Mondros Ateşkesi 30 Ekim 1918’de imzalandı.', true, 'Mondros Limanı’nda, 30 Ekim 1918’de.'],
      ['Mondros’un 7. maddesi İtilaf Devletleri’ne stratejik yerleri işgal hakkı veriyordu.', true, 'İşgallerin hukuki bahanesi buydu.'],
      ['İzmir’i ilk işgal eden devlet İtalya’dır.', false, '15 Mayıs 1919’da İzmir’i Yunan ordusu işgal etti.'],
      ['Wilson İlkeleri Türk çoğunluklu bölgelerin egemenliğini içeriyordu.', true, '12. madde bunu güvence altına alıyordu.'],
      ['Mondros Ateşkesi Rauf Orbay’ın başkanlığında İzmir’de imzalandı.', false, 'Mondros Limanı’nda (Limni) bir savaş gemisinde imzalandı.'],
      ['Sykes-Picot Antlaşması 1916’da yapıldı.', true, 'İngiltere ve Fransa’nın gizli paylaşım anlaşmasıdır.'],
      ['Kuvayımilliye, düzenli ordu birliklerinin adıdır.', false, 'Kuvayımilliye düzensiz yerel direniş birlikleridir.'],
    ],
    secimler: [
      ['Mondros’u Osmanlı adına kim imzaladı?', 'Rauf Orbay', 'Mustafa Kemal', 'Bahriye Nazırı Rauf Orbay imzaladı.'],
      ['İzmir’i hangi devlet işgal etti?', 'Yunanistan', 'İtalya', '15 Mayıs 1919’da Yunan ordusu çıktı.'],
      ['Altı vilayette karışıklık halinde işgal hakkı hangi maddedir?', '24. madde', '7. madde', '24. madde altı vilayetle ilgilidir.'],
      ['Hasan Tahsin’in ünü nedendir?', 'İzmir’de ilk kurşunu sıkması', 'Mondros’u imzalaması', 'Yunan işgaline ilk tepkiyi o gösterdi.'],
      ['Antalya ve Konya çevresini hangi devlet işgal etti?', 'İtalya', 'Fransa', 'Antalya, Konya, Muğla İtalyan işgalindeydi.'],
    ],
    kontroller: [['Wilson İlkeleri hangi yıl yayımlandı?', '1918', '1922', 'ABD Başkanı Wilson 1918’de 14 maddeyi açıkladı.', 8]],
  }),

  tarih12Konusu({
    id: 'trh12-hazirlik',
    ad: 'Millî Mücadele’nin Hazırlık Dönemi',
    kartlar: [
      ['Samsun’a çıkış (1919)', 'Mustafa Kemal 9. Ordu Müfettişi olarak Bandırma Vapuru’yla İstanbul’dan çıktı.\n19 Mayıs 1919’da Samsun’a ulaştı.'],
      ['Havza Genelgesi', 'Mayıs 1919’da işgalleri protesto için mitingler düzenlenmesi istendi.\nHalkın örgütlenmesi başladı.'],
      ['Amasya Genelgesi', '22 Haziran 1919’da yayımlandı.\n“Milletin istiklalini yine milletin azim ve kararı kurtaracaktır” sözü bu belgededir.'],
      ['Amasya’nın kararları', '- **Tehlike:** Vatanın bütünlüğü ve istiklal tehlikede.\n- **Çare:** İstanbul’daki hükûmet sorumluluğunu yerine getirmiyor.\n- **Hedef:** Sivas’ta millî kongre.'],
      ['Erzurum Kongresi', '23 Temmuz-7 Ağustos 1919 arasında toplandı; bölgeseldir.\nManda ve himaye kabul edilmedi, Mustafa Kemal başkanlığa seçildi.'],
      ['Sivas Kongresi', '4-11 Eylül 1919’da toplandı; ulusaldır.\nAnadolu ve Rumeli Müdafaa-i Hukuk Cemiyeti kuruldu, Heyet-i Temsiliye seçildi.'],
      ['Kongrelerin ortak ilkesi', 'Millî sınırlar içinde vatan bir bütündür.\nManda ve himaye reddedildi; kuvvet olarak Kuvayımilliye, hâkim olarak millî irade benimsendi.'],
      ['Amasya Görüşmeleri', 'Ekim 1919’da Bahriye Nazırı Salih Paşa ile Heyet-i Temsiliye görüştü.\nİstanbul Hükûmeti Heyet’i fiilen tanımış oldu.'],
      ['Ankara’ya geçiş', 'Aralık 1919’da Heyet-i Temsiliye Ankara’ya taşındı.\nAnkara, Millî Mücadele’nin siyasi ve askerî merkezi oldu.'],
      ['Misak-ı Millî (1920)', 'Son Osmanlı Mebusan Meclisi 28 Ocak 1920’de kabul etti.\nMondros sınırları içindeki Türk yurdunun bölünmezliği ilan edildi.'],
    ],
    not: 'Erzurum bölgesel, Sivas ulusal kongredir. İkisi de manda ve himayeyi reddetti.',
    notKarti: 5,
    iddialar: [
      ['Amasya Genelgesi 22 Haziran 1919’da yayımlandı.', true, 'Genelge Haziran 1919’da Amasya’da yayımlandı.'],
      ['Erzurum Kongresi ulusal bir kongredir.', false, 'Erzurum bölgesel, Sivas ulusal kongredir.'],
      ['Heyet-i Temsiliye Sivas Kongresi’nde seçildi.', true, 'Sivas’ta tüm yurt adına Heyet-i Temsiliye belirlendi.'],
      ['Mustafa Kemal 19 Mayıs 1919’da Trabzon’a çıktı.', false, '19 Mayıs 1919’da Samsun’a çıktı.'],
      ['Misak-ı Millî Mebusan Meclisi tarafından kabul edildi.', true, 'Son Osmanlı Mebusan Meclisi 28 Ocak 1920’de kabul etti.'],
      ['Sivas Kongresi’nde manda ve himaye fikri kabul edildi.', false, 'Manda ve himaye Erzurum ve Sivas’ta reddedildi.'],
      ['Havza Genelgesi’nin amacı işgalleri protesto etmektir.', true, 'Mitingler ve protestolar istendi.'],
    ],
    secimler: [
      ['Anadolu ve Rumeli Müdafaa-i Hukuk Cemiyeti hangi kongrede kuruldu?', 'Sivas', 'Erzurum', 'Sivas’ta tüm cemiyetler birleştirildi.'],
      ['“Milletin istiklalini yine milletin azim ve kararı kurtaracaktır” hangi belgede?', 'Amasya Genelgesi', 'Havza Genelgesi', 'Amasya Genelgesi 22 Haziran 1919.'],
      ['Mustafa Kemal hangi gemiyle Samsun’a gitti?', 'Bandırma', 'Gülcemal', 'Bandırma Vapuru ile gitti.'],
      ['Heyet-i Temsiliye Ankara’ya hangi ay taşındı?', 'Aralık 1919', 'Mayıs 1919', 'Aralık 1919’da Ankara’ya geçildi.'],
      ['Amasya Görüşmeleri’nde İstanbul Hükûmeti adına kim vardı?', 'Salih Paşa', 'Damat Ferit', 'Bahriye Nazırı Salih Paşa görüştü.'],
    ],
    kontroller: [['İlk bölgesel kongre hangisidir?', 'Erzurum', 'Sivas', 'Erzurum 23 Temmuz 1919’da toplandı.', 5]],
  }),

  tarih12Konusu({
    id: 'trh12-tbmm',
    ad: 'TBMM’nin Açılışı ve İç Ayaklanmalar',
    kartlar: [
      ['İstanbul’un işgali', '16 Mart 1920’de İtilaf Devletleri İstanbul’u resmen işgal etti.\nMeclis-i Mebusan dağıldı, bazı mebuslar Malta’ya sürüldü.'],
      ['Meclisin Ankara’da açılışı', '23 Nisan 1920’de Büyük Millet Meclisi Ankara’da açıldı.\nMustafa Kemal meclis başkanı seçildi.'],
      ['Meclisin niteliği', 'Yasama ve yürütme yetkisi Meclis’te toplandı.\nİcra Vekilleri Heyeti, Meclis içinden seçildi.'],
      ['Teşkilat-ı Esasiye (1921)', '20 Ocak 1921’de kabul edilen ilk anayasadır.\n“Hâkimiyet bilâ kaydü şart milletindir” ilkesi yer alır.'],
      ['İç isyanlar', 'Yozgat, Bolu-Düzce, Konya (Delibaba) ve Anzavur gibi ayaklanmalar çıktı.\nBazıları Halife ordusu olarak bilinen Kuvayı İnzibatiye ile bağlantılıydı.'],
      ['Ayaklananlara tepki', 'Meclis ayaklanmaları bastırmak için askerî güç kullandı.\nİstiklal Mahkemeleri de bu süreçte devreye girdi.'],
      ['Sevr Antlaşması', '10 Ağustos 1920’de İstanbul Hükûmeti Sevr’i imzaladı.\nTBMM, Sevr’i tanımadı ve imzalayanları vatan haini saydı.'],
      ['Sevr’in hükümleri', '- Boğazlar uluslararası denetime geçiyordu.\n- İzmir ve çevresi Yunan yönetimine bırakılıyordu.\n- Doğu Anadolu’da Ermenistan kurulması öngörülüyordu.'],
      ['Sevr’in sonucu', 'Sevr hiç yürürlüğe girmedi.\nMillî Mücadele bu kez TBMM’nin hükûmeti olarak yürütüldü.'],
      ['Düzenli orduya geçiş', 'Kuvayımilliye yerine düzenli ordu kuruldu.\nÇerkez Ethem olayı sonrası merkezî komuta güçlendi.'],
    ],
    not: 'Sevr’i İstanbul Hükûmeti imzaladı ama TBMM kabul etmedi; Sevr yürürlüğe girmedi.',
    notKarti: 7,
    iddialar: [
      ['TBMM 23 Nisan 1920’de Ankara’da açıldı.', true, 'Mustafa Kemal meclis başkanı seçildi.'],
      ['Sevr Antlaşması TBMM tarafından onaylanmıştır.', false, 'TBMM Sevr’i reddetti; yürürlüğe girmedi.'],
      ['Teşkilat-ı Esasiye Kanunu 1921’de kabul edildi.', true, '20 Ocak 1921’de ilk anayasa kabul edildi.'],
      ['İstanbul’un resmen işgali 16 Mart 1920’de gerçekleşti.', true, 'Meclis-i Mebusan bu işgalden sonra dağıldı.'],
      ['TBMM’de yasama ve yürütme yetkisi ayrı organlardadır.', false, 'Meclis’te toplanmıştı; kuvvetler birliği vardı.'],
      ['Sevr Antlaşması’nı TBMM Hükûmeti imzalamıştır.', false, 'İstanbul Hükûmeti imzaladı.'],
      ['Sevr, Boğazları uluslararası denetime bırakıyordu.', true, 'Sevr’in en ağır maddelerinden biridir.'],
    ],
    secimler: [
      ['TBMM hangi ilk anayasayı kabul etti?', 'Teşkilat-ı Esasiye', 'Kanun-ı Esasi', '1921’de Teşkilat-ı Esasiye kabul edildi.'],
      ['Sevr Antlaşması hangi tarihte imzalandı?', '10 Ağustos 1920', '23 Nisan 1920', 'Sevr, 10 Ağustos 1920.'],
      ['TBMM hangi ilkeyi benimsedi?', 'Kuvvetler birliği', 'Kuvvetler ayrılığı', 'Yasama ve yürütme Meclis’te.'],
      ['Meclis-i Mebusan neden dağıldı?', 'İstanbul’un işgali', 'Sevr’in imzası', '16 Mart 1920 işgali sonrası dağıldı.'],
      ['Sevr’i imzayan hükûmet nerede kuruluydu?', 'İstanbul', 'Ankara', 'Sevr’i İstanbul Hükûmeti imzaladı.'],
    ],
    kontroller: [['TBMM hangi tarihte açıldı?', '23 Nisan 1920', '29 Ekim 1923', '29 Ekim 1923 Cumhuriyet’in ilanıdır.', 2]],
  }),

  tarih12Konusu({
    id: 'trh12-dogu-guney',
    ad: 'Doğu ve Güney Cepheleri',
    kartlar: [
      ['Doğu Cephesi', 'Komutan Kazım Karabekir’di.\nErmeni birliklerine karşı Sarıkamış, Kars ve Gümrü yönünde ilerlendi.'],
      ['Doğu Cephesi’nin sonu', 'Kars 30 Ekim 1920’de alındı.\nSavaş, Gümrü Antlaşması ile bitti.'],
      ['Gümrü Antlaşması', '2-3 Aralık 1920’de imzalandı.\nTBMM’nin imzaladığı ilk antlaşmadır.'],
      ['Güney Cephesi', 'Fransız işgaline karşı Maraş, Antep ve Urfa’da halk direndi.\nSütçü İmam, Maraş direnişinin simgesidir.'],
      ['Maraş ve Urfa', 'Maraş’ta direniş Ocak-Şubat 1920’de oldu.\nFransızlar Urfa’yı Nisan 1920’de boşalttı.'],
      ['Antep Savunması', 'Antep, Fransızlara karşı uzun süre direndi.\nŞahin Bey Antep direnişinin önderlerindendir.'],
      ['Direnişin önemi', 'Bu kentler düzenli ordu kurulmadan önce kendi imkânlarıyla direndi.\nKuvayımilliye ruhu en güçlü burada görüldü.'],
      ['Ankara Antlaşması (1921)', '20 Ekim 1921’de Fransa ile imzalandı.\nFransa Kilikya’yı boşaltacak, Güney Cephesi kapanacaktı.'],
      ['Hatay meselesi', 'Ankara Antlaşması İskenderun Sancağı için özel statü verdi.\nHatay 1939’da Türkiye’ye katıldı.'],
      ['Cepheden alınan ders', 'Doğuda ordu, güneyde halk direnişi öne çıktı.\nSonuçta iki cephe de diplomatik çözümle kapandı.'],
    ],
    not: 'Gümrü TBMM’nin ilk, Ankara (1921) ise Fransa ile yapılan antlaşmadır. Karıştırma.',
    notKarti: 3,
    iddialar: [
      ['Doğu Cephesi’nin komutanı Kazım Karabekir’dir.', true, 'Sarıkamış-Kars harekâtını o yönetti.'],
      ['Gümrü Antlaşması TBMM’nin imzaladığı ilk antlaşmadır.', true, '2-3 Aralık 1920 tarihli antlaşma Ermenistan ile yapıldı.'],
      ['Güney Cephesi’nde Türkler İngilizlere karşı savaştı.', false, 'Güney Cephesi’nde Fransızlara karşı savaşıldı.'],
      ['Ankara Antlaşması (1921) Yunanistan ile imzalandı.', false, 'Ankara Antlaşması Fransa ile imzalandı.'],
      ['Kars 1920’de Türk ordusu tarafından alındı.', true, '30 Ekim 1920.'],
      ['Sütçü İmam Antep direnişinin simgesidir.', false, 'Sütçü İmam, Maraş direnişinin simgesidir.'],
      ['Ankara Antlaşması ile Güney Cephesi kapandı.', true, 'Fransa Kilikya’dan çekildi.'],
    ],
    secimler: [
      ['Doğu Cephesi hangi antlaşmayla bitti?', 'Gümrü', 'Mudanya', 'Gümrü Antlaşması Aralık 1920.'],
      ['Fransa ile 1921’de hangi antlaşma yapıldı?', 'Ankara', 'Moskova', 'Ankara Antlaşması 20 Ekim 1921.'],
      ['Güney Cephesi’nde Fransızlar hangi kentten Nisan 1920’de çekildi?', 'Urfa', 'Antalya', 'Urfa Nisan 1920’de boşaltıldı.'],
      ['Doğuda komuta eden kimdi?', 'Kazım Karabekir', 'İsmet İnönü', 'Doğu Cephesi komutanı Karabekir’di.'],
      ['Güney Cephesi’nde direnen kentlerden hangisi doğrudur?', 'Maraş', 'Trabzon', 'Maraş, Antep ve Urfa direndi.'],
    ],
    kontroller: [['TBMM’nin ilk antlaşması hangisidir?', 'Gümrü', 'Ankara', 'Gümrü Antlaşması 1920’de imzalandı.', 3]],
  }),

  tarih12Konusu({
    id: 'trh12-bati',
    ad: 'Batı Cephesi ve Büyük Taarruz',
    kartlar: [
      ['Kuvayımilliye dönemi', 'Batı’da yerel birlikler Yunan ilerleyişini yavaşlattı.\nAydın, Salihli ve Demirci’de direniş görüldü.'],
      ['Düzenli ordu', 'Kuvayımilliye yerine düzenli ordu birlikleri kuruldu.\nBatı Cephesi komutanlığına İsmet (İnönü) getirildi.'],
      ['I. İnönü (Ocak 1921)', '6-10 Ocak 1921’de yapıldı.\nDüzenli ordunun ilk büyük başarısıdır.'],
      ['II. İnönü (Mart 1921)', '23 Mart-1 Nisan 1921’de yapıldı.\nMustafa Kemal: “Siz orada yalnız düşmanı değil, milletin makûs talihini de yendiniz.”'],
      ['Kütahya-Eskişehir', 'Temmuz 1921’de Türk ordusu geri çekildi.\nMeclis Mustafa Kemal’i başkomutan seçti (5 Ağustos 1921).'],
      ['Sakarya Meydan Muharebesi', '23 Ağustos-13 Eylül 1921 arasında 22 gün sürdü.\n“Hattı müdafaa yoktur, sath-ı müdafaa vardır” ilkesi benimsendi.'],
      ['Sakarya’nın sonuçları', 'Yunan taarruz gücü kırıldı.\nMustafa Kemal’e Mareşal rütbesi ve Gazi unvanı verildi.'],
      ['Taarruz hazırlığı', 'Sakarya’dan sonra ordu bir yıl boyunca yenilendi.\nHarekât, Afyon’daki Kocatepe’den yönetildi.'],
      ['Büyük Taarruz', '26 Ağustos 1922’de başladı.\n30 Ağustos’ta Başkomutan Meydan Muharebesi ile Yunan ordusu çöktü.'],
      ['İzmir’in kurtuluşu', '9 Eylül 1922’de Türk ordusu İzmir’e girdi.\n“Ordular! İlk hedefiniz Akdeniz’dir, ileri!” emri 1 Eylül’de verildi.'],
      ['Mudanya Ateşkesi', '11 Ekim 1922’de imzalandı.\nDoğu Trakya Türklere bırakıldı; savaşın silahlı aşaması bitti.'],
    ],
    not: 'Sakarya’da Gazi unvanı, Büyük Taarruz’da Mudanya sonucu gelir. Sırayı hatırla.',
    notKarti: 7,
    iddialar: [
      ['II. İnönü Muharebesi I. İnönü’den önce yapıldı.', false, 'Önce I. İnönü (Ocak), sonra II. İnönü (Mart 1921).'],
      ['Sakarya Meydan Muharebesi 22 gün sürdü.', true, '23 Ağustos-13 Eylül 1921.'],
      ['Büyük Taarruz 26 Ağustos 1922’de başladı.', true, 'Başkomutan Meydan Muharebesi 30 Ağustos’ta kazanıldı.'],
      ['Mustafa Kemal Sakarya’dan önce başkomutan seçildi.', true, '5 Ağustos 1921’de Meclis ona bu yetkiyi verdi.'],
      ['İzmir 9 Eylül 1922’de kurtarıldı.', true, 'Türk ordusu 9 Eylül’de şehre girdi.'],
      ['Mudanya Ateşkesi Doğu Trakya’yı Yunanistan’a bıraktı.', false, 'Doğu Trakya Türklere bırakıldı.'],
      ['Sakarya sonrası Mustafa Kemal’e mareşallik verildi.', true, '19 Eylül 1921, ayrıca Gazi unvanı.'],
    ],
    secimler: [
      ['Düzenli ordunun ilk büyük başarısı hangisidir?', 'I. İnönü', 'Sakarya', '1921 başında I. İnönü.'],
      ['“Hattı müdafaa yoktur, sath-ı müdafaa vardır” hangi savaşta?', 'Sakarya', 'Dumlupınar', 'Sakarya ilkesidir.'],
      ['Başkomutan Meydan Muharebesi hangi tarihte?', '30 Ağustos 1922', '23 Ağustos 1921', 'Büyük Taarruz sonrası 30 Ağustos.'],
      ['Batı Cephesi komutanı kim?', 'İsmet (İnönü)', 'Kazım Karabekir', 'İsmet Paşa Batı Cephesi komutanıydı.'],
      ['Mudanya hangi yıl imzalandı?', '1922', '1923', 'Mudanya Ateşkesi 11 Ekim 1922.'],
    ],
    kontroller: [
      ['Mustafa Kemal hangi muharebe sonrası Gazi oldu?', 'Sakarya', 'II. İnönü', 'Sakarya zaferi sonrası Gazi ve Mareşal.', 7],
      ['Mudanya hangi zaferin ardından imzalandı?', 'Büyük Taarruz', 'Sakarya', 'Mudanya, Ekim 1922’de Büyük Taarruz sonrası.', 11],
    ],
  }),

  tarih12Konusu({
    id: 'trh12-diplomasi',
    ad: 'Diplomatik Başarılar ve Lozan',
    kartlar: [
      ['Moskova Antlaşması', '16 Mart 1921’de SSCB ile imzalandı.\nTBMM’yi tanıyan ve ilk yardım sağlayan büyük devlet SSCB oldu.'],
      ['Moskova’nın hükümleri', '- Misak-ı Millî’nin doğu sınırı büyük ölçüde belirlendi.\n- Batum Gürcistan’da kaldı.\n- Kars ve Ardahan Türkiye’ye bırakıldı.'],
      ['Kars Antlaşması', '13 Ekim 1921’de Kafkas cumhuriyetleriyle imzalandı.\nDoğu sınırı bugünkü hâlini aldı.'],
      ['Ankara Antlaşması', '20 Ekim 1921’de Fransa ile yapıldı.\nFransa Güney Cephesi’ni kapattı, Kilikya boşaldı.'],
      ['Mudanya Ateşkesi', '11 Ekim 1922’de silahlı mücadeleyi bitirdi.\nDoğu Trakya Türkiye’ye geçecekti.'],
      ['Lozan Konferansı', '20 Kasım 1922-4 Şubat 1923 ve 23 Nisan-24 Temmuz 1923 arasında iki aşamada yapıldı.\nTürk heyeti İsmet Paşa başkanlığındaydı.'],
      ['Lozan’ın siyasi hükümleri', '- Türkiye’nin bugünkü batı sınırı çizildi.\n- Kapitülasyonlar kaldırıldı.\n- Azınlık hakları gayrimüslimlere tanındı.'],
      ['Boğazlar ve Musul', 'Boğazlar uluslararası komisyon denetimine bırakıldı (Montrö’ye kadar).\nMusul meselesi çözülemeyip ertelendi.'],
      ['Ekonomik ve diğer hükümler', 'Osmanlı borçlarının paylaştırılması kabul edildi.\nTürk-Rum nüfus mübadelesi (1923) ayrı bir sözleşmeyle düzenlendi.'],
      ['Lozan’ın önemi', 'Yeni Türk devleti uluslararası alanda tam bağımsız tanındı.\nSevr’in yerine Lozan geçti.'],
    ],
    not: 'Lozan’da çözülemeyen konu Musul, Boğazlar rejimi ise Montrö’de (1936) Türk lehine değişti.',
    notKarti: 8,
    iddialar: [
      ['Lozan Antlaşması 24 Temmuz 1923’te imzalandı.', true, 'İkinci aşamanın sonunda imzalandı.'],
      ['Kars Antlaşması batı sınırını belirlemiştir.', false, 'Kars Antlaşması doğu sınırını belirler.'],
      ['Moskova Antlaşması SSCB ile yapıldı.', true, '16 Mart 1921.'],
      ['Lozan’da Boğazlar tamamen Türk denetimine verildi.', false, 'Uluslararası komisyon kuruldu; Türk egemenliği Montrö’de güçlendi.'],
      ['Lozan Konferansı’nda Türk heyetine İsmet Paşa başkanlık etti.', true, 'İsmet Paşa heyet başkanıydı.'],
      ['Lozan’da kapitülasyonlar sürdürüldü.', false, 'Kapitülasyonlar tamamen kaldırıldı.'],
      ['Musul sorunu Lozan’da çözüldü.', false, 'Sorun 1926 Ankara Antlaşması’na bırakıldı.'],
    ],
    secimler: [
      ['TBMM’yi ilk tanıyan büyük devlet?', 'SSCB', 'İngiltere', 'Moskova Antlaşması 1921.'],
      ['Doğu sınırını son belirleyen antlaşma?', 'Kars', 'Lozan', 'Kars (1921) doğu sınırını kesinleştirdi.'],
      ['Lozan’da Türk heyetinin başkanı kimdi?', 'İsmet Paşa', 'Rauf Orbay', 'İsmet Paşa heyet başkanıydı.'],
      ['Lozan’da hangi yük kaldırıldı?', 'Kapitülasyonlar', 'Boğazlar komisyonu', 'Boğaz komisyonu kaldırılmadı.'],
      ['Mudanya hangi toprağı Türkiye’ye bıraktı?', 'Doğu Trakya', 'Musul', 'Musul sorunu ertelendi.'],
    ],
    kontroller: [['Lozan’da hangi ayrıcalıklar kaldırıldı?', 'Kapitülasyonlar', 'Vakıflar', 'Kapitülasyonlar Lozan’la kalktı.', 7]],
  }),
]
