/**
 * Edebiyat oyununun eser–yazar havuzu.
 *
 * ÖSYM'nin AYT Edebiyat'ta her yıl sorduğu eser–yazar eşleştirmelerinden
 * derlendi; ağırlık, çıkmış sorularda en sık geçen isimlerde.
 *
 * Anonim eserler (Dede Korkut Hikâyeleri, Battalname, halk destanları) havuza
 * **alınmadı**: eşleştirme oyununda karşılığında bir yazar tuşu olmayan bir
 * eser, cevabı olmayan bir soru demek.
 *
 * Aynı yazarın birden çok eseri var — bu bilerek: oyun bir ele aynı yazardan
 * iki eser koymuyor (`edebiyat.ts`), ama farklı ellerde farklı eserleri
 * sorabilmek havuzu zenginleştiriyor.
 */

import type { Zorluk } from './ritim'

export type EdebiyatDonemi =
  | 'ilk'
  | 'divan'
  | 'halk'
  | 'tanzimat'
  | 'servet'
  | 'milli'
  | 'cumhuriyet-siir'
  | 'cumhuriyet-roman'

export type EdebiyatEsi = {
  eser: string
  yazar: string
  donem: EdebiyatDonemi
  /**
   * Zorluk.
   *
   * Edebiyatta zorluğu belirleyen şey dönem değil eserin **ne kadar tanındığı**:
   * *Seyahatnâme* de divan edebiyatıdır, *Sihâm-ı Kazâ* da — ama biri her
   * müfredatta, öteki yalnızca ayrıntıya inende geçer. Dönem tabanı veriyor,
   * tanınırlık tek tek düzeltiyor.
   */
  zorluk: Zorluk
}

export const DONEM_ADI: Record<EdebiyatDonemi, string> = {
  ilk: 'İlk Türk-İslam eserleri',
  divan: 'Divan edebiyatı',
  halk: 'Halk ve tekke edebiyatı',
  tanzimat: 'Tanzimat edebiyatı',
  servet: 'Servet-i Fünûn ve Fecr-i Âtî',
  milli: 'Millî Edebiyat',
  'cumhuriyet-siir': 'Cumhuriyet dönemi şiiri',
  'cumhuriyet-roman': 'Cumhuriyet dönemi roman ve hikâyesi',
}

/** `[eser, yazar]` çiftlerini tek döneme bağlar — havuzu okunur tutmak için. */
function donem(
  donem: EdebiyatDonemi,
  taban: Zorluk,
  ciftler: ([string, string] | [string, string, Zorluk])[],
): EdebiyatEsi[] {
  return ciftler.map(([eser, yazar, zorluk]) => ({
    eser,
    yazar,
    donem,
    zorluk: zorluk ?? taban,
  }))
}

export const EDEBIYAT_HAVUZU: EdebiyatEsi[] = [
  ...donem('ilk', 'orta', [
    ['Kutadgu Bilig', 'Yusuf Has Hâcib', 'kolay'],
    ['Divânü Lugâti’t-Türk', 'Kâşgarlı Mahmut', 'kolay'],
    ['Atabetü’l-Hakayık', 'Edip Ahmet Yükneki'],
    ['Divan-ı Hikmet', 'Ahmet Yesevî'],
    ['Muhakemetü’l-Lugateyn', 'Ali Şîr Nevâî'],
    ['Garipnâme', 'Âşık Paşa'],
    ['Baburnâme', 'Babür Şah', 'kolay'],
    ['Kısasü’l-Enbiyâ', 'Rabguzî', 'kolay'],
    ['Ferhad ü Şirin', 'Ali Şîr Nevâî'],
    ['Mecâlisü’n-Nefâis', 'Ali Şîr Nevâî'],
    ['Süheyl ü Nevbahar', 'Hoca Mesud'],
    ['Muhabbetnâme', 'Harezmî', 'zor'],
    ['Şecere-i Terâkime', 'Ebulgazi Bahadır Han', 'zor'],
    ['Kitâbü’l-İdrâk li-Lisâni’l-Etrâk', 'Ebû Hayyân', 'zor'],
    ['Yûsuf u Zelîhâ', 'Şeyyad Hamza', 'zor'],
    ['Marzubannâme çevirisi', 'Şeyhoğlu Mustafa', 'zor'],
    // Geçiş dönemi ve Harezm–Kıpçak–Çağatay sahası zayıf kalmıştı; AYT'de
    // "hangi sahaya ait" sorusu bu eserler üzerinden kuruluyor.
    ['Orhun Abideleri', 'Yollug Tigin', 'orta'],
    ['Çarhnâme', 'Ahmed Fakih', 'orta'],
    ['Nehcü’l-Ferâdis', 'Mahmud bin Ali', 'zor'],
    ['Mukaddimetü’l-Edeb', 'Zemahşerî', 'zor'],
    ['Gülistan Tercümesi', 'Seyf-i Sarâyî', 'zor'],
    ['Kelile ve Dimne Tercümesi', 'Kul Mesud', 'zor'],
    ['Kıssa-i Yûsuf', 'Kul Ali', 'zor'],
    ['Yüz Hadis Yüz Hikâye', 'Erzurumlu Darîr', 'zor'],
    ['Ferhengnâme-i Sa’dî', 'Hoca Mesud', 'zor'],
    ['Envârü’l-Âşıkîn', 'Ahmed Bîcan', 'zor'],
    ['Lisânü’t-Tayr', 'Ali Şîr Nevâî', 'zor'],
    ['Şecere-i Türk', 'Ebulgazi Bahadır Han', 'zor'],
  ]),

  ...donem('divan', 'zor', [
    ['Hüsn ü Aşk', 'Şeyh Galip', 'orta'],
    ['Harnâme', 'Şeyhî', 'orta'],
    ['Hüsrev ü Şirin', 'Şeyhî'],
    ['Mantıku’t-Tayr', 'Gülşehrî'],
    ['Hayriyye', 'Nâbî'],
    ['Hayrâbâd', 'Nâbî'],
    ['Leylâ ile Mecnun', 'Fuzûlî', 'kolay'],
    ['Şikâyetnâme', 'Fuzûlî', 'orta'],
    ['Su Kasidesi', 'Fuzûlî', 'kolay'],
    ['Beng ü Bâde', 'Fuzûlî'],
    ['Mesnevî', 'Mevlânâ', 'kolay'],
    ['Divan-ı Kebir', 'Mevlânâ'],
    ['Fîhi Mâ Fîh', 'Mevlânâ'],
    ['İskendernâme', 'Ahmedî'],
    ['Kâbusnâme çevirisi', 'Mercimek Ahmet'],
    ['Keşfü’z-Zünûn', 'Kâtip Çelebi'],
    ['Cihannümâ', 'Kâtip Çelebi'],
    ['Seyahatnâme', 'Evliya Çelebi', 'kolay'],
    ['Vesîletü’n-Necât (Mevlid)', 'Süleyman Çelebi', 'orta'],
    ['Kanunî Mersiyesi', 'Bâkî'],
    ['Sihâm-ı Kazâ', 'Nef’î'],
    ['Tazarrunâme', 'Sinan Paşa'],
    ['Meşâirü’ş-Şuarâ', 'Âşık Çelebi'],
    ['Tezkiretü’ş-Şuarâ', 'Latîfî'],
    ['Naîmâ Tarihi', 'Naîmâ'],
    ['Sefaretnâme', 'Yirmisekiz Çelebi Mehmet'],
    ['Hadîkatü’s-Süedâ', 'Fuzûlî', 'kolay'],
    ['Kitâb-ı Bahriye', 'Pîrî Reis', 'kolay'],
    ['Mârifetnâme', 'Erzurumlu İbrahim Hakkı', 'kolay'],
    ['Şehzade Mustafa Mersiyesi', 'Taşlıcalı Yahya', 'kolay'],
    ['Muhammediye', 'Yazıcıoğlu Mehmed', 'orta'],
    ['Lutfiyye', 'Sünbülzâde Vehbî', 'orta'],
    ['Kerem Kasidesi', 'Ahmed Paşa', 'orta'],
    ['Mirâtü’l-Memâlik', 'Seydi Ali Reis', 'orta'],
    ['Tâcü’t-Tevârih', 'Hoca Sadettin Efendi'],
    ['Mîzânü’l-Hak', 'Kâtip Çelebi'],
    ['Rind ü Zâhid', 'Fuzûlî'],
    ['Tuhfetü’l-Harameyn', 'Nâbî'],
    ['Şâh u Gedâ', 'Taşlıcalı Yahya'],
    ['Şem ü Pervâne', 'Zâtî'],
    ['Muhayyelât', 'Giritli Ali Aziz Efendi'],
    // Divan nesri (tezkire, tarih, siyasetnâme, sûrnâme) havuzda çok azdı;
    // oysa çıkmış sorularda "eser–tür" eşleştirmesi buradan çıkıyor.
    ['Nedîm Divanı', 'Nedîm', 'kolay'],
    ['Sahâifü’l-Ahbâr Tercümesi', 'Nedîm', 'zor'],
    ['Güneş Kasidesi', 'Ahmed Paşa', 'orta'],
    ['Necâtî Bey Divanı', 'Necâtî Bey', 'orta'],
    ['Koçi Bey Risalesi', 'Koçi Bey', 'orta'],
    ['Hâbnâme', 'Veysî'],
    ['Nihâlistân', 'Nergisî'],
    ['Sûrnâme-i Hümâyun', 'İntizâmî'],
    ['Sûrnâme-i Vehbî', 'Seyyid Vehbî'],
    ['Tuhfe-i Vehbî', 'Sünbülzâde Vehbî'],
    ['Cemşîd ü Hurşîd', 'Cem Sultan'],
    ['Vâmık u Azrâ', 'Lâmiî Çelebi'],
    ['Fezleke', 'Kâtip Çelebi'],
    ['Heşt Behişt', 'Sehî Bey'],
    ['Künhü’l-Ahbâr', 'Gelibolulu Âlî'],
    ['Âsafnâme', 'Lütfi Paşa'],
    ['Hümâyunnâme', 'Alâeddin Ali Çelebi'],
    ['Divân-ı Türkî-i Basît', 'Edirneli Nazmî'],
    ['Pendnâme', 'Güvâhî'],
    ['Netâyicü’l-Fünûn', 'Nev’î'],
    ['Şehrengîz-i Edirne', 'Mesîhî'],
    ['Târih-i Peçevî', 'Peçevî İbrahim Efendi'],
    ['Tuhfe-i Şâhidî', 'Şâhidî İbrahim Dede'],
    ['Hilye-i Hâkânî', 'Hâkânî Mehmed Bey'],
    ['Mihnetkeşân', 'Keçecizâde İzzet Molla'],
    ['Zenannâme', 'Enderunlu Fâzıl'],
    ['Fezâilü’l-Cihâd', 'Bâkî'],
    ['Fetihnâme-i Kamaniçe', 'Nâbî'],
  ]),

  ...donem('halk', 'zor', [
    ['Risâletü’n-Nushiyye', 'Yunus Emre', 'orta'],
    ['Budalanâme', 'Kaygusuz Abdal'],
    ['Dilgüşâ', 'Kaygusuz Abdal'],
    ['Makâlât', 'Hacı Bektaş Velî', 'orta'],
    ['Dostlar Beni Hatırlasın', 'Âşık Veysel'],
    ['Deyişler', 'Âşık Veysel', 'orta'],
    ['Şairnâme', 'Âşık Ömer', 'orta'],
    ['Vâridât', 'Şeyh Bedreddin', 'orta'],
    ['Müzekki’n-Nüfûs', 'Eşrefoğlu Rûmî', 'orta'],
    ['Dehnâme', 'Şah İsmail Hatâyî', 'orta'],
    ['Kitâb-ı Miglâte', 'Kaygusuz Abdal'],
    ['Saraynâme', 'Kaygusuz Abdal'],
    ['Mevâidü’l-İrfân', 'Niyâzî-i Mısrî'],
    ['Sergüzeştnâme', 'Bayburtlu Zihni'],
    // Âşık edebiyatı yalnızca Âşık Veysel ve Âşık Ömer'le temsil ediliyordu;
    // müfredatın saz şairleri (Karacaoğlan, Dadaloğlu, Köroğlu, Pir Sultan)
    // ve tekke nesri eklendi ki bu dönem tek başına el kurabilsin.
    ['Yunus Emre Divanı', 'Yunus Emre', 'kolay'],
    ['Kara Toprak', 'Âşık Veysel', 'kolay'],
    ['İncecikten Bir Kar Yağar', 'Karacaoğlan', 'kolay'],
    ['Kalktı Göç Eyledi Avşar Elleri', 'Dadaloğlu', 'orta'],
    ['Gelin Canlar Bir Olalım', 'Pir Sultan Abdal', 'orta'],
    ['Benden Selam Olsun Bolu Beyi’ne', 'Köroğlu', 'orta'],
    ['Genç Osman Destanı', 'Kayıkçı Kul Mustafa', 'orta'],
    ['Gevherî Divanı', 'Gevherî', 'orta'],
    ['Dîvân-ı İlâhiyyât', 'Niyâzî-i Mısrî'],
    ['Tarîkatnâme', 'Eşrefoğlu Rûmî'],
    ['Menâkıbü’l-Kudsiyye', 'Elvan Çelebi'],
    ['Rebabnâme', 'Sultan Veled'],
    ['İbtidânâme', 'Sultan Veled'],
    ['Câmiu’l-Fusûleyn', 'Şeyh Bedreddin'],
    ['Vahdetnâme', 'Abdurrahim Karahisârî'],
    ['Nefâisü’l-Mecâlis', 'Aziz Mahmud Hüdâyî'],
    ['Gevhernâme', 'Kaygusuz Abdal'],
    ['Fütüvvetnâme', 'Burgazî'],
    ['Nasihatnâme', 'Şah İsmail Hatâyî'],
    ['Dertli Divanı', 'Dertli'],
  ]),

  ...donem('tanzimat', 'zor', [
    ['Şair Evlenmesi', 'Şinasi', 'kolay'],
    ['Tercüman-ı Ahval Mukaddimesi', 'Şinasi'],
    ['Müntehabat-ı Eş’ar', 'Şinasi'],
    ['İntibah', 'Namık Kemal', 'kolay'],
    ['Cezmi', 'Namık Kemal', 'orta'],
    ['Vatan yahut Silistre', 'Namık Kemal', 'kolay'],
    ['Zavallı Çocuk', 'Namık Kemal', 'orta'],
    ['Terkib-i Bend', 'Ziya Paşa'],
    ['Harâbat', 'Ziya Paşa'],
    ['Zafernâme', 'Ziya Paşa'],
    ['Felâtun Bey ile Râkım Efendi', 'Ahmet Mithat Efendi', 'orta'],
    ['Henüz On Yedi Yaşında', 'Ahmet Mithat Efendi'],
    ['Hasan Mellah', 'Ahmet Mithat Efendi'],
    ['Araba Sevdası', 'Recaizade Mahmut Ekrem', 'kolay'],
    ['Muhsin Bey', 'Recaizade Mahmut Ekrem'],
    ['Talim-i Edebiyat', 'Recaizade Mahmut Ekrem'],
    ['Sergüzeşt', 'Samipaşazade Sezai', 'orta'],
    ['Küçük Şeyler', 'Samipaşazade Sezai'],
    ['Makber', 'Abdülhak Hâmit Tarhan', 'orta'],
    ['Eşber', 'Abdülhak Hâmit Tarhan'],
    ['Sahra', 'Abdülhak Hâmit Tarhan'],
    ['Ömer’in Çocukluğu', 'Muallim Naci'],
    ['Demdeme', 'Muallim Naci'],
    ['Karabibik', 'Nabizade Nâzım', 'orta'],
    ['Zehra', 'Nabizade Nâzım'],
    ['Taaşşuk-ı Talat ve Fitnat', 'Şemsettin Sami', 'orta'],
    ['Kamus-ı Türkî', 'Şemsettin Sami'],
    ['Akif Bey', 'Namık Kemal', 'kolay'],
    ['Şiir ve İnşa', 'Ziya Paşa', 'kolay'],
    ['Zemzeme', 'Recaizade Mahmut Ekrem', 'kolay'],
    ['Duhter-i Hindû', 'Abdülhak Hâmit Tarhan', 'kolay'],
    ['Letaif-i Rivayat', 'Ahmet Mithat Efendi', 'kolay'],
    ['Kâmûsü’l-Âlâm', 'Şemsettin Sami', 'kolay'],
    ['Celâleddin Harzemşah', 'Namık Kemal', 'orta'],
    ['Finten', 'Abdülhak Hâmit Tarhan', 'orta'],
    ['Zoraki Tabip', 'Ahmet Vefik Paşa', 'orta'],
    ['Durûb-ı Emsâl-i Osmâniyye', 'Şinasi', 'orta'],
    ['Çok Bilen Çok Yanılır', 'Recaizade Mahmut Ekrem', 'orta'],
    ['Müşahedat', 'Ahmet Mithat Efendi'],
    ['Ateşpâre', 'Muallim Naci'],
    ['İclâl', 'Samipaşazade Sezai'],
    // Tanzimat'ta tiyatro, çeviri ve eleştiri kolları eksikti; "ilk çeviri
    // roman", "ilk dil bilgisi kitabı" gibi ÖSYM'nin sevdiği ilkler eklendi.
    ['Telemak Çevirisi', 'Yusuf Kâmil Paşa', 'kolay'],
    ['Gülnihal', 'Namık Kemal', 'kolay'],
    ['Zor Nikâh', 'Ahmet Vefik Paşa', 'kolay'],
    ['Tarık yahut Endülüs Fethi', 'Abdülhak Hâmit Tarhan', 'kolay'],
    ['Dürdane Hanım', 'Ahmet Mithat Efendi', 'kolay'],
    ['Zeynep', 'Namık Kemal', 'orta'],
    ['Tahrib-i Harâbat', 'Namık Kemal', 'orta'],
    ['Terceme-i Manzûme', 'Şinasi', 'orta'],
    ['Nijad Ekrem', 'Recaizade Mahmut Ekrem', 'orta'],
    ['Turfanda mı Yoksa Turfa mı?', 'Mizancı Mehmet Murat', 'orta'],
    ['Tarih-i Cevdet', 'Ahmet Cevdet Paşa', 'orta'],
    ['Rüya', 'Ziya Paşa'],
    ['Defter-i Amâl', 'Ziya Paşa'],
    ['Yeniçeri', 'Ahmet Mithat Efendi'],
    ['Çengi', 'Ahmet Mithat Efendi'],
    ['Vuslat yahut Süreksiz Sevinç', 'Recaizade Mahmut Ekrem'],
    ['Nesteren', 'Abdülhak Hâmit Tarhan'],
    ['Belde', 'Abdülhak Hâmit Tarhan'],
    ['Ölü', 'Abdülhak Hâmit Tarhan'],
    ['Müsameretnâme', 'Emin Nihat'],
  ]),

  ...donem('servet', 'orta', [
    ['Mai ve Siyah', 'Halit Ziya Uşaklıgil', 'kolay'],
    ['Aşk-ı Memnu', 'Halit Ziya Uşaklıgil', 'kolay'],
    ['Kırık Hayatlar', 'Halit Ziya Uşaklıgil'],
    ['Eylül', 'Mehmet Rauf', 'kolay'],
    ['Rübâb-ı Şikeste', 'Tevfik Fikret'],
    ['Haluk’un Defteri', 'Tevfik Fikret'],
    ['Şermin', 'Tevfik Fikret', 'zor'],
    ['Elhan-ı Şitâ', 'Cenap Şahabettin'],
    ['Hac Yolunda', 'Cenap Şahabettin', 'zor'],
    ['Evrak-ı Eyyam', 'Cenap Şahabettin', 'zor'],
    ['Şıpsevdi', 'Hüseyin Rahmi Gürpınar'],
    ['Gulyabani', 'Hüseyin Rahmi Gürpınar'],
    ['Mürebbiye', 'Hüseyin Rahmi Gürpınar'],
    ['Şehir Mektupları', 'Ahmet Rasim', 'zor'],
    ['Hayat-ı Muhayyel', 'Hüseyin Cahit Yalçın', 'zor'],
    ['Göl Saatleri', 'Ahmet Hâşim', 'zor'],
    ['Piyale', 'Ahmet Hâşim', 'zor'],
    ['Gurabahâne-i Laklakan', 'Ahmet Hâşim', 'zor'],
    ['Bize Göre', 'Ahmet Hâşim', 'zor'],
    ['Ferdi ve Şürekâsı', 'Halit Ziya Uşaklıgil', 'kolay'],
    ['Kırk Yıl', 'Halit Ziya Uşaklıgil', 'kolay'],
    ['Kuyruklu Yıldız Altında Bir İzdivaç', 'Hüseyin Rahmi Gürpınar', 'kolay'],
    ['Tiryaki Sözleri', 'Cenap Şahabettin', 'kolay'],
    ['Falaka', 'Ahmet Rasim', 'kolay'],
    ['Genç Kız Kalbi', 'Mehmet Rauf'],
    ['Tarih-i Kadîm', 'Tevfik Fikret'],
    ['Şık', 'Hüseyin Rahmi Gürpınar'],
    ['Âfâk-ı Irak', 'Cenap Şahabettin', 'zor'],
    ['Frankfurt Seyahatnamesi', 'Ahmet Hâşim', 'zor'],
    ['Çal Çoban Çal', 'Süleyman Nazif', 'zor'],
    // Servet-i Fünûn'da yalnız romanlar vardı; dönemin asıl tartışması şiir
    // üzerinden yürüdüğü için "Sis", "Merdiven" gibi tek tek sorulan şiirler
    // ve Fecr-i Âtî kanadı (Emin Bülent, Safveti Ziya) eklendi.
    ['Sis', 'Tevfik Fikret', 'kolay'],
    ['Merdiven', 'Ahmet Hâşim', 'kolay'],
    ['Han-ı Yağma', 'Tevfik Fikret'],
    ['Bir Ölünün Defteri', 'Halit Ziya Uşaklıgil'],
    ['Nemide', 'Halit Ziya Uşaklıgil'],
    ['Siyah İnciler', 'Mehmet Rauf'],
    ['Ben Deli miyim?', 'Hüseyin Rahmi Gürpınar'],
    ['Utanmaz Adam', 'Hüseyin Rahmi Gürpınar'],
    ['Rübâbın Cevabı', 'Tevfik Fikret', 'zor'],
    ['Halas', 'Mehmet Rauf', 'zor'],
    ['Tâmât', 'Cenap Şahabettin', 'zor'],
    ['Körebe', 'Cenap Şahabettin', 'zor'],
    ['Muharrir Şair Edip', 'Ahmet Rasim', 'zor'],
    ['Hayal İçinde', 'Hüseyin Cahit Yalçın', 'zor'],
    ['Batarya ile Ateş', 'Süleyman Nazif', 'zor'],
    ['Kin', 'Emin Bülent Serdaroğlu', 'zor'],
    ['Salon Köşelerinde', 'Safveti Ziya', 'zor'],
    ['Efsûs', 'Nigâr Hanım', 'zor'],
  ]),

  ...donem('milli', 'orta', [
    ['Kaşağı', 'Ömer Seyfettin', 'kolay'],
    ['Bomba', 'Ömer Seyfettin', 'zor'],
    ['Yalnız Efe', 'Ömer Seyfettin', 'zor'],
    ['Türkçülüğün Esasları', 'Ziya Gökalp', 'orta'],
    ['Kızıl Elma', 'Ziya Gökalp', 'zor'],
    ['Altın Işık', 'Ziya Gökalp', 'zor'],
    ['Ateşten Gömlek', 'Halide Edib Adıvar', 'kolay'],
    ['Sinekli Bakkal', 'Halide Edib Adıvar', 'kolay'],
    ['Vurun Kahpeye', 'Halide Edib Adıvar', 'kolay'],
    ['Yaban', 'Yakup Kadri Karaosmanoğlu', 'kolay'],
    ['Kiralık Konak', 'Yakup Kadri Karaosmanoğlu', 'orta'],
    ['Nur Baba', 'Yakup Kadri Karaosmanoğlu', 'zor'],
    ['Sodom ve Gomore', 'Yakup Kadri Karaosmanoğlu', 'zor'],
    ['Memleket Hikâyeleri', 'Refik Halit Karay', 'kolay'],
    ['Gurbet Hikâyeleri', 'Refik Halit Karay', 'orta'],
    ['Çalıkuşu', 'Reşat Nuri Güntekin', 'kolay'],
    ['Yaprak Dökümü', 'Reşat Nuri Güntekin', 'kolay'],
    ['Dudaktan Kalbe', 'Reşat Nuri Güntekin', 'orta'],
    ['Türkçe Şiirler', 'Mehmet Emin Yurdakul', 'zor'],
    ['Safahat', 'Mehmet Âkif Ersoy', 'kolay'],
    ['Kendi Gök Kubbemiz', 'Yahya Kemal Beyatlı', 'orta'],
    ['Eski Şiirin Rüzgârıyle', 'Yahya Kemal Beyatlı', 'zor'],
    ['Aziz İstanbul', 'Yahya Kemal Beyatlı', 'zor'],
    ['Pembe İncili Kaftan', 'Ömer Seyfettin', 'kolay'],
    ['Efruz Bey', 'Ömer Seyfettin', 'kolay'],
    ['Türkleşmek İslâmlaşmak Muasırlaşmak', 'Ziya Gökalp', 'kolay'],
    ['Handan', 'Halide Edib Adıvar', 'kolay'],
    ['Ankara', 'Yakup Kadri Karaosmanoğlu', 'kolay'],
    ['Acımak', 'Reşat Nuri Güntekin', 'kolay'],
    ['Âsım', 'Mehmet Âkif Ersoy', 'kolay'],
    ['Forsa', 'Ömer Seyfettin'],
    ['Mor Salkımlı Ev', 'Halide Edib Adıvar'],
    ['Hüküm Gecesi', 'Yakup Kadri Karaosmanoğlu'],
    ['Yeşil Gece', 'Reşat Nuri Güntekin'],
    ['Kirpinin Dedikleri', 'Refik Halit Karay', 'zor'],
    ['Eğil Dağlar', 'Yahya Kemal Beyatlı', 'zor'],
    // Millî Edebiyat'ın Beş Hececiler kanadı ile Ömer Seyfettin'in tek tek
    // sorulan hikâyeleri eksikti; şiir–hikâye dengesi bunlarla kuruldu.
    ['Diyet', 'Ömer Seyfettin', 'kolay'],
    ['Başını Vermeyen Şehit', 'Ömer Seyfettin', 'kolay'],
    ['Türkün Ateşle İmtihanı', 'Halide Edib Adıvar', 'kolay'],
    ['Bingöl Çobanları', 'Kemalettin Kamu', 'kolay'],
    ['Bir Yolcuya', 'Necmettin Halil Onan', 'kolay'],
    ['Beyaz Lale', 'Ömer Seyfettin'],
    ['Yeni Hayat', 'Ziya Gökalp'],
    ['Panorama', 'Yakup Kadri Karaosmanoğlu'],
    ['Bugünün Saraylısı', 'Refik Halit Karay'],
    ['Miskinler Tekkesi', 'Reşat Nuri Güntekin'],
    ['Süleymaniye Kürsüsünde', 'Mehmet Âkif Ersoy'],
    ['Türk Sazı', 'Mehmet Emin Yurdakul'],
    ['Türk Edebiyatında İlk Mutasavvıflar', 'Fuat Köprülü'],
    ['Dikmen Yıldızı', 'Aka Gündüz'],
    ['Rubâîler', 'Yahya Kemal Beyatlı', 'zor'],
    ['Fırtına ve Kar', 'Orhan Seyfi Orhon', 'zor'],
    ['Akından Akına', 'Yusuf Ziya Ortaç', 'zor'],
    ['Baykuş', 'Halit Fahri Ozansoy', 'zor'],
    ['Miras', 'Enis Behiç Koryürek', 'zor'],
    ['Serâb-ı Ömrüm', 'Rıza Tevfik Bölükbaşı', 'zor'],
    ['Geçtiğim Yol', 'Ali Canip Yöntem', 'zor'],
    ['Aydemir', 'Müfide Ferit Tek', 'zor'],
  ]),

  ...donem('cumhuriyet-siir', 'orta', [
    ['Han Duvarları', 'Faruk Nafiz Çamlıbel', 'kolay'],
    ['Çoban Çeşmesi', 'Faruk Nafiz Çamlıbel'],
    ['Kaldırımlar', 'Necip Fazıl Kısakürek', 'kolay'],
    ['Çile', 'Necip Fazıl Kısakürek', 'kolay'],
    ['Memleketimden İnsan Manzaraları', 'Nâzım Hikmet', 'kolay'],
    ['Kuvâyi Milliye', 'Nâzım Hikmet'],
    ['835 Satır', 'Nâzım Hikmet', 'kolay'],
    ['Garip', 'Orhan Veli Kanık', 'kolay'],
    ['Vazgeçemediğim', 'Orhan Veli Kanık', 'zor'],
    ['Perçemli Sokak', 'Oktay Rifat', 'zor'],
    ['Kolları Bağlı Odysseus', 'Melih Cevdet Anday', 'zor'],
    ['Üvercinka', 'Cemal Süreya'],
    ['Göçebe', 'Cemal Süreya', 'zor'],
    ['Tütünler Islak', 'Turgut Uyar', 'zor'],
    ['Dünyanın En Güzel Arabistanı', 'Turgut Uyar', 'zor'],
    ['Yerçekimli Karanfil', 'Edip Cansever'],
    ['Galile Denizi', 'İlhan Berk', 'zor'],
    ['Kınar Hanımın Denizleri', 'Ece Ayhan', 'zor'],
    ['Monna Rosa', 'Sezai Karakoç', 'kolay'],
    ['Otuz Beş Yaş', 'Cahit Sıtkı Tarancı', 'kolay'],
    ['Soğuk Otların Altında', 'Ülkü Tamer', 'zor'],
    ['Sisler Bulvarı', 'Attilâ İlhan', 'kolay'],
    ['Kapalı Çarşı', 'Behçet Necatigil'],
    ['Çocuk ve Allah', 'Fazıl Hüsnü Dağlarca'],
    ['Fahriye Abla', 'Ahmet Muhip Dıranas', 'kolay'],
    ['Sebil ve Güvercinler', 'Ziya Osman Saba', 'zor'],
    ['Adamın Biri', 'Cahit Külebi', 'zor'],
    ['Şeyh Bedreddin Destanı', 'Nâzım Hikmet', 'kolay'],
    ['Bayrak', 'Arif Nihat Asya', 'kolay'],
    ['Hasretinden Prangalar Eskittim', 'Ahmed Arif', 'kolay'],
    ['Ömrümde Sükût', 'Cahit Sıtkı Tarancı', 'kolay'],
    ['Örümcek Ağı', 'Necip Fazıl Kısakürek'],
    ['Rahatı Kaçan Ağaç', 'Melih Cevdet Anday'],
    ['Duvar', 'Attilâ İlhan'],
    ['Umutsuzlar Parkı', 'Edip Cansever'],
    ['Hızırla Kırk Saat', 'Sezai Karakoç'],
    ['Evler', 'Behçet Necatigil'],
    ['Destan Gibi', 'Orhan Veli Kanık', 'zor'],
    ['Üç Şehitler Destanı', 'Fazıl Hüsnü Dağlarca', 'zor'],
    ['Beni Öp Sonra Doğur Beni', 'Cemal Süreya', 'zor'],
    ['İşaret Çocukları', 'Cahit Zarifoğlu', 'zor'],
  ]),

  ...donem('cumhuriyet-roman', 'orta', [
    ['Kürk Mantolu Madonna', 'Sabahattin Ali', 'kolay'],
    ['Kuyucaklı Yusuf', 'Sabahattin Ali', 'kolay'],
    ['Semaver', 'Sait Faik Abasıyanık'],
    ['Sarnıç', 'Sait Faik Abasıyanık', 'zor'],
    ['Bereketli Topraklar Üzerinde', 'Orhan Kemal'],
    ['Murtaza', 'Orhan Kemal', 'zor'],
    ['İnce Memed', 'Yaşar Kemal', 'kolay'],
    ['Yer Demir Gök Bakır', 'Yaşar Kemal', 'zor'],
    ['Devlet Ana', 'Kemal Tahir', 'kolay'],
    ['Yorgun Savaşçı', 'Kemal Tahir'],
    ['Esir Şehrin İnsanları', 'Kemal Tahir', 'zor'],
    ['Tutunamayanlar', 'Oğuz Atay', 'kolay'],
    ['Tehlikeli Oyunlar', 'Oğuz Atay', 'zor'],
    ['Ölmeye Yatmak', 'Adalet Ağaoğlu', 'zor'],
    ['Aylak Adam', 'Yusuf Atılgan', 'kolay'],
    ['Anayurt Oteli', 'Yusuf Atılgan'],
    ['Benim Adım Kırmızı', 'Orhan Pamuk', 'kolay'],
    ['Kar', 'Orhan Pamuk', 'kolay'],
    ['Huzur', 'Ahmet Hamdi Tanpınar', 'kolay'],
    ['Saatleri Ayarlama Enstitüsü', 'Ahmet Hamdi Tanpınar', 'kolay'],
    ['Fatih-Harbiye', 'Peyami Safa'],
    ['Dokuzuncu Hariciye Koğuşu', 'Peyami Safa', 'kolay'],
    ['Küçük Ağa', 'Tarık Buğra'],
    ['Keşanlı Ali Destanı', 'Haldun Taner'],
    ['Şişhane’ye Yağmur Yağıyordu', 'Haldun Taner', 'zor'],
    ['Yılanların Öcü', 'Fakir Baykurt', 'kolay'],
    ['Tütün Zamanı', 'Necati Cumalı', 'zor'],
    ['Zübük', 'Aziz Nesin', 'zor'],
    ['Yaşar Ne Yaşar Ne Yaşamaz', 'Aziz Nesin', 'zor'],
    ['Uzun Sürmüş Bir Günün Akşamı', 'Bilge Karasu', 'zor'],
    ['Buzlar Çözülmeden', 'Cevat Fehmi Başkut', 'zor'],
    ['İçimizdeki Şeytan', 'Sabahattin Ali', 'kolay'],
    ['Beş Şehir', 'Ahmet Hamdi Tanpınar', 'kolay'],
    ['Yalnızız', 'Peyami Safa', 'kolay'],
    ['Osmancık', 'Tarık Buğra', 'kolay'],
    ['Teneke', 'Yaşar Kemal', 'kolay'],
    ['Beyaz Kale', 'Orhan Pamuk', 'kolay'],
    ['Alemdağ’da Var Bir Yılan', 'Sait Faik Abasıyanık', 'kolay'],
    ['Baba Evi', 'Orhan Kemal'],
    ['Matmazel Noraliya’nın Koltuğu', 'Peyami Safa'],
    ['Korkuyu Beklerken', 'Oğuz Atay'],
    ['Kurt Kanunu', 'Kemal Tahir'],
    ['Ayaşlı ve Kiracıları', 'Memduh Şevket Esendal'],
    ['Gözlerimi Kaparım Vazifemi Yaparım', 'Haldun Taner', 'zor'],
    ['Parasız Yatılı', 'Füruzan', 'zor'],
  ]),
]

/** Havuzdaki eser sayısı — tanıtım ekranı bunu yazıyor. */
export const EDEBIYAT_BOYUTU = EDEBIYAT_HAVUZU.length
