/**
 * Canlıların Ortak Özellikleri oyununun soru havuzu.
 *
 * Kapsam 9. sınıf "Canlıların Ortak Özellikleri" ünitesi, yani TYT Biyoloji'nin
 * ilk konusu: hücresel yapı, beslenme, solunum, boşaltım, hareket, uyarılara
 * tepki, üreme, büyüme-gelişme, metabolizma, homeostazi, uyum ve organizasyon.
 * 11-12. sınıfa giren hiçbir başlık (sinir sistemi, fotosentez tepkimeleri,
 * kalıtım hesapları) buraya alınmadı.
 *
 * Çeldiriciler soruyla birlikte yazılıyor: her birinin **açıkça yanlış ama
 * akla yatkın** olması gerekiyor. Rastgele seçilseydi çoğu soru okumadan
 * elenebilirdi.
 */

import { soruKur as s, type BiyolojiSorusu } from './biyoloji'

export const ORTAK_HAVUZU: readonly BiyolojiSorusu[] = [
  s(
    'kolay',
    'Canlıyı cansızdan ayıran, canlılığın en küçük yapı ve görev birimi hangisidir?',
    'Hücre',
    ['Doku', 'Organel', 'Molekül'],
    'Virüsler dışında bütün canlılar hücrelerden oluşur. Organel hücrenin parçası, doku ise hücrelerin topluluğudur.',
  ),
  s(
    'kolay',
    'Aşağıdakilerden hangisi hücresel yapıya sahip değildir?',
    'Virüs',
    ['Bakteri', 'Amip', 'Mantar'],
    'Virüslerin hücresi yoktur; bu yüzden canlıların ortak özelliklerini taşımaz ve sınıflandırmaya alınmaz.',
  ),
  s(
    'kolay',
    'Canlının iç ortamını değişen koşullara rağmen dengede tutmasına ne ad verilir?',
    'Homeostazi',
    ['Metabolizma', 'Adaptasyon', 'Mutasyon'],
    'Vücut sıcaklığının, kan şekerinin, su-tuz dengesinin belirli sınırlar içinde tutulması homeostazidir.',
  ),
  s(
    'kolay',
    'Hücrede gerçekleşen bütün yapım ve yıkım tepkimelerine verilen ortak ad hangisidir?',
    'Metabolizma',
    ['Homeostazi', 'Fotosentez', 'Boşaltım'],
    'Metabolizma = anabolizma (yapım) + katabolizma (yıkım). İkisi de bütün canlılarda görülür.',
  ),
  s(
    'orta',
    'Hücrede yapım (sentez) tepkimelerinin tümüne ne denir?',
    'Anabolizma',
    ['Katabolizma', 'Homeostazi', 'Difüzyon'],
    'Anabolizma enerji harcayarak büyük molekül kurar; katabolizma büyük molekülü parçalayıp enerji açığa çıkarır.',
  ),
  s(
    'kolay',
    'Besinlerin parçalanarak enerjiye dönüştürülmesi hangi ortak özelliktir?',
    'Solunum',
    ['Beslenme', 'Boşaltım', 'Sindirim'],
    'Solunum oksijenli ya da oksijensiz olabilir ama bütün canlılarda vardır; amacı besindeki enerjiyi ATP’ye çevirmektir.',
  ),
  s(
    'orta',
    'Solunumla ilgili olarak bütün canlılar için ortak olan hangisidir?',
    'Besinlerden enerji elde etmesi',
    ['Oksijen kullanması', 'Akciğer bulundurması', 'Karbondioksit vermesi'],
    'Oksijen ve akciğer her canlıda yok; ortak olan tek şey besinden enerji (ATP) elde edilmesidir.',
  ),
  s(
    'zor',
    'Oksijensiz solunum yapan canlılar için hangisi doğrudur?',
    'Glikozu tam parçalayamaz, az enerji elde eder',
    [
      'Hiç ATP üretemez',
      'Yalnızca ökaryot canlılarda görülür',
      'Glikozu oksijenli solunumdan daha çok parçalar',
    ],
    'Oksijensiz solunumda glikoz tam parçalanmadığı için elde edilen ATP, oksijenli solunuma göre çok azdır.',
  ),
  s(
    'kolay',
    'Metabolizma sonucu oluşan atık maddelerin dışarı atılması hangi ortak özelliktir?',
    'Boşaltım',
    ['Sindirim', 'Solunum', 'Üreme'],
    'Boşaltım her canlıda var; yalnız yapısı değişir: tek hücrelide hücre zarından, insanda böbrekle.',
  ),
  s(
    'kolay',
    'Türün devamını sağlayan ortak özellik hangisidir?',
    'Üreme',
    ['Büyüme', 'Beslenme', 'Hareket'],
    'Üreme bireyin yaşaması için zorunlu değildir; ama tür ancak üreyerek devam eder.',
  ),
  s(
    'orta',
    'Aşağıdakilerden hangisi bireyin hayatta kalması için zorunlu değildir?',
    'Üreme',
    ['Solunum', 'Beslenme', 'Boşaltım'],
    'Üremeyen bir birey yaşamını sürdürebilir; solunum, beslenme ve boşaltım durursa süremez.',
  ),
  s(
    'kolay',
    'Bir canlının kütle ve hacminin geri dönüşümsüz olarak artmasına ne denir?',
    'Büyüme',
    ['Gelişme', 'Üreme', 'Metabolizma'],
    'Büyüme niceliksel bir artıştır; gelişme ise hücrelerin farklılaşıp görev kazanmasıdır.',
  ),
  s(
    'orta',
    'Hücrelerin farklılaşarak görev kazanması ve canlının olgunlaşması hangisidir?',
    'Gelişme',
    ['Büyüme', 'Üreme', 'Adaptasyon'],
    'Büyüme "daha büyük olmak", gelişme "daha yetkin olmak"tır; ikisi birlikte yürür.',
  ),
  s(
    'orta',
    'Metabolizma hızı hangi dönemde en yüksektir?',
    'Büyüme ve gelişme döneminde',
    ['Yaşlılık döneminde', 'Kış uykusu sırasında', 'Uyku sırasında'],
    'Büyüme döneminde yapım tepkimeleri hızlandığı için metabolizma en yüksek seviyededir.',
  ),
  s(
    'kolay',
    'Bir canlının yaşadığı ortama kalıtsal olarak uymasına ne ad verilir?',
    'Adaptasyon',
    ['Homeostazi', 'Modifikasyon', 'Mutasyon'],
    'Adaptasyon kalıtsaldır ve yavrulara geçer; modifikasyon çevrenin etkisiyle oluşur, kalıtsal değildir.',
  ),
  s(
    'orta',
    'Kutup tilkisinin kulaklarının küçük, çöl tilkisinin kulaklarının büyük olması hangisine örnektir?',
    'Adaptasyon',
    ['Homeostazi', 'Modifikasyon', 'Büyüme'],
    'Kulak yüzeyi ısı kaybını belirler: soğukta küçük kulak ısıyı korur, sıcakta büyük kulak ısıyı atar.',
  ),
  s(
    'kolay',
    'Aşağıdakilerden hangisi "uyarılara tepki" özelliğine örnektir?',
    'Ayçiçeğinin güneşe dönmesi',
    ['Buzun suda erimesi', 'Demirin paslanması', 'Mumun ısıyla erimesi'],
    'Uyarana tepki canlılığa özgüdür; cansız varlıklardaki değişimler fiziksel ya da kimyasal olaylardır.',
  ),
  s(
    'zor',
    'Aşağıdakilerden hangisi hem canlılarda hem cansız varlıklarda görülebilir?',
    'Hareket',
    ['Üreme', 'Boşaltım', 'Metabolizma'],
    'Rüzgârla sürüklenen bir yaprak da hareket eder; hareketi canlılık belirtisi yapan şey uyarana tepki olmasıdır.',
  ),
  s(
    'orta',
    'Canlılardaki organizasyon (düzenlilik) hangi sırayla ilerler?',
    'Hücre – doku – organ – sistem – organizma',
    [
      'Doku – hücre – organ – sistem – organizma',
      'Hücre – organ – doku – sistem – organizma',
      'Organel – doku – hücre – organ – organizma',
    ],
    'Her basamak bir öncekilerden kurulur; tek hücrelilerde organizasyon hücre basamağında kalır.',
  ),
  s(
    'orta',
    'Aşağıdakilerden hangisi organizasyon özelliğiyle ilgilidir?',
    'Benzer hücrelerin bir araya gelip doku oluşturması',
    [
      'Canlının çevresine uyum sağlaması',
      'Atık maddelerin dışarı atılması',
      'Canlının uyarana tepki vermesi',
    ],
    'Organizasyon, canlının yapısındaki basamaklı düzendir: hücreden organizmaya doğru karmaşıklaşır.',
  ),
  s(
    'kolay',
    'Bütün canlılarda kalıtsal bilgiyi taşıyan molekül hangisidir?',
    'DNA',
    ['ATP', 'Protein', 'Glikoz'],
    'DNA kalıtsal bilgiyi taşır ve eşlenerek yavruya aktarılır; ATP enerji taşır, protein görev yapar.',
  ),
  s(
    'kolay',
    'Hücrede enerjinin taşınmasında ve kullanılmasında ortak olan molekül hangisidir?',
    'ATP',
    ['DNA', 'RNA', 'Selüloz'],
    'Besinlerden çıkan enerji doğrudan kullanılmaz, önce ATP’ye aktarılır. Bütün canlılar ATP kullanır.',
  ),
  s(
    'kolay',
    'Bütün canlıların yapısında en fazla bulunan madde hangisidir?',
    'Su',
    ['Protein', 'Karbonhidrat', 'Yağ'],
    'Su, hücredeki tepkimelerin ortamıdır ve canlı kütlesinin büyük bölümünü oluşturur.',
  ),
  s(
    'kolay',
    'Kendi besinini kendi üreten canlılara ne ad verilir?',
    'Ototrof',
    ['Heterotrof', 'Saprofit', 'Parazit'],
    'Ototroflar inorganik maddelerden organik besin üretir; heterotroflar hazır besinle beslenir.',
  ),
  s(
    'kolay',
    'Hazır besinle beslenen canlılara ne ad verilir?',
    'Heterotrof',
    ['Ototrof', 'Fotoototrof', 'Kemoototrof'],
    'Hayvanlar, mantarlar ve birçok bakteri heterotroftur: besini dışarıdan alır.',
  ),
  s(
    'orta',
    'Işık enerjisini kullanarak kendi besinini üreten canlılara ne denir?',
    'Fotoototrof',
    ['Kemoototrof', 'Heterotrof', 'Saprofit'],
    'Bitkiler, algler ve siyanobakteriler fotoototroftur; enerji kaynakları güneş ışığıdır.',
  ),
  s(
    'orta',
    'Kimyasal tepkimelerden elde ettiği enerjiyle besin üreten canlılara ne denir?',
    'Kemoototrof',
    ['Fotoototrof', 'Saprofit', 'Parazit'],
    'Kemoototroflar ışıksız ortamlarda da besin üretebilen bakterilerdir (nitrit ve kükürt bakterileri gibi).',
  ),
  s(
    'orta',
    'Ölü ve çürümüş organik maddelerle beslenen canlılara ne ad verilir?',
    'Saprofit',
    ['Parazit', 'Ototrof', 'Kemoototrof'],
    'Saprofitler (çürükçüller) madde döngüsünü tamamlar: organik atığı ayrıştırıp toprağa döndürür.',
  ),
  s(
    'orta',
    'Aşağıdakilerden hangisi bütün canlıların ortak özelliği değildir?',
    'Fotosentez yapmak',
    ['Beslenmek', 'Solunum yapmak', 'Boşaltım yapmak'],
    'Fotosentezi yalnızca klorofil taşıyan canlılar yapar; beslenme, solunum ve boşaltım her canlıda vardır.',
  ),
  s(
    'zor',
    'Bir canlıda üreme, büyüme ve gelişme görülüyorsa aşağıdakilerden hangisi kesinlikle söylenir?',
    'Metabolik faaliyetleri vardır',
    ['Ototroftur', 'Çok hücrelidir', 'Oksijenli solunum yapar'],
    'Üreme, büyüme ve gelişme enerji ister; enerjiyi de metabolizma sağlar. Beslenme şekli ve hücre sayısı ise değişebilir.',
  ),

  // --- Hücresel yapı, prokaryot–ökaryot ---
  // Bu blok "canlı = hücre" fikrini oturtuyor: ortak özelliklerin hepsi hücrede
  // yürüdüğü için hücre yapısı bilinmeden gerisi ezber kalıyor.
  s(
    'kolay',
    'Amip, öglena ve paramesyum hücre sayısı bakımından nasıl canlılardır?',
    'Tek hücreli',
    ['Çok hücreli', 'Doku düzeyinde', 'Hücresiz'],
    'Bu canlıların tamamı tek bir hücreden oluşur; beslenme, solunum ve boşaltımın hepsi o tek hücrede yürür.',
  ),
  s(
    'kolay',
    'Çekirdek zarı bulunmayan hücrelere ne ad verilir?',
    'Prokaryot hücre',
    ['Ökaryot hücre', 'Bitki hücresi', 'Mantar hücresi'],
    'Prokaryotlarda kalıtım maddesi sitoplazmada serbest durur. Bitki ve mantar hücrelerinde çekirdek zarı vardır, ikisi de ökaryottur.',
  ),
  s(
    'kolay',
    'Aşağıdaki canlılardan hangisi prokaryot hücre yapısına sahiptir?',
    'Bakteri',
    ['Maya mantarı', 'Amip', 'Kara yosunu'],
    'Yalnızca bakteri ve arkeler prokaryottur; maya, amip ve kara yosunu çekirdek zarı taşıdığı için ökaryottur.',
  ),
  s(
    'orta',
    'Bakterilerde aşağıdaki yapılardan hangisi bulunmaz?',
    'Çekirdek zarı',
    ['Ribozom', 'Hücre zarı', 'DNA'],
    'Bakterinin DNA’sı vardır ama çevresinde zar yoktur. Ribozom ve hücre zarı ise bütün hücrelerde ortaktır.',
  ),
  s(
    'orta',
    'Bütün hücrelerde ortak olarak bulunan yapılar hangi seçenekte doğru verilmiştir?',
    'Hücre zarı, sitoplazma, ribozom ve DNA',
    [
      'Hücre duvarı, kloroplast ve ribozom',
      'Çekirdek, mitokondri ve koful',
      'Kloroplast, lizozom ve hücre duvarı',
    ],
    'Prokaryot–ökaryot ayrımı gözetmeksizin her hücrede bu dört yapı bulunur; kloroplast, mitokondri ve hücre duvarı ise yalnızca bazı hücrelerde vardır.',
  ),
  s(
    'kolay',
    'Protein sentezini gerçekleştiren ve hem prokaryot hem ökaryot hücrelerde bulunan organel hangisidir?',
    'Ribozom',
    ['Mitokondri', 'Golgi cisimciği', 'Lizozom'],
    'Ribozom zarsız bir organeldir, bu yüzden prokaryotlarda da bulunur. Protein sentezi bütün canlılar için zorunludur.',
  ),
  s(
    'kolay',
    'Bitki hücresinde bulunup hayvan hücresinde bulunmayan yapı hangisidir?',
    'Hücre duvarı',
    ['Hücre zarı', 'Ribozom', 'Sitoplazma'],
    'Selülozdan yapılmış hücre duvarı bitkiye desteklik verir; hücre zarı, ribozom ve sitoplazma iki hücrede de vardır.',
  ),
  s(
    'orta',
    'Aşağıdaki organellerden hangisi hayvan hücresinde bulunmaz?',
    'Kloroplast',
    ['Mitokondri', 'Golgi cisimciği', 'Lizozom'],
    'Kloroplast fotosentez organelidir ve yalnızca bitkilerle alglerde bulunur; hayvan hücresi besinini dışarıdan alır.',
  ),
  s(
    'kolay',
    'Hücrenin yönetim merkezi olan ve kalıtsal maddeyi barındıran yapı hangisidir?',
    'Çekirdek',
    ['Ribozom', 'Koful', 'Sentrozom'],
    'Çekirdek DNA’yı korur ve hücrenin bütün faaliyetlerini yönetir; koful depo, ribozom ise üretim yapısıdır.',
  ),
  s(
    'kolay',
    'Oksijenli solunumun yapıldığı, hücrenin enerji santrali sayılan organel hangisidir?',
    'Mitokondri',
    ['Kloroplast', 'Ribozom', 'Golgi cisimciği'],
    'Mitokondride besinlerdeki enerji ATP’ye aktarılır. Kloroplast ise enerjiyi tüketmez, besin üretir.',
  ),
  s(
    'orta',
    'Hücreye giren ve çıkan maddeleri denetleyen seçici geçirgen yapı hangisidir?',
    'Hücre zarı',
    ['Hücre duvarı', 'Çekirdek zarı', 'Sitoplazma'],
    'Hücre duvarı tam geçirgendir, seçme yapmaz; madde alışverişini denetleyen seçici geçirgen yapı hücre zarıdır.',
  ),
  s(
    'zor',
    'Bir hücrede çekirdek zarı yoksa aşağıdakilerden hangisi kesinlikle söylenir?',
    'Ribozom bulundurur',
    ['Kloroplast bulundurur', 'Mitokondri bulundurur', 'Çok hücrelidir'],
    'Çekirdek zarı olmayan hücre prokaryottur; zarlı organel taşımaz ama protein sentezi için ribozomu mutlaka vardır.',
  ),
  s(
    'orta',
    'Mantarlar hücre yapısı bakımından hangi gruba girer?',
    'Ökaryot',
    ['Prokaryot', 'Hücresiz', 'Virüs benzeri'],
    'Mantarlarda çekirdek zarı ve zarlı organeller bulunur; ökaryottur, ancak beslenmeleri heterotroftur.',
  ),
  s(
    'orta',
    'Tek hücreli bir canlıda beslenme, solunum ve boşaltım nerede gerçekleşir?',
    'Tek bir hücrenin içinde',
    ['Farklı dokularda', 'Ayrı organlarda', 'Sistemlerde'],
    'Tek hücrelide doku, organ ve sistem yoktur; bütün yaşamsal olaylar aynı hücrenin içinde yürütülür.',
  ),
  s(
    'zor',
    'Hücre zarı, sitoplazma ve kalıtım maddesi taşıdığı hâlde yalnızca ribozom organeli bulunan canlı grubu hangisidir?',
    'Bakteriler',
    ['Bitkiler', 'Mantarlar', 'Protistler'],
    'Bakteriler prokaryot olduğu için zarlı organel taşımaz; tek organelleri ribozomdur. Diğer üç grup ökaryottur.',
  ),

  // --- Canlı–cansız ayrımı ---
  // Sınavda en çok "bu olay canlılık belirtisi midir" diye soruluyor; ölçüt
  // hareket değil, hücre ve metabolizma.
  s(
    'kolay',
    'Aşağıdakilerden hangisi cansız varlıklarda görülmez?',
    'Metabolizma',
    ['Hareket', 'Kütle artışı', 'Şekil değişimi'],
    'Yuvarlanan bir kar topu da büyür ve hareket eder; ama içinde yapım–yıkım tepkimeleri yoktur. Metabolizma yalnızca canlılara özgüdür.',
  ),
  s(
    'orta',
    'Kar tanesinin büyümesi ile bir bitkinin büyümesi arasındaki temel fark nedir?',
    'Bitkide büyüme hücre bölünmesiyle içeriden gerçekleşir',
    [
      'Kar tanesi daha hızlı büyür',
      'Bitkide kütle artışı olmaz',
      'Kar tanesinde madde birikmesi görülmez',
    ],
    'Cansızda büyüme dışarıdan madde yapışmasıyla olur; canlıda ise hücreler bölünüp çoğalarak içeriden büyür.',
  ),
  s(
    'kolay',
    'Robotların canlı sayılmamasının nedeni aşağıdakilerden hangisidir?',
    'Hücresel yapılarının ve metabolizmalarının olmaması',
    [
      'Hareket edememeleri',
      'Enerji kullanmamaları',
      'Uyarana tepki verememeleri',
    ],
    'Robot hareket eder, enerji harcar, sensörüyle tepki verir; ama hücresi ve metabolizması olmadığı için canlı değildir.',
  ),
  s(
    'orta',
    'Bir varlığın canlı sayılabilmesi için aşağıdakilerden hangisi zorunludur?',
    'Hücresel yapıya sahip olması',
    ['Gözle görülebilir olması', 'Hareket edebilmesi', 'Ses çıkarabilmesi'],
    'Bakteri gözle görülmez, mercan yer değiştirmez; yine de canlıdırlar. Ortak ve zorunlu ölçüt hücresel yapıdır.',
  ),
  s(
    'zor',
    'Canlılarla cansız varlıklar arasında ortak olan özellik hangisidir?',
    'Atom ve moleküllerden oluşma',
    ['Hücre taşıma', 'ATP üretme', 'Kalıtsal madde taşıma'],
    'Madde olmak bakımından ikisi de atomlardan kuruludur; hücre, ATP ve kalıtsal madde ise yalnızca canlılarda bulunur.',
  ),
  s(
    'orta',
    'Aşağıdaki olaylardan hangisi canlılık belirtisi olarak kabul edilir?',
    'Tohumun uygun koşullarda çimlenmesi',
    ['Suyun buharlaşması', 'Kayanın rüzgârla aşınması', 'Demirin ısıyla genleşmesi'],
    'Çimlenme hücre bölünmesi ve metabolizma gerektirir; diğer üçü fiziksel olaydır, canlılıkla ilgisi yoktur.',
  ),

  // --- Virüslerin konumu ---
  // Virüs "canlı mı" tartışması havuzda ayrı bir blok: hem canlı hem cansız
  // yönlerinin tek tek bilinmesi isteniyor.
  s(
    'orta',
    'Virüslerin canlı sayılmamasının temel gerekçesi nedir?',
    'Hücresel yapılarının olmaması',
    [
      'Kalıtım maddesi taşımamaları',
      'Çok küçük olmaları',
      'Protein bulundurmamaları',
    ],
    'Virüsün nükleik asidi ve protein kılıfı vardır; ama sitoplazması, organeli, kısacası hücresi yoktur.',
  ),
  s(
    'orta',
    'Virüsler için aşağıdakilerden hangisi doğrudur?',
    'Yalnızca canlı hücre içinde çoğalabilirler',
    [
      'Cansız ortamda kendi başlarına çoğalırlar',
      'Kendi ribozomlarında protein üretirler',
      'Oksijenli solunum yaparlar',
    ],
    'Virüsler zorunlu hücre içi parazittir; enzimi ve ribozomu olmadığı için çoğalırken konak hücrenin yapılarını kullanır.',
  ),
  s(
    'orta',
    'Virüslerin yapısında aşağıdakilerden hangisi bulunur?',
    'Nükleik asit ve protein',
    ['Sitoplazma ve ribozom', 'Hücre zarı ve çekirdek', 'Mitokondri ve koful'],
    'Virüs, protein kılıf içine alınmış bir nükleik asitten ibarettir; organel ve sitoplazma taşımaz.',
  ),
  s(
    'zor',
    'Virüslerin canlılara benzeyen yönü aşağıdakilerden hangisidir?',
    'Kalıtsal madde taşımaları ve mutasyon geçirebilmeleri',
    [
      'Kendi enzimleriyle metabolizma yürütmeleri',
      'Bağımsız olarak bölünebilmeleri',
      'Boşaltım yapmaları',
    ],
    'Virüs nükleik asit taşır ve değişime uğrar; ama metabolizması, bölünmesi ve boşaltımı yoktur.',
  ),
  s(
    'zor',
    'Aşağıdakilerden hangisi virüslerin cansız özelliğidir?',
    'Hücre dışında kristalleştirilebilmeleri',
    [
      'Mutasyon geçirmeleri',
      'Kalıtsal madde taşımaları',
      'Konak hücrede çoğalmaları',
    ],
    'Virüsler hücre dışında kristal hâlde bekleyebilir; bu tamamen cansız bir davranıştır, diğer seçenekler canlılık yönleridir.',
  ),

  // --- Organizasyon basamakları ---
  // Hücreden biyosfere kadar sıra ezberlenmeden "organizasyon" sorularının
  // hiçbiri çözülemiyor; bu yüzden basamaklar tek tek soruluyor.
  s(
    'kolay',
    'Yapı ve görev bakımından benzer hücrelerin oluşturduğu topluluğa ne ad verilir?',
    'Doku',
    ['Organ', 'Sistem', 'Organel'],
    'Doku, aynı işi yapan hücrelerin bir aradalığıdır; farklı dokular birleşince organ oluşur.',
  ),
  s(
    'kolay',
    'Farklı dokuların birleşip belirli bir görevi üstlenmesiyle oluşan yapı hangisidir?',
    'Organ',
    ['Doku', 'Hücre', 'Sistem'],
    'Mide, kalp ve böbrek birer organdır; her biri birden çok doku çeşidinden kuruludur.',
  ),
  s(
    'orta',
    'Ağız, mide, ince bağırsak ve karaciğerin birlikte çalışması organizasyonun hangi basamağına örnektir?',
    'Sistem',
    ['Organ', 'Doku', 'Organel'],
    'Ortak bir amaç için çalışan organlar topluluğu sistemdir; buradaki amaç sindirimdir.',
  ),
  s(
    'kolay',
    'Kalp, hangi organizasyon basamağında yer alır?',
    'Organ',
    ['Doku', 'Sistem', 'Hücre'],
    'Kalpte kas, sinir ve bağ dokusu birlikte bulunur; birden çok dokudan kurulu yapı organdır.',
  ),
  s(
    'orta',
    'Organizasyon basamaklarında hücreden bir alt basamak hangisidir?',
    'Organel',
    ['Doku', 'Organ', 'Sistem'],
    'Organel hücrenin içindeki görevli yapıdır; ancak canlılık organel düzeyinde değil, hücre düzeyinde başlar.',
  ),
  s(
    'orta',
    'Canlılık özelliği gösteren en küçük organizasyon basamağı hangisidir?',
    'Hücre',
    ['Organel', 'Molekül', 'Atom'],
    'Tek başına bir organel ya da molekül yaşayamaz; beslenme, solunum ve üremeyi birlikte yapabilen en küçük birim hücredir.',
  ),
  s(
    'orta',
    'Organizasyon basamaklarında organizmadan sonra gelen basamak hangisidir?',
    'Popülasyon',
    ['Sistem', 'Organ', 'Doku'],
    'Doku, organ ve sistem organizmanın içindeki basamaklardır; organizmadan sonrası ekolojik basamaklarla, yani popülasyonla sürer.',
  ),
  s(
    'orta',
    'Bir gölde yaşayan bütün sazan balıkları hangi organizasyon basamağını oluşturur?',
    'Popülasyon',
    ['Komünite', 'Ekosistem', 'Organizma'],
    'Popülasyon, belirli bir bölgede yaşayan aynı türden bireylerin tümüdür; farklı türler eklenirse komünite olur.',
  ),
  s(
    'orta',
    'Aynı bölgede yaşayan farklı popülasyonların oluşturduğu birliğe ne ad verilir?',
    'Komünite',
    ['Popülasyon', 'Ekosistem', 'Biyosfer'],
    'Komünite yalnızca canlıları kapsar; cansız çevre de hesaba katılırsa ekosistem adını alır.',
  ),
  s(
    'orta',
    'Komünitenin cansız çevreyle birlikte oluşturduğu bütün hangisidir?',
    'Ekosistem',
    ['Komünite', 'Popülasyon', 'Biyosfer'],
    'Ekosistem = canlılar + toprak, su, ışık gibi cansız etkenler. Bu ikisi sürekli madde ve enerji alışverişi içindedir.',
  ),
  s(
    'kolay',
    'Yeryüzündeki bütün ekosistemleri kapsayan en geniş organizasyon basamağı hangisidir?',
    'Biyosfer',
    ['Ekosistem', 'Komünite', 'Popülasyon'],
    'Biyosfer, canlıların yaşadığı bütün alanların toplamıdır; organizasyonun en üst basamağıdır.',
  ),
  s(
    'orta',
    'Ekolojik organizasyon basamakları hangi seçenekte küçükten büyüğe doğru sıralanmıştır?',
    'Popülasyon – komünite – ekosistem – biyosfer',
    [
      'Komünite – popülasyon – ekosistem – biyosfer',
      'Ekosistem – komünite – popülasyon – biyosfer',
      'Popülasyon – ekosistem – komünite – biyosfer',
    ],
    'Önce aynı türden bireyler (popülasyon), sonra türler bir araya gelir (komünite), cansız çevre eklenir (ekosistem), hepsinin toplamı biyosferdir.',
  ),
  s(
    'zor',
    'Tek hücreli bir canlı için aşağıdakilerden hangisi söylenemez?',
    'Doku ve organ bulundurur',
    [
      'Metabolizma faaliyeti yapar',
      'Uyarılara tepki verir',
      'Kalıtsal madde taşır',
    ],
    'Tek hücrelide organizasyon hücre basamağında biter; doku ve organ yalnızca çok hücrelilerde görülür.',
  ),

  // --- Beslenme: ototrof ve heterotrof çeşitleri ---
  // Havuzda beslenme tipi zaten vardı; burada tipler örnekleriyle ayrıştırılıyor,
  // çünkü sınav "hangi canlı hangi gruba girer" diye soruyor.
  s(
    'kolay',
    'Başka bir canlının üzerinde ya da içinde yaşayarak ondan beslenen canlılara ne ad verilir?',
    'Parazit',
    ['Saprofit', 'Ototrof', 'Kemoototrof'],
    'Parazit besinini yaşayan bir konaktan alır ve ona zarar verir; saprofit ise ölü organik maddeyle beslenir.',
  ),
  s(
    'orta',
    'Tenya ve bağırsak solucanı beslenme bakımından hangi gruba girer?',
    'İç parazit',
    ['Dış parazit', 'Saprofit', 'Ototrof'],
    'Bu canlılar konağın bağırsağında yaşar ve sindirilmiş besini doğrudan emer; sindirim sistemleri bile körelmiştir.',
  ),
  s(
    'orta',
    'Bit ve kene hangi beslenme biçimine örnektir?',
    'Dış parazit',
    ['İç parazit', 'Saprofit', 'Fotoototrof'],
    'Konağın dış yüzeyine tutunup kanıyla beslendikleri için dış parazittirler; iç parazitler konağın içinde yaşar.',
  ),
  s(
    'zor',
    'Sinek kapan gibi böcekçil bitkiler böcek yakalayarak hangi ihtiyacını karşılar?',
    'Azot ihtiyacını',
    [
      'Enerji ihtiyacını',
      'Su ihtiyacını',
      'Karbondioksit ihtiyacını',
    ],
    'Bu bitkiler fotosentez yapar, yani besinini kendi üretir; azotça fakir topraklarda yaşadıkları için azotu böcek proteininden alırlar.',
  ),
  s(
    'kolay',
    'Fotosentezde bitkinin dışarıdan aldığı ham maddeler hangileridir?',
    'Karbondioksit ve su',
    ['Oksijen ve glikoz', 'Azot ve oksijen', 'Glikoz ve karbondioksit'],
    'Karbondioksit ile su ham maddedir; glikoz ve oksijen fotosentezin ürünüdür, ham maddesi değildir.',
  ),
  s(
    'kolay',
    'Fotosentez sonucunda havaya verilen gaz hangisidir?',
    'Oksijen',
    ['Karbondioksit', 'Azot', 'Hidrojen'],
    'Fotosentezde suyun parçalanmasıyla açığa çıkan oksijen havaya verilir; karbondioksit ise tüketilir.',
  ),
  s(
    'orta',
    'Kemosentez yapan bakteriler besin üretmek için gereken enerjiyi nereden sağlar?',
    'İnorganik maddelerin oksitlenmesinden',
    [
      'Güneş ışığından',
      'Hazır besinlerden',
      'Ölü organik maddelerden',
    ],
    'Kemosentetik bakteriler amonyak, nitrit veya kükürt gibi maddeleri oksitleyerek enerji elde eder; bu yüzden ışıksız derinliklerde de yaşayabilirler.',
  ),
  s(
    'orta',
    'Bir ekosistemde üretici olarak adlandırılan canlılar hangileridir?',
    'Ototroflar',
    ['Heterotroflar', 'Parazitler', 'Otçul hayvanlar'],
    'Üretici, inorganik maddeden organik besin yapabilen canlıdır; bu yeteneği yalnızca ototroflar taşır.',
  ),
  s(
    'orta',
    'Besin zincirinde birinci tüketici konumunda bulunan canlılar hangileridir?',
    'Otçullar',
    ['Etçiller', 'Üreticiler', 'Ayrıştırıcılar'],
    'Üreticiyi doğrudan yiyen otçul canlılar birinci tüketicidir; etçiller onları yediği için ikinci sıradadır.',
  ),
  s(
    'orta',
    'Besinini büyük parçalar hâlinde alıp vücudunun içinde sindiren beslenme biçimine ne ad verilir?',
    'Holozoik beslenme',
    ['Saprofit beslenme', 'Parazit beslenme', 'Ototrof beslenme'],
    'İnsan ve çoğu hayvan holozoiktir: besini ağızdan alır, sindirim sisteminde parçalar. Saprofitler ise sindirimi hücre dışında yapar.',
  ),
  s(
    'orta',
    'Amip ve terliksi hayvanda hücre içi sindirimi sağlayan organel hangisidir?',
    'Lizozom',
    ['Ribozom', 'Sentrozom', 'Kloroplast'],
    'Lizozom sindirim enzimi taşır; besin kofuluyla birleşerek besini hücre içinde parçalar.',
  ),
  s(
    'zor',
    'Öglenanın hem ototrof hem heterotrof beslenebilmesinin nedeni nedir?',
    'Kloroplast taşıması ve gerektiğinde hazır besin alabilmesi',
    [
      'Yalnızca karanlıkta yaşayabilmesi',
      'Hücre duvarı bulundurması',
      'Çok hücreli olması',
    ],
    'Öglena ışık varken kloroplastıyla besin üretir, ışık yokken dışarıdan hazır besin alır. Bu yüzden tek başına iki beslenme tipini birden gösterir.',
  ),
  s(
    'orta',
    'Bütün canlılar için beslenmenin ortak amacı nedir?',
    'Enerji ve yapı maddesi sağlamak',
    [
      'Yalnızca su kazanmak',
      'Yalnızca ısı üretmek',
      'Yalnızca boşaltım yapmak',
    ],
    'Canlı hem yakıt hem tuğla ister: besin, ATP üretimi için enerji ve büyüme için yapı maddesi sağlar.',
  ),
  s(
    'orta',
    'Bir canlının ototrof olduğu aşağıdakilerden hangisine bakılarak anlaşılır?',
    'İnorganik maddelerden organik besin üretmesine',
    [
      'Oksijen kullanmasına',
      'Hücre duvarı taşımasına',
      'Çok hücreli olmasına',
    ],
    'Ototrofluğun tek ölçütü besinini kendi üretmesidir; oksijen kullanmak veya hücre duvarı taşımak heterotroflarda da görülür.',
  ),

  // --- Solunum ---
  // Solunum organı değişir, hücresel solunum değişmez. Sorular bu ayrımı
  // tekrar tekrar yokluyor.
  s(
    'kolay',
    'Hücresel solunumda parçalanarak enerji elde edilen temel besin hangisidir?',
    'Glikoz',
    ['Selüloz', 'Vitamin', 'Mineral'],
    'Hücrenin ilk tercihi glikozdur. Vitamin ve mineral enerji vermez; selülozu ise insan sindiremez.',
  ),
  s(
    'orta',
    'Solunumun ilk basamağı olan glikoliz hücrenin neresinde gerçekleşir?',
    'Sitoplazmada',
    ['Mitokondride', 'Çekirdekte', 'Kloroplastta'],
    'Glikoliz bütün canlılarda sitoplazmada olur; mitokondrisi olmayan bakteriler de bu yüzden solunum yapabilir.',
  ),
  s(
    'orta',
    'Oksijenli solunum sonucunda açığa çıkan son ürünler hangileridir?',
    'Karbondioksit ve su',
    ['Etil alkol ve karbondioksit', 'Laktik asit ve su', 'Oksijen ve glikoz'],
    'Glikoz oksijenle tam parçalandığında geriye karbondioksit ve su kalır; etil alkol ve laktik asit fermantasyon ürünüdür.',
  ),
  s(
    'orta',
    'Ekmek hamurunun kabarmasını sağlayan olay hangisidir?',
    'Etil alkol fermantasyonu',
    ['Laktik asit fermantasyonu', 'Oksijenli solunum', 'Fotosentez'],
    'Maya glikozu etil alkol ve karbondioksite çevirir; hamuru kabartan, açığa çıkan karbondioksit gazıdır.',
  ),
  s(
    'orta',
    'Sütten yoğurt elde edilmesini sağlayan olay hangisidir?',
    'Laktik asit fermantasyonu',
    ['Etil alkol fermantasyonu', 'Oksijenli solunum', 'Kemosentez'],
    'Laktik asit bakterileri süt şekerini laktik asite çevirir; ortamın asitlenmesi sütün proteinlerini pıhtılaştırır.',
  ),
  s(
    'orta',
    'Oksijenin yetersiz kaldığı kas hücrelerinde birikerek yorgunluğa yol açan madde hangisidir?',
    'Laktik asit',
    ['Etil alkol', 'Üre', 'Amonyak'],
    'İnsan kas hücresi oksijen yetmediğinde laktik asit fermantasyonu yapar; etil alkol fermantasyonunu insan hücresi yapamaz.',
  ),
  s(
    'orta',
    'Fermantasyon hücrenin hangi kısmında gerçekleşir?',
    'Sitoplazmada',
    ['Mitokondride', 'Çekirdekte', 'Golgi cisimciğinde'],
    'Fermantasyon için mitokondri gerekmez; bu yüzden mitokondrisi bulunmayan bakteriler ve mayalar da fermantasyon yapabilir.',
  ),
  s(
    'zor',
    'Oksijenli solunumun oksijensiz solunuma üstünlüğü nedir?',
    'Aynı miktar glikozdan çok daha fazla ATP elde edilmesi',
    [
      'Enzim gerektirmemesi',
      'Daha az basamaktan oluşması',
      'Karbondioksit açığa çıkarmaması',
    ],
    'Glikoz oksijenle tam parçalandığı için elde edilen ATP, fermantasyonla elde edilenin kat kat üzerindedir.',
  ),
  s(
    'kolay',
    'Balıklarda gaz alışverişi hangi yapıyla gerçekleşir?',
    'Solungaç',
    ['Akciğer', 'Trake', 'Stoma'],
    'Solungaç suda çözünmüş oksijeni alır; akciğer ve trake karada yaşayan canlıların yapılarıdır.',
  ),
  s(
    'kolay',
    'Böceklerde gaz alışverişi hangi yapıyla sağlanır?',
    'Trake',
    ['Solungaç', 'Akciğer', 'Deri'],
    'Trakeler vücudun içine kadar uzanan hava borularıdır; oksijeni doğrudan hücrelere ulaştırır.',
  ),
  s(
    'orta',
    'Toprak solucanında gaz alışverişi nasıl gerçekleşir?',
    'Nemli deri yüzeyinden',
    ['Akciğerle', 'Solungaçla', 'Trakelerle'],
    'Solucanın deri altındaki kılcal damarları gazları doğrudan alır; bu yüzden derisinin kuruması ölümcüldür.',
  ),
  s(
    'orta',
    'Bitkilerde gaz alışverişi yaprağın hangi yapısıyla yapılır?',
    'Stoma',
    ['Kütikula', 'Ksilem', 'Floem'],
    'Stomalar açılıp kapanarak gaz giriş çıkışını denetler; kütikula ise su kaybını önleyen mumsu bir örtüdür.',
  ),
  s(
    'orta',
    'Hücresel solunumda açığa çıkan enerjinin ATP’ye aktarılamayan kısmı ne olur?',
    'Isı olarak yayılır',
    ['Işığa dönüşür', 'Glikoz olarak depolanır', 'Karbondioksite dönüşür'],
    'Enerjinin bir bölümü ATP’ye aktarılır, kalanı ısı olarak çevreye yayılır; vücut sıcaklığının kaynağı budur.',
  ),

  // --- Boşaltım ---
  // Atık maddenin ne olduğu ve nereden atıldığı canlıdan canlıya değişiyor;
  // ortak olan tek şey atığın birikmesine izin verilmemesi.
  s(
    'kolay',
    'Tatlı suda yaşayan tek hücreli canlılarda fazla suyu dışarı atan yapı hangisidir?',
    'Kontraktil koful',
    ['Besin kofulu', 'Lizozom', 'Ribozom'],
    'Tatlı su hücreye sürekli su sokar; kontraktil koful bu fazlalığı dışarı pompalayarak hücrenin patlamasını önler.',
  ),
  s(
    'kolay',
    'İnsanda boşaltımın temel organı hangisidir?',
    'Böbrek',
    ['Mide', 'Pankreas', 'Dalak'],
    'Böbrek kanı süzerek üre, fazla su ve tuzu idrarla atar; mide ve pankreas sindirim organıdır.',
  ),
  s(
    'orta',
    'İnsanda proteinlerin yıkımı sonucu oluşan azotlu atık hangisidir?',
    'Üre',
    ['Nişasta', 'Glikojen', 'Laktoz'],
    'Amino asitlerden ayrılan azot karaciğerde üreye çevrilir ve böbrekle atılır; diğer üçü karbonhidrattır, atık değildir.',
  ),
  s(
    'orta',
    'Kuşlarda ve sürüngenlerde azotlu boşaltım maddesi hangisidir?',
    'Ürik asit',
    ['Üre', 'Amonyak', 'Laktik asit'],
    'Ürik asit çok az suyla atılabildiği için karada ve yumurta içinde su kaybını önler.',
  ),
  s(
    'orta',
    'Suda yaşayan canlıların çoğu azotlu atığını hangi madde olarak atar?',
    'Amonyak',
    ['Üre', 'Ürik asit', 'Kreatin'],
    'Amonyak çok zehirlidir ama bol suda hemen seyreldiği için su canlıları onu dönüştürmeden doğrudan atabilir.',
  ),
  s(
    'orta',
    'Bitkilerde fazla suyun yapraklardan buhar hâlinde atılmasına ne ad verilir?',
    'Terleme',
    ['Damlama', 'Osmoz', 'Fotosentez'],
    'Terleme stomalardan su buharı çıkışıdır; damlama ise suyun sıvı damlalar hâlinde atılmasıdır.',
  ),
  s(
    'orta',
    'Terleme insanda hangi iki görevi birden yerine getirir?',
    'Boşaltım ve vücut sıcaklığının düzenlenmesi',
    [
      'Sindirim ve solunum',
      'Üreme ve büyüme',
      'Dolaşım ve hareket',
    ],
    'Ter, su ve tuz atarak boşaltıma katkı verir; buharlaşırken ısı çektiği için de vücudu serinletir.',
  ),
  s(
    'orta',
    'Tek hücreli canlılarda boşaltım maddeleri hangi yapıdan dışarı verilir?',
    'Hücre zarından',
    ['Böbrekten', 'Malpighi tüplerinden', 'Stomadan'],
    'Tek hücrelide boşaltım organı yoktur; atıklar doğrudan hücre zarından difüzyonla dışarı çıkar.',
  ),
  s(
    'zor',
    'Karbondioksitin vücuttan uzaklaştırılması hangi ortak özelliğin kapsamına girer?',
    'Boşaltım',
    ['Beslenme', 'Üreme', 'Sindirim'],
    'Karbondioksit solunum tepkimelerinin atığıdır; atılması boşaltımdır, bu işte akciğer görev alır.',
  ),
  s(
    'orta',
    'Aşağıdakilerden hangisi bir boşaltım maddesi değildir?',
    'Glikoz',
    ['Üre', 'Karbondioksit', 'Ürik asit'],
    'Glikoz besindir ve sağlıklı böbrekte geri emilir; idrarda glikoza rastlanması hastalık belirtisidir.',
  ),
  s(
    'zor',
    'Böbrekleri görev yapamayan bir insanda kanda hangi maddenin birikmesi beklenir?',
    'Üre',
    ['Glikojen', 'Nişasta', 'Selüloz'],
    'Üre kandan yalnızca böbrekle uzaklaştırılır; böbrek çalışmazsa kanda birikerek zehirlenmeye yol açar.',
  ),
  s(
    'orta',
    'Boşaltımın canlı için önemi aşağıdakilerden hangisidir?',
    'Zararlı atıkların birikmesini önleyerek iç dengeyi korumak',
    [
      'Besin üretimini artırmak',
      'Kalıtsal bilgiyi yavruya aktarmak',
      'Tür sayısını çoğaltmak',
    ],
    'Atıklar birikirse hücre zehirlenir; boşaltım bu yüzden homeostazinin ayrılmaz parçasıdır.',
  ),
]

export const ORTAK_BOYUTU = ORTAK_HAVUZU.length
