/**
 * Deyim ve Atasözü oyununun havuzu.
 *
 * Her satır bir söz, anlamı, türü (deyim mi atasözü mü) ve **konusu**.
 *
 * ## Konu neden var
 *
 * Şıklar sabit bir listeden değil, havuzun kendisinden geliyor: çeldiriciler
 * başka sözlerin anlamları. Ama iki deyim aynı anlama gelebiliyor — *etekleri
 * zil çalmak* ile *ağzı kulaklarına varmak* ikisi de "çok sevinmek" demek. Aynı
 * soruda karşılaşırlarsa iki şık birden doğru olur.
 *
 * Konu etiketi bunu engelliyor: çeldirici **farklı konudan** seçiliyor. Aynı
 * konudaki eşanlamlılar hiçbir zaman yan yana gelmiyor, dolayısıyla havuza
 * rahatça girebiliyorlar.
 *
 * Anlamlar TDK Atasözleri ve Deyimler Sözlüğü'ne dayanıyor ve bilerek kısa
 * tutuldu: dört şıkkın hepsi telefonda tek bakışta okunabilmeli.
 */

import type { Zorluk } from './ritim'

export type SozTuru = 'deyim' | 'atasozu'

export type SozKonusu = 'duygu' | 'davranis' | 'calisma' | 'para' | 'iletisim' | 'akil'

export type SozSorusu = {
  soz: string
  anlam: string
  tur: SozTuru
  konu: SozKonusu
  /**
   * Zorluk.
   *
   * Burada zorluğu belirleyen konu değil, sözün **ne kadar bilindiği**:
   * "küplere binmek" ile "burnundan kıl aldırmamak" aynı konudan ama aynı
   * zorlukta değil. Bu yüzden grup tabanı `orta`, ayrılanlar tek tek işaretli.
   */
  zorluk: Zorluk
}

export const TUR_ADI: Record<SozTuru, string> = {
  deyim: 'Deyim',
  atasozu: 'Atasözü',
}

export const KONU_ADI: Record<SozKonusu, string> = {
  duygu: 'Duygular',
  davranis: 'Davranış ve huy',
  calisma: 'Emek ve çalışma',
  para: 'Para ve geçim',
  iletisim: 'Söz ve iletişim',
  akil: 'Akıl, tedbir, talih',
}

/**
 * Deyim ile atasözünün farkı — tur sonunda yanlış bilinenin altında çıkıyor.
 * İkisinin ayrımı ÖSYM'nin ayrıca sorduğu bir konu.
 */
export const TUR_ACIKLAMASI: Record<SozTuru, string> = {
  deyim:
    'Deyim, anlatımı güçlendirmek için kullanılan kalıplaşmış söz öbeğidir; öğüt vermez, cümlenin içinde bir görev üstlenir.',
  atasozu:
    'Atasözü, uzun deneyimlerden çıkan bir yargıyı bildirir; öğüt verir ve tek başına bir cümle kurar.',
}

/** Havuzu okunur tutmak için: bir konuya ait bütün sözler tek yerde. */
function grup(
  konu: SozKonusu,
  sozler: ([string, string, SozTuru] | [string, string, SozTuru, Zorluk])[],
): SozSorusu[] {
  return sozler.map(([soz, anlam, tur, zorluk]) => ({
    soz,
    anlam,
    tur,
    konu,
    zorluk: zorluk ?? 'orta',
  }))
}

export const SOZ_HAVUZU: readonly SozSorusu[] = [
  ...grup('duygu', [
    ['etekleri zil çalmak', 'Çok sevinmek', 'deyim', 'kolay'],
    ['ağzı kulaklarına varmak', 'Sevinci yüzünden okunmak', 'deyim', 'kolay'],
    ['içi içine sığmamak', 'Sevinçten yerinde duramamak', 'deyim'],
    ['yüreği ağzına gelmek', 'Ansızın çok korkmak', 'deyim'],
    ['ödü kopmak', 'Aşırı derecede korkmak', 'deyim', 'kolay'],
    ['burnunun direği sızlamak', 'Derin bir üzüntü duymak', 'deyim', 'zor'],
    ['içi kan ağlamak', 'Belli etmeden çok üzülmek', 'deyim'],
    ['tepesi atmak', 'Birdenbire çok öfkelenmek', 'deyim', 'kolay'],
    ['küplere binmek', 'Öfkeden kendini kaybetmek', 'deyim', 'kolay'],
    ['yüreği burkulmak', 'Acıma duygusuyla üzülmek', 'deyim'],
    ['gözü korkmak', 'Kötü deneyimden sonra çekinir olmak', 'deyim'],
    ['eli ayağı buz kesmek', 'Korkudan donup kalmak', 'deyim'],
    ['bağrı yanmak', 'Büyük bir acı çekmek', 'deyim', 'zor'],
    ['ağzının tadı kaçmak', 'Huzuru bozulmak', 'deyim'],
    ['yüzü gülmek', 'Sevinçli görünmek', 'deyim', 'kolay'],
    ['içi rahat etmek', 'Kaygısı geçip huzura kavuşmak', 'deyim'],
    ['kanı kaynamak', 'Birine karşı içten yakınlık duymak', 'deyim'],
    ['yüreği hop etmek', 'Ansızın telaşlanmak', 'deyim'],
    ['dünyalar onun olmak', 'Beklediğine kavuşup çok sevinmek', 'deyim', 'zor'],
    ['gönlü olmak', 'Bir şeye sonunda razı olmak', 'deyim'],
    ['bayram etmek', 'Sevinçten coşkuya kapılmak', 'deyim', 'kolay'],
    ['sevinçten uçmak', 'Aşırı sevinç duymak', 'deyim', 'kolay'],
    ['içi içini yemek', 'Sıkıntıdan tedirgin olmak', 'deyim'],
    ['kanı donmak', 'Dehşetten donakalmak', 'deyim', 'zor'],
    ['tüyleri diken diken olmak', 'Korkudan ürpermek', 'deyim', 'kolay'],
    ['gözyaşı dökmek', 'Üzüntüden ağlamak', 'deyim', 'kolay'],
    ['yüreği parçalanmak', 'Dayanılmaz bir acı duymak', 'deyim'],
    ['burnundan solumak', 'Öfkeyle hırslı hırslı soluk almak', 'deyim'],
    ['kanı beynine sıçramak', 'Öfkeyle saldıracak hâle gelmek', 'deyim', 'zor'],
    ['içi cız etmek', 'Birdenbire içi sızlamak', 'deyim', 'zor'],
    ['yüzü asılmak', 'Canı sıkılıp somurtmak', 'deyim', 'kolay'],
    ['gönlü ferahlamak', 'Sıkıntısı dağılıp rahatlamak', 'deyim', 'kolay'],
    ['kalbi kırılmak', 'Bir davranıştan incinmek', 'deyim', 'kolay'],
    ['gözleri dolmak', 'Ağlayacak duruma gelmek', 'deyim', 'kolay'],
    ['dört gözle beklemek', 'Özlemle, sabırsızca beklemek', 'deyim', 'kolay'],
    ['Gönül ferman dinlemez', 'Sevgi buyrukla yönlendirilemez', 'atasozu', 'zor'],
    ['Ateş düştüğü yeri yakar', 'Acının derdini ancak sahibi çeker', 'atasozu'],
    // Havuz 420'ye çıkarıldı: 220 soruda aynı sözler tur içinde erken tekrar ediyordu.
    // Duyguda sevinç ve korku kalabalıktı, şaşkınlık ile utanç hiç yoktu; eksik olan tarafa yüklenildi.
    ['yüreğine su serpilmek', 'İyi bir haberle içi ferahlamak', 'deyim'],
    ['gözü yollarda kalmak', 'Gelmesini bekleyip özlem çekmek', 'deyim'],
    ['yüreği yufka olmak', 'Kolayca duygulanıp acıyan yapıda olmak', 'deyim', 'zor'],
    ['gözü gönlü açılmak', 'Ferahlayıp neşelenmek', 'deyim'],
    ['içine kurt düşmek', 'Kuşkuya kapılıp tedirgin olmak', 'deyim'],
    ['gözünün yaşına bakmamak', 'Acımadan sert davranmak', 'deyim', 'zor'],
    ['saçını başını yolmak', 'Büyük bir üzüntüyle çırpınmak', 'deyim'],
    ['yüzü kızarmak', 'Utancından yüzü renklenmek', 'deyim', 'kolay'],
    ['yerin dibine geçmek', 'Çok utanıp ezilmek', 'deyim', 'kolay'],
    ['başı göğe ermek', 'Umulmadık bir mutluluğa erişmek', 'deyim', 'zor'],
    ['gözleri parlamak', 'Sevinçle bakmak', 'deyim', 'kolay'],
    ['canı sıkılmak', 'Sıkıntı duyup keyfi kaçmak', 'deyim', 'kolay'],
    ['gözü arkada kalmak', 'Geride bıraktığı için içi rahat etmemek', 'deyim', 'zor'],
    ['hüngür hüngür ağlamak', 'Katıla katıla, sesli ağlamak', 'deyim', 'kolay'],
    ['yüreği sızlamak', 'İçten içe acı duymak', 'deyim'],
    ['canı burnuna gelmek', 'Sıkıntıdan bunalıp usanmak', 'deyim', 'zor'],
    ['içine atmak', 'Derdini kimseye söylemeyip içinde tutmak', 'deyim'],
    ['gönlünü almak', 'Kırgınlığını gidermek', 'deyim', 'kolay'],
    ['gönlünü kaptırmak', 'Birine âşık olmak', 'deyim'],
    ['ağzının suyu akmak', 'Bir şeye imrenip çok istemek', 'deyim', 'kolay'],
    ['eli ayağı titremek', 'Heyecandan kendini tutamamak', 'deyim'],
    ['kara kara düşünmek', 'Kaygıyla derin derin düşünmek', 'deyim', 'kolay'],
    ['başından aşağı kaynar sular dökülmek', 'Kötü haberle şaşkına dönüp bunalmak', 'deyim', 'zor'],
    ['kalbi küt küt atmak', 'Heyecandan kalbi hızlanmak', 'deyim', 'kolay'],
    ['ağzı açık kalmak', 'Görüp işittiğine çok şaşırmak', 'deyim', 'kolay'],
    ['küçük dilini yutmak', 'Aşırı şaşırmak', 'deyim', 'zor'],
    ['gözlerine inanamamak', 'Gördüğünün gerçekliğinden kuşku duymak', 'deyim', 'kolay'],
    ['yüreğine inmek', 'Ani üzüntüden yıkılmak', 'deyim', 'zor'],
    ['Gözden ırak olan gönülden de ırak olur', 'Uzak kalan kişi zamanla unutulur', 'atasozu'],
    ['Gönülden gönüle yol vardır', 'Karşılıklı sevgi kendini duyurur', 'atasozu', 'zor'],
    ['Her şeyin yenisi, dostun eskisi', 'Eski dost yenisinden değerlidir', 'atasozu'],
    ['Gönül kimi severse güzel odur', 'Sevilen kişi sevene güzel görünür', 'atasozu', 'zor'],
    ['Dostluk başka, alışveriş başka', 'Dostlukla çıkar işleri karıştırılmaz', 'atasozu'],
  ]),

  ...grup('davranis', [
    ['burnu havada olmak', 'Kibirli davranmak', 'deyim', 'kolay'],
    ['çam devirmek', 'Farkında olmadan kırıcı söz söylemek', 'deyim'],
    ['pireyi deve yapmak', 'Küçük bir olayı büyütmek', 'deyim', 'kolay'],
    ['kaş yaparken göz çıkarmak', 'İyilik yapayım derken zarar vermek', 'deyim'],
    ['burnundan kıl aldırmamak', 'Kimseye söz hakkı tanımayacak kadar aksi olmak', 'deyim', 'zor'],
    ['kabak tadı vermek', 'Tekrarlandığı için bıkkınlık vermek', 'deyim'],
    ['göze girmek', 'Davranışıyla beğeni kazanmak', 'deyim', 'kolay'],
    ['gözden düşmek', 'Eski değerini yitirmek', 'deyim', 'kolay'],
    ['el üstünde tutmak', 'Birine çok değer vermek', 'deyim'],
    ['yüzü tutmamak', 'Çekindiği için isteyememek', 'deyim', 'zor'],
    ['burnunu sokmak', 'Kendini ilgilendirmeyen işe karışmak', 'deyim', 'kolay'],
    ['yüz vermek', 'Yakınlık göstererek şımartmak', 'deyim'],
    ['Huylu huyundan vazgeçmez', 'İnsan alışkanlıklarından kolay kolay kurtulamaz', 'atasozu', 'kolay'],
    ['Ağaç yaş iken eğilir', 'Eğitim küçük yaşta verilir', 'atasozu', 'kolay'],
    ['Üzüm üzüme baka baka kararır', 'İnsan yakın olduğu kişiden etkilenir', 'atasozu'],
    ['Komşunun tavuğu komşuya kaz görünür', 'Başkasının malı insana büyük görünür', 'atasozu', 'zor'],
    ['Kendi düşen ağlamaz', 'Kendi hatasından zarar gören kimseyi suçlayamaz', 'atasozu', 'kolay'],
    ['Eşek hoşaftan ne anlar', 'Değer bilmeyene sunulan şey boşa gider', 'atasozu', 'zor'],
    ['kulak ardı etmek', 'Söyleneni önemsemeyip duymazdan gelmek', 'deyim'],
    ['burnu büyümek', 'Şımarıp kendini beğenmiş olmak', 'deyim'],
    ['ayak diremek', 'İnadından dönmeyip direnmek', 'deyim'],
    ['diş bilemek', 'İçin için öç almayı beklemek', 'deyim'],
    ['kılı kırk yarmak', 'En küçük ayrıntıya kadar titizlenmek', 'deyim', 'kolay'],
    ['gözü kara olmak', 'Korkusuzca atılgan olmak', 'deyim'],
    ['omuz silkmek', 'Aldırmadığını davranışıyla belirtmek', 'deyim'],
    ['kuyusunu kazmak', 'Birine gizlice kötülük hazırlamak', 'deyim'],
    ['burun kıvırmak', 'Beğenmediğini davranışıyla belli etmek', 'deyim', 'kolay'],
    ['çıngar çıkarmak', 'Ortalığı karıştırıp kavga çıkarmak', 'deyim', 'zor'],
    ['foyası meydana çıkmak', 'Gizlediği kötülüğü ortaya çıkmak', 'deyim', 'zor'],
    ['kabak başına patlamak', 'Suçun bedelini tek başına ödemek', 'deyim'],
    ['Gülme komşuna gelir başına', 'Başkasının derdiyle alay eden aynısını yaşar', 'atasozu', 'kolay'],
    ['İt ürür kervan yürür', 'Boş eleştiriler işini yapanı durduramaz', 'atasozu'],
    ['Armut dibine düşer', 'Çocuk anne babasına benzer', 'atasozu', 'kolay'],
    ['Sürüden ayrılanı kurt kapar', 'Topluluktan kopan kişi tehlikeye düşer', 'atasozu', 'kolay'],
    ['Havlayan köpek ısırmaz', 'Çok bağırıp çağıran kişi zarar veremez', 'atasozu', 'kolay'],
    ['Rüzgâr eken fırtına biçer', 'Kötülük yapan daha büyüğüyle karşılaşır', 'atasozu', 'zor'],
    ['Tencere yuvarlanmış kapağını bulmuş', 'Birbirine denk iki kişi bir araya gelmiş', 'atasozu'],
    // Davranış konusu 37'de kalmıştı; kibir ve inatçılık kalabalıkken korkusuzluk,
    // sahip çıkma ve ikiyüzlülük tarafı boştu. Eksik kalan huylara ağırlık verildi.
    ['burnu Kaf dağında olmak', 'Kimseyi beğenmeyecek kadar kibirlenmek', 'deyim', 'zor'],
    ['kılını kıpırdatmamak', 'Hiçbir tepki vermeden durmak', 'deyim'],
    ['kafa tutmak', 'Büyüğüne karşı gelip diklenmek', 'deyim', 'kolay'],
    ['el pençe divan durmak', 'Saygıyla eller bağlı beklemek', 'deyim', 'zor'],
    ['ayağını kaydırmak', 'Oyun kurup birini yerinden etmek', 'deyim'],
    ['çelme takmak', 'Birinin işini gizlice engellemek', 'deyim', 'kolay'],
    ['kazan kaldırmak', 'Topluca başkaldırıp ayaklanmak', 'deyim', 'zor'],
    ['başına buyruk olmak', 'Kimseye danışmadan dilediğince davranmak', 'deyim'],
    ['sırtını dönmek', 'Desteğini çekip ilgilenmez olmak', 'deyim', 'kolay'],
    ['gözünü budaktan sakınmamak', 'Hiçbir tehlikeden çekinmemek', 'deyim', 'zor'],
    ['iki dirhem bir çekirdek', 'Özenle, şık biçimde giyinmiş', 'deyim', 'zor'],
    ['ayağının tozuyla', 'Gelir gelmez, hiç dinlenmeden', 'deyim', 'zor'],
    ['baltayı taşa vurmak', 'Sözüyle karşısındakini istemeden incitmek', 'deyim'],
    ['burnunun dikine gitmek', 'Öğüt dinlemeyip bildiğini yapmak', 'deyim', 'kolay'],
    ['yağ çekmek', 'Çıkar için birini aşırı övmek', 'deyim', 'kolay'],
    ['gözü yükseklerde olmak', 'Elindekini beğenmeyip yükseği istemek', 'deyim'],
    ['kendini naza çekmek', 'İstediği hâlde istemez görünmek', 'deyim'],
    ['içi dışı bir olmak', 'Göründüğü gibi olan, içten kişi', 'deyim', 'kolay'],
    ['kabak çiçeği gibi açılmak', 'Sıkılganlığını atıp aşırı serbestleşmek', 'deyim', 'zor'],
    ['kılına dokunmamak', 'Hiçbir zarar vermemek', 'deyim'],
    ['kol kanat germek', 'Birini koruyup gözetmek', 'deyim', 'kolay'],
    ['kucak açmak', 'Sığınmak isteyeni sıcak karşılamak', 'deyim', 'kolay'],
    ['sırtını sıvazlamak', 'Övüp yüreklendirmek', 'deyim'],
    ['ağzı süt kokmak', 'Toy ve deneyimsiz olmak', 'deyim', 'zor'],
    ['Ne ekersen onu biçersin', 'İnsan yaptığının karşılığını görür', 'atasozu', 'kolay'],
    ['Isıracak köpek dişini göstermez', 'Asıl zarar verecek kişi niyetini belli etmez', 'atasozu', 'zor'],
    ['Meyveli ağacı taşlarlar', 'Değerli kişi çok eleştiri alır', 'atasozu'],
    ['Bir kötünün yedi mahalleye zararı vardır', 'Kötü kişi çevresindeki herkese zarar verir', 'atasozu'],
    ['Kel ölür sırma saçlı olur, kör ölür badem gözlü olur', 'Ölenin kusurları unutulup övgüyle anılır', 'atasozu', 'zor'],
    ['Adam adamı bir kere aldatır', 'Bir kez aldatana bir daha güvenilmez', 'atasozu'],
    ['Kurt kocayınca köpeğin maskarası olur', 'Güçlü kişi güçsüz düşünce hor görülür', 'atasozu', 'zor'],
    ['İyilik eden iyilik bulur', 'İyi davranan karşılığını iyilikle görür', 'atasozu', 'kolay'],
    ['Misafir umduğunu değil bulduğunu yer', 'Konuk ev sahibinin sunduğuyla yetinir', 'atasozu', 'kolay'],
  ]),

  ...grup('calisma', [
    ['ipe un sermek', 'Bahane bulup işi savsaklamak', 'deyim', 'zor'],
    ['dirsek çürütmek', 'Uzun süre öğrenim görmek', 'deyim', 'zor'],
    ['kolları sıvamak', 'Bir işe girişmek', 'deyim', 'kolay'],
    ['göz nuru dökmek', 'Uzun ve yorucu emek harcamak', 'deyim', 'zor'],
    ['ekmeğini taştan çıkarmak', 'Zor koşullarda geçimini sağlamak', 'deyim'],
    ['alnının teriyle kazanmak', 'Kendi emeğiyle kazanç sağlamak', 'deyim'],
    ['canla başla çalışmak', 'Bütün gücüyle uğraşmak', 'deyim'],
    ['iş başa düşmek', 'İşi kendisi yapmak zorunda kalmak', 'deyim'],
    ['taşı sıksa suyunu çıkarmak', 'Çok güçlü ve becerikli olmak', 'deyim', 'zor'],
    ['ter dökmek', 'Bir iş için çok emek harcamak', 'deyim', 'kolay'],
    ['eli ekmek tutmak', 'Geçimini sağlayacak işe kavuşmak', 'deyim'],
    ['kan ter içinde kalmak', 'Çalışmaktan aşırı yorulmak', 'deyim'],
    ['iki eli kanda olsa', 'Ne kadar önemli işi olursa olsun', 'deyim', 'zor'],
    ['eli yatkın olmak', 'Bir işi yapmaya alışkın olmak', 'deyim', 'zor'],
    ['Bugünün işini yarına bırakma', 'İşi ertelemek zarar getirir', 'atasozu', 'kolay'],
    ['Zahmetsiz rahmet olmaz', 'Emek vermeden kazanç elde edilmez', 'atasozu', 'zor'],
    ['Ekmeden biçilmez', 'Emek harcamadan sonuç alınmaz', 'atasozu'],
    ['Bir elin nesi var, iki elin sesi var', 'Birlikte çalışmak daha verimlidir', 'atasozu', 'kolay'],
    ['Acele işe şeytan karışır', 'Aceleyle yapılan iş bozulur', 'atasozu', 'kolay'],
    ['El elin eşeğini türkü çağırarak arar', 'Başkasının işi özenle yapılmaz', 'atasozu', 'zor'],
    ['yüzüne gözüne bulaştırmak', 'Bir işi beceremeyip berbat etmek', 'deyim'],
    ['el atmak', 'Bir işi üstlenip yürütmeye başlamak', 'deyim', 'kolay'],
    ['geceyi gündüze katmak', 'Ara vermeden gece gündüz çalışmak', 'deyim', 'kolay'],
    ['ayak sürümek', 'İsteksizce davranıp işi ağırdan almak', 'deyim'],
    ['ekmeğinden etmek', 'Birini işinden yoksun bırakmak', 'deyim', 'zor'],
    ['yükünün altından kalkmak', 'Zor bir işi başarıyla bitirmek', 'deyim'],
    ['elini taşın altına koymak', 'Sorumluluğu üstlenip yardıma girişmek', 'deyim'],
    ['harcı olmamak', 'Bir işi başaracak güçte olmamak', 'deyim', 'zor'],
    ['yan gelip yatmak', 'Hiçbir iş yapmadan rahatına bakmak', 'deyim', 'kolay'],
    ['elinden iş gelmek', 'Birçok işi yapabilecek yetenekte olmak', 'deyim'],
    ['göbeği çatlamak', 'Bir işi yaparken aşırı zorlanmak', 'deyim', 'zor'],
    ['İşleyen demir pas tutmaz', 'Çalışan kişi dinç ve yetkin kalır', 'atasozu', 'kolay'],
    ['Aç ayı oynamaz', 'Karnı doymayan kişi iş göremez', 'atasozu', 'zor'],
    ['Erken kalkan yol alır', 'Erken davranan işini çabuk bitirir', 'atasozu', 'kolay'],
    ['Alet işler el övünür', 'İş uygun araçla kolayca yapılır', 'atasozu', 'zor'],
    ['Sanat altın bileziktir', 'Meslek sahibi geçimini her yerde sağlar', 'atasozu'],
    ['Ağustosta gölge kovan, zemheride karnın ovar', 'Yazın çalışmayan kışın aç kalır', 'atasozu', 'zor'],
    // Çalışma konusunda "çok emek harcamak" doluydu; işbirliği, işe başlama ve
    // zamanlama tarafı boştu. Yeni sözler bu üç eksiği kapatıyor.
    ['el ele vermek', 'Bir işi birlikte yapmaya girişmek', 'deyim', 'kolay'],
    ['tereyağından kıl çeker gibi', 'Hiç zorlanmadan, kolayca', 'deyim', 'zor'],
    ['çorbada tuzu bulunmak', 'Bir işe küçük de olsa katkısı olmak', 'deyim'],
    ['işin ucundan tutmak', 'Ortak bir işe yardıma girişmek', 'deyim', 'kolay'],
    ['kolu kanadı kırılmak', 'Çalışamayacak duruma düşmek', 'deyim', 'zor'],
    ['iğneyle kuyu kazmak', 'Çok zahmetli bir işi güçlükle sürdürmek', 'deyim'],
    ['kırk fırın ekmek yemek', 'O düzeye gelmek için çok deneyim gerekmek', 'deyim', 'zor'],
    ['işi başından aşkın olmak', 'Yetişemeyecek kadar çok işi olmak', 'deyim', 'kolay'],
    ['elini çabuk tutmak', 'Acele edip işi hızlandırmak', 'deyim', 'kolay'],
    ['ağır aksak gitmek', 'Çok yavaş ve aksayarak ilerlemek', 'deyim'],
    ['çığır açmak', 'Yeni bir yol açıp öncü olmak', 'deyim', 'zor'],
    ['temel atmak', 'Bir işin ilk adımını atmak', 'deyim', 'kolay'],
    ['yükünü çekmek', 'Birinin sorumluluğunu üstlenip katlanmak', 'deyim'],
    ['çile çekmek', 'Uzun süre sıkıntıya katlanmak', 'deyim', 'kolay'],
    ['dört elle sarılmak', 'Bir işe bütün gücüyle bağlanmak', 'deyim'],
    ['iş inada binmek', 'İş, karşılıklı inatla sürdürülür olmak', 'deyim', 'zor'],
    ['ekmeğiyle oynamak', 'Birinin geçim kaynağını tehlikeye atmak', 'deyim'],
    ['hamallık etmek', 'Ağır ve yorucu iş yapmak', 'deyim'],
    ['ekmeğini yemek', 'Birinin yanında çalışarak geçinmek', 'deyim'],
    ['başa çıkmak', 'Bir güçlüğün üstesinden gelmek', 'deyim', 'kolay'],
    ['yaya kalmak', 'Bir işten geri kalıp yoksun kalmak', 'deyim', 'zor'],
    ['ekmek elden su gölden', 'Emeksiz, başkasının sırtından geçinmek', 'deyim', 'zor'],
    ['ayak işlerine bakmak', 'Küçük ve önemsiz işleri yapmak', 'deyim'],
    ['canını dişine takmak', 'Bütün gücünü toplayıp dayanmak', 'deyim'],
    ['Terzi kendi söküğünü dikemez', 'Kişi kendi işini başkasınınki kadar göremez', 'atasozu', 'kolay'],
    ['Yalnız taş duvar olmaz', 'Tek başına büyük iş başarılamaz', 'atasozu', 'kolay'],
    ['Balık baştan kokar', 'Bozukluk baştakinden başlayarak yayılır', 'atasozu', 'kolay'],
    ['Demir tavında dövülür', 'Her iş tam zamanında yapılmalıdır', 'atasozu'],
    ['Ağaç yaprağıyla gürler', 'Kişi çevresindekilerle güçlü olur', 'atasozu'],
    ['Yuvarlanan taş yosun tutmaz', 'Sürekli yer değiştiren birikim yapamaz', 'atasozu', 'zor'],
    ['İşini kış tut da yaz çıkarsa bahtına', 'En kötüsüne göre hazırlanmak gerekir', 'atasozu', 'zor'],
    ['Çobansız koyunu kurt kapar', 'Başsız kalan topluluk zarara uğrar', 'atasozu', 'zor'],
    ['Kervan yolda düzülür', 'İşe başlanır, eksikler yol boyunca giderilir', 'atasozu', 'zor'],
  ]),

  ...grup('para', [
    ['eli açık olmak', 'Cömert davranmak', 'deyim', 'kolay'],
    ['eli sıkı olmak', 'Cimri davranmak', 'deyim', 'kolay'],
    ['ayağını yorganına göre uzatmak', 'Geliri kadar harcamak', 'deyim', 'kolay'],
    ['kesenin ağzını açmak', 'Bol bol para harcamak', 'deyim'],
    ['yükünü tutmak', 'Yeterince mal mülk edinmek', 'deyim', 'zor'],
    ['iki yakası bir araya gelmemek', 'Geçim sıkıntısından kurtulamamak', 'deyim'],
    ['para canlısı olmak', 'Parayı her şeyden üstün tutmak', 'deyim'],
    ['cebi delik olmak', 'Elinde hiç para durmamak', 'deyim'],
    ['beş parasız kalmak', 'Hiç parası kalmamak', 'deyim', 'kolay'],
    ['eli darda olmak', 'Parasızlık çekmek', 'deyim'],
    ['boğazından kesmek', 'Yeme içmeden kısarak biriktirmek', 'deyim', 'zor'],
    ['kazık atmak', 'Aşırı fiyat isteyerek zarara sokmak', 'deyim'],
    ['bir lokma bir hırka', 'Aza kanaat ederek yaşamak', 'deyim', 'zor'],
    ['babasının hayrına çalışmak', 'Bir karşılık almadan iş yapmak', 'deyim', 'zor'],
    ['Damlaya damlaya göl olur', 'Küçük birikimler zamanla büyür', 'atasozu', 'kolay'],
    ['Kaz gelecek yerden tavuk esirgenmez', 'Büyük kazanç için küçük fedakârlık yapılır', 'atasozu', 'zor'],
    ['Sakla samanı gelir zamanı', 'Değersiz görünen şey ileride işe yarar', 'atasozu', 'kolay'],
    ['Ucuz etin yahnisi yavan olur', 'Ucuza alınan malın kalitesi düşük çıkar', 'atasozu', 'zor'],
    ['Borç yiğidin kamçısıdır', 'Borç insanı çalışmaya iter', 'atasozu', 'zor'],
    ['Az veren candan, çok veren maldan', 'Az veren imkânı kadar verir, küçümsenmez', 'atasozu', 'zor'],
    ['tuzu kuru olmak', 'Sıkıntısı olmayacak kadar varlıklı olmak', 'deyim'],
    ['köşeyi dönmek', 'Kısa yoldan çok para kazanmak', 'deyim', 'kolay'],
    ['kemer sıkmak', 'Harcamaları kısarak idare etmek', 'deyim', 'kolay'],
    ['ekmek kapısı', 'Geçim sağlanan iş yeri', 'deyim'],
    ['para etmemek', 'Alıcı bulamayacak kadar değersizleşmek', 'deyim', 'kolay'],
    ['başını sokmak', 'Barınacak bir yer bulmak', 'deyim'],
    ['el açmak', 'Muhtaç durumda para dilenmek', 'deyim', 'zor'],
    ['sırtı pek karnı tok', 'Yiyeceği giyeceği yerinde olmak', 'deyim', 'zor'],
    ['Para parayı çeker', 'Varlıklı kişi daha kolay kazanır', 'atasozu', 'kolay'],
    ['Aç tavuk kendini buğday ambarında sanır', 'Yoksun kişi düşünde bolluk görür', 'atasozu'],
    ['İşten artmaz dişten artar', 'Birikim harcamayı kısmakla olur', 'atasozu', 'zor'],
    ['Mal canın yongasıdır', 'İnsan malını canı gibi korur', 'atasozu', 'zor'],
    ['Bal tutan parmağını yalar', 'Bir işten çıkar sağlayan pay alır', 'atasozu'],
    ['Emanet ata binen tez iner', 'Ödünç alınan şey çabuk elden gider', 'atasozu', 'zor'],
    ['Zenginin malı züğürdün çenesini yorar', 'Yoksul, zenginin varlığını konuşup durur', 'atasozu', 'zor'],
    ['Kanaat tükenmez hazinedir', 'Yetinmeyi bilen kişi yoksulluk çekmez', 'atasozu'],
    // Para konusunda cimrilik-cömertlik ikilisi doluydu; borç, pahalılık ve
    // birikim tarafı zayıftı. Yeni sözler alışveriş ve borç ekseninde seçildi.
    ['belini doğrultmak', 'Parasızlıktan kurtulup düzene girmek', 'deyim'],
    ['para yemek', 'Savurganca çok para harcamak', 'deyim', 'kolay'],
    ['pahalıya patlamak', 'Beklenenden çok masrafa yol açmak', 'deyim', 'kolay'],
    ['ucuza kapatmak', 'Bir malı çok az paraya almak', 'deyim'],
    ['hesabını bilmek', 'Harcamalarını ölçülü tutmak', 'deyim', 'kolay'],
    ['cebini doldurmak', 'Haksız yoldan çok kazanç sağlamak', 'deyim'],
    ['dünyalığını çıkarmak', 'Ömrüne yetecek parayı kazanmak', 'deyim', 'zor'],
    ['geçim derdine düşmek', 'Yaşamını sürdürme kaygısına kapılmak', 'deyim', 'kolay'],
    ['aç susuz kalmak', 'Yiyecek içecek bulamaz duruma düşmek', 'deyim', 'kolay'],
    ['borca girmek', 'Sonra ödemek üzere para almak', 'deyim', 'kolay'],
    ['borç harç etmek', 'Sağdan soldan borçlanıp parayı denkleştirmek', 'deyim', 'zor'],
    ['bir dikili ağacı olmamak', 'Hiçbir mal mülk sahibi olmamak', 'deyim', 'zor'],
    ['ev bark sahibi olmak', 'Ev kurup düzenini oturtmak', 'deyim'],
    ['boğaz tokluğuna çalışmak', 'Yalnız karnını doyurma karşılığı çalışmak', 'deyim'],
    ['küpünü doldurmak', 'Kısa yoldan çokça mal biriktirmek', 'deyim', 'zor'],
    ['yağlı kapı', 'Çok kazandıran iş yeri', 'deyim', 'zor'],
    ['parayı sokağa atmak', 'Parayı boş yere harcayıp ziyan etmek', 'deyim', 'kolay'],
    ['ateş pahası', 'Alınamayacak kadar pahalı', 'deyim', 'kolay'],
    ['sudan ucuz', 'Değerinin çok altında ucuz', 'deyim', 'kolay'],
    ['eli para görmek', 'Eline hiç olmadığı kadar para geçmek', 'deyim'],
    ['kuru ekmeğe muhtaç olmak', 'Yiyecek alacak parası bile kalmamak', 'deyim', 'zor'],
    ['kuruş kuruş biriktirmek', 'Azar azar para artırmak', 'deyim'],
    ['eli genişlemek', 'Parasal durumu rahatlamak', 'deyim'],
    ['gözü doymamak', 'Ne kadar alsa da yetinmeyip daha çok istemek', 'deyim'],
    ['Ak akçe kara gün içindir', 'Biriktirilen para zor günde işe yarar', 'atasozu', 'kolay'],
    ['Altın yere düşmekle pul olmaz', 'Değerli olan kötü duruma düşse de değerini korur', 'atasozu', 'kolay'],
    ['İki gönül bir olunca samanlık seyran olur', 'Sevenler için yoksulluk sorun olmaz', 'atasozu', 'kolay'],
    ['Ucuz alan pahalı alır', 'Kalitesiz ucuz mal sonunda daha pahalıya gelir', 'atasozu'],
    ['Az olsun uz olsun', 'Az ama işe yarar olması yeğdir', 'atasozu'],
    ['Aza kanaat etmeyen çoğu bulamaz', 'Azı beğenmeyen çoğa da erişemez', 'atasozu'],
    ['Veresiye şarap içen iki kere sarhoş olur', 'Borçla harcayan bedelini iki kez öder', 'atasozu', 'zor'],
    ['Aç doymam, tok acıkmam sanır', 'İnsan içinde bulunduğu durumun süreceğini sanır', 'atasozu', 'zor'],
    ['Çok mal haramsız, çok söz yalansız olmaz', 'Aşırı kazanç da aşırı söz de temiz kalmaz', 'atasozu', 'zor'],
    ['Baba malı tez tükenir, evlat gerek kazana', 'Hazıra konan varlık çabuk biter', 'atasozu', 'zor'],
  ]),

  ...grup('iletisim', [
    ['ağzından baklayı çıkarmak', 'Sakladığı sözü sonunda söyleyivermek', 'deyim', 'kolay'],
    ['ağzı laf yapmak', 'Etkileyici biçimde konuşmak', 'deyim'],
    ['dilinin altında bir şey olmak', 'Söylemek istediğini gizlemek', 'deyim', 'zor'],
    ['kulağına çalınmak', 'Bir haberi rastlantıyla duymak', 'deyim'],
    ['laf taşımak', 'Duyduğunu başkasına yetiştirip dedikodu yaymak', 'deyim', 'kolay'],
    ['ağzını bıçak açmamak', 'Üzüntüden konuşamaz olmak', 'deyim'],
    ['sözünü esirgememek', 'Düşündüğünü çekinmeden söylemek', 'deyim'],
    ['dile düşmek', 'Herkesin dedikodusuna konu olmak', 'deyim'],
    ['iğneli söz söylemek', 'Dokundurmak amacıyla konuşmak', 'deyim', 'zor'],
    ['ağzı var dili yok', 'Sessiz, hakkını arayamayan', 'deyim', 'zor'],
    ['lafı ağzına tıkamak', 'Konuşmasını sert biçimde kesmek', 'deyim'],
    ['kulak kabartmak', 'Gizlice dinlemeye çalışmak', 'deyim', 'kolay'],
    ['sözünde durmak', 'Verdiği sözü yerine getirmek', 'deyim', 'kolay'],
    ['dilinin ucunda olmak', 'Hatırlamak üzere olup söyleyememek', 'deyim'],
    ['ağzından kaçırmak', 'Söylememesi gerekeni istemeden söylemek', 'deyim'],
    ['Bir ağızdan çıkan bin dile yayılır', 'Söylenen söz çabucak duyulur', 'atasozu', 'zor'],
    ['Söz gümüşse sükût altındır', 'Susmak kimi zaman konuşmaktan değerlidir', 'atasozu', 'kolay'],
    ['Tatlı dil yılanı deliğinden çıkarır', 'Güzel söz en katı kişiyi bile yumuşatır', 'atasozu', 'kolay'],
    ['Ateş olmayan yerden duman çıkmaz', 'Söylentinin bir dayanağı vardır', 'atasozu', 'kolay'],
    ['Bin bilsen de bir bilene danış', 'Ne kadar bilgili olsan da başkasına danışmalısın', 'atasozu', 'zor'],
    ['ağzı kalabalık olmak', 'Karışık ve düzensiz konuşmak', 'deyim', 'zor'],
    ['çenesi düşük olmak', 'Gereksiz yere çok konuşmak', 'deyim', 'kolay'],
    ['ağzını aramak', 'Sırrını öğrenmek için dolaylı konuşmak', 'deyim'],
    ['sözü geçmek', 'Sözü dinlenip etkili olmak', 'deyim'],
    ['lafı çevirmek', 'Konuyu başka yöne kaydırmak', 'deyim', 'kolay'],
    ['ağzından çıkanı kulağı duymamak', 'Öfkeyle düşünmeden konuşmak', 'deyim'],
    ['kem küm etmek', 'Sıkışınca geveleyip duraksamak', 'deyim', 'zor'],
    ['dil dökmek', 'Kandırmak için tatlı tatlı konuşmak', 'deyim'],
    ['ağzını açıp gözünü yummak', 'Öfkeyle ağır sözler söylemek', 'deyim', 'zor'],
    ['kulağını doldurmak', 'Birini söz taşıyarak etkilemek', 'deyim', 'zor'],
    ['ağız birliği etmek', 'Aynı sözü söylemekte anlaşmak', 'deyim', 'zor'],
    ['nutku tutulmak', 'Şaşkınlıktan konuşamaz olmak', 'deyim'],
    ['Doğru söyleyeni dokuz köyden kovarlar', 'Gerçeği söyleyen kişi sevilmez', 'atasozu', 'kolay'],
    ['Söyleyene bakma söyletene bak', 'Sözün ardındaki asıl niyeti görmeli', 'atasozu', 'zor'],
    ['Dost acı söyler', 'Gerçek dost hoşa gitmeyen doğruyu söyler', 'atasozu', 'kolay'],
    ['Anlayana sivrisinek saz, anlamayana davul zurna az', 'Kavrayışlı kişiye küçük bir işaret yeter', 'atasozu'],
    // İletişimde "çok konuşmak" ve dedikodu kalabalıktı; söz verme, dinleme ve
    // yerinde konuşma tarafı eksikti. Yeni sözler bu üç eksene dağıtıldı.
    ['ağzının payını vermek', 'Haddini bildirecek karşılığı vermek', 'deyim', 'kolay'],
    ['başının etini yemek', 'Sürekli söylenip birini bunaltmak', 'deyim', 'kolay'],
    ['söz vermek', 'Bir işi yapacağına güvence vermek', 'deyim', 'kolay'],
    ['sözünden dönmek', 'Verdiği sözü tutmamak', 'deyim', 'kolay'],
    ['söz açmak', 'Bir konudan konuşmaya başlamak', 'deyim', 'kolay'],
    ['sözü uzatmak', 'Gereğinden çok konuşup uzatmak', 'deyim', 'kolay'],
    ['kulak vermek', 'Dikkatle dinlemek', 'deyim', 'kolay'],
    ['dile getirmek', 'Bir düşünceyi sözle anlatmak', 'deyim', 'kolay'],
    ['söz dinlemek', 'Öğüde uyup denileni yapmak', 'deyim', 'kolay'],
    ['yüzüne vurmak', 'Kusurunu açıkça söyleyip utandırmak', 'deyim'],
    ['laf altında kalmamak', 'Söylenene hemen karşılık vermek', 'deyim'],
    ['dilini tutmak', 'Konuşmasını denetleyip susmayı bilmek', 'deyim'],
    ['dili varmamak', 'Bir sözü söylemeye gönlü elvermemek', 'deyim'],
    ['söz kesmek', 'Evlilik için anlaşıp sözlenmek', 'deyim'],
    ['iki çift söz etmek', 'Kısaca birkaç söz söylemek', 'deyim'],
    ['diline dolamak', 'Bir konuyu sürekli tekrarlayıp durmak', 'deyim'],
    ['kulağı delik olmak', 'Olup biteni herkesten önce duymak', 'deyim'],
    ['kulağına küpe olmak', 'Alınan ders unutulmayacak biçimde yerleşmek', 'deyim'],
    ['ağzını açtırmamak', 'Karşısındakine konuşma fırsatı vermemek', 'deyim'],
    ['ağzını hayra açmak', 'Kötü değil, iyi şeyler söylemek', 'deyim', 'zor'],
    ['lafı gediğine koymak', 'Sözü tam yerinde ve etkili söylemek', 'deyim', 'zor'],
    ['ağzından bal damlamak', 'Çok tatlı ve etkileyici konuşmak', 'deyim', 'zor'],
    ['ağız yapmak', 'Oyalamak için gerçek dışı konuşmak', 'deyim', 'zor'],
    ['ağzından girip burnundan çıkmak', 'Uzun uzun konuşarak birini kandırmak', 'deyim', 'zor'],
    ['Lafla peynir gemisi yürümez', 'Sözle iş görülmez, yapmak gerekir', 'atasozu', 'kolay'],
    ['Az söyle çok dinle', 'Çok konuşmak yerine dinlemek yeğdir', 'atasozu', 'kolay'],
    ['Yalancının mumu yatsıya kadar yanar', 'Yalan er geç ortaya çıkar', 'atasozu', 'kolay'],
    ['Bilmemek ayıp değil, öğrenmemek ayıp', 'Kusur bilmemek değil, öğrenmeye çalışmamaktır', 'atasozu', 'kolay'],
    ['Ayıpsız dost arayan dostsuz kalır', 'Kusursuz arkadaş arayan yalnız kalır', 'atasozu'],
    ['Kem söz sahibinindir', 'Kötü söz söyleyenin kendine döner', 'atasozu'],
    ['Sözünü bilmeyen kişinin yüzünü karartır', 'Düşünmeden konuşan kişi utanca düşer', 'atasozu', 'zor'],
    ['Danışan dağı aşmış, danışmayan düz yolda şaşmış', 'Danışarak iş gören yolunu kolay bulur', 'atasozu', 'zor'],
    ['Sükût ikrardan gelir', 'Susan kişi kabul etmiş sayılır', 'atasozu', 'zor'],
    ['Ağız yer yüz utanır', 'İyilik gören, iyilik edenin karşısında utanır', 'atasozu', 'zor'],
  ]),

  ...grup('akil', [
    ['akıntıya kürek çekmek', 'Sonuç alınamayacak işle uğraşmak', 'deyim'],
    ['pusulayı şaşırmak', 'Ne yapacağını bilemez duruma düşmek', 'deyim', 'zor'],
    ['ipin ucunu kaçırmak', 'Bir işin denetimini elden bırakmak', 'deyim'],
    ['bir taşla iki kuş vurmak', 'Tek işle iki sonuç birden almak', 'deyim', 'kolay'],
    ['ateşle oynamak', 'Tehlikeli bir işe girişmek', 'deyim', 'kolay'],
    ['iki arada bir derede kalmak', 'İki güç durum arasında sıkışmak', 'deyim'],
    ['gözden kaçmak', 'Fark edilmeden geçmek', 'deyim', 'kolay'],
    ['şansı yaver gitmek', 'İşleri istediği gibi yolunda gitmek', 'deyim'],
    ['kestirip atmak', 'Kesin bir kararla işi bitirmek', 'deyim', 'zor'],
    ['pabucu dama atılmak', 'Yerini daha iyisine kaptırmak', 'deyim', 'zor'],
    ['Sütten ağzı yanan yoğurdu üfleyerek yer', 'Kötü deneyim yaşayan sonrasında çok dikkatli olur', 'atasozu', 'kolay'],
    ['Görünen köy kılavuz istemez', 'Apaçık olan şey açıklama gerektirmez', 'atasozu'],
    ['Sabreden derviş muradına ermiş', 'Sabreden sonunda istediğine kavuşur', 'atasozu', 'zor'],
    ['Sakınan göze çöp batar', 'Aşırı korunan şey yine de zarar görebilir', 'atasozu', 'zor'],
    ['Damdan düşen halden anlar', 'Aynı sıkıntıyı yaşayan başkasını anlar', 'atasozu', 'zor'],
    ['Denize düşen yılana sarılır', 'Sıkışan kişi her çareye başvurur', 'atasozu', 'kolay'],
    ['Gülü seven dikenine katlanır', 'İstediğine ulaşmak için sıkıntıya katlanılır', 'atasozu', 'kolay'],
    ['Her yiğidin bir yoğurt yiyişi vardır', 'Herkesin kendine göre bir yöntemi vardır', 'atasozu', 'zor'],
    ['Su testisi su yolunda kırılır', 'Kişi çoğunlukla işini yaptığı yerde zarar görür', 'atasozu', 'zor'],
    ['Talihsiz hacıyı deve üstünde yılan sokar', 'Şanssız kişinin başına gelmedik kalmaz', 'atasozu', 'zor'],
    ['aklı başına gelmek', 'Yanlışını anlayıp doğruyu görmek', 'deyim', 'kolay'],
    ['kafa yormak', 'Bir konuyu uzun uzun düşünmek', 'deyim', 'kolay'],
    ['ayağını denk almak', 'Tedbirli davranıp dikkatli olmak', 'deyim'],
    ['köprüleri atmak', 'Bir daha dönmemek üzere ilişkiyi bitirmek', 'deyim'],
    ['çıkmaza girmek', 'Çözümsüz bir duruma düşmek', 'deyim'],
    ['göze almak', 'Kötü sonuca katlanmayı baştan kabul etmek', 'deyim', 'kolay'],
    ['aklı ermek', 'Bir konuyu kavrayabilmek', 'deyim', 'kolay'],
    ['kaşla göz arasında', 'Kimse fark etmeden çok kısa sürede', 'deyim', 'zor'],
    ['sudan çıkmış balığa dönmek', 'Bulunduğu ortama uyum sağlayamamak', 'deyim', 'zor'],
    ['aklının köşesinden geçmemek', 'Hiç ummamış, düşünmemiş olmak', 'deyim', 'zor'],
    ['bel bağlamak', 'Birine güvenip umut bağlamak', 'deyim', 'kolay'],
    ['Öfkeyle kalkan zararla oturur', 'Öfkeyle davranan sonunda zarar eder', 'atasozu', 'kolay'],
    ['Sona kalan dona kalır', 'Geç kalan kişi payını alamaz', 'atasozu'],
    ['Bir çiçekle bahar olmaz', 'Tek örnek genel bir sonuç doğurmaz', 'atasozu'],
    ['Su akar yatağını bulur', 'İşler kendi doğal yolunda yürür', 'atasozu', 'zor'],
    ['Zorla güzellik olmaz', 'İstemeyene bir şey zorla yaptırılamaz', 'atasozu', 'kolay'],
    ['Ummadığın taş baş yarar', 'Önemsenmeyen şey büyük zarar verebilir', 'atasozu'],
    // Akıl konusunda tedbir ve talih vardı ama karar verme, aldanma ve zamanlama
    // yoktu; oyunda en çok bu üç eksende soru isteniyor, ağırlık oraya verildi.
    ['iş işten geçmek', 'Düzeltmek için artık geç kalınmış olmak', 'deyim', 'kolay'],
    ['aklı almamak', 'Bir şeyi bir türlü kavrayamamak', 'deyim', 'kolay'],
    ['aklına yatmak', 'Bir düşünceyi uygun bulup benimsemek', 'deyim', 'kolay'],
    ['akıl vermek', 'Birine ne yapacağını öğütlemek', 'deyim', 'kolay'],
    ['aklını başına toplamak', 'Düşüncesizliği bırakıp ölçülü davranmak', 'deyim', 'kolay'],
    ['kafası karışmak', 'Ne düşüneceğini bilemez duruma gelmek', 'deyim', 'kolay'],
    ['şansını denemek', 'Sonucu bilinmeyen işe girişip bakmak', 'deyim', 'kolay'],
    ['ayak uydurmak', 'Yeni duruma uyum sağlamak', 'deyim', 'kolay'],
    ['kendini ateşe atmak', 'Bile bile tehlikeye atılmak', 'deyim'],
    ['gözden çıkarmak', 'Yitirmeyi baştan kabullenmek', 'deyim'],
    ['yağmurdan kaçarken doluya tutulmak', 'Bir dertten kaçarken daha büyüğüne düşmek', 'deyim'],
    ['gözü açık olmak', 'Uyanık davranıp kolay kolay aldanmamak', 'deyim'],
    ['kırk yılın başı', 'Çok seyrek, uzun aralıklarla', 'deyim'],
    ['çıkar yol bulmak', 'Sıkıntıdan kurtaracak çözümü bulmak', 'deyim'],
    ['göz önünde bulundurmak', 'Karar verirken hesaba katmak', 'deyim'],
    ['kısmeti açılmak', 'Talihi dönüp iyi fırsatlar çıkmak', 'deyim'],
    ['ölçüp biçmek', 'Karar öncesi iyice düşünüp tartmak', 'deyim'],
    ['başına iş açmak', 'Kendine dert olacak duruma yol açmak', 'deyim'],
    ['körü körüne', 'Düşünmeden, gözü kapalı biçimde', 'deyim'],
    ['faka basmak', 'Tuzağa düşüp aldanmak', 'deyim', 'zor'],
    ['ok yaydan çıkmak', 'Geri döndürülemeyecek adım atılmış olmak', 'deyim', 'zor'],
    ['ayağı suya ermek', 'Gerçeği geç de olsa anlamak', 'deyim', 'zor'],
    ['yumurta kapıya dayanmak', 'İş, ertelenemeyecek kadar sıkışmak', 'deyim', 'zor'],
    ['burnunun ucunu görememek', 'Yakın geleceği bile öngörememek', 'deyim', 'zor'],
    ['Akıl yaşta değil baştadır', 'Akıllılık yaşla değil kişinin kendisiyle ilgilidir', 'atasozu', 'kolay'],
    ['Perşembenin gelişi çarşambadan bellidir', 'Bir işin sonu gidişinden anlaşılır', 'atasozu'],
    ['İki karpuz bir koltuğa sığmaz', 'Aynı anda iki büyük iş birden yürütülemez', 'atasozu'],
    ['Çok bilen çok yanılır', 'Bilgisine aşırı güvenen daha çok hata yapar', 'atasozu'],
    ['Keskin sirke küpüne zarar verir', 'Öfkeli kişi asıl kendine zarar verir', 'atasozu'],
    ['Sabır acıdır, meyvesi tatlıdır', 'Sabretmek güçtür ama sonucu güzel olur', 'atasozu'],
    ['Kul sıkışmadıkça Hızır yetişmez', 'Yardım çoğu zaman ancak son anda gelir', 'atasozu', 'zor'],
    ['Akıl için yol birdir', 'Doğru düşünen herkes aynı sonuca varır', 'atasozu', 'zor'],
    ['Bir musibet bin nasihatten yeğdir', 'Yaşanan tek kötü olay bin öğütten çok öğretir', 'atasozu', 'zor'],
  ]),
] as const

export const SOZ_BOYUTU = SOZ_HAVUZU.length
